### ISSUE TITLE
Flash is not rendered in layout when two or more include tags are present

### ISSUE THREAD

**Issue by MiguelAngel82** [grails/grails-core#9796] opened 2016-03-14 12:52 UTC
I have a problem related with flash scope and the tag "<g:include>", but I don't know if is a bug or not. The problem is like this:
You have an action in a controller that assigns a value to "flash.message", a GSP (as a response of the action) with a layout and two (or more) "<g:includes>" in the same GSP. If you try to print the value of "flash.message" in the layout is empty. With one "<g:include>" it works perfectly.
The code is similar to this:
Controller:
```
def index() {
        flash.message = "Test"
        [:]
    }
```
GSP:
```
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="main"/>
</head>

<body>
    <p>Flash message in index view: ${flash.message}</p>
    <p><g:include controller="test" action="test"/></p>
    <p><g:include controller="test" action="test"/></p>
</body>
</html>
```
and the layout contains the following code:
```
<p>Flash message in main view, before tag layoutBody: ${flash.message}</p>

<g:layoutBody/>
```
I'm using Grails 3.1.3.
I really appreciate your help

This is a demo of the problem: https://github.com/MiguelAngel82/testIncludesFlash.git

Thank you!

**Comment by graemerocher** [comment] 2016-03-17 14:56
@jeffbrown another related issue regarding the recent changes to flash, possibly a duplicate of #9370

**Comment by jeffbrown** [comment] 2016-03-23 14:17
I think this is the same issue as #9370

**Closed by jeffbrown** 2016-03-23 14:17 UTC
