### ISSUE TITLE
original params are chained when redirecting

### ISSUE THREAD

**Issue by skufle** [grails/grails-core#10965] opened 2018-03-16 10:30 UTC
Seems like Grails 3.3.3 has introduced a bug where the original input params are chained when redirecting.

See the screenshots for example and notice the URL change in request params when redirected to index page on Grails 3.3.3

### Steps to Reproduce

1. Create simple app with a few fields that redirects to index with not found when create is submitted
2. Notice that the original input params to save are added to the index URL

### Expected Behaviour

Should not chain the original input parameters

### Actual Behaviour

Original input parameters are chained

### Environment Information

- **Operating System**: Ubuntu
- **Grails Version:** 3.3.3
- **JDK Version:** 1.8.0_131

### Example Application
https://github.com/skufle/redirectbug

![screenshot from 2018-03-16 11-01-06](https://user-images.githubusercontent.com/4528177/37516111-5c5ecc12-290d-11e8-9aaa-4cfca27101a3.png)
![screenshot from 2018-03-16 11-01-17](https://user-images.githubusercontent.com/4528177/37516112-5c7915c2-290d-11e8-8510-aa4ff8a9f81b.png)
![screenshot from 2018-03-16 11-03-49](https://user-images.githubusercontent.com/4528177/37516114-5c9393fc-290d-11e8-9eff-65d294cb7507.png)
![screenshot from 2018-03-16 11-03-56](https://user-images.githubusercontent.com/4528177/37516115-5cb056fe-290d-11e8-9eff-d949fc4328bc.png)

**Comment by jeffbrown** [comment] 2018-03-16 13:13
Possibly related to some of this...

https://github.com/grails/grails-core/commit/a7c58744661b11de7d4d046ab9198dbc1b6d49f1#diff-9e4f34554ed5b8c51b79aa7900c7dafc

https://github.com/grails/grails-core/commit/c815fea8d51e5a84facead01b4636264372c0398#diff-9e4f34554ed5b8c51b79aa7900c7dafc

https://github.com/grails/grails-core/commit/a8e22804f1c897ad7bebc0576b25b010b06a2bd4#diff-9e4f34554ed5b8c51b79aa7900c7dafc

https://github.com/grails/grails-core/commit/62cd7d6bac06822ad0b12fa55607a7c9dbcf3360#diff-9e4f34554ed5b8c51b79aa7900c7dafc

**Comment by jamescookie** [comment] 2018-03-22 20:20
I was upgrading to 3.3.3 from 3.3.0 and found this problem prevents a `delete` actionSubmit tag from working.
I have two actionSubmits (one for delete and one for update) on an edit page, therefore need to remove the 'method' from the form:
```
    <g:form resource="${this.thing}">
        <g:hiddenField name="version" value="${this.thing?.version}" />
        <fieldset class="form">
            <f:all bean="thing"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
            <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
        </fieldset>
    </g:form>
```

However, as the params (including the `_method`) are now passed on by the redirect of the delete to the index (which is not allowed to `delete`), you get a 405.

Also, when editing a large form, the url for the next page is terrible as it includes all the fields.

**Comment by jamescookie** [comment] 2018-03-22 20:28
Note: This bug was introduced fixing: #10622

**Comment by ilopmar** [comment] 2018-03-23 08:25
@jamescookie I fix the original problem reported in this issue. To make sure that your code also works, could you please create a sample project that reproduces the issue and share here the github url?

**Comment by jamescookie** [comment] 2018-03-23 08:51
See this project: https://github.com/jamescookie/grails-bug-redirect
Create a thing, then delete it (via the edit page), you'll get a 405

**Comment by ilopmar** [comment] 2018-03-23 10:11
Thanks for the sample project. I've been taking a look and the code is not working in Grails 3.3.0, although it's not the same problem as in Grails 3.3.3. The issue is that `actionSubmit` behaves "special". From https://gsp.grails.org/latest/ref/Tags/actionSubmit.html:

> The implementation of the actionSubmit tag means that it does not sit entirely comfortably with URL mappings, particularly the default one. The reason for this is that URL mappings work on the URL of the request, but actionSubmit uses a parameter to determine the action to execute.

If you inspect the HTML generated by the tag:
```
<form action="/thing/index/3" method="post" >
	<input type="hidden" name="version" value="0" id="version" />
	<fieldset class="form">
		<div class='fieldcontain required'>
			<label for='name'>Name
			<span class='required-indicator'>*</span>
			</label>
			<input type="text" name="name" value="999" required="" id="name" />
		</div>
	</fieldset>
	<fieldset class="buttons">
		<input type="submit" name="_action_Update" value="Update" class="save" />
		<input type="submit" name="_action_Delete" value="Delete" class="delete" formnovalidate="" onclick="return confirm(&#39;Are you sure?&#39;);" />
	</fieldset>
</form>
```
You can see that the form action is `/thing/index/3` and the HTTP method is `POST`. Before calling the action on the controller Grails checks the `allowedMethods` and the parameters are `actionName = update` and HTTP `method = POST`. That method is not allowed for your action, hence the 405.
If you change `allowedMethods` in `ThingController` to:
```
static allowedMethods = [save: "POST", update: ["PUT", "POST"], delete: ["DELETE", "POST"]]
```
or 
```
static allowedMethods = [save: "POST", update: "POST", delete: "POST"]
```
Then everything works again.


After trying with my local Grails version with the original issue fixed, you still need to change the `allowedMethods` to make it work. With that, then everything works as expected.

**Comment by erichelgeson** [comment] 2018-04-04 14:36
I just noticed this yesterday as well - post data is put in as get params on redirect - very unexpected behavior.

**Comment by jeffbrown** [comment] 2018-04-04 14:37
The problem is understood and I expect the fix will be included in 3.3.4.

**Comment by sarbyn** [comment] 2018-04-04 14:54
@jeffbrown When it will be released approximately? Just to know if it is better wait for 3.3.4 or downgrade to 3.3.2. Thanks

**Comment by ilopmar** [comment] 2018-04-04 17:17
Grails 3.3.4 has been published with the fix for this bug.

**Comment by ilopmar** [comment] 2018-04-04 20:48
The original issue reported here was fixed but in this case with @erichelgeson's sample app is failing again. I'm reopening the ticket and I'll investigate the cause...

**Comment by ilopmar** [comment] 2018-04-04 21:08
The issue was introduced when fixing this https://github.com/grails/grails-core/issues/10622. The new behavior for that issue was to be able to redirect from a `UrlMappings` defining something like this:
```
"/test/deprecated" (redirect: [uri: "/test/newHotness"])
```
While keeping the original request params. 

In both the original fix and the latest one I was trying to "discover" if the request was being originated from that redirect from `UrlMappings` but I can see that there are more cases that I haven't took into account.
So, instead of trying to discover all those cases I was thinking about adding a new parameter to make explicit that we want to keep the params in the redirect and only in that case keep them. To do that we would need to write the previous url mapping like this:
```
"/test/deprecated" (redirect: [uri: "/test/newHotness", keepParams: true])
```
And only in that case when `keepParams == true` keep the original params when redirecting. Then I would add that new param to the documentation.

What do you guys think about this?

**Comment by ilopmar** [comment] 2018-04-04 22:03
I've made the changes here: https://github.com/grails/grails-core/commit/06e5b07595dd6f7480b84b20098612c9702ab924 and I've decided the rename the parameter to `keepParamsWhenRedirect`. I want to make it explicit and I want to make sure that the parameter is not there accidentally. 
If you want to try it now you can build Grails locally from that branch. Tomorrow morning (it's midnight here) I'll update the documentation and I'll make sure that all the test pass and hopefully we can release a new version and finally fix this issue.

I'm really sorry for all the troubles :disappointed:

**Comment by ilopmar** [comment] 2018-04-05 07:15
I've published a snapshot version with the fix. Please change this in your `gradle.properties`:

```
grailsVersion=3.3.5.BUILD-SNAPSHOT
```

Please test it and let me know.

Thanks.

**Comment by erichelgeson** [comment] 2018-04-05 14:17
I've verified it on my sample app a larger app as well - both work as they did prior to 3.3.3. Thanks!

**Comment by ilopmar** [comment] 2018-04-05 21:07
I've created new functional tests to make sure this doesn't fail again:

- This is the first one I created with the first sample project attached to this issue: https://github.com/grails/grails3-functional-tests/commit/1a192a58eb7c5634115c4c77390d4d2b4f1b29f6
- This is with Eric's test project: https://github.com/grails/grails3-functional-tests/commit/ab4b7e880deec017edb2fc9c335e9a5511e03478
- These are new tests that check the new behavior to redirect from `UrlMappings` with and without the new param `keepParamsWhenRedirect`: https://github.com/grails/grails3-functional-tests/commit/b7ee2e025b0e55ea0f1df29dca7923410576eb22

If you guys think about new and different tests cases please let me know and I'll create new tests.

**Comment by sarbyn** [comment] 2018-04-06 11:00
On 3.3.5.BUILD-SNAPSHOT all works as expected :)

**Closed** 2018-04-11 09:07 UTC
