### ISSUE TITLE
Url mappings: having excludes for REST url mapping returns 403 with JSON content only if X-Requested-With is set

### ISSUE THREAD

**Issue by kuceram** [grails/grails-core#9325] opened 2015-10-08 11:55 UTC
UrlMappings

```
"/users"(resources: 'users', namespace: 'v1', excludes: ['delete'])
```

When I try to  `[DELETE] /users/1` I receive http 403 with HTML content. I would expect to receive JSON as I set Content-Type header to application/json.

More interestingly, I receive JSON response when I set header `X-Requested-With` to `XMLHttpRequest`...

I would also expect that my custom 403 url mapping is be called but it isn't

```
"403"(controller: 'error', action: 'forbidden')
```

**Comment by sdelamo** [comment] 2017-05-23 09:17
With version 3.2.9, trying to call delete, in a resource where delete has been excluded, returns 404 which I think it is the correct response code. 

I have created a sample repository: 

https://github.com/grails-core-issues-forks/github-issue-9325

with the next code sample: 

`grails-app/domain/demo/Book.groovy`

```
package demo
import grails.rest.Resource
@Resource
class Book {
    static constraints = {
    }
}
```

`grails-app/controllers/demo/UrlMappings.groovy`

```
package demo
class UrlMappings {
    static mappings = {
        delete "/$controller/$id(.$format)?"(action:"delete")
        get "/$controller(.$format)?"(action:"index")
        get "/$controller/$id(.$format)?"(action:"show")
        post "/$controller(.$format)?"(action:"save")
        put "/$controller/$id(.$format)?"(action:"update")
        patch "/$controller/$id(.$format)?"(action:"patch")

        "/books"(resources: 'book', excludes: ['delete'])

        "/"(controller: 'application', action:'index')
        "500"(view: '/error')
        "404"(view: '/notFound')
    }
}
```

`grails-app/init/demo/BootStrap.groovy`

```
package demo

class BootStrap {

    def init = { servletContext ->

        def b = new Book(name: 'Petete')
        b.save(failOnError: true)

    }
    def destroy = {
    }
}
```

`grails-app/init/demo/BookDeleteSpec`

```
package demo

import grails.plugins.rest.client.RestBuilder
import grails.test.mixin.integration.Integration
import spock.lang.Specification

@Integration
class BookDeleteSpec extends Specification {

    def "delete has ben excluded, thus return 404"() {
        when:
        RestBuilder rest = new RestBuilder()
        def resp = rest.delete("http://localhost:${serverPort}/books/1") {
            accept('application/json')
        }

        then:
        resp.status == 404
    }
}
```

@kuceram I am going to close this issue since I think 404 it is the correct answer. If you don't agree please reopen the issue and indicate me how to validate. 

Regarding: 
> I would also expect that my custom 403 url mapping is be called but it isn't
> "403"(controller: 'error', action: 'forbidden')

I have included in the linked repository a functional test which validates 403 error mapping works. If you are able to create a sample repository with a reproducible error of 403 mapping not working please create a separate issue and link to the sample.

**Closed by sdelamo** 2017-05-23 09:17 UTC
Labels: in progress, REST

**Comment by kuceram** [comment] 2017-05-23 14:13
Ad 1. - excludes
Well, this should actually be http `405 Method not Allowed`.

404 - not found means that resource you try to delete doesn't exist.
405 - method not allowed means that given http method is not allowed for this resource.

Ad 2. - default url mapping
I think it was connected. Excluded http method wasn't covered by default error mapping. Maybe it's working now...

I don't have sufficient rights to reopen this issue. :-)

**Comment by sdelamo** [comment] 2017-05-23 15:29
> Ad 1. - excludes
> Well, this should actually be http 405 Method not Allowed.

> 404 - not found means that resource you try to delete doesn't exist.
> 405 - method not allowed means that given http method is not allowed for this resource.

I am not sure I agree with you. When you add `excludes` in URLMapping what you are saying is. Ok, for this resource generate a restful controller but don't include the delete action. It means the delete action is not available at all. Does not matter the http verb: POST, DELETE etc. 

We normally return 405 when you have for example constrained an action with allowedMethods to a particular http verb and your accessing the action with a different http verb.

**Comment by kuceram** [comment] 2017-05-24 07:38
I see, this make sense though. Thanks @sdelamo
