### ISSUE TITLE
Grails 3.3.0 - run-app Error: Could not find or load main class

### ISSUE THREAD

**Issue by petereddy** [grails/grails-core#10795] opened 2017-08-28 12:54 UTC
$ grails -v
    |Grails Version: 3.3.0
    |Groovy Version: 2.4.11
    |JVM Version: 1.8.0_144

    $ gradle -v

    ------------------------------------------------------------
    Gradle 4.1
    ------------------------------------------------------------
    
    Build time:   2017-08-07 14:38:48 UTC
    Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2
    
    Groovy:       2.4.11
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
    OS:           Mac OS X 10.12.6 x86_64
    
    $ grails create-app test
    ...................
    |Application created at /Users/user/work/temp/test
    $ cd test/
    $ grails
    |Resolving Dependencies. Please wait...
    
    CONFIGURE SUCCESSFUL in 1s
    |Starting interactive mode...
    |Enter a command name to run. Use TAB for completion:

    grails> run-app
    |Running application...
    Error: Could not find or load main class 
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':bootRun'.
    > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with no    n-zero exit value 1
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 4s
    Error |
    Failed to start server (Use --stacktrace to see the full trace)
    grails>

**Comment by jeffbrown** [comment] 2017-08-28 14:30
Does the problem happen if you have Gradle 3.5 configured in your GRADLE_HOME?

**Comment by jeffbrown** [comment] 2017-08-28 14:40
Also, does the problem happen if you run `./gradlew bootRun` using the default `gradlew` that is initially configured with the project?

**Comment by jeffbrown** [comment] 2017-08-28 15:23
FYI... This is what I am seeing (not able to reproduce): http://jeffscreencasts.s3.amazonaws.com/issue10795.mp4

**Comment by petereddy** [comment] 2017-08-28 15:32
It happens when I have GRADLE_HOME set to /Users/user/.sdkman/candidates/gradle/3.5. I also tried adding $GRADLE_HOME/bin to my PATH with the same results. Same result also when using ./gradlew bootRun.

This was all working fine for me up until a week or so ago.

**Comment by jeffbrown** [comment] 2017-08-28 15:53
> This was all working fine for me up until a week or so ago.

That suggests that something probably changed in the environment.

**Comment by alvarosanchez** [comment] 2017-08-28 15:59
This could probably be a stale instance of the Gradle daemon.

Please try with `gradle --stop`, or even the good old `killall -9 java`, and let us know if it made any difference.

**Comment by petereddy** [comment] 2017-08-28 16:38
Yes, the problem seemed to have started when I added a dependency to a project and my dependencies were refreshed, though I don't see how that would have affected unrelated projects like the example above. 

I've already tried killall -9 java several times with no success.

**Comment by petereddy** [comment] 2017-08-29 12:59
So I tried to reproduce the problem on another machine. It worked fine initially. I noticed that sdkman was not at the current version on the machine where grails was working fine, so I ran "sdk selfupdate". After that, I get the same failure on the second machine. I have no idea why that might be though, I didn't do any other operations through sdkman.

**Comment by petereddy** [comment] 2017-08-29 13:56
Uninstalling sdkman (rm -rf ~/.sdkman) and then removing it's initialization at the bottom of my ~/.bash_profile, then re-installing sdkman fixed the problem for me on one machine (the one that I'd mentioned was previously working) but, frustratingly, not on the original machine that had the problem.

**Comment by petereddy** [comment] 2017-08-29 15:53
If I don't use sdkman and instead install Grails manually the problem goes away. I'm not interested in pursuing the reasons why the sdkman installation doesn't work but if anyone else is and wants me to test something, I will happily do that.

**Comment by petereddy** [comment] 2017-08-31 19:20
This issue reoccured when I attempted to add a new dependency, and the steps above didn't fix it this time. Instead I had to add GRAILS_OPTS="-server -Xverify:none" to my environment. I suppose something's being corrupted at some point, but not sure where. In any case, that environment setting is a bad idea, especially in production environments. Posting it here in case it helps others.

**Comment by ilopmar** [comment] 2018-06-20 12:46
Closing it as not being able to reproduce it.

**Closed by ilopmar** 2018-06-20 12:46 UTC
Labels: Cannot Reproduce
