### ISSUE TITLE
Hibernate second level cache not works for newly created app 

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10346] opened 2016-12-07 20:03 UTC
Create app by grails 3.2.3

1.  Add domain with cache option in mapping
2.  enable SQL log
3.  load entity by id
4.  load same entity by id again 

In log I see query for second load, but it mast be loaded from cache
I have tried to add provider_class: net.sf.ehcache.hibernate.EhCacheProvider -- without success =(

### Example Application

https://github.com/demon101/grails-bug-10346

start app and open / page -- see one query in log (ok)
refresh page -- query again -- bug

**Comment by jeffbrown** [comment] 2016-12-07 21:40
This may be a duplicate of #10307

**Closed by jeffbrown** 2016-12-07 21:40 UTC
