### ISSUE TITLE
Grails 3 - YAML configuration causes properties with dots to be seperated

### ISSUE THREAD

**Issue by ckalan** [grails/grails-core#647] opened 2015-04-16 12:09 UTC
Let's say you have a "application.groovy" file in which you set a property like this:

```
'/**/favicon.ico' : 'permitAll' 
```

This is actually what we have been doing with spring security plugins or other url matching codes. Because of the dot ( . ) in the property key, YAML parses this config incorrectly as 

```
'/**/favicon': ['ico' : 'permitAll']
```
 which means you can't use dot in any property key. 

This is actually a spring problem but as discussed here

http://stackoverflow.com/questions/23350778/how-to-prevent-spring-boot-from-parsing-yaml-keys-with-dots

the solution may be to use some Grails specific PropertySource to handle this. 

This looks like an important issue because currently there is no easy workaround we could figure out except from loading & parsing configuration files manually.

**Comment by jeffbrown** [comment] 2015-04-16 16:28
I think this is a duplicate of #634.

**Comment by graemerocher** [comment] 2015-06-05 16:16
It isn't duplicate as the other related to .groovy files whilst this relates to .yml files

**Closed** 2015-06-08 13:25 UTC
Labels: Blocker, Configuration, In Progress
