### ISSUE TITLE
Grails 3.3.10 Plugin UrlMappings overwrites Default-UrlMappings

### ISSUE THREAD

**Issue by brischniz** [grails/grails-core#11335] opened 2019-05-28 16:01 UTC
Since Grails 3.3.10 the UrlMappings in my plugins overwrite the Default-UrlMappings in the Host-App. As I had a deeper look at it, it seems that there is a new class `IsGrailsPluginComparator` which sorts the UrlMappings at start time in the class `UrlMappingsHolderFactoryBean`.
Unfortunately it sorted wrong since the Default-UrlMappings are loaded before the plugin-UrlMappings. 

### Steps to Reproduce

1. Create a Default-UrlMapping (e.g. "/")
2. Create a plugin with a similar UrlMapping
3. Fire up the app - the UrlMapping of the plugin is used instead of the Default-UrlMapping

IMHO it should be sufficient to change the compare method of the `IsGrailsPluginComparator`  into the following:

```
public int compare(GrailsClass o1, GrailsClass o2) {
  if (o1.getPluginName() != null && o2.getPluginName() == null) {
    return -1;
  }
  if (o1.getPluginName() == null && o2.getPluginName() != null) {
    return 1;
  }
  return 0;
}
```

### Quickfix / Workaround
You can throw a fixed version of the `IsGrailsPluginComparator`  inside your app within the correct package. This should solve this problem for the moment.

**Comment by codeconsole** [comment] 2019-06-04 03:43
I experienced the same behavior in Grails 4. 
I had a plug-in with the out of the box UrlMappings create-plugin creates. I wasn’t sure what the problem was and since I wasn’t using the UrlMappings of the plugin, I deleted it and everything worked fine again.

Whatever fix is done for this will need to be pushed to 4.x

**Comment by demon101** [comment] 2019-06-11 15:00
got same bug after grails 3.3.9 -> 3.3.10 update

**Comment by jameskleeh** [comment] 2019-06-21 15:32
Fixed by https://github.com/grails/grails-core/commit/a7c608c94df430107c97307effdadf53f9155617

**Comment by jameskleeh** [comment] 2019-06-21 18:17
@demon101 @codeconsole @brischniz Can you please verify this is resolved with 3.1.11.BUILD-SNAPSHOT?

**Closed by jameskleeh** 2019-06-21 18:17 UTC
Labels: Bug

**Comment by demon101** [comment] 2019-07-09 08:58
@jameskleeh  nope, same bug. But Quickfix from description works well

**Comment by jameskleeh** [comment] 2019-07-09 13:27
@demon101 If you can reproduce in a sample app please upload it here. I wasn't able to reproduce the issue with this fix

**Comment by demon101** [comment] 2019-07-11 13:16
@jameskleeh  https://github.com/demon101/grails-11335
usually shows ok after start, but with plugin shows standard grails start page

> compile 'org.grails.plugins:iCalendar:0.6.3'

**Comment by jameskleeh** [comment] 2019-07-11 18:16
@demon101 I have pushed another fix - please give it a go

**Comment by demon101** [comment] 2019-07-12 12:59
@jameskleeh works well with snapshot
