### ISSUE TITLE
Grails console in 2.5.0 won't save objects with dateCreated and lastUpdated

### ISSUE THREAD

**Issue by kousen** [grails/grails-core#697] opened 2015-05-10 23:38 UTC
If you create a trivial domain class in 2.5.0:

    class Model {
        String name
        Date dateCreated
        Date lastUpdated
    }

with a scaffolded controller, then "run-app" works correctly. If you start the grails console instead:

    > grails console

Then you can't save a new object. Specifying `name` alone is not sufficient:

    Model m = new Model(name:'name').save()

then you get the following error:

```
org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value : Model.dateCreated; nested exception is org.hibernate.PropertyValueException: not-null property references a null or transient value : Model.dateCreated
```

Adding in a `dateCreated` field in the constructor:

    Model m = new Model(name:'name', dateCreated: new Date()).save()

doesn't change anything. You still get the same error.

**Comment by jeffbrown** [comment] 2015-05-10 23:53
Does the problem only happen in the console?

The fact that assigning it a value in the named arguments passed to the constructor doesn't work doesn't surprise me.  That is the designed and intended behavior.  The `dateCreated` field is `bindable: false` by default.  See https://github.com/grails/grails-core/blob/23461301a310956df6c8f7c49f12d189b906f55e/grails-web-databinding/src/main/groovy/org/grails/web/databinding/DefaultASTDatabindingHelper.java#L78.

**Comment by kousen** [comment] 2015-05-10 23:55
I tried it in a regular web app (i.e., run-app), and it was fine. It failed
in the console.

I didn't expect adding it to a constructor arg to matter; I just thought I
should try that before I reported the problem.

Ken

On Sun, May 10, 2015 at 7:53 PM, Jeff Scott Brown <notifications@github.com>
wrote:

> Does the problem only happen in the console?
>
> The fact that assigning it a value in the named arguments passed to the
> constructor doesn't work doesn't surprise me. That is the designed and
> intended behavior. The dateCreated field is bindable: false by default.
> See
> https://github.com/grails/grails-core/blob/23461301a310956df6c8f7c49f12d189b906f55e/grails-web-databinding/src/main/groovy/org/grails/web/databinding/DefaultASTDatabindingHelper.java#L78
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grails/grails-core/issues/697#issuecomment-100716492>.
>



-- 
Kenneth A. Kousen
President
Kousen IT, Inc.

**Comment by jeffbrown** [comment] 2015-05-11 00:01
Will look into it.  I expect something is wrong with the `ClosureEventListener` registration.  Should be easy enough to track down. Thanks for the feedback.

**Comment by jeffbrown** [comment] 2015-05-11 00:02
I didn't intend to close the issue after my first comment.  I clicked "Close and comment" instead of "Comment".  Sorry about that.  It is re-opened now.

**Comment by irstevenson** [comment] 2015-05-29 06:17
Seeing the same problem in grails 2.4.4. Domain class works fine in integration tests, no good in grails console.

And for completeness, it's also on the dataCreated field:
```
org.springframework.dao.DataIntegrityViolationException: not-null property references a null or transient value : todo.Project.dateCreated; nested exception is org.hibernate.PropertyValueException: not-null property references a null or transient value : todo.Project.dateCreated
```

**Closed** 2015-05-29 13:20 UTC
Labels: Blocker, In Progress, v2.5.1

**Comment by jiromgir2013** [comment] 2015-07-21 08:03
hello, 

 ¿ is there any manner of testing domain classes which contains dateCreated ?

**Comment by biniama** [comment] 2016-08-25 12:34
Which version of HIbernate shall I use to get this update?
Thanks.
