### ISSUE TITLE
Grails 3.2.4: <g:include> causes that the application does not stop

### ISSUE THREAD

**Issue by atasc** [grails/grails-core#10411] opened 2017-01-17 16:01 UTC
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Full description
Using <g:include view="..."/> inside a gsp page causes that the application does not stop.
If the <g:include view="..."/> is removed the application stops correctly.

### Steps to Reproduce

1. create an empty 3.2.4 app
2. create a controller (TestController) and an action (index)
3. create a view for the action TestController->index (grails-app/views/test/index.gsp)
4. create a gsp to include (grails-app/views/test/test_include.gsp)
5. Add <g:include view="/test/test_include.gsp"/> to index.gsp
6. in a terminal run the command "grails run-app"
7. open http://localhost:8080/test/index
8. press "ctrl+c"
9. check your process list (ps -e), you can see two Java processes appended
10. run the command "grails run-app" again, you'll get the exception "java.net.BindException: Address already in use" 

### Expected Behaviour

The application stops, all the java process are closed and the tcp port released.

### Actual Behaviour

The application stops to respond to http requests but the Java processes are not closed and the tcp port continues to be in use.

### Environment Information

- **Operating System: Linux 64 bit
- **Grails Version: 3.2.4
- **JDK Version: 1.8.0_111

### Example Application
[myapp.zip](https://github.com/grails/grails-core/files/711592/myapp.zip)

**Comment by jeffbrown** [comment] 2017-01-17 17:50
I can't reproduce this.  Will ask another team member to test.

**Comment by jameskleeh** [comment] 2017-01-17 21:39
@jeffbrown I can't reproduce with the same application

**Comment by atasc** [comment] 2017-01-17 22:30
open http://localhost:8080/test/index after run-app and then press ctrl-c

**Comment by jeffbrown** [comment] 2017-01-17 22:43
> open http://localhost:8080/test/index after run-app and then press ctrl-c

That did it.

**Comment by snimavat** [comment] 2017-03-24 04:51
This seem to happen only when the view includes another view.. works fine as long as the view includes another controller/action

**Comment by benrhine** [comment] 2018-05-07 13:13
Doing research related to #10991 and #10424. This also does not happen if you run using gradle

`./gradlew bootRun`

**Comment by bobbywarner** [comment] 2020-07-01 04:54
Closing as this no longer happens with Grails 4.0.3

**Closed by bobbywarner** 2020-07-01 04:54 UTC
Labels: status: acknowledged
