### ISSUE TITLE
[3.1.8] GORM unavailable for Domain Class suffixed as *Service.groovy

### ISSUE THREAD

**Issue by dmahapatro** [grails/grails-core#10010] opened 2016-06-23 21:03 UTC
GORM operations are not possible on Domain class with suffix as `*Service.groovy`. For example, dynamic finders, where queries, criteria and even named queries will be available for a domain class with name `SpecialService`. If the domain class name is changed to anything else (say, `SpecialServiceDomain` or `SpecialServiceFoo`) then everything works fine. Sample app has  integration tests to show case the same.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run `gradle check` on [sample app](https://github.com/dmahapatro/domain-name-issue/tree/master/src/integration-test/groovy/com/example)

### Expected Behaviour
Expected `SpecialService` should be recognized as a domain class and test should pass for this domain class

### Actual Behaviour
Integration Test fail for domain class with name `SpecialService` but passed for a domain class with name `SpecialServiceDomain`

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.1.8
- **JDK Version:** 1.8_91
- **Container Version (If Applicable):** Embedded TC

### Example Application
https://github.com/dmahapatro/domain-name-issue/tree/master/src/integration-test/groovy/com/example

**Comment by jeffbrown** [comment] 2016-06-23 21:05
I think this is a duplicate of #9195

**Closed by jeffbrown** 2016-06-23 21:05 UTC
Labels: Duplicate
