### ISSUE TITLE
registerObjectMarshaller() does not seem to work in an integration test environment

### ISSUE THREAD

**Issue by sarbogast** [grails/grails-core#10475] opened 2017-02-14 15:51 UTC
I had a certain number of integration tests in my 3.2.3 application that passed perfectly, and that are now failing miserably in 3.2.6 without any other change.

The problem is that I am using `JSON.registerObjectMarshaller()` to register a closure that will convert any Enum instance value to the result of its `toString()` method.

What is even weirder is that the object marshaller seems to work perfectly when the app is run in the browser.

The base project that works like it should is there: https://github.com/sarbogast/MyApp323
The upgraded project that works as intended with run-app but fails on test-app: https://github.com/sarbogast/MyApp326

**Comment by jameskleeh** [comment] 2017-02-14 16:45
I think this is a duplicate of https://github.com/grails-plugins/grails-rest-client-builder/issues/34

**Comment by graemerocher** [comment] 2017-02-14 16:55
11 days old is old?

**Comment by jameskleeh** [comment] 2017-02-14 16:56
@sarbogast I edited my comment to link to the correct issue that was reported recently

**Comment by sarbogast** [comment] 2017-02-14 16:57
Indeed, I was looking at the old linked, number 34

**Comment by sarbogast** [comment] 2017-02-14 16:58
The thing is that in my sample application, I'm not using a restBuilder bean at all, I am calling new RestBuilder() inside the test.

**Comment by jeffbrown** [comment] 2017-02-14 17:03
https://github.com/sarbogast/MyApp326/pull/1 shows 1 way to make it work.

**Comment by jameskleeh** [comment] 2017-02-14 19:16
The fix will be in the next GORM 6.0.x release: https://github.com/grails/grails-data-mapping/commit/0be3beae85c87f9a03f615c50553852f438fcfd3

**Closed by jameskleeh** 2017-02-14 19:16 UTC
