### ISSUE TITLE
https://repo.grails.org/grails/plugins certificate got expired today 8/28/2018

### ISSUE THREAD

**Issue by sujithsas** [grails/grails-core#11084] opened 2018-08-28 16:38 UTC
Thanks for reporting an issue for Grails framework, please review the task list below before submitting the 
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

### Steps to Reproduce

1. https://repo.grails.org/grails/plugins in the browser and check for certificate end date and validity

### Expected Behaviour

The certificate should be valid and secured

### Actual Behaviour

Invalid certificate.The garils run app would fail if we try to download any plugin 

### Environment Information

- **Operating System**: Any
- **Grails Version:** Any
- **JDK Version:** Any
- **Container Version (If Applicable):** Any

**Comment by jeffbrown** [comment] 2018-08-28 16:40
I think this is a duplicate of #11082

**Closed by jeffbrown** 2018-08-28 16:40 UTC
