### ISSUE TITLE
Trouble using controller with traits having action with parameters

### ISSUE THREAD

**Issue by bdbogjoe** [grails/grails-core#10560] opened 2017-03-31 10:02 UTC
I'm trying to use traits for controllers to avoid duplication of code, but seems parameters are not given to the method as argument, see description of the sample app below for details

### Environment Information

- **Operating System**: linux
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_121

### Example Application

https://github.com/bdbogjoe/grails-controller-trait

**Comment by graemerocher** [comment] 2017-03-31 10:29
Try annotating the method with `@Action`

**Comment by bdbogjoe** [comment] 2017-03-31 10:30
done already : https://github.com/bdbogjoe/grails-controller-trait/blob/master/src/main/groovy/controller/trait/ShowTrait.groovy#L11

**Comment by snimavat** [comment] 2017-03-31 11:19
The issue is [here](https://github.com/snimavat/grails-core/blob/fed687f1c60150e1d8be14bd761d6f1d07317d6c/grails-plugin-controllers/src/main/groovy/org/grails/compiler/web/ControllerActionTransformer.java#L696-L696), when ControllerActionTransformer runs, the argument names of the action method is changed to arg1, arg2 etc, do it does not find it in params.

Putting @RequestParameter on argument dint work either, because some how, those annotations doesnt work on trait method arguments, and  param.getAnnotations returns nothing

**Comment by jameskleeh** [comment] 2017-03-31 14:24
A workaround for this would be to use a command object that contained an id property

**Comment by snimavat** [comment] 2017-03-31 14:58
@jameskleeh probably this is some thing related to groovy itself ? -- even without grails, when i compile a groovy project, even with debug information, i see that the method argument names are changed in traits, but not for regular classes !

**Comment by jameskleeh** [comment] 2017-03-31 16:42
Fixed by https://github.com/grails/grails-core/commit/6da4fe308c91bd24961f9498b778790fcfaf5f8c

**Closed by jameskleeh** 2017-03-31 16:42 UTC
Labels: Acknowledged

**Comment by bdbogjoe** [comment] 2017-03-31 17:30
Thanks ! So fast, great 👍
