### ISSUE TITLE
Multiple datasource not working as documented for grails 3.3.0.M1 had been working on 3.2.8

### ISSUE THREAD

**Issue by vahidhedayati** [grails/grails-core#10650] opened 2017-05-25 16:34 UTC
https://github.com/vahidhedayati/grails330multipledatasource

In short when attempting to add a second data source a variety of problems caused underlying issue appears to be:

Expression parsing failed; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'dataSource' cannot be found on null

The purpose of the upgrade was to test if encodeAsRaw had been fixed which appears to be still an issue. 

Is there a reason why things that had been working perfectly fine under 2 and certain earlier versions of grails 3 are recently breaking/broken ?

**Comment by genuinefafa** [comment] 2017-05-27 23:26
Is there any workaround for this? I'm starting a new project and would like to use 3.3.x since will be launching in a few months... (by that time 3.3.0 will be out probably)

**Comment by vahidhedayati** [comment] 2017-05-28 11:38
Hi genuinefafa on my local app I had done further tests. I think moving the default dsn  outside of the data sources block for the main call and environmental blocks appeared to change error and appears to have moved on from that error. I don't think it was quite working after it but it wasn't a small demo project to know for sure if that had worked. Worth a test on for example a small project like above. Sorry not on pc to be testing it all again

**Comment by sdelamo** [comment] 2017-05-28 12:19
I will take a look into this early tomorrow

**Comment by sdelamo** [comment] 2017-05-29 04:19
A workaround is replace this block with: 

```
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

dataSources:
    lookup:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost/lookup
        dbCreate: update

environments:
    development:
        dataSources:
            dataSource:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            lookup:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
                driverClassName: com.mysql.jdbc.Driver
                username: root
                password: root
                url: jdbc:mysql://localhost/lookup
                dbCreate: update
    test:
        dataSources:
            dataSource:
                dbCreate: update
                url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSources:
            dataSource:
                dbCreate: update
                url: jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
                properties:
                   jmxEnabled: true
                   initialSize: 5
            lookup:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
                driverClassName: com.mysql.jdbc.Driver
                username: root
                password: root
                url: jdbc:mysql://localhost/lookup
                dbCreate: update
```

with: 

```
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
---
dataSources:
    lookup:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost/lookup
        dbCreate: update
environments:
    development:
        dataSources:
            lookup:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
                driverClassName: com.mysql.jdbc.Driver
                username: root
                password: root
                url: jdbc:mysql://localhost:8889/lookup
                dbCreate: update
    production:
        dataSources:
            lookup:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
                driverClassName: com.mysql.jdbc.Driver
                username: root
                password: root
                url: jdbc:mysql://localhost:8889/lookup
                dbCreate: update
```

**Comment by zyro23** [comment] 2017-05-29 05:53
ref. grails/gorm-hibernate5#25 - if the "new" syntax is the only supported one from grails-3.3 on (good! less confusion.), could the current state of the database-migration plugin be released? 3.0.0 does only support the legacy syntax. and the pr supporting the new syntax is already merged (grails-plugins/grails-database-migration#123). thanks!

**Comment by graemerocher** [comment] 2017-05-29 10:22
Changes documented here https://github.com/grails/gorm-hibernate5/commit/e3c66520c2a6c0564dad6722cbaeca8cdc533a5a

**Closed by graemerocher** 2017-05-29 10:22 UTC
Labels: Documentation, Not a Bug, Workaround Available

**Comment by genuinefafa** [comment] 2017-05-29 14:38
I can confirm that the domain class is now running;

But i'm having an issue with `@Resource` tag, throwing a "Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread" not sure if it is related... since is not the `dataSource` but the secondary one.

**Comment by graemerocher** [comment] 2017-05-29 14:55
Use a join query to fetch your data or alternatively you can enable `hibernate.enable_lazy_load_no_trans` for the secondary data source. Note that this has performance implications. See https://vladmihalcea.com/2016/09/05/the-hibernate-enable_lazy_load_no_trans-anti-pattern/

**Comment by genuinefafa** [comment] 2017-05-29 21:19
@graemerocher it is a simple domain class with a composite id; actually, i did try to avoid using multiple databases and got #10653 

but in this case, i tried using in `application.yml`

```yml
hibernate:
    enable_lazy_load_no_trans: true
dataSource:
    # default db
environments:
    development:
        dataSource:
            # default db
        dataSources:
            extra:
                pooled: true
                readOnly: true
                hibernate:
                    enable_lazy_load_no_trans: true
```


same issue, this is the entire stacktrace

```trace
java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
        at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:329)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:285)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:116)
        at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.count(AbstractHibernateGormStaticApi.groovy:152)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.count(GormEntity.groovy:621)
        at grails.rest.RestfulController.countResources(RestfulController.groovy:277)
        at grails.rest.RestfulController.index(RestfulController.groovy:64)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        ... 14 common frames omitted
Caused by: org.hibernate.HibernateException: No Session found for current thread
        at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
        at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:688)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:327)
        ... 24 common frames omitted
```

**Comment by graemerocher** [comment] 2017-05-30 10:44
The is using the default data source, you need to add `@Transactional` and specify the connection name. See http://gorm.grails.org/6.1.x/api/grails/gorm/transactions/Transactional.html#connection

**Comment by graemerocher** [comment] 2017-05-30 12:11
Just to clarify you can setup transaction management for a controller for another data source with:

```
@Transactional("mySecondaryDataSource")
```

Using `@Transactional` by itself results in using the default data source. The `@Resource` tag using `@Transactional` by itself and hence doesn't apply the correct transaction manager.

You therefore must create a `RestfulController` that applies the correct transaction manager.

Another option is to enable chained transaction management for the application. However, this has performance implications. See http://docs.grails.org/3.3.x/guide/upgrading.html

Section "TransactionManager Chaining for Multiple Data Sources Disabled by Default"

**Comment by genuinefafa** [comment] 2017-05-30 12:21
I get it now... The TransactionManager Chaining will do the trick for me, since:
 * i'm using a readOnly connection (no transaction needed anyway)
 * the default datasource is on memory

**Comment by sdelamo** [comment] 2017-06-07 18:35
@zyro23 I have released version [3.0.1](https://bintray.com/grails/plugins/database-migration/3.0.1) of [Database Migration Plugin](https://github.com/grails-plugins/grails-database-migration)

**Comment by zyro23** [comment] 2017-06-07 18:42
@sdelamo perfect, thanks. i saw you also made some docs adjustments reg. the multi-datasource syntax. could you maybe maybe take a look at grails/gorm-hibernate5#25 - perhaps that can now just be closed?

**Comment by erodrig** [comment] 2018-01-08 09:38
When having that kind of configuration:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        dataSources:           
            lookup:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
                driverClassName: com.mysql.jdbc.Driver
                username: root
                password: root
                url: jdbc:mysql://localhost/lookup
                dbCreate: update
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
        dataSources:           
            lookup:
                dialect: org.hibernate.dialect.MySQLInnoDBDialect
                driverClassName: com.mysql.jdbc.Driver
                username: root
                password: root
                url: jdbc:mysql://localhost/lookup
                dbCreate: update



I can inject lookup as "datasource_lookup" inside my services but trying to inject the default datasource do not longer work, when having multiple datasources.
Injection only detects datasources in the "        dataSources:           " section of the yml

**Comment by romaicus** [comment] 2018-11-14 00:00
I have noticed that lazy loading works if we specify datasource name on "@Transactional" annotation - does it mean that now we can only use data from one datasource in a controller?
[](https://github.com/romaicus/grails-nondefault-datasource-lazy-loading-fail/commit/139e0ee20db80dcd6b59e3bf847d61fe3c3693a7)
