### ISSUE TITLE
Grails 3.0.1: Text field of property without explicit `blank:true` has wrong `required` attribute

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#8998] opened 2015-06-04 12:22 UTC
`validate()` works expectedly. But the generated create.gsp and edit.gsp have unnecessary `required` attribute on the text field.

**Comment by nobeans** [comment] 2015-06-04 12:25
reproducible example: https://github.com/nobeans/grails3-sample-issue8998
See http://localhost:8080/book/create after run it.

**Comment by nobeans** [comment] 2015-06-04 12:57
I've realized that even if "required" attribute goes away by a fix, the blank value converts to null by data binder, then violation for "nullable:false" occurs. 
To fix this, both to remove "required" attribute and add "grails.databinding.convertEmptyStringsToNull=false" to application.* are required.

It's not instinctive...

**Comment by graemerocher** [comment] 2015-06-04 13:18
I think this subject has been covered before @jeffbrown can comment

**Comment by jeffbrown** [comment] 2015-06-15 14:29
I haven't looked into it yet but since this is related to the generated input fields, I suspect this is probably an issue for the fields plugin.  Is the text field in question being generated by the `<f:all ...` tag?

**Comment by jeffbrown** [comment] 2015-06-15 14:39
The piece of this that relates to the data binder converting empty strings to null is behaving as designed.  Unless `grails.databinding.convertEmptyStringsToNull` is set to false, the binder is supposed to convert empty strings to null.  Is it the case that the thing in question here is whether or not `<f:all ...` should be generating the `required` attribute?

**Comment by nobeans** [comment] 2015-06-16 01:33
> Is the text field in question being generated by the <f:all ... tag?

Yes.

* https://github.com/nobeans/grails3-sample-issue8998/blob/master/grails-app/domain/grails3/blank/sample/Book.groovy#L12
* https://github.com/nobeans/grails3-sample-issue8998/blob/master/grails-app/views/book/create.gsp#L30

> Is it the case that the thing in question here is whether or not <f:all ... should be generating the required attribute?

Perhaps, yes.

**Comment by Schlogen** [comment] 2016-08-12 13:52
@jeffbrown The problem is here: https://github.com/grails-fields-plugin/grails-fields/blob/5a8e7a4e95cfa062798c554692a3defc4aa91eb5/src/groovy/grails/plugin/formfields/BeanPropertyAccessorImpl.groovy#L72

If the property returns `false`, it uses the default - which is `true`.

**Comment by jameskleeh** [comment] 2016-08-30 15:38
Fixed in the fields plugin version 2.1.3 via https://github.com/grails-fields-plugin/grails-fields/commit/a74953c1e8459ddd17a4ac4bbf703cd4d099411e

**Closed by jameskleeh** 2016-08-30 15:38 UTC
Labels: Acknowledged, v3.x
