### ISSUE TITLE
No signature of method: java.lang.String.encodeAsHTML()

### ISSUE THREAD

**Issue by jglapa** [grails/grails-core#10715] opened 2017-07-05 09:18 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run the example app from here: https://github.com/jglapa/grails-javamelody-issue/
2. open localhost:8080 in browser
3. exception will be thrown

### Expected Behaviour

no exception

### Actual Behaviour

This affects version 3.2.11 and plugin java-melody. Without this plugin the app starts without problems. When the plugin is added the following exception is thrown upon `<g:link>` generation.

```
2017-07-05 11:12:33.471 ERROR --- [nio-8080-exec-1] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/index.gsp:58] Error executing tag <g:link>: No signature of method: java.lang.String.encodeAsHTML() is applicable for argument types: () values: []
Possible solutions: encodeAsHex(), encodeAsMD5(), encodeAsSHA1(), encodeAsSHA256()] with root cause

groovy.lang.MissingMethodException: No signature of method: java.lang.String.encodeAsHTML() is applicable for argument types: () values: []
Possible solutions: encodeAsHex(), encodeAsMD5(), encodeAsSHA1(), encodeAsSHA256()
        at org.grails.plugins.web.taglib.ApplicationTagLib$_closure7.doCall(ApplicationTagLib.groovy:225)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:417)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
        at Users_jglapa_jglapa_github_javaMelodyIssue_grails_app_views_index_gsp$_run_closure2.doCall(Users_jglapa_jglapa_github_javaMelodyIssue_grails_app_views_index_gsp:71)
        at org.grails.taglib.TagBodyClosure.executeClosure(TagBodyClosure.java:200)
        at org.grails.taglib.TagBodyClosure.captureClosureOutput(TagBodyClosure.java:102)
        at org.grails.taglib.TagBodyClosure.call(TagBodyClosure.java:213)
        at org.grails.plugins.web.taglib.SitemeshTagLib.captureTagContent(SitemeshTagLib.groovy:48)
        at org.grails.plugins.web.taglib.SitemeshTagLib$_closure3.doCall(SitemeshTagLib.groovy:156)
        at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:417)
        at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
        at Users_jglapa_jglapa_github_javaMelodyIssue_grails_app_views_index_gsp.run(Users_jglapa_jglapa_github_javaMelodyIssue_grails_app_views_index_gsp:83)
        at org.grails.gsp.GroovyPageWritable.doWriteTo(GroovyPageWritable.java:162)
        at org.grails.gsp.GroovyPageWritable.writeTo(GroovyPageWritable.java:82)
        at org.grails.web.servlet.view.GroovyPageView.renderTemplate(GroovyPageView.java:76)
        at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
        at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.grails.web.sitemesh.GrailsLayoutView.renderInnerView(GrailsLayoutView.java:150)
        at org.grails.web.sitemesh.GrailsLayoutView.obtainContent(GrailsLayoutView.java:128)
        at org.grails.web.sitemesh.GrailsLayoutView.renderTemplate(GrailsLayoutView.java:63)
        at org.grails.web.servlet.view.AbstractGrailsView.renderWithinGrailsWebRequest(AbstractGrailsView.java:71)
        at org.grails.web.servlet.view.AbstractGrailsView.renderMergedOutputModel(AbstractGrailsView.java:55)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:230)
        at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

### Environment Information

- **Operating System**: macOS Sierra
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_121

### Example Application

https://github.com/jglapa/grails-javamelody-issue/

**Comment by graemerocher** [comment] 2017-07-05 11:09
See https://github.com/javamelody/grails-melody-plugin/issues/43

**Comment by jglapa** [comment] 2017-07-05 12:52
I was also first thinking of raising the issue for the plugin but this started breaking in `3.2.11`  out of nowhere. 
It's as if the meta methods for String class are not registering. The plugin was working fine up till now (also the previous versions). 
I have a feeling that the plugin maintainer will bounce the ball back here.

**Comment by graemerocher** [comment] 2017-07-05 13:09
My guess is something to do with the Groovy version, Groovy 2.4.11 is used in 3.2.11

**Comment by evernat** [comment] 2017-07-09 23:09
I have reproduced the issue using the sample project https://github.com/jglapa/grails-javamelody-issue/
If adding `compile 'org.codehaus.groovy:groovy-all:2.4.8'` in build.gradle of that sample, the issue disappears. If adding 2.4.9 or 2.5.0-beta-1 the issue appears again.
So it seems that the issue is caused by groovy 2.4.9 and not by the grails-melody-plugin.
For people searching the groovy 2.4.9 changelog, here it is: http://groovy-lang.org/changelogs/changelog-2.4.9.html

**Comment by graemerocher** [comment] 2017-07-10 06:37
Seems worthy of an issue report to https://issues.apache.org/jira/projects/GROOVY

**Comment by jglapa** [comment] 2017-07-10 10:26
@graemerocher how would you approach submitting an issue to Groovy about Grails related issue?
Looks like the meta methods `String.encodeAs*` are not being registered by Grails any more or something is removing those when the plugin is used.
Could you provide a code pointer where those method meta methods are created right now in Grails?

**Comment by graemerocher** [comment] 2017-07-10 10:54
Nothing has changed in the Grails side in this area for a long time. The methods are registered by this class https://github.com/grails/grails-core/blob/master/grails-encoder/src/main/groovy/org/grails/encoder/CodecMetaClassSupport.groovy#L44

**Comment by bassmartin** [comment] 2017-07-12 19:13
I confirm workaround of 

> adding compile 'org.codehaus.groovy:groovy-all:2.4.8' in build.gradle

is working

**Comment by paulk-asert** [comment] 2017-07-12 21:51
Still investigating but `git bisect` says:
```
# first bad commit: [b18062a9e524512769e370b1e204a6df5a35c03e] GROOVY-8067: Possible deadlock when creating new ClassInfo entries in the cache (closes #489)
```

**Comment by jglapa** [comment] 2017-07-13 07:53
FYI the plugin starts working fine when it's packaged with grails version using groovy `>2.4.9`
see here: https://github.com/javamelody/grails-melody-plugin/issues/43#issuecomment-314929657

**Comment by jwagenleitner** [comment] 2017-07-17 00:20
Prior to the commit that Paul mentioned the `clearModifiedExpandos` method didn't actually clear all expando metaclasses ([see this comment for details](https://issues.apache.org/jira/browse/GROOVY-8067?focusedCommentId=16088680&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16088680)).  This was fixed as a side-effect from the fix for [GROOVY-8067](https://issues.apache.org/jira/browse/GROOVY-8067).  The [`ExpandoMetaClass#enableGlobally` call in the grails-melody-plugin](https://github.com/javamelody/grails-melody-plugin/blob/4da5c1e7092f7841e6133fd790baa0419340a6ad/src/main/groovy/grails/melody/plugin/MelodyInterceptorEnhancer.groovy#L32) triggers a call to `clearModifiedExpandos` which now clears the `encodeAsHTML` method set to Grails.

This is just from a quick look and I may be missing something.  Since I am not sure how the above can be fixed by compiling the plugin against a newer Grails.

**Comment by graemerocher** [comment] 2017-07-24 02:35
Melody plugin shouldn't be calling enableGlobally in Grails 3. This is therefore a bug in the melody plugin and this line https://github.com/javamelody/grails-melody-plugin/blob/4da5c1e7092f7841e6133fd790baa0419340a6ad/src/main/groovy/grails/melody/plugin/MelodyInterceptorEnhancer.groovy#L32 needs to be removed

**Closed by graemerocher** 2017-07-24 02:35 UTC
Labels: Won't Fix
