### ISSUE TITLE
Grails 3.x performance issue

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10463] opened 2017-02-10 10:51 UTC
### Task List
- [X] Steps to reproduce provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create simple grails 2 app
2. Create same app on Grails 3
3. compare results by siege

### Expected Behaviour

Performance of Grails 3 app should be same with Grails 2 

### Actual Behaviour

Performance of Grails 3 app **36%** less then Grails 2 

### Environment Information

- **JDK Version:** jdk1.8.0_121.jdk

### Example Application

- https://github.com/demon101/grails-performance

For performance test siege has been used (with warm up)

siege -c 100 -b -r 200 http://localhost:8080/index/index/1 
siege -c 100 -b -r 200 http://localhost:8080/grails2/index/index/1

Actually, on our production app, after grails migration 2.4.5-> 3.1.15 we get 2,5x performance degradation. With groovy 2.4.8 it's become better, 1,3x performance degradation
On simple app groovy 2.4.8 don't increase performance. But on production with thousands users per day it shows real performance improvement

**Comment by demon101** [comment] 2017-02-10 12:48
siege -c 100 -b -r 200  http://localhost:8080/grails2/index/index/1

## grails 2.4.5

```
Transactions:		       20000 hits
Availability:		      100.00 %
Elapsed time:		        8.67 secs
Data transferred:	       16.59 MB
Response time:		        0.04 secs
Transaction rate:	     2306.81 trans/sec
Throughput:		        1.91 MB/sec
Concurrency:		       96.01
```

siege -c 100 -b -r 200  http://localhost:8080/index/index/1

## Grails 3.2.6:

```
Transactions:		       20000 hits
Availability:		      100.00 %
Elapsed time:		       11.95 secs
Data transferred:	       29.18 MB
Response time:		        0.06 secs
Transaction rate:	     1673.64 trans/sec
Throughput:		        2.44 MB/sec
Concurrency:		       97.65
```

full report on https://github.com/demon101/grails-performance/blob/master/README.md

**Comment by graemerocher** [comment] 2017-02-10 13:17
So I tested both apps. For the Grails 3 app I did `grails prod war` and then ran:

```
java -Xmx2048M -Xms256M -jar grails3-0.1.war
```

Followed by

```
siege -c 100 -b -r 200 http://localhost:8080/index/index/1
```

The results were 

```
Transactions:              20000 hits
Availability:              100.00 %
Elapsed time:              38.97 secs
Data transferred:          29.04 MB
Response time:              0.06 secs
Transaction rate:         510.65 trans/sec
Throughput:             0.75 MB/sec
Concurrency:               31.55
Successful transactions:       20000
Failed transactions:               0
Longest transaction:            1.12
Shortest transaction:           0.00
```
I ran this on my dev machine which is probably slower than what you are testing on.

Since you can't create a runnable WAR with Grails 2 I built the WAR and deployed to Tomcat 7.0.65 running with the same JVM memory arguments.

The results were:

```
Transactions:              20000 hits
Availability:             100.00 %
Elapsed time:              45.70 secs
Data transferred:          16.59 MB
Response time:              0.22 secs
Transaction rate:         437.64 trans/sec
Throughput:             0.36 MB/sec
Concurrency:               97.22
Successful transactions:       20000
Failed transactions:               0
Longest transaction:           20.15
Shortest transaction:           0.00
```
So so far I am not seeing the behaviour you are describing. Maybe if you tell us more about how you are deploying etc.

**Comment by demon101** [comment] 2017-02-10 13:35
@graemerocher , have you warm up started app?

For test I just run app by run-app & bootRun

For prod env, we build app by war command and deploy it to tomcat 8

**Comment by demon101** [comment] 2017-02-10 13:41
@graemerocher could you deploy grails 3 app to same for testing tomcat?
For me, on dev pc, runnable war app slower then run-app

**Comment by graemerocher** [comment] 2017-02-10 14:56
You cannot just use `run-app` or `bootRun` since development mode is slower due to spring loaded, reloading, lack of caching etc. so it isn't a valid test.

I will test deploying to Tomcat instead of a runnable war no problem.

**Comment by demon101** [comment] 2017-02-10 15:01
> so it isn't a valid test.
Agree!

I will test with deployment to tomcat. But we have really huge performance degradation on production after migration to grails 3 and it's not a problem of dev mode

**Comment by benorama** [comment] 2017-02-10 20:46
Interesting, I have the same feeling: after our migration to Grails3 and launch to prod (2 weeks ago), we had to add around 30% more servers to handle load.
No that we have iron out remaining bugs linked to our migration and stabilized our platform, we are going to work on performance optimization to see if we can match previous performance.
So I'll follow this discussion with interest and let you know if we found anything.
Thanks.

**Comment by mkuchin** [comment] 2017-02-13 09:27
I'd changed datasource configuration for test at https://github.com/demon101/grails-performance
Previous version generated errors in the production environment. 

Tested war files were deployed into Tomcat 8.5.11 with Java 1.8.0_121 on Ubuntu 16.04 Digital Ocean 2Gb instance. 
Tomcat running with `-Xmx1024M` in CATALINA_OPTS.

grails 3 war was built with the command:
    
    ./gradlew war

grails 2 war was built with the command:
   
    ./grailsw war

Before testing I preheat JVM with 

    siege -c 100 -b -r 500 http://localhost:8080/index/index/1

then test with the command:

    siege -c 100 -b -r 500 http://localhost:8080/index/index/1

My results:
## Grails 3.1.15 with groovy 2.4.8 

```
Transactions:		       20000 hits
Availability:		      100.00 %
Elapsed time:		       20.80 secs
Data transferred:	       29.18 MB
Response time:		        0.10 secs
Transaction rate:	      961.54 trans/sec
Throughput:		        1.40 MB/sec
Concurrency:		       97.90
Successful transactions:       20000
Failed transactions:	           0
Longest transaction:	        0.54
Shortest transaction:	        0.00
```

## Grails 2.4.5 

```
Transactions:		       20000 hits
Availability:		      100.00 %
Elapsed time:		       21.61 secs
Data transferred:	       16.59 MB
Response time:		        0.11 secs
Transaction rate:	      925.50 trans/sec
Throughput:		        0.77 MB/sec
Concurrency:		       97.89
Successful transactions:       20000
Failed transactions:	           0
Longest transaction:	        0.54
Shortest transaction:	        0.00
```

## Grails 3.1.15 with default Groovy version

```
Transactions:		       20000 hits
Availability:		      100.00 %
Elapsed time:		       21.96 secs
Data transferred:	       29.18 MB
Response time:		        0.11 secs
Transaction rate:	      910.75 trans/sec
Throughput:		        1.33 MB/sec
Concurrency:		       97.72
Successful transactions:       20000
Failed transactions:	           0
Longest transaction:	        0.69
Shortest transaction:	        0.00
```

**Comment by jagiro** [comment] 2017-02-13 10:18
@benorama,

I also feel it slower. 
It is not always. At the moment I can't reproduce it, but sometimes some queries that took 1s now take 10s. 

In production I have 2.5.0 and now I am thinking migrate to 3.2.4.

**Comment by graemerocher** [comment] 2017-03-06 10:33
Closing this until a concrete example of a performance degradation can be produced

**Closed by graemerocher** 2017-03-06 10:33 UTC
Labels: Awaiting Feedback, Cannot Reproduce
