### ISSUE TITLE
Performance degradation after 3.1.15 -> 3.2.8 migration

### ISSUE THREAD

**Issue by demon101** [grails/grails-core#10589] opened 2017-04-18 07:10 UTC
@jeffbrown After update from 3.1.15 to 3.2.8 CPU load was increased:

![tomcat-time-day](https://cloud.githubusercontent.com/assets/1362920/25101332/2ace1284-23b4-11e7-94ba-7683f4c579c2.png)

In global, CPU load changned from 55% to 90% for same user activity

**Comment by graemerocher** [comment] 2017-04-18 08:39
like anything we will need an example that reproduces the issue

**Comment by demon101** [comment] 2017-04-18 09:16
What is the major difference between 3.1.15 and 3.2.8? GORM only?
I know about the example, but creating of it -- not trivial.

**Comment by graemerocher** [comment] 2017-04-18 09:18
There are too many differences to list here and performance issues may be application level or framework level. Hence we need an example.

**Comment by demon101** [comment] 2017-04-18 09:27
@graemerocher I think, it a framework level. 
we have had problems during migration from 2.4 to 3.1. Most of them had been caused by framework changes.
I have few application with simple business logic (usualy read only) but with 30-100K simultaneous sessions and 50-150 req/sec (only to tomcat) 

it is difficult to create simple demonstration example. I need to know, approximate direction of the search for example preparation

**Comment by graemerocher** [comment] 2017-04-18 09:38
The key phrase in your comment is "I think", which takes us no where.

**Comment by demon101** [comment] 2017-04-18 09:40
@graemerocher  is it stop phrase for you? =)

**Comment by graemerocher** [comment] 2017-04-18 09:41
No, but there is not enough information is this issue report to take it forward.

**Comment by demon101** [comment] 2017-04-18 09:42
@graemerocher In few days I will try to downgrade GORM and compare performance.  
Will write results

**Comment by graemerocher** [comment] 2017-04-28 07:01
Closing as cannot reproduce

**Closed by graemerocher** 2017-04-28 07:01 UTC
Labels: Awaiting Feedback, No Example Attached

**Comment by demon101** [comment] 2017-05-04 12:27
<img width="777" alt="screen shot 2017-05-04 at 14 20 35" src="https://cloud.githubusercontent.com/assets/1362920/25703230/f919c2aa-30d4-11e7-9b10-421bcffb9636.png">
Black line -- upgraded grails 3.1.15 ->3.2.9 without significant changes in app
After upgrade to grails 3.2.9
1. very tight run: request processing time was about 300ms 
2. CPU usages increased two times
3. Request tomcat processing time increased from 20ms to 40ms

We will return to grails 3.1.15, 3.2.9 not production ready

**Comment by graemerocher** [comment] 2017-05-04 12:42
Provide an example that reproduces the issue and we can take a look

**Comment by demon101** [comment] 2017-05-04 12:46
@graemerocher I understand, but it not simple to create a simple example. I have no idea where is a reason of performance fall

**Comment by graemerocher** [comment] 2017-05-04 13:06
Then "not production ready" only applies to your application for the moment I'm afraid

**Comment by demon101** [comment] 2017-05-04 13:17
@graemerocher bugs like https://github.com/grails/grails-core/issues/10609 in version 3.2.9 (not in 3.2.RC9) are bright signal for "not production ready" =)

For Grails version 2 was safe to upgrade after 3-4 minor releases. But with grails 3 I'm already I'm afraid to upgrade before 10-15 minor releases =)

I am grateful for the updates (really!). 
But Grails release plan looks really risky. You add major GORM changes during minor Grails updates.

**Comment by graemerocher** [comment] 2017-05-04 13:26
@demon101 Issue #10609 is unfortunate I agree, but the changes that introduced that particular bug were not major and were added to allow a new version of Spring security to be released. The change the caused the regression was https://github.com/grails/grails-data-mapping/commit/8fec30088567d527f1c409c88e68bd53961d5604

Other than that I don't believe GORM is the first piece of software to introduce a bug in a patch release or are you going to be pointing out instability issues every time a new bug comes up in a patch release? 

As it happens in the next release of Grails we have to rollback to Spring 4.3.7 because Spring 4.3.8 introduced a bug that is causing #10616 ... so looks like Spring is equally buggy and unstable.

Finally, in general your snarky comments such as this latest one and the comments on #10609 combined with you either incomplete or unhelpful errors reports are not helping progress forward.

**Comment by demon101** [comment] 2017-05-04 13:34
@graemerocher 

> Finally, in general your snarky comments such as this latest one and the comments on #10609 combined with you either incomplete or unhelpful errors reports are not helping progress forward.

Sorry, I'm not a full time grails tester, sometimes I work irresponsible

**Comment by lhotari** [comment] 2017-05-11 16:03
I added a comment about https://jira.spring.io/browse/SPR-11864 to https://github.com/grails/grails-core/issues/10633#issuecomment-300832990 . It might be related to the performance degrade since the optimization was removed by 3433ece because of compatibility reasons. 

Perhaps there should be a way in Grails to still use OptimizedAutowireCapableBeanFactory (or any other custom BeanFactory implementation)?

**Comment by demon101** [comment] 2017-05-11 19:17
DI also affect controllers creation if you don't use singleton type (default for grails 3, but not for Grails 2)

**Comment by demon101** [comment] 2017-05-12 13:29
But the performance of DI in domains also different in Grails 3.1.15 and Grails 3.2.9. 

<img width="795" alt="screen shot 2017-05-11 at 11 04 34" src="https://cloud.githubusercontent.com/assets/1362920/25954347/4ae15602-3666-11e7-931c-341d28d51f56.png">

Blue line at right part -- after replacing DI in domains by a simple static facade in Grails 3.2.9.
Red line -- after switching from  Grails 3.2.9 to 3.1.15.

Tomorrow I will have chart for comparison 3.1.15 and 3.2.9 with Facade instead of DI in domains

**Comment by erichelgeson** [comment] 2017-05-12 13:31
@demon101 can you share an example of how you implemented the facade in your domain classes?

**Comment by graemerocher** [comment] 2017-05-12 13:33
@demon101 Great. The fix is to not use DI which his our recommendation going forward. We will no longer be maintaining hacks to Spring to support this use case hence why DI is disabled by default in 3.2.x.  Feel free to vote for https://jira.spring.io/browse/SPR-11864 and if that issue ever gets resolved we can revisit the issue.

**Comment by demon101** [comment] 2017-05-12 13:41
@erichelgeson I have implemented hack just for performance testing. Dummy code. I have already refactored some business logic. Some of utils services was replaced by tags and codecs

```
class DIFrontend {
    static CacheService cacheService
.....
}
```

in bootstrap: 
```
def cacheService
def init = { servletContext ->
DIFrontend.cacheService = cacheService

```
Repeat it only at own your risk =))))

**Comment by demon101** [comment] 2017-05-13 21:23
Now I see, a performance of grails 3.2.9 with disabled DI slightly better than 3.1.15 with DI in domains
I agree, DI in Grails 3 working slower because of https://jira.spring.io/browse/SPR-11864 , but DI speed in domains degraded more in Grails 3.2 compare to Grails 3.1. I don't know, does it also affects usual DI. 

In most cases deactivating of DI in domains solve performance issue, but application with intensive beans creations can (not sure) have problem
