### ISSUE TITLE
Interceptor is invoked after resolved controller, not for actual URI

### ISSUE THREAD

**Issue by artemik** [grails/grails-core#10746] opened 2017-07-24 17:07 UTC
### Steps to Reproduce

1. Create sample grails 3 web profile project.
2. Create interceptor that `matchesAll()`
3. Visit `/this-uri-doesnt-exist`

### Expected Behaviour

Interceptor hit for `/this-uri-doesnt-exist` request.

### Actual Behaviour

Interceptor hit for `/error`, i.e. after logic that decided to resolve the request to the error 404 controller.

### Environment Information

- **Operating System**: Windows
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8

Interceptors should not be coupled with the logic that decides which controller should be invoked. Instead, interceptors should be invoked before this logic - should have actual URIs. Because, for example, now it's not possible to log unexisting page access in interceptor. It's not possible to apply security constraints and an unauthorized user can see 404 error.

**Comment by jameskleeh** [comment] 2017-07-24 17:13
You can assign the 404 url mapping to a controller to implement whatever behavior you want to happen on a 404

**Comment by artemik** [comment] 2017-07-25 14:47
This sounds like a workaround and a different kind of things. Following this logic, I can implement my interceptor's logic in all my controllers, but then what is the purpose of an interceptor then? It should intercept everything before it hits controllers, including the logic that decides to route the request to the 404.

**Comment by jameskleeh** [comment] 2017-07-25 14:53
> This sounds like a workaround and a different kind of things.

I don't think it is a workaround since the current behavior is the way it is designed. You're requirements are to have custom behavior to happen on a 404 and my suggestion will allow you to do so.

**Comment by artemik** [comment] 2017-07-31 10:46
If I create an interceptor for path (`/this_url_doesnt_exist`) I literally want to intercept these requests. But now I can't. Grails decides it's 404 and doesn't let me do this.

**Comment by sdelamo** [comment] 2017-10-26 11:04
Interceptors with `matchAll` are hit for none existing endpoints. 

Steps to reproduce: 

```
10746 $ grails -version
10746 $ grails create-app demo --inplace
```

Create controller: 

`grails-app/controllers/demo/BookController.groovy`

```
package demo

class BookController {

    def index() {
        render 'Book'
    }
}
```

Create an interceptor `grails-app/controllers/demo/TestInterceptor.groovy`

```
package demo

import groovy.transform.CompileStatic

@CompileStatic
class TestInterceptor {

    TestInterceptor() {
        matchAll()
    }

    boolean before() {
        log.info('inside testinterceptor')
        true
    }

    boolean after() { true }

    void afterView() {
        // no-op
    }
}
```

log info traces. Add to `grails-app/conf/logback.groovy`

`root(INFO, ['STDOUT'])`

Start the app and hit `http://localhost:8080/this_url_doesnt_exist`

As you can see the interceptor is hit: 

```
2017-10-26 12:56:35.496  WARN --- [io-8080-exec-10] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/this_url_doesnt_exist] in DispatcherServlet with name 'grailsDispatcherServlet'
2017-10-26 12:56:35.500  INFO --- [io-8080-exec-10] demo.TestInterceptor                     : inside testinterceptor
```

With the previously described behaviour and the ability to map response codes to controllers, as mentioned by @jameskleeh , I believe you can achieve the fucntionality you describe. 

I am going to close this issue.

**Closed by sdelamo** 2017-10-26 11:04 UTC
