### ISSUE TITLE
java.sql.Date property is type-mismatched in scaffolded UI

### ISSUE THREAD

**Issue by nutmix** [grails/grails-core#11126] opened 2018-10-19 15:59 UTC
### Task List

- [Y ] Steps to reproduce provided
- [N] Stacktrace (if present) provided
- [Y] Example that reproduces the problem uploaded to Github
- [Y] Full description of the issue provided (see below)

### Steps to Reproduce
1. create a domain object such as "User" with a java.sql.Date filed such as "birthDate"
1. create a controller such as UserController with "static scaffold=User"
1. Open the scaffoleded user contoller, create a new User, using the DD, MM, YYYY dropdowns to set a  birthDate.
1. Hit the create button and observe the error.

### Expected Behaviour
IT should have saved the birthDate

Tell us what should happen
the error.

### Actual Behaviour
java.sql.Date property is type-mismatched 

### Environment Information
```
MacOs 10.13.6
Grails: 3.3.8
JVM: 1.8.0_131

```
### Example Application

File: UserController.groovy

```
package x
class UserController {
    static scaffold=User
}
```

File: User.groovy

```
package x
class User {
    String first
    java.sql.Date birthDate
}
```

**Comment by ilopmar** [comment] 2018-10-23 10:31
Sample application https://github.com/grails-core-issues-forks/grails-issue-11126

**Comment by ilopmar** [comment] 2018-10-26 08:03
This issue is not because of scaffolding but because of data binding. You can reproduce it creating this action:
```
def saveUser(User user) {
    render user.errors
}
```
And sending the request:
```
$ curl -X POST 'http://localhost:8080/user/saveUser' --data 'name=John&birthDate=date.struct&birthDate_day=23&birthDate_month=10&birthDate_year=2018&create=Create'
```
During data binding Grails builds the date from the `year`, `month` and `day` sent as parameters and returns a `java.util.Date`. That's why the error is `type-mismatched`.

I'm going to fix it, but to make it consistent I need to introduce a breaking change, so this issue will be fixed in Grails 4.0 (currently `master` branch).
I'm going to change the behavior of  `params.getDate("birthDate")` that you can use when not using data binding to return a `java.util.Date` built from the parameters sent.

**Comment by jeffbrown** [comment] 2018-10-26 14:05
> I'm going to fix it, but to make it consistent I need to introduce a breaking change, so this issue will be fixed in Grails 4.0 (currently master branch).

@ilopmar I don't think this needs to wait until 4.0.  This is indeed a bug.  We have explicit support for binding to a `java.sql.Date`.  Some of that code is at https://github.com/grails/grails-core/blob/6b588fc1684e8c6d5c2dec7bd669b66cf6501a94/grails-web-common/src/main/groovy/org/grails/web/binding/StructuredDateEditor.java#L86.  The problem is that because of the way the date is being retrieved from the params `type` at that point is `java.util.Date` instead of `java.sqlDate` so that if condition doesn't help.  

I think this is a bug that should be fixed in Grails 3.

**Comment by jameskleeh** [comment] 2018-10-26 14:16
@jeffbrown The problem is we can't retrieve the value from the params without being a `java.util.Date`. The PR is changing so that `params["foo"]` will return `date.struct` instead of a `java.util.Date` where `params` is a `GrailsParameterMap`. We don't do any other conversions in the `get` method, so it doesn't make sense that we would that kind of date processing there either.

In order to fix this without this change we would have to assume knowledge of `GrailsParameterMap` in the databinding code and hack a workaround if `.get` returns a `Date`.

**Comment by ilopmar** [comment] 2018-10-26 14:18
@jeffbrown That code works properly. The issue is that during binding. when executing 
https://github.com/grails/grails-core/blob/3.3.x/grails-databinding/src/main/groovy/grails/databinding/SimpleDataBinder.groovy#L224

We are calling this in `GrailsParameterMap` 
https://github.com/grails/grails-core/blob/3.3.x/grails-web-common/src/main/groovy/grails/web/servlet/mvc/GrailsParameterMap.java#L168-L171
And that code makes the params being evaluated and returned as a `java.util.Date`. Simple removing that `if` makes the code you link works properly.

**Closed** 2018-10-31 13:57 UTC
Labels: Pull Request

**Comment by nutmix** [comment] 2019-02-17 02:10
I have been unable to find any work around for this problem.  If anyone has any kind of solution for saving dates, let me know.   Interestingly, in the controller, e..g

```
   def update(User user) {
       log.error "birthDate" + user.birthDate
       userService.save(user)
   }
```

it appears to be a string (outputs "2010-01-01").

I tried this:

def update(User user) {

      user.birthDate = new java.sql.Date(params.int('birthDate_year') - 1900, params.int("birthDate_month"), params.int("birthDate_day"))

          userService.save(user)
   }

so I am actually setting user.birthDate to a real java.sql.Date, but I still get the data binding error.

Is there any workaround?  This is a bit of a show stopper.
