### ISSUE TITLE
Grails 3.0.1: performance issue

### ISSUE THREAD

**Issue by wizzardo** [grails/grails-core#640] opened 2015-04-13 13:37 UTC
I've just created simple application by 
`create-app [NAME] --profile=web`
add mapping like 
      `"/hello"(controller: 'hello', action: 'hello')`

```
class HelloController {
    def hello = {
        render 'Hello world!'
    }
}
```

I run it with `grails run-app` or `./gradlew run` and get about 4.2k rps, it uses about 250 mb of ram and don't generate much garbage

but if I create war and deploy it to tomcat or jetty, they will render only about 400 rps, for 1 minute tests this app generates about 67 gigabytes of garbage

I tested it on jetty 9.2.9 and tomcat 8.0.21, jdk1.8.0_40, ubuntu x64, kernel 3.19

**Comment by mgkimsal** [comment] 2015-04-14 01:45
I don't have any specifics to help fix this, but will note that my own small 'hello world' benchmarks seem to show grails 3 being measurably slower than 2.4.x as of last week.  perhaps on more complex stuff it's faster(?) but I was a bit taken aback by the results.

**Comment by graemerocher** [comment] 2015-05-25 08:10
Will investigate, but I doubt very much the performance is worse than 2.x

**Comment by wizzardo** [comment] 2015-05-25 12:39
I've just tested this in grails 2.5.0, it can handle about 9.5k rps on my laptop

**Comment by graemerocher** [comment] 2015-06-09 08:05
So using the [siege](http://linux.die.net/man/1/siege) load testing tool I created a hello world app using Grails 3.0 and ran the application with (which starts the application in Tomcat):

     java -jar perf-0.1.war

 Then I ran the following command which performs a benchmark with 100 concurrent requests: 

      siege -c 100 -b http://localhost:8080/hello/index

The results were:

	Transactions:		       16437 hits
	Availability:		      100.00 %
	Elapsed time:		       36.17 secs
	Data transferred:	        0.19 MB
	Response time:		        0.02 secs
	Transaction rate:	      454.44 trans/sec

And then performed the same steps but with Grails 2.4.x and the results are 

	Transactions:		       16452 hits
	Availability:		      100.00 %
	Elapsed time:		       29.33 secs
	Data transferred:	        0.17 MB
	Response time:		        0.06 secs
	Transaction rate:	      560.93 trans/sec

So indeed there is a degradation in performance, but not drastically so and I did not detect any memory leak. The performance is something we can definitely optimise however...

**Comment by graemerocher** [comment] 2015-06-09 08:14
I have requested a YourKit license to perform profiling to see where can improve in this area

**Comment by graemerocher** [comment] 2015-06-10 14:46
I pushed some changes these improved performance to be better than 2.x:

	Transactions:		       16461 hits
	Availability:		      100.00 %
	Elapsed time:		       24.13 secs
	Data transferred:	        0.19 MB
	Response time:		        0.03 secs
	Transaction rate:	      682.18 trans/sec

Probably more optimisations that can be done, but closing this one for now...

**Comment by shawnchain** [comment] 2016-07-15 15:37
I also noticed a  performance drop down after migrated my app to grails 3.1.9. 

My app will expose an HTTP API that generate a geojson string data of 1000 devices, the data size might be 200K.
I applied a performance interceptor on APIController before/after call and noticed the performance drop.

  - Before upgrade (using grails 2.5.5),  the initial call to the api (where no cached data to be used)  is about 5000+ ms
  - After upgraded to 3.1.9, the initial call to the api will lasting for 18000 ~ 30000 ms

@graemerocher  Any idea about that ? 

Thanks,

Shawn

**Comment by demon101** [comment] 2017-02-08 10:05
Hi @shawnchain , have you found any reasons?

On production env after application upgrade grails 2.4.5-> 3.1.15 CPU usages increased 2,5X

**Comment by jagiro** [comment] 2017-03-13 17:00
The same problem here. 

I have stopped the migration from Grails 2.5.0 to Grails 3.2.4 because the load tests showed performance degradation about 40%.

With simple test, 2.5 and 3.x have similar performance results, but with a real application with complex domain and similar data of production environment into database, the results are very disappointing.

I found closed issues about performance degradation, has someone solved migration with similar performance?

**Comment by graemerocher** [comment] 2017-03-13 17:08
Still waiting for someone to provide an example that actually reproduces this issue.

**Comment by demon101** [comment] 2017-03-13 19:23
@jagiro I have report #10463 , but it's difficult to reproduce performance degradation on a simple app.

In our project we have achieved comparable performance by:
* Switching controller scope from prototype to singleton (reduced ~20% of difference)
* Upgrade to groovy 2.4.9 (~10%)
* Upgrade to Hibernate 5 (~5%)
* CodeCache java 8 option (Only on one of our application it save 30% of CPU)

On the other hand, Grails 3, because of groovy, use 5-15% less memory

**Comment by jjchiw** [comment] 2017-03-15 00:11
Ok I think I made an example yay!

https://github.com/jjchiw/grails-performance-2v3-sample

I compared `2.5.0` and `3.2.4`

This were the results

siege -c 25 -b -r 15  http://localhost:8080/g2/foo/

## grails 2.5.0

```
Transactions:                    250 hits
Availability:                 100.00 %
Elapsed time:                   0.96 secs
Data transferred:               7.29 MB
Response time:                  0.05 secs
Transaction rate:             261.23 trans/sec
Throughput:                     7.61 MB/sec
Concurrency:                   12.99
Successful transactions:         250
Failed transactions:               0
Longest transaction:            0.87
Shortest transaction:           0.01
```

siege -c 25 -b -r 15  http://localhost:8080/g3/foo/

## Grails 3.2.4:

```
Transactions:                    250 hits
Availability:                 100.00 %
Elapsed time:                   1.81 secs
Data transferred:               6.79 MB
Response time:                  0.09 secs
Transaction rate:             138.12 trans/sec
Throughput:                     3.75 MB/sec
Concurrency:                   12.53
Successful transactions:         250
Failed transactions:               0
Longest transaction:            1.68
Shortest transaction:           0.01
```
In order to run the samples we have to change the `database url` in order to target where the database resides....

The database has just a table with 100 rows....

In all the others tests that I've made I think the problem resides in how `gorm` "materialize" the results of the query to a list of objects, because when I change the query and use `projections` `grails3` is faster than `grails2`...... so I'm not really sure the problem is `grails3` is more about `gorm` :/

I don't have screenshot but the numbers where something like this

`grails2`
* query 3ms
* after "materializing" the overall was 27ms so in the "materializing" it spent 24ms

`grails3`
* query 3ms
* after "materializing" the overall was 80ms so in the "materializing" it spent 77ms

Even the numbers were not consistent in all the requests `grails3` always had more queries above 100ms

Anyway I hope this examples "works" and we can find what's causing this performance issues that are in the air, :)

**Comment by demon101** [comment] 2017-03-15 07:19
@jjchiw in our app we use criteria only in couple places. But performance also fall down

**Comment by jjchiw** [comment] 2017-03-15 09:05
@demon101 I think the same happens with retrieving a large list of objects, the way I'm checking the query times is using

* http://www.profilesql.com/
* Using this script https://gist.github.com/nobeans/5167629

Here is how I use it, in the service

```
def list(User customer, String term=null) {
    timeRecoreds = [:].withDefault { 0.0 }
    def result= []
    withTimeRecording("query") {
        def result = Foo.createCriteria().list{
                gt 'id', 0L
        }
    }
    printResult()
    return result
}
```

Then I check the query made in the profiler view duration of the query and then the result printed that's how I not-so-accurate take the time of the whole createCriteria, I think the same would be with `findAllBy*`,

**Comment by graemerocher** [comment] 2017-03-15 13:12
Ok so I have analysed the problem and yes the issue is more GORM centric and is down to a couple of things.

The major one is that in Grails 3 GORM are translated into events that can be listened for via Reactor. This has quite a huge performance cost (around 30% in my benchmarking) and represents the majority of the gap. 

For Grails 3.3 as part of https://github.com/grails/grails-core/issues/10273 we will look to disable this by default and make it an optional add on. For Grails 3.2.x we will make it possible to disable the events by configuration and maybe have them disabled by default for new applications.

In the meantime you can work around the issue by adding the following to `grails-app/conf/spring/resources.groovy`:

```groovy
beans = {
    springReactorEventTranslator(Dummy)
}
class Dummy {}
```
What this does is simply override the bean that registers the GORM event translation, disabling the translation.

The second performance regression is in GORM and represents around 5-10% and is due to the fact that in GORM 5 and above we use an AST transformation to modify all of the setters to track changes to objects for dirty checking. However, when we did that we should have switched the default reflection access to use the field instead of the property (which is the Hibernate default anyway)

In GORM 6.1 this field access is actually the default, so you can in fact improve the performance again by using Grails 3.2.7 and upgrading to GORM 6.1 RC1 which uses field access by default. This can be done by configuring `gradle.properties` as follows:

```
grailsVersion=3.2.7
gormVersion=6.1.0.RC1
gradleWrapperVersion=3.0
```

Then configuring `build.gradle` as follows:

```groovy
configurations.all {
 exclude module:'grails-datastore-simple'
}
dependencies {
     ....
     compile "org.grails.plugins:hibernate5:${gormVersion}"
}
```

With these two changes the performance on my machine is roughly the same for both Grails 2 and Grails 3 in my tests.

**Comment by demon101** [comment] 2017-03-15 13:18
@graemerocher good news!

**Comment by demon101** [comment] 2017-03-15 19:32
One more issue:
**WebRequestTraceFilter** controller enabled in newly created app (You can add breakpoint in doFilterInternal method)

It  synchronized for every request
```
public void add(Map<String, Object> map) {
    Trace trace = new Trace(new Date(), map);
	 synchronized (this.traces) {
```

Better to disable it

**Comment by erichelgeson** [comment] 2017-03-15 19:39
Related discussion on WebRequestTraceFilter https://github.com/spring-projects/spring-boot/issues/8322

**Comment by demon101** [comment] 2017-03-15 19:45
@erichelgeson  good link, they also compare performance with/without spring-boot-actuator

**Comment by ColinHarrington** [comment] 2017-03-15 19:49
@demon101 you should be able to disable the actuator endpoints via config. http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-customizing-endpoints

**Comment by demon101** [comment] 2017-03-15 19:52
@ColinHarrington yes, I can. but it only disabling /trace endpoint for TraceRepository
WebRequestTraceFilter continues to work =(

**Comment by erichelgeson** [comment] 2017-03-15 20:04
@demon101 that was changed in 3.1.8 https://github.com/erichelgeson/grails-versions/compare/3.1.7...3.1.8#diff-5c41a8e8312dc0c562d22fe2d1f3e54bR67

**Comment by demon101** [comment] 2017-03-15 20:07
@erichelgeson cool, I'm using grails 3.1.15, and endpoint activated. It can be a side effect of some of plugins. As I wrote, in new application it disabled

**Comment by demon101** [comment] 2017-03-15 20:51
I suggest to remove **compile "org.springframework.boot:spring-boot-starter-actuator"** from default build

**Comment by demon101** [comment] 2017-03-18 12:59
Have a look at blue line. The app has been restarted at 5:00, java 8 codecache option has been added. At result, it use 3x less processor.  
![cpu-pids-day](https://cloud.githubusercontent.com/assets/1362920/24072141/5f6f8aca-0be2-11e7-9323-ff0d32c5cbf2.png)
On another app, with same code base, but with another usage profile, the option didn't show noticeable difference

One day before springReactorEventTranslator(Dummy) fix has been added, it gives us ~10%  cpu benefit

**Comment by graemerocher** [comment] 2017-03-20 14:04
An option exists to now disable Reactor events. I also recommend disabling autowiring:

```yaml
grails:
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
```

As for the actuator stuff, it is simple enough to just comment out the dependency. If https://github.com/spring-projects/spring-boot/pull/8650 gets merged then we will disable the filter by default as well in config to improve this.

@demon101 If there is more data you can provide to @wilkinsona about how the filter impacts your app that would help. See https://github.com/spring-projects/spring-boot/pull/8650#issuecomment-287760907

**Closed** 2017-03-20 14:04 UTC
Labels: Blocker, Improvement, Major, Performance

**Comment by demon101** [comment] 2017-04-18 16:02
@jjchiw Could you rerun your test with grails 3.2.8?

**Comment by jjchiw** [comment] 2017-04-19 08:43
@demon101 

I did the test and as graemerocher  said are "roughly the same"

I tested grails 3 with

- grailsVersion=3.2.8
- gormVersion=6.1.1.RELEASE
- gradleWrapperVersion=3.4.1

In our production application we couldn't apply all the performance suggestions since we have some domains that have services autowired so we can't turn it off.....

We did some changes to our environment with we are ok with them. 
As you suggested we added `CodeCache`
we changed from `c3p0` to `hikari`
tomcat connector `apr` to `nio`

**Comment by demon101** [comment] 2017-04-20 08:00
@jjchiw have you got any marked improvement from changing c3p0-> hikari and apr->nio?

**Comment by jjchiw** [comment] 2017-04-21 08:36
@demon101

Changing `c3p0` to `hikari` it helps us with how the connection pool was being used with `c3p0` we always reached the maximum and many dropped connections, testing with `siege`, we tested `hikari` and it worked better out of the box.... one year and we couldn't configure `c3p0` correctly :(

About `apr` to `nio` well this was more like a "let see how it goes" when you run `java -jar my.war` the connector by default in springboot is `nio` so we just made the change..... Our thought was, "well if they use nio (Non Blocking IO) the cool kids of nodejs talks about non blocking stuff, let's make the change, because who wants to block threads and waste resources"  :)
