### ISSUE TITLE
Grails 5.1.1 app fails to start when war is deployed in container

### ISSUE THREAD

**Issue by miguelabautista** [grails/grails-core#12278] opened 2021-12-21 09:37 UTC
Environment:

Grails 5.1.1 (Error affects ONLY this version. no problem with version 5.0.3)
Java 8
Tomcat 9

Problem:

the error occurs when I try to add any grails plugin. (Simply create a new project and add any grails plugin)

Note:

I had to add this to application.yml:

 main:
        allow-bean-definition-overriding: true
        allow-circular-references: true

Example:

https://github.com/miguelabautista/GrailsTomcatError

Exception:

2021-12-21 10:30:51.652 ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter -

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method setInterceptors in org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter required a bean named 'classLoader' that could not be found.

Action:

Consider defining a bean named 'classLoader' in your configuration.

21-Dec-2021 10:30:51.657 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [C:\apache-tomcat-9.0.56\webapps\crsFatca.war]

**Comment by qvarnis** [comment] 2021-12-25 09:00
Got the same issue after upgrade from 4.X!

**Comment by qvarnis** [comment] 2022-01-04 07:51
Still got this problem, seem to be related to grails-plugins and Resources.groovy.
Another issue on this was removed by someone. There were at least 5-8 people with the same issue under the christmas holidays.

**Comment by puneetbehl** [comment] 2022-01-04 13:00
Duplicate of #12288

**Closed as completed by puneetbehl** 2022-01-04 13:00 UTC
