### ISSUE TITLE
Fix Beans not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13844] opened 2024-11-15 16:58 UTC
[methodValidationPostProcessor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/beanvalidation/MethodValidationPostProcessor.html) is scanning all beans 

```
2024-11-15T07:26:14.342-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'dataSourceConnectionSourceFactory' of type [org.grails.datastore.gorm.jdbc.connections.CachedDataSourceConnectionSourceFactory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:14.342-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'hibernateConnectionSourceFactory' of type [org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.158-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'hibernateDatastore' of type [org.grails.orm.hibernate.HibernateDatastore] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.159-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'grailsDomainClassMappingContext' of type [org.grails.orm.hibernate.cfg.HibernateMappingContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.161-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'messageSource' of type [org.grails.spring.context.support.PluginAwareResourceBundleMessageSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.162-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'validateableConstraintsEvaluator' of type [org.grails.plugins.domain.support.DefaultConstraintEvaluatorFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.164-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'validateableConstraintsEvaluator' of type [org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.186-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'grailsUrlConverter' of type [grails.web.CamelCaseUrlConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.189-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean '(inner bean)#543f83de' of type [org.grails.web.mapping.UrlMappingsHolderFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.189-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean '(inner bean)#543f83de' of type [org.grails.web.mapping.mvc.GrailsControllerUrlMappings] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.190-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'urlMappingsTargetSource' of type [org.grails.spring.beans.factory.HotSwappableTargetSourceFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.190-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'urlMappingsTargetSource' of type [org.springframework.aop.target.HotSwappableTargetSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
2024-11-15T07:26:15.191-08:00  WARN 49835 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'grailsUrlMappingsHolder' of type [org.springframework.aop.framework.ProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [methodValidationPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
```

**Comment by jamesfredley** [comment] 2024-11-15 20:49
duplicate of https://github.com/grails/grails-core/issues/13654

**Closed as completed** 2024-11-16 06:57 UTC
