### ISSUE TITLE
SynchronizerTokensHolder doesn't persist token changes with certain session managers

### ISSUE THREAD

**Issue by exell-christopher** [grails/grails-core#623] opened 2015-04-08 02:57 UTC
We've run into an interesting issue with the SynchronizerTokensHolder and the Jetty mongodb session manager. This may present with other session managers. When the SynchronizerTokensHolder is retrieved from the session, no attribute changes are made to the session if the holder already exists.

```
    static SynchronizerTokensHolder store(HttpSession session) {
        SynchronizerTokensHolder tokensHolder = session.getAttribute(HOLDER)
        if (!tokensHolder) {
            tokensHolder = new SynchronizerTokensHolder()
            session.setAttribute(HOLDER, tokensHolder)
        }
        return tokensHolder
    }
```

Because of this, the jetty mongodb session manager, doesn't know that the SynchronizerTokensHolder has been changed because the session attribute is never updated, but the data contained in it is.  Would it make sense to re-add the the SynchronizerTokensHolder to the session whenever there is a modification of the tokens stored?  This would cause session managers to properly persist changes to the SynchronizerTokensHolder object.

**Comment by graemerocher** [comment] 2015-05-25 08:28
Please upload an example to Github that reproduces the problem

**Comment by graemerocher** [comment] 2015-07-06 13:52
closing as no feedback provided

**Closed by graemerocher** 2015-07-06 13:52 UTC
Labels: Incomplete, No Example Attached

**Comment by felixscheinost** [comment] 2021-12-28 09:00
This is also the case with most (all?) implementations in [Spring Session](https://github.com/spring-projects/spring-session).

They track `setAttribute` calls and only persist attribute where `setAttribute` was called.

Since `2.2.0.RELEASE` there is `SaveMode` which could be used to work around this problem but this requires Spring 5.2 which I think is Grails 5 only.
