### ISSUE TITLE
[Grails 3.1.1] --profile=rest-api  app not generating war and not running properly on Tomcat8

### ISSUE THREAD

**Issue by pamartineza** [grails/grails-core#9735] opened 2016-02-25 22:00 UTC
**Steps to reproduce:**

grails create myapp --profile=rest-api _--> Creates app that run ok in localhost_
grails war  _--> Generates .jar file that doesn't run porperly when deployed on Tomcat 8_

**Steps to fix it:**
In build.gradle
Add apply plugin: "war" _--> this generates war_
Replace: compile "org.springframework.boot:spring-boot-starter-tomcat"  by: provided "org.springframework.boot:spring-boot-starter-tomcat" _--> this makes app run properly in Tomcat8_

**Comment by graemerocher** [comment] 2016-02-26 07:51
Fixed by https://github.com/grails/grails-profile-repository/commit/2596783fbc1995ebc9c8f9dde7827839f4d0f5a6

The latter "issue" is by design. You can either execute as a runnable WAR/JAR or deploy to tomcat, if the later make the dependency provided as you have done.

**Closed by graemerocher** 2016-02-26 07:51 UTC

**Comment by pamartineza** [comment] 2016-02-26 08:05
you are right, thanks!
