### ISSUE TITLE
Grails CLI issue:  single unit test cannot be run with simple class name

### ISSUE THREAD

**Issue by benorama** [grails/grails-core#10260] opened 2016-10-21 11:44 UTC
### Steps to Reproduce

1. `grails create-app test-app`
2. `cd test-app`
3. `grails create-controller Foo`
4. `grails test-app FooController`

### Expected Behaviour

```
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/ben/Documents/Projects/benorama/grails3/test-app/build/reports/tests/index.html
```

### Actual Behaviour

```
Execution failed for task ':test'.
> No tests found for given includes: [FooController]
```

### Environment Information

- **Operating System**: Mac OSX 10.12
- **Grails Version:** 3.2.1 and 3.1.12
- **JDK Version:** 1.8.0_25

### Workaround

The only way to run individual test is to specify the exact Spec file, package included:

```
grails test-app test.app.FooControllerSpec
```

Other issue: when specifying `-unit`, it runs all the tests and not a single unit test.

**Comment by graemerocher** [comment] 2016-10-21 12:33
I imagine that `grails test-app *FooController*` probably works

**Comment by benorama** [comment] 2016-10-21 12:38
Indeed, that's another workaround.

Other issue: `grails test-app -unit *FooController*` will run all the tests.

**Comment by jeffbrown** [comment] 2016-10-21 14:52
Does `./gradlew test --tests *FooController*` work?

**Comment by benorama** [comment] 2016-10-21 23:19
No, it does not work. Same issue.

```Execution failed for task ':test'.
> No tests found for given includes: [FooController]```

**Comment by jeffbrown** [comment] 2016-10-22 03:38
I cannot reproduce that:

```
~ $ git clone git@github.com:jeffbrown/issue10260.git
Cloning into 'issue10260'...
remote: Counting objects: 85, done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 85 (delta 4), reused 85 (delta 4), pack-reused 0
Receiving objects: 100% (85/85), 180.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
~ $ 
~ $ cd issue10260/
issue10260 master $ 
issue10260 master $ ./gradlew test --tests *FooController*
:compileJava UP-TO-DATE
:compileGroovy
:buildProperties
:processResources
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test

BUILD SUCCESSFUL

Total time: 8.886 secs
issue10260 master $ ls -l build/test-results/test/
total 8
-rw-r--r--  1 jeff  staff  402 Oct 21 22:36 TEST-demo.FooControllerSpec.xml
drwxr-xr-x  5 jeff  staff  170 Oct 21 22:36 binary
issue10260 master $
```

**Comment by jeffbrown** [comment] 2016-10-22 03:39
`grails test-app *FooController*` also works for me.

**Comment by jeffbrown** [comment] 2016-10-22 03:59
> The only way to run individual test is to specify the exact Spec file, package included

@benorama If you can upload a sample project which demonstrates that, we can troubleshoot it from there.

Thanks for the feedback.

**Comment by benorama** [comment] 2016-10-22 18:32
Here it is: https://github.com/benorama/grails-core-issue10260
Just clone and run `grails test-app FooController` (as specified in Grails documentation).
It results in:
```
Execution failed for task ':test'.
> No tests found for given includes: [FooController]
```
As a workaround, It will work if you run `grails test-app *FooController*` or `./gradlew test --tests *FooController*`.

**Comment by jameskleeh** [comment] 2016-10-22 18:48
I believe the documentation just needs updated. The way it is working today has been the case since Grails 3.0. Gradle vs custom build system

**Comment by jeffbrown** [comment] 2016-10-22 23:55
@benorama Your last comment makes sense to me.  Before that you had said that `./gradlew test --tests *FooController*` wasn't working.  I agree that this isn't a bug and the docs just need to be updated.

**Comment by benorama** [comment] 2016-10-23 22:56
Great, thanks for the clarification.

**Comment by jameskleeh** [comment] 2016-10-24 19:25
Fixed by https://github.com/grails/grails-doc/commit/8bf2c72a1309cecc5922f1560d13c9b174f3ca78

**Closed by jameskleeh** 2016-10-24 19:25 UTC
Labels: Documentation, Not a Bug

**Comment by clarkmeier** [comment] 2017-11-07 02:41
The package class name issue tripped me up, too.
This works:  grails test-app my.package.SimpleControllerSpec
This fails:  grails test-app my.package.SimpleController
This fails:  grails test-app SimpleControllerSpec

The documentation (http://docs.grails.org/latest/guide/testing.html) implies that you omit the "Spec" suffix in the class name and that the package name is optional:

     grails test-app SimpleController
     This will run any tests for the class named SimpleController. Wildcards can be used…​
     grails test-app *Controller
     This will test all classes ending in Controller. Package names can optionally be specified…​
     grails test-app some.org.*Controller

...but that's not working for me in Grails 3.3.0 RC1.
