### ISSUE TITLE
Problem with run-command

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#11638] opened 2020-10-23 16:11 UTC
### Steps to Reproduce

1. Create a new 4.0.4 app
2. Use `grails create-command demo` to create a command
3. Use `grails run-command demo` or `gradlew runCommand -Pargs="demo"`

### Expected Behaviour

The command should run.

### Actual Behaviour

Error is reported on the command line:

    Missing application class name and script name arguments

Debugging the command with `./gradlew runCommand -Pargs="demo" --debug-jvm` indicates that the `main` method at https://github.com/grails/grails-core/blob/000430a5769fde4ff5e86b12ec893b71c13f62f5/grails-console/src/main/groovy/grails/ui/command/GrailsApplicationContextCommandRunner.groovy#L92 is executed twice.  The first time `args` contains 2 elements.  The first is `"demo"` and the second is the fully qualified name of the application's main `Application` class.  The second time the method is called `args` only contains `"demo"`.

**NOTE**: A simple way to setup the IDE to debug that class is to add an explicit dependency on `compile "org.grails:grails-console"` to `build.gradle`.

### Environment Information

- **Operating System**: macOs
- **Grails Version:** 4.0.4
- **JDK Version:** openjdk version "11.0.2" 2019-01-15

**Comment by puneetbehl** [comment] 2020-10-23 16:26
Duplicate of #11588

**Closed by puneetbehl** 2020-10-23 16:26 UTC
Labels: type: bug
