### ISSUE TITLE
Grails 3.3.0 - stop-app no longer works

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#10791] opened 2017-08-25 05:19 UTC
```
$ grails -v
| Grails Version: 3.3.0
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_144

$ grails create-app test
| Application created at /Users/user/Documents/workspace/delete/test
$ cd test
$ grails
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
grails> run-app 
grails> Grails application running at http://localhost:8080 in environment: development
stop-app 
| Shutting down application...
| Error Application not running.
grails> 
```

BUT application is running and available on http://localhost:8080

**Comment by graemerocher** [comment] 2017-08-25 07:18
Can't reproduce this personally. Are you using SDK man? what is your `gradle -version`?

**Comment by ilmoralito** [comment] 2017-08-25 23:07
Same problem

Using grails version 3.3.0.RC1
Using gradle version 3.3

**Comment by codeconsole** [comment] 2017-08-28 22:27
$ gradle -version

------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

**Comment by codeconsole** [comment] 2017-08-28 22:28
Via the wrapper 
$ ./gradlew -version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

**Comment by codeconsole** [comment] 2017-08-28 22:37
If I update everything to the latest, it still doesn't work:
`
computer:delete $ groovy -v
Groovy Version: 2.4.12 JVM: 1.8.0_144 Vendor: Oracle Corporation OS: Mac OS X
computer:delete $ gradle -v

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

computer:delete $ grails -v
| Grails Version: 3.3.0
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_144
computer:delete $ grails create-app test
| Application created at /Users//Documents/workspace/delete/test
computer:delete $ cd test
| Resolving Dependencies. Please wait...

| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
grails> run-app
| Running application...
objc[10902]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x1087e44c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libins<=======Grails application running at http://localhost:8080 in environment: development
<=<===========--><===========--> 85% EXECUTING [1m 27s]
> :bootRun
stop    stop-app 
| Shutti<===========--> 85% EXECUTING [1m 32s]
| Error Application not running.
grails> 

`

**Comment by codeconsole** [comment] 2017-08-28 23:26
Now I have an even bigger problem.  After that update using sdkman my Controller classes don't reload after an update.  I see the recompiled message, but the changes don't take effect. 

Even if I manually set the versions back, everything is still screwed up.  

I eventually figured out I had to purge the .gradle folder.  Strange that even when gradle -v was showing 3.0 it was still using the latest?

Do you have to have gradle installed in order to run grails?

**Comment by sdelamo** [comment] 2017-10-26 09:05
@codeconsole You can use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) to run Grails without a local Gradle installation.

**Comment by kevintanhongann** [comment] 2018-01-23 13:24
`./grailsw run-app` to do so, as of what is suggested by @sdelamo 

Please proceed to closing the issue if problem doesn't persist anymore.

**Comment by alorenzatti** [comment] 2018-02-06 12:56
Same problem here with the following:
 Grails Version: 3.3.1
 Groovy Version: 2.4.7
 JVM Version: 1.8.0_152
Windows 10 x64

When I try to stop the app it gives the following error:
 Error java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.WindowsAttachProvider could not be instantiated

and it prints my login page gsp (no idea why) in the console and gives the following message:
Stopping build. Please wait...

After all this, it doesn't stop.

At home I did a fresh install with grails 3.3.2 and it is working.

**Comment by jnunderwood** [comment] 2018-03-23 18:03
Environment:
Grails 3.3.3
Java 1.8.0_152
Ubuntu Linux 16.04

I am having similar problem to alorenzatti. When I issue a 'stop' command from the grails console, the console displays the source of the login page and then freezes.

**Comment by benrhine** [comment] 2018-05-15 12:47
As per above using the gradle wrapper ex. `./gradlew bootRun` to run your application will avoid all of the  mentioned issues in this thread. 

For the specific grails interactive mode this seems to be fixed in the most recent 3.3.5 release.

I did not observe any issues with interactive mode with the following 3 versions

```
| Grails Version: 3.3.0
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_163

| Grails Version: 3.3.1
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_163

| Grails Version: 3.3.2
| Groovy Version: 2.4.13
| JVM Version: 1.8.0_163
```
I was able to reproduce using the following two versions. 
```
| Grails Version: 3.3.3
| Groovy Version: 2.4.14
| JVM Version: 1.8.0_163

| Grails Version: 3.3.4
| Groovy Version: 2.4.14
| JVM Version: 1.8.0_163
```
Interactive `stop-app` is working correctly again in 3.3.5
```
| Grails Version: 3.3.5
| Groovy Version: 2.4.15
| JVM Version: 1.8.0_163
```

Note: All versions installed with sdkman 5.6.3+299, no local gradle installed

**Comment by ilopmar** [comment] 2018-06-20 12:57
Closing as not being able to reproduce it with latest version.

**Closed by ilopmar** 2018-06-20 12:57 UTC

**Comment by joemccall86** [comment] 2018-11-06 17:54
For those encountering this: please make sure you have `JAVA_HOME` set up correctly in environment.
