### ISSUE TITLE
grails artifactory https configuration uses expired certificates

### ISSUE THREAD

**Issue by tlazar** [grails/grails-core#11576] opened 2020-06-25 06:07 UTC
Although this isn't a grails issue, it relates to the official grails Artifactory repository.

The certificate path for https://repo.grails.org/ contains expired certificates (COMODO RSA Certification Authority, expired May 30, 2020) and AddTrust External CA Root (expired May 30, 2020).  You can see details [here](https://certcheckerapp.com/chain/932).  This is causing failures when grails tries to pull down dependencies.  Can you please update the certificate path to use a newer version of COMODO RSA Certification Authority?

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not download web.jar (org.grails.profiles:web:4.0.0)
> Could not get resource 'https://repo.grails.org/grails/core/org/grails/profiles/web/4.0.0/web-4.0.0.jar'.
   > Could not HEAD 'https://repo.grails.org/grails/core/org/grails/profiles/web/4.0.0/web-4.0.0.jar'.
      > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by erichelgeson** [comment] 2020-06-25 11:28
Duplicate of https://github.com/grails/grails-core/issues/11561

**Closed by erichelgeson** 2020-06-25 11:28 UTC
