### ISSUE TITLE
Services not injected into filters in unit tests

### ISSUE THREAD

**Issue by dmurvihill** [grails/grails-core#9191] opened 2015-08-17 14:19 UTC
[GRAILS-8976](https://jira.grails.org/browse/GRAILS-8976) seems to have reoccurred in Grails 2.4.4, and services are not being injected into filters in unit tests. I took the example app from the 8976 bug report and updated it to 2.4.4.

File `controllers/service/injection/SimpleController.groovy`:
```
package service.injection

class SimpleController {

    def index() { }
}
```

File `grails-app/conf/service/injection/SimpleFilters.groovy`:
```
class SimpleFilters {

	def simpleService
	
    def filters = {
        all(controller:'*', action:'*') {
            before = {
				// uncommenting the following line causes the test to pass
				// def simpleService = Holders.applicationContext.getBean(SimpleService)
				println simpleService.serviceMethod()
            }
            after = { Map model ->

            }
            afterView = { Exception e ->

            }
        }
    }
}
```

File `grails-app/services/service/injection/SimpleService.groovy:`
```
package service.injection

class SimpleService {

    def serviceMethod() {
		println "service method"
    }
}
```

File `test/unit/service/injection/SimpleFiltersTests.groovy`:
```
package service.injection


import grails.test.mixin.*

@Mock(SimpleFilters)
class SimpleFiltersTests {

    void testInjection() {
		defineBeans {
			simpleService(SimpleService)
		}
		
		SimpleController controller = mockController(SimpleController);

		withFilters(controller:"simple" , action:"index"){
			controller.index()
		}
    }
}
```

```
$ grails test-app :unit
Starting Grails 2.4.4
...
Running 1 unit test... 1 of 1
| Failure:  testInjection(service.injection.SimpleFiltersTests)
|  java.lang.NullPointerException: Cannot invoke method serviceMethod() on null object
	at service.injection.SimpleFilters$_closure1_closure2_closure3.doCall(SimpleFilters.groovy:13)
	at grails.test.mixin.web.FiltersUnitTestMixin.withFilters(FiltersUnitTestMixin.groovy:111)
	at service.injection.SimpleFiltersTests.testInjection(SimpleFiltersTests.groovy:16)
| Completed 1 unit test, 1 failed in 0m 2s
| Tests FAILED  - view reports in /Users/dmurvihill/Downloads/service-injection/target/test-reports
```

**Comment by jeffbrown** [comment] 2015-08-18 14:39
One way to test a scenario like this is shown at https://github.com/jeffbrown/issue_9191/blob/0322169dc0b9db19d110d589be0ec1a3affb9fec/test/unit/service/injection/SimpleFiltersSpec.groovy.

**Comment by jeffbrown** [comment] 2015-08-18 14:48
I went to update the user guide with respect to this and I don't even see any references to `defineBeans` in the guide at this point.

Any objections to close this as Not A Bug?

**Closed** 2015-08-19 23:27 UTC
Labels: Not a Bug

**Comment by orubel** [comment] 2015-08-20 02:31
Well 'filters' were replaced with 'Interceptors' according to documentation and you can autowire your services...

	@Autowired
	ApiRequestService apiRequestService
	@Autowired
	ApiResponseService apiResponseService
	@Autowired
	ApiDomainService apiDomainService
	@Autowired
	ApiCacheService apiCacheService

At least thats the way I did it. This works perfectly fine. So I dont know whether this is an issue or not.

**Comment by jeffbrown** [comment] 2015-08-20 02:41
> Well 'filters' were replaced with 'Interceptors' according to documentation and you can autowire your services...

This report is against Grails 2.4.4 which was released before interceptors replaced filters.

**Comment by jeffbrown** [comment] 2015-08-20 02:48
The test linked above is setup like this:

    package service.injection

    import grails.test.mixin.Mock
    import grails.test.mixin.TestFor
    import spock.lang.Specification

    @TestFor(SimpleController)
    @Mock(SimpleFilters)
    class SimpleFiltersSpec extends Specification {

        static doWithSpring = {
            simpleService simple.injection.SimpleService
        }

        void "test filter injection"() {
            when:
            withFilters(controller:"simple" , action:"index"){
                controller.index()
            }

            then:
            response.text == 'Magic Number: 42'
        }
    }

With that in place, the `simpleService` property will be autowired into the `SimpleFilters` filter when the unit test runs.  That property is defined at https://github.com/jeffbrown/issue_9191/blob/0322169dc0b9db19d110d589be0ec1a3affb9fec/grails-app/conf/service/injection/SimpleFilters.groovy#L5.

That tests injects an instance of the real `SimpleService` class, but of course a bean of any type could be configured in the unit test.

**Comment by orubel** [comment] 2015-08-20 02:57
oh... heh heh. well then :)

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by jeffbrown** [comment] 2015-08-20 03:05
Note that there is no need for `@Autowired` in the sample app that I provided because filters are subjected to autowire by name by default.  As of Grails 3.0.2 the same is true for interceptors.

**Comment by dmurvihill** [comment] 2015-08-20 14:48
Hi @jeffbrown, thanks for your assistance.
