### ISSUE TITLE
Grails 3.0.4 Can't test actions returning models

### ISSUE THREAD

**Issue by and-dmitry** [grails/grails-core#9163] opened 2015-08-03 14:39 UTC
Unit tests don't work for controllers' actions implemented with `return model`.

Tests:

```groovy
    void "test view"() {
        when:
        controller.index()

        then:
        view == '/book/index'
    }

    void "test model"() {
        when:
        controller.index()

        then:
        model.foo == 'bar'
    }
```

Render-based implementation (passes test):
```groovy
    def index() {
        render view: 'index', model: [foo: 'bar']
    }
```

Return-model implementation (fails):
```groovy
    def index() {
        return [foo: 'bar']
    }
```

I've tried to investigate the issue, but I'm new to grails. `ControllerUnitTestMixin` relies`controller.modelAndView` which is `null` for actions returning model. It tries to use `webRequest.actionName` to get the default view but it is also `null`.

Of course one can check the return value of the action method, but I suppose these tests shouldn't depend on implementation.

**Comment by jeffbrown** [comment] 2015-08-03 14:51
I don't think this is a bug.  See the section labelled at Testing Actions Which Return A Map at http://grails.github.io/grails-doc/3.0.4/guide/testing.html#unitTestingControllers.

**Comment by jeffbrown** [comment] 2015-08-03 14:53
I misread the report initially which is why I marked it as a blocker.  I think this is not a bug.  Sorry for the noise.

**Closed by jeffbrown** 2015-08-03 14:53 UTC
Labels: Not a Bug
