### ISSUE TITLE
Interceptor doesn't working in controller

### ISSUE THREAD

**Issue by btboys** [grails/grails-core#9266] opened 2015-09-17 16:38 UTC
For example,
```java
class ApplicationController {
    def beforeInterceptor = {
        log.info("beforeInterceptor")
    }

   def index(){ }

}
```
this is my code。

But at the time of operation, the log has not been output。

Who know is how to return a responsibility? Or need other configuration?

**Comment by graemerocher** [comment] 2015-09-17 18:43
which version of Grails?

**Comment by btboys** [comment] 2015-09-18 03:13
@graemerocher 
3.0 I start with, until now the latest version.

**Comment by graemerocher** [comment] 2015-09-18 09:53
Please upload an example that reproduces the problem, if you are using the web-api profile there is a known issue in this area

**Comment by pledbrook** [comment] 2015-09-18 11:00
I thought that type of interceptor had been removed from Grails 3? They should be in a separate class now.

**Comment by graemerocher** [comment] 2015-09-18 11:46
@pledbrook ah yeah, you are right, this is a duplicate of #635

See the note in the upgrade docs http://grails.github.io/grails-doc/latest/guide/upgrading.html

**Closed by graemerocher** 2015-09-18 11:46 UTC

**Comment by bdbogjoe** [comment] 2015-09-18 11:51
Removal of before and after interceptors
Before and after interceptors were removed. So all beforeInterceptor and afterInterceptor need to be replaced by Stand alone interceptors.
