### ISSUE TITLE
Index out of bounds exception triggered by unexpected URI 

### ISSUE THREAD

**Issue by sdthomas69** [grails/grails-core#11408] opened 2019-09-18 20:49 UTC
### Task List

- [ X] Steps to reproduce provided
- [X ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new application and run it (grails run-app)
2. Go to localhost:8080/conn.asp../1.php (Our application is regularly tested by these sorts of probing requests).

### Expected Behaviour

Grails should render the default 404 error page without throwing an exception.
[exception.txt](https://github.com/grails/grails-core/files/3628305/exception.txt)

### Actual Behavior

A java.lang.StringIndexOutOfBoundsException is thrown and the 500 error page is rendered with the stack trace.

### Environment Information

- **Operating System**: Mac OS 10.14.6
- **Grails Version:** 3.2.11
- **JDK Version:** 1.8.0_73

### Example Application

An example application is not needed since the exception is so easily triggered.  The issue can be addressed by making a range check in grails.util.GrailsNameUtils.getPropertyNameRepresentation (line 256).

**Comment by jameskleeh** [comment] 2019-10-09 19:09
Please verify this happens with the latest 3.3.x release

**Comment by sdthomas69** [comment] 2019-10-09 21:43
It does not occur with Grails 3.3.  I’d be happy to submit a patch though for the 3.2.11 release in which it does occur.

**Comment by jameskleeh** [comment] 2019-10-10 02:03
@sdthomas69 I think this was fixed in 3.2.12. Try upgrading to the latest 3.2 release https://github.com/grails/grails-core/commit/c40740df6a6bd07345aebedaf0ad8d88787b8218

**Comment by jameskleeh** [comment] 2019-10-10 02:04
Duplicate of https://github.com/grails/grails-core/issues/10767

**Closed by jameskleeh** 2019-10-10 02:04 UTC
Labels: Duplicate
