### ISSUE TITLE
Data binding not working automatically with Rest calls,is bean not instantiated ?

### ISSUE THREAD

**Issue by arvind-das** [grails/grails-core#9131] opened 2015-07-24 12:01 UTC
Hi Guys

I am using grails 3.x.x for my project. Front End is in AngularJS and I am using angular services to make form submissions(mostly rest calls) . When I Provide my command object as a parameter to my action , binding does not occur and validation fails but if I create a new object in that action, it works.
Code sample is here:

Not Working:

def saveUser(UserRegisterCommand userRegisterCommand){
println userRegisterCommand.validate()
}
 
Working :

def saveUser(UserRegisterCommand userRegisterCommand){
userRegisterCommand = new UserRegisterCommand()
println userRegisterCommand.validate()
}

Please let me know what could be the cause

**Comment by jeffbrown** [comment] 2015-07-24 12:15
The title includes "...is bean not instantiated ?"  The answer is that it should be.  Are you getting null passed to your action or an instantiated object?

There is no reason to call `.validate()` in your first example.  If `UserRegisterCommand` is validateable then it will already have been validated before it is passed into your action.

In general, data binding for command objects does work.  It isn't clear why your data binding isn't working in your scenario.  Can you describe how the request is being initiated, what the Accept header looks like, what the body of the request looks like, what request parameters are being sent and what the source for `UserRegisterCommand` looks like?

**Comment by jeffbrown** [comment] 2015-07-24 12:19
def saveUser(UserRegisterCommand userRegisterCommand){
        userRegisterCommand = new UserRegisterCommand()
        println userRegisterCommand.validate()
    }

That fact that validation is passes there suggests to me that your constraints are such that data binding doesn't even have to happen in order for validation to pass.  I am interested to see the source code for `UserRegisterCommand`.

**Comment by arvind-das** [comment] 2015-07-24 12:21
Here it is

class UserRegisterCommand{
    String email
    String password
    String password2
    String role

    static constraints = {
        email blank:false,nullable:false,email:true
        password blank:false,nullable:false
        password2 blank:false,nullable:false
        role blank:false,nullable:false
    }
}

**Comment by jeffbrown** [comment] 2015-07-24 12:23
That doesn't make sense.  Are you sure that validation really is passing when you do this?

    def saveUser(UserRegisterCommand userRegisterCommand){
        userRegisterCommand = new UserRegisterCommand()
        println userRegisterCommand.validate()
    }

**Comment by jeffbrown** [comment] 2015-07-24 12:27
I expect that there is something elsewhere in your application which explains why data binding isn't happening and that may or may not be affecting validation.  Please push a sample app to GitHub which demonstrates what you are describing and I will take a look at that.

Thanks for the feedback.

**Comment by arvind-das** [comment] 2015-07-24 12:32
Yes, I just tried again after cleaning, binding happens but validation is success in every case (which really does not make sense) . Will try other way out and post a sample project on github

**Comment by jeffbrown** [comment] 2015-07-24 12:35
The original bug report says the following:

> binding does not occur and validation fails 

The last comment says the following:

>  binding happens but validation is success in every case 

Is the latter what you are seeing?

**Comment by arvind-das** [comment] 2015-07-24 12:37
Yes, Sorry but the later one is the case .

**Comment by jeffbrown** [comment] 2015-07-24 12:38
Ok.  That definitely doesn't make sense but maybe there is something in your app that explains that behavior.  Go ahead with the sample project and I will take a look.  

Thanks again.

**Comment by arvind-das** [comment] 2015-07-24 13:34
Hi Jeff

I just created a clean application performing the same and it Worked! Binding and Validations are working properly. My main app is configured with spring boot security and other configurations so it will not be possible to post a similar project in short time but Yes, there is something wrong on my end, I will debug and let you know.

**Comment by jeffbrown** [comment] 2015-07-24 13:49
> Yes, there is something wrong on my end, I will debug and let you know.

I am not sure what you could be doing that could cause validation to always succeed, but if you track it down please let us know.  I am going to go ahead and close this issue for now.  If you find the problem, instead of reopening this one just create a new one.  This one was originally about binding not working, which appears to not be the issue anyway.  Thanks for the feedback.

**Comment by arvind-das** [comment] 2015-07-25 04:26
I am not going to open this again or new one but changing this code fixed my issue.

Data binding and validation while using angularjs factory in this manner does not work : 

registrationService.createUser({userInfo:$scope.userSignupData});

yourApp.factory('registrationService',['$resource',function($resource){

return $resource('registrationService', {}, {
				createUser : {
					headers: {'Content-Type':'application/json'},
					url:"/register/registerUserFromPublicPage",
					params : {
					email : "@userInfo.email",
					role : "@userInfo.role",
					password : "@userInfo.password",
					password2 : "@userInfo.password2"
					},
					method: "POST"
				}
				});
}]);
 
But this works : 

registrationService.createUser({email:$scope.userSignup.email,role:$scope.userSignup.radioModel,password:$scope.userSignup.password1,password2:$scope.userSignup.password2});

yourApp.factory('registrationService',['$resource',function($resource){

return $resource('registrationService', {}, {
				createUser : {
					headers: {'Content-Type':'application/json'},
					url:"/register/registerUserFromPublicPage",
					params : {
					email : "@email",
					role : "@role",
					password : "@password",
					password2 : "@password2"
					},
					method: "POST"
				}
				});
}]);

When  called from angularjs controller if we just pass whole object to service and exttract as done in first code block, binding does not work but works when you pass direct values. 
:)

**Comment by jeffbrown** [comment] 2015-07-25 13:17
@arvind-das 

I am trying to recreate that behavior.

In your app, do `$scope.userSignupData` and `$scope.userSignup` have the same value?

**Comment by jeffbrown** [comment] 2015-07-25 13:29
> Data binding and validation while using angularjs factory in this manner does not work

Can you share a runnable example in which this doesn't work?  I cannot reproduce.

**Comment by arvind-das** [comment] 2015-07-25 13:30
Oh! my bad yes they are same $scope.userSignupData and $scope.userSignup , let me get the same example .

**Comment by jeffbrown** [comment] 2015-07-25 13:31
> let me get the same example .

Thanks.  That will be helpful.

**Comment by jeffbrown** [comment] 2015-07-25 13:33
If you can share a runnable example which demonstrates the problem, I am sure I can fix it.

**Comment by arvind-das** [comment] 2015-07-25 14:02
Hi Jeff , here is the git, https://github.com/arvind-das/grails3hello , sorry for some bad code there in logging and assets, just did it to run the app.

**Comment by jeffbrown** [comment] 2015-07-25 14:11
Great.  I will look at it right now.

**Comment by jeffbrown** [comment] 2015-07-25 14:38
When your app is making the request, you are seeing the `Content-Type` to be `application/json`.  When Grails is imposing data binding on the command object, since the `Content-Type` is `application/json`, the body of the request is used as the data binding source, not the request parameters.  

When you click your `Will Pass` button, the body of the request will look something like this:

    [password:d, username:d]

When you click your `Will Fail` button, the body of the request will look something like this:

    [userInfo:[password:my password, username:my username]]

The body needs to be structured to match the property structure in your command object.  Since there is no `userInfo` property, the data binder will ignore that entry in the body of the request so there is nothing to bind.  This is all by design.

Does that make sense?

**Comment by arvind-das** [comment] 2015-07-25 14:44
Okay, what I am interpreting is : 

createUser : {
                headers: {'Content-Type':'application/json'},
                url:"/register/registerUserFromPublicPage",
                params : {
                email : "@userInfo.email",
                role : "@userInfo.role",
                password : "@userInfo.password",
                password2 : "@userInfo.password2"
                },
                method: "POST"
            }

 userInfo is a object, in the end we are passing its values to the keys email,role ,password and password2. printing params in controller is printing correct information.

**Comment by jeffbrown** [comment] 2015-07-25 14:51
> printing params in controller is printing correct information.

That is correct, but the params are not being used for data binding.  The JSON in the body of the request is being used.

**Comment by jeffbrown** [comment] 2015-07-25 14:53
If you are going to use the body of the request for data binding, the JSON in the body needs to be structured like `{"username":"some user name", "password":"some password"}`, not `{"userInfo": {"username":"some user name", "password":"some password"}}`.

Does that make sense?

**Comment by jeffbrown** [comment] 2015-07-25 14:55
Is it intentional that you are populating the body of the request and the request parameters?

**Closed** 2015-07-25 15:11 UTC
Labels: Awaiting Feedback, Not a Bug

**Comment by arvind-das** [comment] 2015-07-26 16:19
Yes, that is intentional. I was trying to write small,clean code, so did that.

**Comment by jeffbrown** [comment] 2015-07-26 17:22
> Yes, that is intentional. I was trying to write small,clean code, so did that.

If small clean code is your goal, having the params there is sort of working against you.  I think you can delete the `params` specified at https://github.com/arvind-das/grails3hello/blob/4d7f4a8dbaf9bdf0ab0c95d1c435f952ea2c8837/src/main/webapp/js/main.js#L25 and the app will yield the exact same behavior.  The body of the request is what is being used for data binding, not the request parameters.  I think your params are superfluous.

**Comment by jeffbrown** [comment] 2015-07-26 17:24
It isn't clear to me why you want the params to be there in addition to populating the body of the request.

I am not an Angular expert so I asked a friend to look at your app.  This is part of what he has to say:

> I think he doesn't quite understand $resource here.  $resource can make life easier when you want to create a service that maps to a standard REST API (GET retrieves, POST creates, PUT updates etc...)

> What both $resource calls in this example are doing, is creating a new resource with a url of "registrationService" (or registrationServiceWorking) and then creating a custom action on top of it that overrides the url to the real one (/register/saveUser).  The params object that is being passed into the custom action is meant to override url parameters if they aren't present.  This would be more useful on a GET request than a POST.

> If he wants to keep the server side the same, it would really be more appropriate to use $http.  If he wants to use $resource, the server side should be refactored to be RESTful.  If that is done, I don't believe he would even need to create custom actions.

> See: https://code.angularjs.org/1.3.17/docs/api/ngResource/service/$resource -- in particular the Credit Card example for ideal usage.

Does any of that help?

**Comment by arvind-das** [comment] 2015-07-26 17:40
Yup that completely makes sense and helps a lot. I was in initial phase and did not make that completely restful causing me issues. Will fix these things before I create any questions/issues anywhere. Thanks!
