### ISSUE TITLE
Grails 3.0.3: gradle run throws exception "Createprocess error=206; the filename or extension is too long"

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#9125] opened 2015-07-22 15:12 UTC
When starting a clean grails 3.0.3 app with just a few additional dependencies, the app won't execute.

```
Createprocess error=206; the filename or extension is too long
```

This seems to be a Windows issue as there is a maximum of 30. 000 of characters for a command (see https://support.microsoft.com/en-en/kb/830473).

So, on windows based machines you would never be able to start your app with some additional (transitive) dependencies .

I tried to solve this with a couple of gradle workarounds as mentioned here:
https://discuss.gradle.org/t/filename-too-long-in-windows/9222
http://stackoverflow.com/questions/22659463/add-classpath-in-manifest-using-gradle

but they don't solve this problem. I think grails itself is generating the classpath param (-cp)

**Comment by graemerocher** [comment] 2015-07-22 16:13
Grails itself is not generating the class path, it is Gradle, this is a long standing issue. Apparently the solution is to use a pathing JAR or preferably abandon Windows ;-)

**Comment by mhuebner** [comment] 2015-07-23 10:07
I see. We already tested some "pathing JAR" concepts but none of them really did the job. Abandoning Windows ist a nice idea but frightfully expensive :-/

**Comment by mhuebner** [comment] 2015-07-23 12:40
btw: they (the gradle guys) say "this particular issue has to be resolved on the Grails side." 
https://issues.gradle.org/browse/GRADLE-3260

**Comment by graemerocher** [comment] 2015-07-23 13:21
@mhuebner Yup, and we haven't come up with a solution that works yet either

**Comment by anshbansal** [comment] 2015-07-25 15:55
If it is length issue then how about a hack? I mean something like
>set CLASSPATH=%CLASSPATH%;FIRST_DEPENDENCY
>set CLASSPATH=%CLASSPATH%;SECOND_DEPENDENCY

and so on. Haven't tried but might work.

**Comment by graemerocher** [comment] 2015-09-04 20:22
Related thread as the problem exists in Spring Boot too https://discuss.gradle.org/t/filename-too-long-in-windows/9222/2

**Comment by graemerocher** [comment] 2015-09-04 20:22
And another: http://stackoverflow.com/questions/30411520/how-to-overcome-the-filename-or-extension-is-too-long-error-with-gradle-in-win

**Comment by Davehuu** [comment] 2015-10-29 14:02
Use this tool “Long Path Tool”
Awesome tool to fix this error
Thanks

**Comment by flofreud** [comment] 2015-12-28 10:56
A possible workaround is to add the following to your build.gradle (at least it works for our project)

```
import org.gradle.internal.os.OperatingSystem

if (OperatingSystem.current().isWindows()) {
    task pathingJar(type: Jar) {
        dependsOn configurations.runtime
        appendix = 'pathing'

        doFirst {
            manifest {
                // Build the Class-Path for absolute paths based on runtime dependencies.
                attributes "Class-Path": configurations.runtime.files.collect {
                    it.toURL().toString().replaceFirst(/file:\/+/, '/')
                }.join(' ')
            }
        }
    }

    // This gradle task will be called by `grails run-app`.
    bootRun {
        dependsOn pathingJar
        doFirst {
            // Add the compiled app classed to the classpath of the pathing jar. Probably there is a gradle variable for them?
            classpath = files("$buildDir/classes/main", "$buildDir/resources/main", "$projectDir/gsp-classes", pathingJar.archivePath)
        }
    }

    // Do the same for like for bootRun for the run task executable by `gradle run`.
    run {
        dependsOn pathingJar
        doFirst {
            classpath = files("$buildDir/classes/main", "$buildDir/resources/main", "$projectDir/gsp-classes", pathingJar.archivePath)
        }
    }
}
```

In principle we could also use the pathing jar on all platforms. There is also a small issue with the assetCompile task of the asset pipeline. It is attached to the jar task and therefore the pathing jar will contain the compile assets.

@graemerocher: Is there a easier (and more consistent) solution to get the compiled artefact folders used in the `bootRun` / `run` task? I expect that the `gsp-classes` entry is there only if the `org.grails.grails-gsp` plugin is used and there will be probably other cases in which other directories have to be added onto the classpath.

Probably the best solution would be to generate the pathing jar inside the `run` / `bootRun`.

**Comment by flofreud** [comment] 2015-12-28 13:23
Here is the fix for the issue with the asset inside the pathing jar (which will break asset reloading):

```
if (OperatingSystem.current().isWindows()) {
    task pathingJar(type: Jar) {
        dependsOn configurations.runtime
        appendix = 'pathing'

        doFirst {
            manifest {
                // Build the Class-Path for absolute paths based on runtime dependencies.
                attributes "Class-Path": configurations.runtime.files.collect {
                    it.toURL().toString().replaceFirst(/file:\/+/, '/')
                }.join(' ')
            }
        }

        // assetCompile will be execute for all Jar-type tasks
        // (see https://github.com/bertramdev/asset-pipeline/blob/master/asset-pipeline-gradle/src/main/groovy/asset/pipeline/gradle/AssetPipelinePlugin.groovy#L85)
        // at least exclude the assets from pathing jar
        exclude { it.file.absolutePath.contains('assetCompile') }
    }

    // This gradle task will be called by `grails run-app`.
    bootRun {
        dependsOn pathingJar
        doFirst {
            // Add the compiled app classed to the classpath of the pathing jar. Probably there is a gradle variable for them?
            classpath = files("$buildDir/classes/main", "$buildDir/resources/main", "$projectDir/gsp-classes", pathingJar.archivePath)
        }
    }

    // Do the same for like for bootRun for the run task executable by `gradle run`.
    run {
        dependsOn pathingJar
        doFirst {
            classpath = files("$buildDir/classes/main", "$buildDir/resources/main", "$projectDir/gsp-classes", pathingJar.archivePath)
        }
    }
}
``` 

The assetCompile task will be still executed but the assets not packaged into the pathing jar.

**Comment by dubininss** [comment] 2016-01-25 11:49
@flofreud thanks for your workaround! Very helpfull!

**Comment by Schlogen** [comment] 2016-02-24 13:04
Fixed by https://github.com/grails/grails-core/pull/9728. Will be included in the next 3.0.x and 3.1.x release.

**Closed by Schlogen** 2016-02-24 13:04 UTC
Labels: Windows

**Comment by Schlogen** [comment] 2016-02-24 16:08
For future reference, to enable the behavior your `build.gradle` must have the `pathingJar` option set to true:

```
grails {
    pathingJar = true
}
```

**Comment by smilanko** [comment] 2016-03-08 16:30
@Schlogen so do we still need to define our custom pathingJar task, or is the code you provided supposed to be the entire solution?

**Comment by Schlogen** [comment] 2016-03-08 16:54
@smilanko The code I listed above is the entire solution

**Comment by smilanko** [comment] 2016-03-08 17:07
@Schlogen If i copy and paste your code into my build.gradle, I get this error:

Error Gradle build terminated with error: No such property: pathingJar for class: org.grails.gradle.plugin.core.GrailsExtension

Is this not supported by 3.1.1 ?

**Comment by Schlogen** [comment] 2016-03-08 17:22
@smilanko No, support began in 3.1.2

**Comment by keltik85** [comment] 2016-07-19 15:03
@Schlogen I added your code snippet and i get this error:
```groovy
Could not find method grails() for arguments [build_biqz4eh7002vnl06i84yesayk$_run_closure1@6f387973] on root project 'myfunnygrailsproject'.
```

I am on Grails version 3.1.4

**Comment by Schlogen** [comment] 2016-07-19 15:12
@keltik85 That most likely means the grails gradle plugin isn't included in your build.gradle. Create a fresh 3.1.4 application and look at the differences between the `build.gradle` files.

**Comment by gandra** [comment] 2016-10-04 18:22
@flofreud 
your workarround is very helpfull.

THANKS A LOT!!!!!!

**Comment by indukuri033** [comment] 2016-12-19 20:37
@jameskleeh, I tried the work around with 

grails {
    pathingJar = true
}

I still see the following error:

Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long

**Comment by jameskleeh** [comment] 2016-12-19 20:38
@indukuri033 What version of Grails?

**Comment by indukuri033** [comment] 2016-12-19 20:40
its 3.1.14

**Comment by jameskleeh** [comment] 2016-12-19 20:45
@indukuri033 If you can reproduce the issue in a fresh 3.2.3 application, create a separate issue with the example application attached and exact steps to reproduce and I'll take a look

**Comment by indukuri033** [comment] 2016-12-19 22:50
@jameskleeh So here is a very quick update, I have a old copy of the code which i used to build using the grails 3.1.10, when i first build this application i got the Exception: Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long

i followed this form and added the pathingJar value true and the build was successful, i dont see any issues with the old application even with grails 3.2.3.

We had a recent release last week, so i went back and check out the latest code, there were too many updates to the old code base, we also upgraded grail to 3.1.14 to accommodate those changes.
when i build using 3.1.14 i see Exception: Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long, as per your suggestion i tied with 3.2.3 and still have the same issue.

attached is the old build gradle and the new build gradle. properties




[gradle_OLD_NEw.docx](https://github.com/grails/grails-core/files/662342/gradle_OLD_NEw.docx)

**Comment by woodmawa** [comment] 2017-03-22 12:42
hit same problem - i think i added some extra dependencies and all of a sudden the build started to fail.  

i upgraded to gradle 3.4.1 - failed.  Trired gradle 3.3 failed. 

tried to add pathingJar option in build 

```
buildscript {

    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.11.6"
        classpath "org.grails.plugins:hibernate5:6.0.7"
        classpath "org.grails.plugins:views-gradle:1.2.0"  //added view compilation tasks
    }
}

/*ext {
    //overcome error executing java for gson views compilation
    grails {
        pathingJar = true
    }
}*/
```

and removed comments - fails with 
`Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method grails() for arguments [build_aniogvc26rmjtm000qpc5hdju$_run_closure1$_closure2$_closure5@2bc03d04] on object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.
`

what are we supposed to do with this to fix it ?

**Comment by graemerocher** [comment] 2017-03-22 12:47
why is your `grails` block within a `ext` block?

**Comment by woodmawa** [comment] 2017-03-23 16:24
Hi Graeme tried it project level failed 

 

Read this 

https://github.com/grails/grails-core/issues/9125

 

so tried it in ext{} – also fails

 

project is here at mo – think its all pushed and updated 

 

https://github.com/woodmawa/coffeeShopApp

**Comment by graemerocher** [comment] 2017-03-23 16:33
@woodmawa I think the JSON views gradle plugin does not yet support the pathing JAR.. @jameskleeh will need to confirm.

Can probably be worked around by adding the following to the end of `build.gradle`:

```groovy
compileGsonViews {
    classpath = project.files("${project.buildDir}/classes/main",
              "${project.buildDir}/resources/main", pathingJar.archivePath)
}
```

Or by not using Windows.

**Comment by jameskleeh** [comment] 2017-03-23 18:09
@woodmawa The compileGsonViews task should be supported with the pathing jar. One thing that is not correct is https://github.com/woodmawa/coffeeShopApp/blob/master/build.gradle#L70. The `views-gradle` dependency should only be in the buildscript. The `views-json` dependency should be in it's place.

**Comment by woodmawa** [comment] 2017-03-23 18:42
Well gol dang it, at one time I had that as views-json:1.1.5, 

 

Must have got my self all confused on the updates – saw the new gradle plugin in buildscript – but I updated in the main dependencies, saw the views-json-templates and id added that as I was going to enable mongo, 

 

However thanks for spotting that  - just corrected locally and its started to compile/dev run again .

 

I’ll update the stackoverflow in a sec

 

Thanks for that got into a pickle and was spinning whilst trying to do my day job at the same time – couldn’t focus properly on either.  I’ll give it a go and check it works with the localDateTime as well which 1.1.5 didn’t handle in domain classes 

 

Thanks again 

 

Will

**Comment by EricClarcks** [comment] 2017-08-19 12:21
I recommend that you try long path tool, it's really useful tool and it had worked with me.
