### ISSUE TITLE
Hot Reload is failing no matter what is modified

### ISSUE THREAD

**Issue by mangelo123** [grails/grails-core#11401] opened 2019-09-06 18:32 UTC
If I modify a controller, service, etc I get the error below. I understand domain classes may be the exception, but the hot reload feature used to work in Grails 3.x

I am on 4.0

Caused by: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@//opsrac113.xxxxxxxxxxx

**Comment by jmorrispa** [comment] 2019-10-02 04:56
Same behavior with mysql. In the logs there is a loop of messages like this:
2019-10-01 23:53:29.491  INFO --- [  restartedMain] o.h.v.internal.engine.ConfigurationImpl  : HV000002: Ignoring XML configuration.
2019-10-01 23:53:29.501  WARN --- [  restartedMain] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000341: Could not obtain connection metadata : No suitable driver found for jdbc:mysql://localhost/mos
2019-10-01 23:53:29.502  INFO --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
2019-10-01 23:53:29.502  INFO --- [  restartedMain] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000422: Disabling contextual LOB creation as connection was null
2019-10-01 23:53:30.917  WARN --- [  restartedMain] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 08001
2019-10-01 23:53:30.918 ERROR --- [  restartedMain] o.h.engine.jdbc.spi.SqlExceptionHelper   : No suitable driver found for jdbc:mysql://localhost/mos
2019-10-01 23:53:30.951  INFO --- [  restartedMain] o.h.v.internal.engine.ConfigurationImpl  : HV000002: Ignoring XML configuration.
2019-10-01 23:53:30.958  WARN --- [  restartedMain] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000341: Could not obtain connection metadata : No suitable driver found for jdbc:mysql://localhost/mos
2019-10-01 23:53:30.958  INFO --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
2019-10-01 23:53:30.958  INFO --- [  restartedMain] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000422: Disabling contextual LOB creation as connection was null
2019-10-01 23:53:32.366  WARN --- [  restartedMain] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 08001
2019-10-01 23:53:32.366 ERROR --- [  restartedMain] o.h.engine.jdbc.spi.SqlExceptionHelper   : No suitable driver found for jdbc:mysql://localhost/mos
....

**Comment by jameskleeh** [comment] 2019-10-10 04:29
@mangelo123 @jmorrispa Can either of you provide a sample app that reproduces the issue?

**Comment by mangelo123** [comment] 2019-10-10 14:00
I have since resolved "Caused by: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@//opsrac113.xxxxxxxxxxx". There is code in our Bootstrap.groovy that was using Sql.newInstance vs injecting dataSource. Once I refactored the code, everything is working including auto-restart.

**Comment by jameskleeh** [comment] 2019-10-10 19:36
Going to close this then. If anyone else is having the same issue please open a new issue with an example app

**Comment by jmorrispa** [comment] 2019-10-11 02:46
Hi James,

In my case I found the problem shows up when dataSource.polled=false in application.yml.

if dataSource.polled=true, reloading works fine.

Find attached a sample project.

[hotleload.zip](https://github.com/grails/grails-core/files/3715403/hotleload.zip)

**Comment by jameskleeh** [comment] 2019-10-11 15:51
This is happening because for non pooled connections we use `org.springframework.jdbc.datasource.DriverManagerDataSource` which relies on the JDBC driver to register itself in the `DriverManager`. On shutdown (caused by a reload), the `DataSourceGrailsPlugin` clears the drivers in the `DriverManager` and thus the data source can no longer find the driver.

Possible solutions:
1. Stop deregistering the drivers
2. Use `SimpleDriverDataSource` instead of `DriverManagerDataSource`

**Comment by erichelgeson** [comment] 2019-10-11 16:18
Some discussion on deregistering in boot - https://github.com/spring-projects/spring-boot/issues/2612

**Comment by mangelo123** [comment] 2019-10-11 17:07
Is it possible to have the reload function not reload Spring security? I noticed that happens when we make small change to a controller class.

**Comment by jameskleeh** [comment] 2019-10-11 17:13
@mangelo123 I'm not sure how that is relevant to this issue

**Comment by graemerocher** [comment] 2019-10-14 08:46
I think the correct thing to do is disable deregistration of the drivers in dev mode

**Closed** 2019-10-14 15:42 UTC
Labels: Bug

**Comment by mangelo123** [comment] 2019-10-14 16:50
I have since encountered another issue with reload. If a service is modified, I am seeing the following:

`
Exception in thread "Thread-26" BUG! exception in phase 'semantic analysis' in source unit 'C:\Users\mangelo\IdeaProjects\sandbox4\grails-app\services\sandbox4\CustomerService.groovy' unexpected NullpointerException
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1089)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:645)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:623)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at grails.boot.GrailsApp.compileGroovyFile(GrailsApp.groovy:383)
	at grails.boot.GrailsApp.recompile(GrailsApp.groovy:369)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:64)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:184)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:310)
	at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at groovy.lang.Closure.run(Closure.java:486)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.grails.datastore.gorm.services.implementers.AbstractDetachedCriteriaServiceImplementor.doImplement(AbstractDetachedCriteriaServiceImplementor.groovy:79)
	at org.grails.datastore.gorm.services.implementers.AbstractReadOperationImplementer.implement(AbstractReadOperationImplementer.groovy:62)
	at org.grails.datastore.gorm.services.transform.ServiceTransformation.visitAfterTraitApplied(ServiceTransformation.groovy:278)
	at org.grails.datastore.gorm.transform.AbstractTraitApplyingGormASTTransformation.visit(AbstractTraitApplyingGormASTTransformation.groovy:52)
	at org.grails.datastore.gorm.transform.AbstractTraitApplyingGormASTTransformation.visit(AbstractTraitApplyingGormASTTransformation.groovy:42)
	at org.grails.datastore.gorm.transform.AbstractGormASTTransformation.visit(AbstractGormASTTransformation.groovy:59)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:145)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:189)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1084)
	... 29 more
`

I have included a sample project at: [https://github.com/mangelo123/sandbox4.git]

If you simply modify the getOne() method in CustomerService, you should get the same error.

**Comment by mangelo123** [comment] 2019-10-16 15:07
Can this issue be reopened or should I create a new one with my latest findings?

**Comment by jameskleeh** [comment] 2019-10-16 15:08
@mangelo123 That problem is unrelated to this issue so I would recommend creating a new issue
