### ISSUE TITLE
Use sensible defaults to avoid excessive use of marshallers and converters for REST apis

### ISSUE THREAD

**Issue by ejaz-ahmed** [grails/grails-core#9673] opened 2016-02-10 17:58 UTC
Grails default json/xml response is not quite usable in most of the cases and user has to register marshallers for collection and individual items. For large projects, it is hard to maintain such boiler plate and grails sort of loose its attraction as being rapid app development framework. Example is, no one needs class attribute (org.grails.demo.Book) in json/xml response. Similarly, related entities have just class name and id. It can be replaced with id and other useful members and class should be excluded from default attributes.

**Comment by jeffbrown** [comment] 2016-02-10 18:01
Is the request to exclude `class` and to generate a deep representation in the JSON by default?

**Comment by ejaz-ahmed** [comment] 2016-02-10 18:18
Yes. Although class has been removed from 3.1.x but JSON is not useful. It should render other attributes of related classes too and this should be back ported to 3.0.x branch too. This issue when combined to [this issue](https://github.com/grails/grails-core/issues/9672) produces more value.

**Comment by graemerocher** [comment] 2016-02-11 08:28
These changes won't be back ported to 3.0.x since they are breaking changes. Also, marshallers and converters have been replaced by GSON views in 3.1.x which are much more flexible and superior

**Comment by ejaz-ahmed** [comment] 2016-02-11 09:37
It is fine if these changes are not back-ported to grails 3.0.x and it makes sense for feature requests. Regarding GSON views, you are right in a sense they are more flexible and superior to marshallers and converters. In my opinion, GSON views should be used only when there is some specific requirement. For normal use case, grails should provide required response out of the box like Spring Data Rest. Look at HAL example you have there in README.md of grails-views project. If a person has to repeat this code for each and every domain and in worst case some boilerplate for every view too. What will be the situation if someone needs xml as well as json? Twice the effort. Grails follows DRY principle everywhere and it should be taken care of in REST APIs as well.

**Comment by graemerocher** [comment] 2016-02-11 09:46
Agreed, but that is more because we are missing a `hal.render(obj)` method in the same way you can do `g.render(obj)`, which seems like a reasonable feature request.

I don't agree regarding GSON views being only for some specific requirement however, Spring Data REST ends up leaning very heavily on Jackson, which is horrible.

As for XML support, that is become more and more rare, but we do have GML views for that as well.

**Comment by ejaz-ahmed** [comment] 2016-02-11 10:04
The use of GSON views can be avoided for most of the cases and for simple domain objects by choosing reasonable defaults (probably it is my opinion). It will have a reasonable impact of developer's productivity. The example of Spring Data REST was for reference that we should have similar stuff in grails. I am not aware of its internal architecture, but if I have similar solution for my project, it will be enough for 80 % of my needs and doing customizations for 20% is not a problem. If I go with GSON views, I have to repeat same piece of code for every domain class and for every view too, in that case I'll go for marshallers instead. Achieving more with less code is some times better versus flexibility and verbosity.

**Comment by graemerocher** [comment] 2016-02-11 11:11
This issue could be solved simply by allowing a default GSON view that is rendered if no other view is found for an object.

**Comment by ctoestreich** [comment] 2016-02-16 20:52
I was hoping this would work, but no dice.

``` groovy
import com.bsb.content.BcpContent
import grails.converters.JSON

model {
	BcpContent bcpContent
}

JSON.use('admin'){
    json g.render(bcpContent)
}
```

**Comment by graemerocher** [comment] 2016-02-17 07:36
I think you were confusing what I said. The JSON converters APIs found in `grails.converters.*` cannot be used by GSON views. The way GSON views solve the problem is that you can have 2 views, one called "admin" and one called "default" for example, that render different GSON depending what you want to achieve. These can then be enabled via the `render` or `respond` methods:

       respond obj, view:'admin'

This effectively achieves the same thing as what namespaced converters used to. You can also break up those views using templates so that common logic can be used by both.

**Comment by ctoestreich** [comment] 2016-02-17 20:15
Following the examples laid out [here](https://github.com/grails/grails-views#templates) to recreate nested gson template rendering it would appear that the relative path isn't recognized for g.render and the fully qualified path is required even when the template is located in the same directory as the calling gson file.

Doing this `contents g.render(template: "content", collection: managedContent.contents, var: 'content')` breaks and fails to render

<img width="1334" alt="screen shot 2016-02-17 at 2 10 58 pm" src="https://cloud.githubusercontent.com/assets/691357/13123190/b642a682-d580-11e5-93b4-c517e55df439.png">

**Comment by jeffbrown** [comment] 2016-02-17 20:24
@ctoestreich I think that is a separate issue than the one described at the top here.

**Comment by ctoestreich** [comment] 2016-02-17 20:56
@jeffbrown Totally, I am not calling this out as an issue per say, just an observation of us dealing with how to move our named JSON marshallers to the gson views which is where this conversation seemed to be leading.

I, personally, like the introduction of the gson views.  I actually don't know if the defaults currently are not sensible.  I think it is just the case that most times you are going to customize the marshallers for security, data size, etc.  So if we are all in for gson views, then let's clear up how to move to that and what is the best way to do the deep custom marshalling and share across endpoints.

**Comment by graemerocher** [comment] 2016-02-18 07:37
@ctoestreich could you raise a separate issue for the relative path problem

**Comment by cavemansspa** [comment] 2016-04-11 13:40
Is there an issue created for the relative path problem as described by @ctoestreich?  I am hitting that problem and not seeing a new issue anywhere so that it can be resolved

Currently, I'm unable share a common json view across folders / controllers.

**Comment by graemerocher** [comment] 2016-04-11 13:54
@cavemansspa upload an example to github that reproduces the problem and create a new issue please

**Comment by ctoestreich** [comment] 2016-04-12 19:31
@cavemansspa Our main problem ATM is that views get compiled but not correctly.  See details here https://github.com/grails/grails-views/issues/13

Otherwise running normal debug via bootRun seems to work fine.  You have to use absolute pathing (with the views directory being the / aka root ) to do this.  Something like  this for a file in the `grails-app/views/templates/common/_rule.json` to reference another file `grails-app/views/templates/common/_condition.json`

##### File grails-app/views/templates/common/_rule.json

``` groovy
import com.bsb.managed.content.rules.Rule

model {
	Rule rule
}

json {
    id rule.id.toString()
    name rule.name
    conditions g.render(template: "/templates/common/condition", collection: rule.conditions, var: 'condition')
}
```

**Comment by graemerocher** [comment] 2016-07-25 10:34
Closing this as of Grails 3.2 M2 by default JSON views are used to render all JSON responses and the converters API is not used. Since JSON views provide all of the features and flexibility necessary I don't see the need to leave this issue open.

**Closed by graemerocher** 2016-07-25 10:34 UTC
Labels: Improvement, REST
