### ISSUE TITLE
Grails 2.5: unable to deep render Objects with collection attributes.  render  collection as {"empty":false}

### ISSUE THREAD

**Issue by xmlking** [grails/grails-core#680] opened 2015-05-03 16:14 UTC
I have a [CustomUserDetails] (https://github.com/xmlking/grails-batch-rest/blob/master/src/groovy/org/sumo/apiapp/security/CustomUserDetails.groovy) that I am trying to render in [LoginController](https://github.com/xmlking/grails-batch-rest/blob/master/grails-app/controllers/org/sumo/apiapp/security/LoginController.groovy#L140)

```groovy
    @Secured(value=["isAuthenticated()"], httpMethod='GET')
    def User currentUser() {
        println springSecurityService.principal.authorities  // <-- this prints authorities
		// respond  springSecurityService.principal ,  [formats:['json']]  <-- authorities empty 
		JSON.use('deep') {
			respond springSecurityService.principal, [formats:['json']]  //<-- authorities empty  even with deep. 
		}
    }
```
Result:
```json
{"accountNonExpired":true,"accountNonLocked":true,"authorities":{"empty":false},"credentialsNonExpired":true,"departmentNumber":"NO_DEP","displayName":"Chintha, Sumanth","email":"sumo@demo.com","enabled":true,"id":1,"ldapAuth":false,"postalCode":"55555","title":"IT Consultant","uid":"sumo","username":"sumo"}
```
Expected Result:
```json
{"accountNonExpired":true,"accountNonLocked":true,"authorities":["ROLE_SUPER_ADMIN", "ROLE_USER"],"credentialsNonExpired":true,"departmentNumber":"NO_DEP","displayName":"Chintha, Sumanth","email":"sumo@demo.com","enabled":true,"id":1,"ldapAuth":false,"postalCode":"55555","title":"IT Consultant","uid":"sumo","username":"sumo"}
```
I also declared some custom Renderers in [resources.groovy](https://github.com/xmlking/grails-batch-rest/blob/master/grails-app/conf/spring/resources.groovy#L26) but no difference with or without those settings.

**Comment by xmlking** [comment] 2015-05-04 05:12
found this had been reported at https://jira.grails.org/browse/GRAILS-11892

**Comment by zyro23** [comment] 2015-05-04 07:18
another related/duplicate: https://github.com/grails/grails-core/issues/615

**Comment by jeffbrown** [comment] 2015-05-04 13:54
Closing as a duplicate of #615.

**Closed by jeffbrown** 2015-05-04 13:54 UTC
Labels: Duplicate
