### ISSUE TITLE
GRAILS - Unable to Name a Domain Class "Service" ... Naming Conflict...

### ISSUE THREAD

**Issue by MauiMana** [grails/grails-core#9195] opened 2015-08-19 03:10 UTC
I realize that the term *Service* is a keyword in a number of contexts. However, with the ability to prefix such terms with a fully-qualified namespace path it seems quite plausible to support use of such terms in naming domain classes, etc. In my specific case, he notion of a *service* can easily exist as an integral concept within a specific domain one is attempting to model. Here is a domain class and corresponding test case which exemplify the particular issue:

    // Service Domain Class
    package com.sandbox.namingconflict

    class Service {
        String name

        static constraints = {
            name blank: false, nullable: false
        }
    }

    // Test Case
    package com.sandbox.namingconflict

    import grails.test.mixin.integration.Integration
    import grails.transaction.Rollback
    import spock.lang.Specification

    @Integration
    @Rollback
    class ServiceSpec extends Specification {

        void "Build a valid Service"() {
            given:
               def theService = new Service( name: "The Service" )
               theService.save( failOnError: true )

            expect:
               Service.findByName( "The Service" ).id == theService.id
        }
    }

If one refactors the name of the example domain class to something other than the term *Service*, all will work fine, but the purity of the domain model understandably suffers...

**Comment by leadVisionary** [comment] 2015-09-23 06:26
I'm going to have to +1 this, as I just got bitten by it. 

The frustrating thing is that the failure message on my unit test was as follows:
```groovy
groovy.lang.MissingMethodException: No signature of method: com.fooze.Service.validate() is applicable for argument types: () values: []
Possible solutions: wait()
	at com.fooze.ServiceSpec.rejects blank name(ServiceSpec.groovy:17)
```

This message persists if I rename my class to `ApplicationService` or `CoolService`. If I name it something that doesn't have `Service` in it, like `BlueBerry`, the test passes without issue.

It'd be nice for the testing mixin to either make the test fail hard on `*Service`, or not assume that `Service` is a suffix for something in the Service Layer/reserved word.

**Comment by Schlogen** [comment] 2016-08-23 19:25
Fixed by https://github.com/grails/grails-core/pull/10082

**Closed by Schlogen** 2016-08-23 19:25 UTC
Labels: Minor

**Comment by jeffbrown** [comment] 2016-08-23 19:32
> It'd be nice for the testing mixin to either make the test fail hard on *Service, or not assume that Service is a suffix for something in the Service Layer/reserved word.

I don't think this is really an issue with the testing mixin.  The testing stuff is behaving the way that it should as far as I can tell.  I think the issue is that the class was being configured as a service, not as a domain class.
