### ISSUE TITLE
Plugins should be able to use plugin.groovy along with plugin.yml

### ISSUE THREAD

**Issue by longwa** [grails/grails-core#9403] opened 2015-11-06 03:11 UTC
We have an inline plugin with configuration that is shared with several application modules. In Grails 2, much of this configuration is in a PluginNameConfig.groovy file which is automatically included in the application.

However, in Grails 3, the only built-in way to get plugin configuration into the application seems to be with the plugin.yml file.

The plugin.yml is ok for some things, but we have several cases where we need to use .groovy configuration (for example, some spring security config params take a Closure).

It would be nice and consistent if plugin.groovy was also an option in the same way that application.groovy is an option for the application.

I was able to hack together something in the plugin itself that loads a Config.groovy via ConfigSlurper and merge(), but that doesn't fix the springsecurity example, for instance, b/c that plugin has to load before our plugin loads (we override some of the beans).

**Comment by longwa** [comment] 2015-11-06 16:55
@graemerocher  As a workaround in 3.0, is there an early place to hook into the configuration load such that I could config slurp my own config into the grailsApplication.config object?

I know setEnvironment() gets called early, but it doesn't seem like the grailsApplication is available at that point. It really needs to be after the grailsApplication.config is loaded but before any plugins are loaded.

**Comment by graemerocher** [comment] 2015-11-06 17:28
You would have to override `GrailsApplicationPostProcessor.loadApplicationConfig()`

**Comment by longwa** [comment] 2015-11-06 21:59
Perfect, looks like I can hook into that through the GrailsAutoConfiguration class. I'm really liking how much simpler the framework code seems to be now.

**Comment by ctoestreich** [comment] 2015-12-28 16:01
Below is what we did this for the time being to allow us to `run` and test the inline web plugin.  This keeps the two files in sync.  I will look at the code today and see what I can do about having the plugins recognize the application.yml.  I think there should probably be a decision on whether to keep the plugin.yml around or not if application.yml is supported.  It might just get convoluted having multiple ways to config the project via yml. @graemerocher thoughts before I PR?

```
task copyApplicationYml(type: Copy) {
	from 'grails-app/conf'
	into 'grails-app/conf'
	include "plugin.yml"
	rename('plugin.yml', 'application.yml')
}

bootRun.dependsOn copyApplicationYml
```

**Comment by Schlogen** [comment] 2016-02-03 20:35
Fixed by https://github.com/grails/grails-core/pull/9630

Note that it is one or the other, plugin.yml or plugin.groovy

**Closed by Schlogen** 2016-02-03 20:35 UTC
Labels: Improvement

**Comment by olliefreeman** [comment] 2016-04-12 11:59
I know this issue is stated that it's fixed, but it doesn't seem this way to me. #9630 still ensures either yml or groovy. 

I'm working through my project updating configurations to grails 3.1.4 and using plugin.yml converting from application.yml and application.groovy. I have both of these as I have several groovy only configuration elements, such as the below, both of these I can't see any way of doing in the yml file.

```groovy
grails.gorm.default.constraints = {
    phoneNumber(matches: /(((\+44)? ?(\(0\))? ?)|(0))( ?[0-9]{3,4}){3}/)
    postcode(
            matches: /(GIR ?0AA|[A-PR-UWYZ]([0-9]{1,2}|[A-HK-Y][0-9]([0-9ABEHMNPRV-Y])?|[0-9][A-HJKPS-UW]) ?[0-9][ABD-HJLNP-UW-Z]{2})/)
    nhsOrgCode(size: 3..12, matches: /[A-Z0-9]{3,12}/)
    snomedCt(size: 6..18, matches: /\d{6,18}/)
    snomed(size: 6..8, matches: /[A-Z0-9]*/)
}

grails.gorm.default.mapping = {

    StandardNamingStrategy namingStrategy = it.getBean('namingStrategy')

    hibernateCustomUserType type: PersistentLocalDate, class: LocalDate
    hibernateCustomUserType type: PersistentOffsetDateTime, class: OffsetDateTime

    String schemaName = namingStrategy.canonicalNameToSchemaName(className)
    String tableName = namingStrategy.canonicalNameToTableName(className)

    table name: tableName, schema: schemaName
    datasources namingStrategy.getDataSources(className)

    autoImport false
}
```

If there is another way of doing this then I would be appreciative of knowing how. Otherwise I will take the advice above and override the `GrailsApplicationPostProcessor`

**Comment by danielritter** [comment] 2018-08-17 12:17
I'm also interested in a solution for this issue.

**Comment by jameskleeh** [comment] 2018-08-17 13:44
@danielritter There are no plans to support both. I don't see any reason why all of the config can't be in one or the other.

**Comment by danielritter** [comment] 2018-08-17 14:27
@jameskleeh I have in my plugin next to my application.yml file a file called plugin.groovy (or application.groovy, both does not work) with following constraints in it. This constraints work only in "groovy-style":

```
// Default constraints.
grails.gorm.default.constraints = {
    defaultShortTextInputConstraint(blank: false, nullable: true, size: 1..64)
    defaultTextInputConstraint(blank: false, nullable: true, size: 1..128)
}
```

So it would be nice if I can use the application.yml and the plugin.groovy/application.groovy file in the plugin.

**Comment by olliefreeman** [comment] 2018-08-17 14:31
@jameskleeh i think the issue is that the preferred way and documented way now is for yml for config. So much so that if you set everything up its all yml...then you want to add constraints or mappings and these can only be done in groovy. Which means you then have to work out how to change all your yml config into groovy or remember to add all the plugin groovy config to the including application groovy file...currently our 2 major projects support over 10 plugins in 1 and 5 in another....this is tedious to ensure its always matched up correctly.

Being able to just define both would make life easier.

**Comment by jameskleeh** [comment] 2018-08-17 14:32
@danielritter `application.(groovy|yml)` will not be passed as config to applications that use your plugin. The configuration `plugin.(groovy|yml)` will. If you need to use Groovy for some reason, then just have all of your config in Groovy.

**Comment by jameskleeh** [comment] 2018-08-17 14:39
@olliefreeman 

> So much so that if you set everything up its all yml

Grails doesn't provide a `plugin.yaml` by default.

> Which means you then have to work out how to change all your yml config into groovy

I realize if you started out using `plugin.yml` and then came across the need to use Groovy, that it would take a small amount of time to convert it and that is not ideal.

> or remember to add all the plugin groovy config to the including application groovy file

That would be a specific requirement of yours. I don't think that is typical. Most of the plugins have just the config needed to test the application in `application.groovy`, which is different than `plugin.groovy`.

Overall I don't think this is something we will revisit because of the increased complexities of ensuring the order of configuration properties is what people would expect. To me this is a minor inconvenience that some users may experience if they encounter what I said above.

**Comment by olliefreeman** [comment] 2018-08-17 14:40
fair enough.

**Comment by danielritter** [comment] 2018-08-17 14:44
@jameskleeh Ah, the ``plugin.groovy`` file and its configuration will only be passed in the application and not in the plugin itself? Because I want to set default constraints which I want to reference in a domain class of the plugin. So that when I want to pass my test in my plugin I get an error message that the shared constraints are not available.

**Comment by jameskleeh** [comment] 2018-08-17 14:44
@danielritter Correct

**Comment by danielritter** [comment] 2018-08-17 14:47
@jameskleeh Ok. Is there a way to share the constraints in the plugin itself?

**Comment by longwa** [comment] 2018-08-17 15:08
It would be nice if the `plugin.groovy` were loaded for tests. We had some places where we had to copy stuff from `plugin.groovy` to `application.groovy` just for testing. That seems like a completely separate ticket though.
