### ISSUE TITLE
Can't allocate new domain object with params in 3.0.2

### ISSUE THREAD

**Issue by cylon** [grails/grails-core#9126] opened 2015-07-22 15:33 UTC
Allocating a new domain object with the params object fails.

    new DomainObject(params)

--> `Caused by: groovy.lang.MissingPropertyException: No such property: controller for class: ...`

The params object looks like:
`[description:Nice Description, searchString:XYZ, controller:destination, format:null, action:create]`

**Comment by jeffbrown** [comment] 2015-07-22 15:40
It looks like `DomainObject` isn't a domain class.  Where is its source defined?

**Comment by jeffbrown** [comment] 2015-07-22 15:46
The normal Groovy constructor behavior is if you pass a `Map` to the constructor, all of the keys in the `Map` have to correspond with property names in that object.  We add a special constructor to Grails domain classes that ignores entries that don't have corresponding properties in the class.  This is useful because it is common to want to instantiate an instance of a domain class with the request parameters, which often contain a bunch of entries that don't correspond to properties in the class.  It looks like you are passing `params` to the constructor of a non domain class.  If it is a domain class, then please show the source code for any constructors that you have defined in that domain class.

**Comment by cylon** [comment] 2015-07-22 16:21
Maybe it's a complicating issue, but it is a hibernate mapped class.  This used to work in 2.x.

```java
@Entity
@Table(name="DESTINATION_GROUPS")
public class DestinationGroup  implements java.io.Serializable
{
...
    public DestinationGroup() {
    }


    public DestinationGroup(String searchString, String description) {
        this.searchString = searchString;
        this.description = description;
    }
    public DestinationGroup(String searchString, String description, Set<Destination> destinations) {
        this.searchString = searchString;
        this.description = description;
        this.destinations = destinations;
    }
...

}
```

**Comment by jeffbrown** [comment] 2015-07-23 13:47
> Maybe it's a complicating issue, but it is a hibernate mapped class.

I doubt that it being a hibernate mapped class is the relevant bit. All domain classes by default are hibernate mapped.  I expect the issue has more to do with the fact that the domain class is written in Java.  I think we probably are not adding the dynamic constructor to Java classes in 3.  Will investigate.

Knowing that the class is written in Java is helpful.  Thanks for the feedback.

**Comment by arvind-das** [comment] 2015-07-24 09:46
At this point of time I did this in my controller before assigning to my domain classes

['controller','action','format'].each{
            params.remove(it)
        }

Working as a temporary solutions. Command Objects are also not working and not binding data, any Ideas ?

**Comment by jeffbrown** [comment] 2015-07-24 11:54
> Command Objects are also not working and not binding data, any Ideas ?

I know what is wrong with the Java domain classes and we are working on a solution.  That problem would not affect command objects so if there is a problem with command objects that would be separate.  Please file an issue and describe under what circumstances data binding is not working for command objects.

Thanks for the feedback.

**Comment by mhuebner** [comment] 2015-08-06 13:47
I've got the same problem:
    ```def create() {
        respond new CreateOriginCommand(params)
    }
    ```

Results in 
```
Caused by: groovy.lang.MissingPropertyException: No such property: controller for class: de.pfc.admin.origin.CreateOriginCommand
	at de.pfc.admin.origin.OriginController$$EPKaY4Kt.$tt__create(OriginController.groovy:40) ~[na:na]
	at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:93) ~[grails-core-3.0.4.jar:3.0.4]
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:90) ~[grails-core-3.0.4.jar:3.0.4]
	... 3 common frames omitted
```

**Comment by arvind-das** [comment] 2015-08-06 13:57
You can simply remove controller and action from params by
params.exclude['controller','action '] before assigning to create origin
command but there should be no need to pass as command object should
automatically bind. Let me know .

**Comment by mhuebner** [comment] 2015-08-26 12:23
3.0.4 is also affected.

@arvind-das Yes, would be a workaound.

**Comment by HenriPablo** [comment] 2015-11-21 19:24
For what it's worth, I ran into the same issue (I think) using the following Groovy/Grails combo when porting from Grails 2.x:

Grails Version: 3.0.9
Groovy Version: 2.4.5
JVM Version: 1.8.0_66

In my controller, in the 'save' method had to do the following:

 ['create', 'controller', 'format','action'].each { params.remove it }

In the 'update' method I had to bind domain properties 'manually' (tiny object, only 2 props):

        aircraftCategoryAndClassInstance.aircraftClass = params.aircraftClass
        aircraftCategoryAndClassInstance.aircraftCategory = params.aircraftCategory

With those modification the 'legacy' controller's CRUD operations function as expected.

**Comment by jeffbrown** [comment] 2016-02-12 22:16
> I've got the same problem:
> def create() { respond new CreateOriginCommand(params) } 

@mhuebner 

That is not a bug.  When you invoke `new CreateOriginCommand(params)` you are passing a `Map` to the constructor and the default Groovy constructor behavior is imposed, which is supposed to throw an exception if the `Map` contains entries that don't have corresponding properties in the class.

**Comment by graemerocher** [comment] 2016-07-25 10:03
Automatic binding via the constructor only works for GORM entities... not any other objects. for other objects using `bindData`

**Closed by graemerocher** 2016-07-25 10:03 UTC
Labels: in progress, Won't Fix
