### ISSUE TITLE
Reloading a new method in a controller fails

### ISSUE THREAD

**Issue by olavgg** [grails/grails-core#9713] opened 2016-02-17 15:33 UTC
Grails 3.014
openjdk version "1.8.0_66-internal"
Linux

How to reproduce.

1. Create a new Grails app
2. run-app
3. create-controller com.olavgg.Blogcontroller (OK)
4. modify the controller com.olavgg.Blogcontroller and add a new action:
5. Stacktrace:

```
grails> File /home/olav/projects/test-projects/reloadcontroller/grails-app/controllers/com/olavgg/BlogController.groovy changed, recompiling...
ERROR org.springsource.loaded.agent.Watcher - FileWatcher caught serious error, see cause
org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class com.olavgg.BlogController] of type [class org.grails.core.DefaultGrailsControllerClass]: InvocationTargetException
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:170) ~[grails-core-3.0.14.jar:3.0.14]
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:784) ~[grails-core-3.0.14.jar:3.0.14]
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:480) ~[grails-core-3.0.14.jar:3.0.14]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169) ~[groovy-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) ~[groovy-2.4.5.jar:2.4.5]                                                                                                                           
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-2.4.5.jar:2.4.5]  
        at org.grails.plugins.web.controllers.ControllersGrailsPlugin.onChange(ControllersGrailsPlugin.groovy:185) ~[grails-plugin-controllers-3.0.14.jar:3.0.14]                                                                                       
        at org.grails.plugins.DefaultGrailsPlugin.notifyOfEvent(DefaultGrailsPlugin.java:792) ~[grails-core-3.0.14.jar:3.0.14]
        at org.grails.plugins.AbstractGrailsPluginManager.informOfClassChange(AbstractGrailsPluginManager.java:386) ~[grails-core-3.0.14.jar:3.0.14]
        at org.grails.dev.support.GrailsSpringLoadedPlugin.reloadEvent(GrailsSpringLoadedPlugin.java:52) ~[grails-core-3.0.14.jar:3.0.14]
        at org.springsource.loaded.TypeRegistry.fireReloadEvent(TypeRegistry.java:2022) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:444) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:1014) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251) [springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235) [springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:161) ~[grails-core-3.0.14.jar:3.0.14]
        ... 21 common frames omitted
Caused by: org.grails.core.exceptions.GrailsConfigurationException: Cannot find invokable controller action: list
        at org.grails.core.DefaultGrailsControllerClass.methodStrategy(DefaultGrailsControllerClass.java:122) ~[grails-core-3.0.14.jar:3.0.14]
        at org.grails.core.DefaultGrailsControllerClass.<init>(DefaultGrailsControllerClass.java:67) ~[grails-core-3.0.14.jar:3.0.14]
        ... 27 common frames omitted
Caused by: java.lang.NoSuchMethodException: no such method: com.olavgg.BlogController.list()Object/invokeVirtual
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:873) ~[na:1.8.0_45]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990) ~[na:1.8.0_45]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1382) ~[na:1.8.0_45]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:858) ~[na:1.8.0_45]
        at org.grails.core.DefaultGrailsControllerClass.methodStrategy(DefaultGrailsControllerClass.java:119) ~[grails-core-3.0.14.jar:3.0.14]
        ... 28 common frames omitted
Caused by: java.lang.NoSuchMethodError: com.olavgg.BlogController.list()Ljava/lang/Object;
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[na:1.8.0_45]
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962) ~[na:1.8.0_45]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987) ~[na:1.8.0_45]
        ... 31 common frames omitted
```

**Comment by jeffbrown** [comment] 2016-02-17 15:35
I think this is a duplicate of #9686.

**Closed by jeffbrown** 2016-02-17 15:35 UTC

**Comment by olavgg** [comment] 2016-02-17 15:38
Yes it is! Sorry, I tried to find it before I submitted a new one.

**Comment by jeffbrown** [comment] 2016-02-17 15:38
@olavgg No worries.  Thank  you for the feedback.
