### ISSUE TITLE
RxGorm MongoDB

### ISSUE THREAD

**Issue by theiosdevguy** [grails/grails-core#11312] opened 2019-04-27 22:35 UTC
Hello Grails Team,

I believe with latest updates, RxGORM for MongoDB is being discontinued / deprecated. Is that correct? Is there any specific reason for this?

I have found the plugin very useful for handling Asynchronous tasks and doing DB operations in a separate thread. What would be the alternative that you suggest?

Thanks.

**Comment by bobbywarner** [comment] 2020-07-01 03:38
I'm not sure of the status of RxGORM for Mongo, but this issue is a duplicate of https://github.com/grails/gorm-mongodb/issues/97

Hopefully @puneetbehl can comment on the status of RxGORM for Mongo on [that issue](https://github.com/grails/gorm-mongodb/issues/97)

**Closed by bobbywarner** 2020-07-01 03:38 UTC
