### ISSUE TITLE
Grails 3.0.7 - gradle publish - POM 'org.grails:grails-bom' not found in repository

### ISSUE THREAD

**Issue by mhuebner** [grails/grails-core#9274] opened 2015-09-21 15:31 UTC
A fresh grails plugin with the "maven-publish" Gradle plugin applied ... and a simple publication 

```
/**
 * Publications
 */

publishing {
    repositories {
        maven {
            url "https://myRepo"
        }
    }
    publications {
        jar(MavenPublication) {
            from components.java
        }
    }
}
```
...produces the error (gradle publish)

```
   > Unable to initialize POM pom-default.xml: POM 'org.grails:grails-bom' not found in repository: Unable to download the artifact from any repository
     
       org.grails:grails-bom:pom:3.0.7
     
     from the specified remote repositories:
       central (http://repo1.maven.org/maven2)
     
```

even if I remove this repo (mavenCentral()) from repositories! 

All other defined repos are skipped. Even if i set 

```
    maven {
        url "https://repo.grails.org/grails/core"
    }
```
as the only repo in repositories list.

**Comment by mhuebner** [comment] 2015-09-21 15:42
Have a look at the build script: https://github.com/mhuebner/issue_9274/blob/master/build.gradle

And an example app:https://github.com/mhuebner/issue_9274

Just do a 

```
gradle publish
````

**Comment by mhuebner** [comment] 2015-09-22 07:48
Another note: it seems that the dependencyManagement gradle plugin resolves it's dependencies from maven's settings.xml not from the repositories which are defined in the build script. The only workaround I can imagine is to define https://repo.grails.org/grails/core in maven's settings.xml ;-(

**Comment by graemerocher** [comment] 2015-09-22 09:27
The issue seems to be that for the last 2 releases of Grails maven central sync has broken down:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.grails%22%20AND%20a%3A%22grails-bom%22

The newest version is 3.0.6

We will raise an issue with Sonatype to find out what is going on

**Comment by mhuebner** [comment] 2015-09-22 09:49
@graemerocher  Thank you! What do you think about the problem that I am not able to change the repository to resolve from? dependencyManagement looks into maven's settings.xml, and does not use the repositories which are defined in the gradle build script.

**Comment by graemerocher** [comment] 2015-09-22 09:50
@mhuebner That looks to be the case, but it isn't something we can fix, you will have to file an issue for that here https://github.com/spring-gradle-plugins/dependency-management-plugin

**Comment by mhuebner** [comment] 2015-09-22 10:07
Yes, I'll file an issue there... Thanks a lot!

**Comment by wilkinsona** [comment] 2015-09-22 10:40
As described in the [dependency management plugin's README](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/README.md#using-a-bom-that-is-not-in-maven-central), Gradle 2.3 requires any pom that's referenced from the pom that is being published to be available from Maven Central (or perhaps its whatever's configured in Maven's settings.xml). 2.4 no longer has this problem, presumably due to [these changes](https://docs.gradle.org/2.4/release-notes#mavendeployer-no-longer-uses-global-maven-settings.xml).

**Comment by graemerocher** [comment] 2015-09-22 10:41
@mhuebner Upgrading to Grails 3.1 M1 will solve your issue, as that uses Gradle 2.6

**Comment by mhuebner** [comment] 2015-09-22 10:48
Ok, in the referenced issue @wilkinsona posted a link to a documented gradle limitation 
> In Gradle 2.3 and earlier, pom generation requires any boms referenced in a pom's <dependencyManagement> section to be available from Maven Central.

https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/README.md#using-a-bom-that-is-not-in-maven-central

**Comment by graemerocher** [comment] 2015-09-22 12:00
This was fixed in Grails 3.1 M1 which uses Gradle 2.6

**Closed** 2015-09-22 12:00 UTC

**Comment by mhuebner** [comment] 2015-09-22 13:17
It's the same issue in Grails 3.1.0.M1 - when I switch to Gradle 2.7 (separate installation) it works.

```
   > Unable to initialize POM pom-default.xml: POM 'org.springframework.integration:spring-integration-bom' not found in repository: Unable to download the artifact from any repository
     
       org.springframework.integration:spring-integration-bom:pom:4.2.0.RC1
     
     from the specified remote repositories:
       central (http://repo1.maven.org/maven2)
     
      for project org.springframework.integration:spring-integration-bom

```

**Comment by mhuebner** [comment] 2015-09-22 14:10
Sample grails plugin: https://github.com/mhuebner/dependencyMgt_58

```
gradlew publish
```

**Comment by mhuebner** [comment] 2015-09-22 14:40
Might this be a problem?
```
distributionUrl=https\://services.gradle.org/distributions/gradle-2.3-bin.zip
```
Is this gradle-wrapper.jar an "old" one? When looking inside I cannot find any metadata but the files are from Nov. 2014

**Comment by Paradoxia** [comment] 2015-10-03 05:54
I can confirm that @mhuebner observation of upgrading to gradle 2.7 fixes this problem. I had the same problem which vanished after i updated the ```gradle-wrapper.properties``` file.
