### ISSUE TITLE
GrailsCompileStatic causes getters to fail when calling to an interface wrapping a domain class.

### ISSUE THREAD

**Issue by chriserickson** [grails/grails-core#10374] opened 2016-12-22 17:34 UTC
Given an interface:
```
interface SomeInterfaceForADomainClass {
    String name
}
```

A domain object:
```
class DomainClass implements SomeInterfaceForADomainClass {
    String name

    static constraints = {
    }
}
```

And a class set to be statically compiled, which delegates to the interface:
```
@GrailsCompileStatic
class DomainClassWrapper {
    private final SomeInterfaceForADomainClass someInterface

    public DomainClassWrapper(SomeInterfaceForADomainClass someInterface) {
        this.someInterface = someInterface
    }

    String getName() { someInterface.name }
}
```

The following test will fail:
```
class BasicCompiledStaticTest extends Specification {
     void "sanity test"() {
        when:
        def domain = new DomainClassWrapper(new DomainClass(name: "Test"))

        println ("Domain name: ${domain.name}")

        then:
        domain.getName() == "Test" // returns null
        domain.name == "Test" // returns null

    }
}
```

I did a similar test with `@CompileStatic` in groovy, and did not see the problem there.

### Environment Information

- **Operating System**: Windows 7 enterprise, SP1
- **Grails Version:** 2.5.4
- **JDK Version:** 1.8.0_112

### Example Application
I don't have git installed right now, so I'll just attach the project directly:
[testGrailsCompileStatic.zip](https://github.com/grails/grails-core/files/669399/testGrailsCompileStatic.zip)

**Comment by jeffbrown** [comment] 2016-12-22 22:14
I can't tell what you are trying to do but the test fails with both `@CompileStatic` and `@GrailsCompileStatic`.  The issue is that you have declared an interface with a property in it and not assigned it a value.  Interface properties are `final` so yours is `null`.  You have a test that is attempting to retrieve that value and asserting that it is not `null`.  If you change your interface to look like the following, the test will pass:

```
interface SomeInterfaceForADomainClass {
    String getName()
}
```

**Closed by jeffbrown** 2016-12-22 22:14 UTC

**Comment by chriserickson** [comment] 2016-12-22 22:52
Ahh, I understand. In this case I naively assumed a property in an interface would imply the getters/setters like it does in classes, although I understand that it doesn't.

In my opinion, adding @GrailsCompileStatic should not alter the behavior of the program, which in this case it does. (Without the annotation, the test passes)

So, my request would be that either it fails without the annotation, or that the compiler would spit out an error for this case. The fact that the behavior is different and it silently fails.

Updating my plain groovy case shows that the same is true for @CompileStatic, so it seems this might be a groovy, not grails issue.

**Comment by chriserickson** [comment] 2016-12-22 23:05
I reported a separate issue, mainly focused on the inconsistent behavior against Groovy:
https://issues.apache.org/jira/browse/GROOVY-8028

**Comment by jeffbrown** [comment] 2016-12-27 14:00
@chriserickson That issue doesn't look like a bug to me but of course the Groovy team can sort that out and make a decision.  Thanks for the feedback.

**Comment by jeffbrown** [comment] 2016-12-27 17:44
> In my opinion, adding @GrailsCompileStatic should not alter the behavior of the program, which in this case it does. (Without the annotation, the test passes)

I don't think that is a reasonable expectation.  Both `@GrailsCompileStatic` and `@CompileStatic` do have the potential to change behavior.  When using them you are disabling dynamic dispatch and doing so potentially changes the behavior.  The scenario you stumbled across is a good example of a case where I would expect it to change the behavior.

A simpler version of the same issue is one where you use `ExpandoMetaClass` to replace some existing method.  If you invoke that method from Groovy, normally the runtime metaprogrammed method will be invoked but if you invoke that same method from Groovy that is marked with `@CompileStatic`, the runtime metaprogrammed method will not be invoked but instead the original method will be invoked.  That is all by design and is an example where `@CompileStatic` changes the behavior of the program.

I hope that is making sense.
