### ISSUE TITLE
Grails 3 interceptors intercepts static resources(resolves 'js' and 'css' file path as controller, action) and executes before() call on it

### ISSUE THREAD

**Issue by charu-jain89** [grails/grails-core#10779] opened 2017-08-17 10:52 UTC
In grails 3.2.7 interceptor intercepts static resources.  it's currently intercepting js and css files e.g
<script src="/appName/js/apps/file.js"></script>  as   
controllerName == js, actionName == apps, params == [controller:js, action:apps, id:file.js]  
I want to prevent such interception. I want that my Interceptor should only work on hit to controller, actions. Not for static resources.

For Steps to Reproduce, Expected & Actual Behavior. Please refer https://github.com/charu-jain89/DemoInterceptorApp/blob/master/README.md

### Environment Information

- **Operating System**: CentOS 6.4, Linux
- **Grails Version:** 3.2.7
- **JDK Version:** 1.8

### Example Application

Sample App : https://github.com/charu-jain89/DemoInterceptorApp

### StackOverflow Question:
https://stackoverflow.com/questions/45710120/grails-3-interceptors-intercepts-static-resourcesresolves-js-and-css-file-p

**Comment by jeffbrown** [comment] 2017-08-17 13:07
Related to #9724

**Comment by graemerocher** [comment] 2017-08-21 07:29
This is by design for `matchAll` which matches all URIs. There is an argument to be had that we need `matchAllControllers` that matches only controllers, but that is a new feature

**Comment by ilopmar** [comment] 2018-06-20 13:02
Closing it because it's not a bug. @charu-jain89 please open an issue for the new feature `matchAllControllers` if you want.

**Closed by ilopmar** 2018-06-20 13:02 UTC
Labels: Not a Bug
