### ISSUE TITLE
"create-integration-test" command not found (3.3.8)

### ISSUE THREAD

**Issue by dlehammer** [grails/grails-core#11066] opened 2018-08-16 19:59 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

```
$ grails create-plugin any-name-will-do --profile=plugin
| Plugin created at any-name-will-do

$ cd any-name-will-do/

any-name-will-do$ ./grailsw create-integration-test MyService
| Error Command not found create-integration-test
Did you mean: create-unit-test or test or create-script?

any-name-will-do$ grails create-integration-test MyService
| Error Command not found create-integration-test
Did you mean: create-unit-test or test or create-script?
```

### Expected Behaviour

As stated in the Grails 3  [15.2 Integration Testing](https://docs.grails.org/3.3.8/guide/testing.html#integrationTesting) documentation.

> The above command will create a new integration test ...

### Actual Behaviour

An error-message is printed, and no file is created.

### Environment Information

- **Operating System**: Ubuntu 16.04 (64-bit)
- **Grails Version:** 3.3.8
- **JDK Version:** OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
- **Container Version (If Applicable):** N/A

### Example Application

- N/A

**Comment by jeffbrown** [comment] 2018-08-16 20:14
FYI... I think the command would work if the plugin were using the default plugin profile (`web-plugin`).  The command is defined in the `web` profile.

**Comment by dlehammer** [comment] 2018-08-21 20:59
@jeffbrown thank you for a work-around :)

As far as I can tell, the scope is different for the Grails profiles `plugin`, `rest-plugin` and `web-plugin`.
This is exposed by symptoms like this (#11066) and #11074, where behavior differ depending on the Grails profile.

Unfortunately the intended profile-scope isn't (currently) available in the documentation, perhaps someone in the know would address; [What's the difference between plugin and web-plugin?](https://github.com/grails-profiles/plugin/issues/5)

**Comment by puneetbehl** [comment] 2018-10-30 13:01
Duplicate of #11016

**Closed** 2018-10-30 13:02 UTC
Labels: Duplicate
