### ISSUE TITLE
UrlMappings for thrown errors not mapping, throws InvocationTargetException instead

### ISSUE THREAD

**Issue by cvharris** [grails/grails-core#9957] opened 2016-05-23 17:40 UTC
This used to work for me in Grails 2.5 but for whatever reason any `throw`n errors in Grails 3 are skipping any mapping in UrlMappings and going to some other setting. There are plenty of examples out on StackOverflow, the docs, and elsewhere that I'm following to develop this pattern but it still is broken for me. 

What seems to be the issue is that the root cause of the stack trace is an InvocationTargetException thrown after my custom `RestException` has been thrown, interrupting the mapping. What's wrong?

### Steps to Reproduce

With a given `UrlMappings`:
```java
class UrlMappings {

    static mappings = {
        "/orders/$id"(controller: 'order', action: 'getOrder')

        "500"(controller:'error', action:'index')
        "404"(controller:'error', action:'index')
    }
}
```
and a custom `ErrorController`:
```java
class ErrorController {
    static responseFormats = ['json']

    def index() {
        Exception cause = request?.exception?.cause
        def content = [:]

        if(cause instanceof RestException) {
            RestException restException = (RestException)cause;
            content = [
                    status: restException.status.code,
                    message: restException.message,
                    source: restException.source,
                    errors: restException.errors
            ];
        } else {
            content = [
                    status: 500,
                    message: (cause && cause.message) ? cause.message : 'unknown cause',
                    source: Holders.config.grails.project.groupId,
                    errors: [:]
            ];
        }
        log.error("Exception raised. Response=${content}")

        response.status = content.status

        respond content
    }
}
```
This is what it looks like in my `OrderController`:
```java
class OrderController {

    def getOrder(Long id) {
        def result = orderService.getOrder(id)

        if (!result) {
            throw new RestException("No Order found by id=${id}", RestException.RestStatus.NOT_FOUND)
        } else {
            respond result
        }
    }
}
```

### Expected Behaviour

I'm trying to `throw` a custom `RestException` in my controller and have the `500` mapping pick it up to send it to the `ErrorController`. In debug mode I expect the `index()` to be called when I hit the `localhost:8080/order-api/orders/1234` endpoint, forcing a `404` error.

### Actual Behaviour

Instead of being routed to the `ErrorController` the `/error` view is used to output an error page. Here's the stacktrace:
```
DEBUG org.grails.web.errors.GrailsExceptionResolver - Resolving exception from handler [org.grails.web.mapping.mvc.GrailsControllerUrlMappingInfo@3244285e]: java.lang.reflect.InvocationTargetException
DEBUG org.grails.web.errors.GrailsExceptionResolver - Resolving to view '/error' for exception of type [java.lang.reflect.InvocationTargetException], based on exception mapping [java.lang.Exception]
DEBUG org.grails.web.errors.GrailsExceptionResolver - Exposing Exception as model attribute 'exception'
ERROR org.grails.web.errors.GrailsExceptionResolver - RestException occurred when processing request: [GET] /order-api/api/orders/1234
No Order found by id=1234. Stacktrace follows:
java.lang.reflect.InvocationTargetException: null
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.wwt.orderapi.errors.RestException: No Order found by id=1234
	at com.wwt.orderapi.OrderController.throwRestException(OrderController.groovy:59)
	at com.wwt.orderapi.OrderController.getOrder(OrderController.groovy:32)
	... 3 common frames omitted
DEBUG org.grails.web.errors.GrailsExceptionResolver - Matched URI [/order-api/api/orders/1234] to URL mapping [org.grails.web.mapping.mvc.GrailsControllerUrlMappingInfo@528b9d80], forwarding to [/error/index] with response [class org.apache.catalina.connector.ResponseFacade]
```

### Environment Information

- **Operating System**: Mac OSX El Capitain
- **Grails Version:** 3.1.4
- **JDK Version:** 1.8

**Comment by graemerocher** [comment] 2016-05-24 06:38
Please upload an example that reproduces the problem.

**Comment by marcDeSantis** [comment] 2016-05-24 18:15
@cvharris I have narrowed the source of this problem down to an internally used plugin. We should be able to close this issue.

**Closed** 2016-05-24 20:06 UTC
Labels: Awaiting Feedback

**Comment by ClemensSchneider** [comment] 2018-08-16 23:09
What was the cause of this issue? I'm currently facing the same problem as described by @cvharris but using Grails 3.2.10.
The exception that is provided to my error.gson is a `InvocationTargetException` thrown at

```
java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ClemensSchneider** [comment] 2018-08-16 23:55
In `org.grails.core.DefaultGrailsControllerClass` there is a distinction between development-mode and other environments that sets a reflection-based handler to invoke controller actions. In this case, an `InvocationTargetException` is getting thrown.

```
if(Environment.isDevelopmentMode()) {
    methodNames.put(methodName, new ReflectionInvoker(method));
}
```

Shouldn't the `org.grails.web.errors.GrailsExceptionResolver` also check for `InvocationTargetException` when getting the root-cause of an exception?

```
if ((e instanceof InvokerInvocationException)||(e instanceof GrailsMVCException)) {
            Throwable t = getRootCause(e);
            if (t instanceof Exception) {
                e = (Exception) t;
            }
        }
```
