### ISSUE TITLE
Grails 4.0.0.RC1 - Auto complete no longer works in shell

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11306] opened 2019-04-20 17:36 UTC
```
grails create-app shell
cd shell
grails
create-domain-class Car
create-scaffold-controller # hit the tab key and no suggestions are provided
```
This works fine in Grails 3.3.9

**Comment by rvanderwerf** [comment] 2019-04-22 16:26
I'm seeing the same behavior.

**Comment by rvanderwerf** [comment] 2019-04-22 22:59
Now it's working for me after debugging it. Are you running ./grailsw or grails 4.0.1 RC1 via sdkman?

**Comment by codeconsole** [comment] 2019-04-23 03:51
There is no 4.0.1 RC1 via sdkman
I am using 4.0.0.RC1 via sdkman

**Comment by rvanderwerf** [comment] 2019-04-23 13:31
apologies meant 4.0.0.RC1.

**Comment by rvanderwerf** [comment] 2019-04-23 13:48
ok.. can you try using ./grailsw to start the console and see if you have the same issue. I am seeing it work in this case, but if I have sdkman set to 4.0.0.RC1 and just run grails in the 'shell' example directory, it is not working like you say for me too.

**Comment by rvanderwerf** [comment] 2019-04-23 23:08
I found the cause.. jline 2.12.1 is the last version where autocomplete works properly. I'll work on a pr.

**Comment by codeconsole** [comment] 2019-04-24 02:09
Awesome, good work!

**Comment by codeconsole** [comment] 2019-04-24 02:27
Easier to upgrade to jline3?

**Comment by rvanderwerf** [comment] 2019-04-24 04:55
So jline 3.x isn't directly compatible so that's not a great option without rewriting lots of code. Jeff Scott Brown found a linkage of Apache Groovy console has dependencies on Jline 2.14 so I will need to determine if a downgrade breaks anything with Groovy. I will do more testing tomorrow to verify downgrade doesn't cause ill effects or if I can fix the completers to work better with the version Groovy is using.

**Comment by rvanderwerf** [comment] 2019-04-29 04:27
I updated my pr with the solution for this - a change in behavior in later jline versions required a change in one of the competers. Just waiting to get for https://github.com/grails/grails-core/pull/11309 to be  approved and merged.

**Closed** 2019-05-16 12:52 UTC
