### ISSUE TITLE
Grails controller losing request parameter - sometimes

### ISSUE THREAD

**Issue by ydd0072** [grails/grails-core#9968] opened 2016-05-27 17:02 UTC
Grails 3.1.0
JDK 1.8u72
Linux

We have forgot password flow in our application where email is sent out to user and user clicks on that link. When user clicks on that link, a grails controller method takes the request parameter and decode that and resets the password.
This whole forgot password flow work very well but doesn't work some times.

When I investigated, I found out that grails controller is loosing request parameter on some random request (and this is happening in PROD env only where we have high load)

Code is below
def change(PasswordResetCommand cmd) {

```
    if (cmd.hasErrors()) {
        processCommandErrors(cmd, new ViewModel(ServiceResponseStatus.fail))
        log.error(" User supplied token is null : " + cmd.token) // This is logged even when we see that token is available in request quary string
        return
    }
```

Here is the example link : xxxxxx/change?token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

This seems like a grails bug and needs to be fixed.

**Comment by ctoestreich** [comment] 2016-05-27 17:14
I can confirm this issue is happening, attempting to recreate project now.  Also nginx logs show the param in the request but by the time grails gets the request the params.token is showing up as null.

**Comment by ctoestreich** [comment] 2016-05-27 22:19
@colinharrington we suspect this is possibly another threading issue but are having trouble recreating in non prod with a sinple war and jmeter.  It might have to do with out whole stack and the complex stack.  We see about a 2% error rate where the param is lost against prod using jmeter, but the same load against local simple was has 0% errors.  Our logs in sumo also show about a 1-2% occurance of the null param.

**Comment by ctoestreich** [comment] 2016-05-27 22:22
We are looking at any hashmap objects in the request pipeline.  We are looking at this file for potential issues.  https://github.com/grails/grails-core/blob/639d7039d24031dbc1353f95b6d2c88a100da850/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/DefaultUrlCreator.java

**Comment by ctoestreich** [comment] 2016-05-28 21:01
I am going to take our test app and add some forwards to happen during the load test to see if somehow the action of forwarding while getting params is the thread safety problem.  https://github.com/grails/grails-core/blob/639d7039d24031dbc1353f95b6d2c88a100da850/grails-web-url-mappings/src/main/groovy/org/grails/web/mapping/UrlMappingUtils.java

**Comment by ydd0072** [comment] 2016-05-31 21:23
<img width="1566" alt="screen shot 2016-05-31 at 4 18 17 pm" src="https://cloud.githubusercontent.com/assets/10049531/15690977/d4936e2e-274b-11e6-975a-63e022962d9a.png">

We put in good logging around our application password recovery flow and its clear that grails controller looses parameter on some random request.
Please see the attached log snippet where in parameter is lost on sub-sequent request.

Thanks

**Comment by ctoestreich** [comment] 2016-07-06 18:25
We are seeing this on many controllers now at about a 1.8% occurance rate, but only in prod under prod type load.

**Comment by jeffbrown** [comment] 2016-07-06 18:30
> We are seeing this on many controllers now at about a 1.8% occurance rate, but only in prod under prod type load.

Are you saying that in prod under prod type load that about 1.8% of all request parameters appear to be being dropped somewhere before your controller code is executed?

**Comment by liorhson** [comment] 2016-07-07 07:27
Hey @ydd0072,

Regarding your decode issue, follow this thread: #10025

**Comment by ctoestreich** [comment] 2016-07-07 12:15
@jeffbrown That sounds correct.  We can NOT reproduce in lower environment using jmeter.  I do believe that we can get this to happen doing a SOASTA load against production which generates a substantially higher multi user load across many pages of the site.  We also see this during normal user traffic in production.

It was isolated to the link above, however as we broaden our scope of load testing and new features we have started to see it on more controllers that use url params.  Our typical pages doesn't use many, if any, querystring params, so this hasn't showed up in many places.  This MAY have to do with #10025, however the behavior is slightly different where the params are simply seen as NULL once the controller code is executed. 

We thought it was interceptor related at first but the small fraction of users that get the params nulled out execute the same interceptors in the same order as those who don't.  

We are still investigating.

**Comment by ctoestreich** [comment] 2016-07-11 16:03
@jeffbrown The latest update is that we are trying 2 different variations of the code to determine where the problem is. 


### Use Spring controller but still construct and use a GrailsParameterMap object ###

We have migrated the controller to a spring controller like the following

``` groovy
@Slf4j
@CompileStatic
@Controller
class SpringSearchController {

    @Autowired
    SearchViewModelService searchViewModelService
    @Autowired
    UserSessionService userSessionService

    @RequestMapping(["/springSearch", "/springSearch/**"])
    ModelAndView index(
            @RequestParam Map<String, String> allRequestParams, HttpServletRequest request, HttpServletResponse response) {
        GrailsParameterMap localParams = new GrailsParameterMap(allRequestParams, request)

        if (!localParams.categoryId && !localParams.q) {
            log.error("Search failed due to missing parameters, url=\"${request.requestURL}\", queryString=\"${request.queryString}\"")
            response.setStatus(HttpStatus.SC_BAD_REQUEST)
            return new ModelAndView(HttpStatusViewMappingType.SC_BAD_REQUEST.view, 'model', new ViewModel(ServiceResponseStatus.fail, new Message(MessageType.ERROR, 'Category ID or keyword must be provided')))
        }

        ....//do work
}
```

Using this approach we are still seeing params lost sometimes.  This leads us to the thread safety of GrailsParameterMap.  So we are trying the following to see if it clears up the issue.

### Use spring controller with MultiValueMap ###

We are currently deploying a version of the code above **without** the conversion to the GrailsParameterMap and simply using the raw map passed into the controller from spring.  This required some more changes to use a raw map down the call stack and we will be going to production later today after we pass functional tests to perform the same load tests on the server while it is under real customer load to see if we see the same issues with lost parameters.

**Comment by graemerocher** [comment] 2016-10-28 10:16
@alvarosanchez Any luck?

**Comment by skray** [comment] 2017-01-12 21:04
I have not found a way to consistently reproduce this, but we are seeing this as well, using Grails 3.2.3.

**Comment by beapiio** [comment] 2017-01-12 23:02
I know how to fix it... and this isn't spam. It really does work when you abstract the communication logic from the business logic. This error is gone. I saw this a long time ago and was able to work through it.

**Comment by bessb** [comment] 2017-01-18 16:10
I have been able to reproduce this for a specific situation, but I am unsure of whether it's considered programmer error or not. Here's a repo with a test project, the README explains how to reproduce the issue: https://github.com/bessb/grails-request-param-issue

In our case, we're doing some work in a `task`, which had an `onError` block that would log the Exception. We're not waiting for the task to finish before returning from the controller method. This triggers a separate exception, stack trace below:
```
java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:210)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
What this ends up doing is clearing out the request parameters for other controllers. This is demonstrated in the test code.

It seems like the fix in our case is to ensure all asynchronous code is finished (via `waitAll`) before returning from the controller method. This isn't ideal, since we've got some long-running tasks that we'd like to run in the background.

Let me know if you have any questions.

**Comment by kevana** [comment] 2017-01-19 04:51
@bessb Neither @ctoestreich or I are still at the company where this was happening so we can't check the logs for stacktraces like that. But thinking back, we did start noticing this around the same time that we started to use async tasks heavily in other parts of the codebase.

**Comment by graemerocher** [comment] 2017-01-19 07:02
looking at the code I can see how that would happen if the async request were to time out. In that sense the RxJava plugin may be better solution for this tasks.

**Comment by ctoestreich** [comment] 2017-01-20 20:18
In our case we had lots of tasks running all the time for rendering inventory, details, pricing, etc. The issue was showing up in a controller that didn't use tasks. However if these tasks would timeout, which they did frequently, and that happened to clear request Params then what we would see would hold with the above observation.

**Comment by graemerocher** [comment] 2017-04-12 13:48
Closing as not reproducible and @alvarosanchez case was a Jetty container bug

**Closed by graemerocher** 2017-04-12 13:48 UTC
Labels: Awaiting Feedback, Cannot Reproduce

**Comment by snimavat** [comment] 2024-04-30 16:21
@bessb We are facing this issue too with grails 5.x. We too run some code in backgroud (but not using grails tasks) which keeps running while request returns. But we dont use grails async tasks for it.

Unable to reproduce consistently, but it happens randomly on prod

Can any one point me to the code, which could be resetting the params, in the case of a background task failing.

**Comment by qwood-mil** [comment] 2024-09-10 17:31
@snimavat Have you had any luck getting this resolved? We are experiencing a similar issue with grails 6.x.

We are unable to reproduce in our testing environments and it only seems to happen when we have a heavy load on prod.
