### ISSUE TITLE
grails create-command missing

### ISSUE THREAD

**Issue by rvanderwerf** [grails/grails-core#9540] opened 2016-01-07 18:48 UTC
According to the docs http://grails.github.io/grails-doc/3.0.x/ref/Command%20Line/create-command.html
This should be there. In grails 3.0.11 the command is not recognized.

**Comment by graemerocher** [comment] 2016-01-08 09:13
It is only available for plugins at the moment

**Comment by salex772** [comment] 2016-01-10 22:44
So maybe we need to update docs?

**Comment by rvanderwerf** [comment] 2016-01-11 03:00
yes if that's the case and there is no plan to make it work in apps. It
seems a bit tricky because of the buildscript part to make it work in an
app I would assume be difficult. It doesn't sound like the command then are
a real replacements for the Scripts stuff?

**Comment by salex772** [comment] 2016-01-11 10:30
For us newbies it's always a temptation to run a code inside a running app to perform some tasks (like console plugin do), especially considering that quartz plugin does not work at all (for me). Without that I feel some inconvenience.

**Comment by graemerocher** [comment] 2016-01-13 09:32
The issue is as @rvanderwerf stated that there is no way to put app sources in the build script classpath so commands cannot be added to Gradle. You can however manually create a Gradle task that executes a command. For example:

    task myCommand(type: ApplicationContextCommandTask) {
        classpath = project.sourceSets.main.runtimeClasspath + project.configurations.console
        command = 'my-command'
    }

This will create the necessary gradle task to invoke a command like:

       gradle myCommand

You then need to add a command in `src/main/groovy` that implements `ApplicationCommand`:


    class MyCommand implements ApplicationCommand {

        final String description = "My new command"

        @Override
        boolean handle(ExecutionContext executionContext) {
            // your logic
        }
    }

**Comment by salex772** [comment] 2016-01-13 17:07
@graemerocher Thank you very much for your advise. But unfortunately I do not understand why it's not possible to add these lines like "task myCommand..." to build.gradle as a result of running "create-command" script and create a file in `src/main/groovy`.

**Comment by sergiodelamoshoptimix** [comment] 2016-02-29 17:14
@graemerocher thanks for the gradle workaround.

 I am trying to inject a service as shown below in my command object defined with a gradle task as you suggested. 

```
import org.springframework.beans.factory.annotation.Autowired

import grails.dev.commands.*
import org.springframework.beans.factory.annotation.Autowired

class MyCommand implements ApplicationCommand {
@Autowired
def myService
```

However, the injections it is not working. Do I have to configure it something else to get this working?

**Comment by sergiodelamoshoptimix** [comment] 2016-02-29 17:24
My bad. Found my mistake I had to replace

@Autowired
def myService

with: 

@Autowired
MyService myService

Defining the class explicitly solved the issue. Again thanks for the tip about how to make make possible to run commands in no plugin projects.

**Comment by sergiodelamoshoptimix** [comment] 2016-03-01 14:31
How can I pass arguments to the gradle task and access them inside the command class. For example:

`String[] args = ctx.commandLine.getRawArguments()`

I've tried with `gradle myCommand -Dfoo`

**Comment by graemerocher** [comment] 2016-03-01 14:33
you would have to pass them in via your `build.gradle`:

```
task myCommand(type: ApplicationContextCommandTask) {
    classpath = project.sourceSets.main.runtimeClasspath + project.configurations.console
    command = 'my-command'
    args "foo", "bar" 
}
```

**Comment by sergiodelamoshoptimix** [comment] 2016-03-01 14:50
thanks. You put me on the right track. This works: 

```
task myCommand(type: ApplicationContextCommandTask) {
    classpath = project.sourceSets.main.runtimeClasspath + project.configurations.console
    command = 'my-command'
    args "$fileName" 
}

gradle myCommand -PfileName="/Users/groovycalamari/Downloads/test.text"
```

**Comment by jameskleeh** [comment] 2016-09-17 16:32
Closing this issue in favor of the more descriptive issue here https://github.com/grails/grails-core/issues/10032

**Closed by jameskleeh** 2016-09-17 16:32 UTC
Labels: in progress, New Feature
