### ISSUE TITLE
Grails4 Could not find matching constructor for InterceptedUrl

### ISSUE THREAD

**Issue by kszymko** [grails/grails-core#11384] opened 2019-08-09 16:02 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. generate the simple app:
```
    grails create-app helloworld4
```
2. in build.gradle add dependencies:
```
dependencies {
    ...
    compile 'org.grails.plugins:spring-security-core:4.0.0.RC2'
    compile 'org.springframework.security:spring-security-core:5.1.5.RELEASE'
}
```
3. in application.yml add:

```
grails:
    plugin:
        springsecurity:
            # Whether the plugin is enabled
            active: true
            interceptUrlMap:
                - { pattern: '/assets/**',               access: ['permitAll'] }
                - { pattern: '/css/**',                  access: ['permitAll'] }
                - { pattern: '/images/**',               access: ['permitAll'] }
            securityConfigType: 'InterceptUrlMap'
```
4. gradle clean bootRun

### Expected Behaviour

Application should start without any problems.

### Actual Behaviour

Exception is thrown:

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: grails.plugin.springsecurity.InterceptedUrl(String, ArrayList, org.grails.config.NavigableMap$NullSafeNavigator)

### Environment Information

- **Operating System**:  Win 10
- **Grails Version:** 4.0.0
- **JDK Version:** 1.8.0_221
- **Container Version (If Applicable):** N/A

### Example Application

- N/A

**Comment by zoladkow** [comment] 2019-08-13 09:32
Putting those mappings in YAML is out of the picture now, you should move to application.groovy file as described in [plugin documentation](https://grails-plugins.github.io/grails-spring-security-core/latest/#requestMappings)

**Comment by kszymko** [comment] 2019-08-13 09:51
According to [plugin documentation](https://grails-plugins.github.io/grails-spring-security-core/latest/):

> The Spring Security plugin maintains its configuration in grails-app/conf/application.groovy, **although you can keep the plugin config in application.yml** with the rest of the configuration if you prefer. Default values are in the plugin’s grails-app/conf/DefaultSecurityConfig.groovy file, and you add application-specific values to application.groovy (or application.yml). The default configuration is merged with your settings, with application values overriding the defaults and setting missing values.

I could NOT find anything saying that some Grails3 behaviour was dropped that's why I consider it a bug. Would be nice if you can point me to the doc where you have seen such an info. Thanks.

And by the way I know it works when put into application.groovy, but this should be put into migration info if it is really necessary.

**Comment by zyro23** [comment] 2019-08-13 10:00
related: https://github.com/grails-plugins/grails-spring-security-core/issues/573

**Comment by zoladkow** [comment] 2019-08-13 10:29
there https://grails-plugins.github.io/grails-spring-security-core/latest/#newInV3

> There are a few breaking configuration changes as of version 3.0.0.M2. Prior to that version, some configuration properties were specified as a Map where the keys and values were both data. This caused various problems, primarily due to period characters in map keys. There are now no configuration properties that are single maps; all have been converted to lists of single-entry maps. This includes controllerAnnotations.staticRules and interceptUrlMap (see Configuring Request Mappings to Secure URLs), ipRestrictions (see IP Address Restrictions), filterChain.chainMap (see Filters), secureChannel.definition (see Channel Security), and failureHandler.exceptionMappings.

**Comment by kszymko** [comment] 2019-08-13 11:16
With `compile 'org.grails.plugins:spring-security-core:3.2.3'` the above configuration in **application.yml** works just fine in Grails3 app. So, documentation is misleading here. 

Anyway this is NOT a single map it is list of maps which should work fine according to this:

> There are now no configuration properties that are single maps; all have been converted to lists of single-entry maps.

**Comment by zoladkow** [comment] 2019-08-13 12:33
Ok. I see your point. Also checked the actual source for InterceptedUrl, which does not seem to have changed at all. Anyway, wherever the magic matching the `pattern:` and `access:` to those constructor parameters was, it's clearly broken now...

**Comment by jameskleeh** [comment] 2019-08-13 13:39
Duplicate of https://github.com/grails-plugins/grails-spring-security-core/issues/573

**Closed by jameskleeh** 2019-08-13 13:39 UTC

**Comment by rkimaoui** [comment] 2019-10-15 16:14
I have the same problem when using application.yml
