### ISSUE TITLE
Static Scaffolding Not Respecting Custom Templates

### ISSUE THREAD

**Issue by MauiMana** [grails/grails-core#10094] opened 2016-08-10 01:44 UTC
I submitted this issue over on the 'scaffolding' plugin but I'm not exactly sure if 'static' scaffolding is being handled by the plugin, or grails itself. But in any case, the issue is with the static scaffolding facility apparently not respecting customized templates (please see 'steps to reproduce' section)

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails install-templates
2. modify one of the installed templates (e.g., src/main/templates/scaffolding/index.gsp)
3. grails generate-views <domain class>
4. inspect generated gap files (e.g., views/.../index.gsp

### Expected Behavior
generated index.gsp file should be in terms of the modified template

### Actual Behaviour
generated index.gsp file was solely based on grails-internal template, not the modified one

### Environment Information

- **Operating System**: OS X (latest)
- **Grails Version:** 3.1.10
- **JDK Version:** 1.8

**Comment by jeffbrown** [comment] 2016-08-10 02:40
> I submitted this issue over on the 'scaffolding' plugin but I'm not exactly sure if 'static' scaffolding is being handled by the plugin, or grails itself.

It is handled by the plugin.

I think this is a duplicate of https://github.com/grails3-plugins/scaffolding/issues/22.

**Closed by jeffbrown** 2016-08-10 02:40 UTC
