### ISSUE TITLE
Dependency management plugin breaks at importing multiple mavenBom in Grails 3.0.3

### ISSUE THREAD

**Issue by gilinykh** [grails/grails-core#9142] opened 2015-07-28 16:31 UTC
Create new app. Add one more mavenBom import to dependency management import closure:
```
dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
        mavenBom "org.springframework.cloud:spring-cloud-aws:1.0.2.RELEASE"
    }
    applyMavenExclusions false
}
```
Run the app. Build fails:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> org.codehaus.groovy.runtime.DefaultGroovyMethods.leftShift(Ljava/util/List;Ljava/lang/Object;)Ljava/util/List;
```

**Comment by jfrosch** [comment] 2015-08-21 22:58
I encouintered the same error when adding mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Angel.SR3" to dependencyManagement.imports:

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Angel.SR3"
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

However, though I fully don't understand why, I discovered that if I swap the two entries, the build succeeds:

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Angel.SR3"
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

When I build a distribution, I see that I'm getting the correct versions of the Grails default dependencies  (3.0.4) and the correct versions of the spring-cloud dependencies; i.e. the Netflix components all came in as the correct 1.0.3 version.

I hope this might help resolving the issue more permanently.

**Comment by graemerocher** [comment] 2015-09-02 10:42
The issue is that `mavenBom "org.springframework.cloud:spring-cloud-aws:1.0.2.RELEASE"` causes an earlier version of Groovy to be downloaded (2.3.11) because it is part of that BOM. The correct fix is to always have the `grails-bom` as the last BOM as described in the previous comment.

**Closed by graemerocher** 2015-09-02 10:42 UTC
Labels: Not a Bug, Won't Fix
