### ISSUE TITLE
Service is not injected in controller while testing controller

### ISSUE THREAD

**Issue by agustincba** [grails/grails-core#9909] opened 2016-05-02 07:49 UTC
Hi !. I am having this issue with my grails project. While testing one of my controller, the associated service is not injected and this is why I get the following stacktrace:

`|Running 13 unit tests... 5 of 13
|Running 13 unit tests... 6 of 13
Failure:  |
testIndex(us.jbilling.grailstestprizypricer.controller.AdministratorControllerSpec)
 |
java.lang.NullPointerException: Cannot invoke method obtainAllProducts() on null object
        at us.jbilling.grailstestprizypricer.controller.AdministratorController.index(AdministratorController.groovy:23)
        at us.jbilling.grailstestprizypricer.controller.AdministratorControllerSpec.testIndex(AdministratorControllerSpec.groovy:17)
|Running 13 unit tests... 7 of 13`

I am using Grails 2.4.3 and Java 1.7 u79 (with NB 6.9).

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce
1) Create controller on the controller folder.
2) Create a service on the service folder.
3) Create a domain class.
4) Create a method on the db service to query the created domain class
5) Go to the unit testing folder and create a test method to check the controller method where the service is used.
6) When the unit testing reaches my controller test, it throws in the console log the stack trace I put above.

1] Controller:
![grails_1](https://cloud.githubusercontent.com/assets/654436/14949382/de976396-101f-11e6-9971-55dadfe733d8.jpg)

2] Service:
![grails_2](https://cloud.githubusercontent.com/assets/654436/14949402/0c1ced22-1020-11e6-82ed-04949c303607.jpg)
![grails_3](https://cloud.githubusercontent.com/assets/654436/14949403/0c23e898-1020-11e6-91d8-a63863dbf655.jpg)

The controll'er's test method is the "index" method.

### Expected Behaviour

I expect that the service is injected into the controller when the controller is tested. What happened is that, before handing this simple project (is for a company to decide is I am in or out and that's why it's cimportant), the service wasn't null so I don't know what I have done.

### Actual Behaviour

I have built several tests but when the testing process reaches one where the queryservice is used, it throws a NullPointer exception.

### Environment Information

- **Operating System**: Windows 8
- **Grails Version:** v2.4.3
- **JDK Version:** 1.7 up79
- **Container Version (If Applicable):** tomcat:7.0.55

### Example Application

[PrizyPricer.zip](https://github.com/grails/grails-core/files/244666/PrizyPricer.zip)

I'll be around if more info is needed !. Thankx

**Comment by agustincba** [comment] 2016-05-02 07:51
Pics from the tested controller:

![cholordo_0372](https://cloud.githubusercontent.com/assets/654436/14949569/6e44aeee-1021-11e6-8180-7348c79a1892.jpg)

**Comment by jeffbrown** [comment] 2016-05-02 14:28
There are a number of options you have.  If you want to use the real service, you can just register an instance as a bean in the context by doing the following in your unit test:

    static doWithSpring = {
        queryService us.jbilling.somepackage.QueryService
    }

You could also make the `queryService` bean be an instance of some test class, or you could create a Stub or a Mock. 

This is not a bug report or a feature request so I am going to go ahead and close this issue.  If you would like to ask questions about how to use Grails, please post the mailing list at  https://groups.google.com/forum/#!forum/grails-dev-discuss, join our Slack channel at http://grails.slack.com or post a question to StackOverflow at http://stackoverflow.com/questions/tagged/grails.

**Closed by jeffbrown** 2016-05-02 14:28 UTC

**Comment by ptitcoutu** [comment] 2017-01-06 10:50
The issue here is that you have to precise with @Build([Product]) that Product has to be mocked in order to the service to be mocked and injected correctly by grails
