### ISSUE TITLE
Grails ver.3.1.7, @EnableScheduling / @Scheduled does not work.

### ISSUE THREAD

**Issue by nobusugi246** [grails/grails-core#9949] opened 2016-05-20 14:39 UTC
- [X] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. add @EnableScheduling to init/Application.groovy class.
2. add @Scheduled(fixedRate=1000L) to any method.
3. grails run

### Expected Behaviour

The method with @Scheduled should be called every 1s.

### Actual Behaviour

The method never called.

With Grails ver.3.1.6, this works fine.

**Comment by graemerocher** [comment] 2016-05-20 14:40
Please provide an example that reproduces the problem

**Comment by nobusugi246** [comment] 2016-05-20 14:47
Please see below.

https://github.com/nobusugi246/groovy-knowledge-integrator/blob/master/grails-app/init/gki/Application.groovy

https://github.com/nobusugi246/groovy-knowledge-integrator/blob/master/grails-app/services/gki/chat/ChatService.groovy

**Comment by graemerocher** [comment] 2016-05-26 11:53
Services were previously erroneously eagerly loaded, this was fixed in 3.1.7 and this is why the `@Scheduled` is not working because the service is never loaded. To fix this problem add following to your service:

     static lazyInit = false

**Closed by graemerocher** 2016-05-26 11:53 UTC
Labels: Blocker, in progress, Won't Fix

**Comment by nobusugi246** [comment] 2016-05-26 16:12
Thanks for investigation. The problem fixed.
