### ISSUE TITLE
Grails 3.3.9 BigDecimal being cast to Integer

### ISSUE THREAD

**Issue by lRaulMN7** [grails/grails-core#11499] opened 2020-03-02 07:43 UTC
When using [Command Objects](https://docs.grails.org/3.3.9/guide/single.html#commandObjects), BigDecimal values are cast to Integers, no matter what decimal notation I use. 

You can test it by clone this [test project](https://github.com/lRaulMN7/BigDecimalIssue)

The controller rendered shows 2 inputs, a "text" one and a "number" one. When I type either 10,20 or 10.20, the log.info ubicated at the index controller displays 1020. 

I'd like to keep my CommandObject instead of using params to get that number. Because I have been using params.price and I never got an error with BigDecimal, but few days ago I started using CommandObjects because they are good for validation and I'm not able to retrieve decimal numbers.

Operating System: Ubuntu 19.04
Grails Version: 3.3.9
JDK Version: 1.8 java

**Comment by lRaulMN7** [comment] 2020-03-10 12:07
?

**Comment by davydotcom** [comment] 2020-06-29 15:00
Tested in English Locale decimal 3.14 worked perfectly..

https://bertram.d.pr/yHw7dg

Unable to reproduce based on test information.

**Comment by bobbywarner** [comment] 2020-06-30 13:03
I can reproduce this issue when using a Spanish locale.

**Comment by davydotcom** [comment] 2020-06-30 14:18
Upon further review the sample code is incorrect. It is using an input of type="number". Number input types automatically convert localized numbers to standard javascript number formats with the . Since your locale is wanting to use a `,` as its delimiter this will not work. The client browser is converting 3,14159 to 3.14159 in the request to the server (inspect the server request to see this). The Locale Aware TypeConverter is trying to parse in the locale format but the browser is not sending it properly. This number field type is more ideal for non decimal based numbers or for client side localization. Recommend using a text field instead with a pattern validator:

Example Information:
https://stackoverflow.com/questions/13412204/localization-of-input-type-number

**Comment by bobbywarner** [comment] 2020-06-30 14:32
Good catch @davydotcom !

Correct, this is not an issue with Grails, but rather a known issue with `input type="number"`.  Closing as there is nothing to fix in Grails for this.

**Closed by bobbywarner** 2020-06-30 14:32 UTC

**Comment by lRaulMN7** [comment] 2020-06-30 15:08
Thanks @davydotcom , I didn't think about that one!
