### ISSUE TITLE
why grails console always hang at :bootRun

### ISSUE THREAD

**Issue by wayshall** [grails/grails-core#641] opened 2015-04-13 15:54 UTC
I'am a novice. 
the grails console hang at bootRun when I try to run app, as shown below
![grails](https://cloud.githubusercontent.com/assets/965315/7119430/1e9d665a-e238-11e4-84f6-ab7ec90e4cc5.png)

grails version: 3.0.1
os: osx
jdk: 1.8
groovy: 2.4.3

**Comment by littleiffel** [comment] 2015-04-13 17:30
@wayshell I think this means the app is running and as log says try access the url http://localhost:8080 in your browser

**Comment by wayshall** [comment] 2015-04-14 02:56
@littleiffel yes, I know that. 
in fact, the grails app run normal, and I can access it by url http://localhost:8080
but the :bootRun tips always show and not going to disappear.
and I can't input any grails command againt, like stop-app.
Is it a issue?

**Comment by olavgg** [comment] 2015-04-14 11:57
Same thing here, on Linux/OSX. Wondering if this is an issue or not.

**Comment by ikakara** [comment] 2015-04-18 08:19
Same on Windows 8.1 (jdk 1.8.0_45)

**Comment by fotisp** [comment] 2015-04-22 15:22
I am also having this issue but do not understand the solution linked on #652

**Comment by faraz-ali** [comment] 2015-04-23 05:36
Same issue here. Even happens when you do a grails > gradle run. It gets stuck on Building 83% > :run

**Comment by rainerfrey** [comment] 2015-04-23 06:40
What I experience: nothing "hangs" or "gets stuck". But run-app from an interactive grails shell runs in the foreground, and therefore blocks the console. So it is not possible to run further commands, like generators, while the app ist running. IIRC this was different in grails 2.x. Maybe this issue could be interpreted as an improvement request to run in background.

Would running a second interactive shell for the same app work, or would they interfere in bad ways (like triggering recompiles that the other shell would not be able to deal with)? If that works, I'd consider that solved.

Another minor glitch is the strange percent progress number, that seems to cause confusion. The app is fully running, but the output says s.th. like 83% build progress. Minor, as it doesn't seem to have any impact. I assume this is in gradle or the gradle spring-boot plugin,  I've seen the same with a plain spring-boot application,

**Comment by davidvz** [comment] 2015-04-26 20:09
Hello, as rainerfrey says this is an issue with the Spring Boot Gradle plugin, and not Grails. A vanilla Spring Boot app with Gradle does the exact same thing. App runs fine, the output just appears to "hang" with the bootRun line.

(snip)
Application in 6.537 seconds (JVM running for 7.198)
Initialisation complete
> Building 80% > :bootRun

I'm not sure how feasible it is to keep an interactive grails console going while the app is running in this way...

**Comment by ava305** [comment] 2015-04-27 15:04
same issue on windows 7 ultimate

**Comment by becksnow** [comment] 2015-04-28 04:17
same issue on xubuntu 15.04

**Comment by ava305** [comment] 2015-04-28 06:20
A i have not find any stop-app command.

**Comment by rodrigosalinas** [comment] 2015-05-04 17:22
Same issue. OSX, Grails 3.0.1, JVM 1.8. Docs say I should run stop-app to restart the container. But I can't run anything while the prompt get stuck on 
> Building 83% > :bootRun

**Comment by legilioli** [comment] 2015-05-24 20:50
Same issue when running 'run-app' and 'shell' command, prompt gets stuck. Ubuntu 14.04, Grails 3.01, JVM 1.8.0_45

**Comment by Santeee** [comment] 2015-06-10 07:17
The same on:
Java 1.7.79
Groovy 2.4.3
Grails 3.0.1

**Comment by ecemis** [comment] 2015-06-11 05:16
Same issue, and I can't run 'grails shell', it gets stuck with "Building 83% > :shell".  (Mac OS 10.10.3, Grails Version: 3.0.1, Groovy Version: 2.4.3, JVM Version: 1.8.0_45)

**Comment by csbubbles** [comment] 2015-06-11 05:34
Same here. Prompt gets completely stuck.

Grails Version: 3.0.1
Groovy Version: 2.4.3
JVM Version: 1.8.0_20

**Comment by racercode** [comment] 2015-06-11 16:46
| Grails Version: 3.0.1
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_40

When I run grails on prompt in my win 8.1 its stuck.2015-06-11 22:15:09
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode):

"pool-1-thread-1" #16 prio=5 os_prio=0 tid=0x00000000168de800 nid=0x1408 runnabl
e [0x000000001790e000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Object.clone(Native Method)
        at com.sun.crypto.provider.GHASH.blockMult(GHASH.java:73)
        at com.sun.crypto.provider.GHASH.processBlock(GHASH.java:151)
        at com.sun.crypto.provider.GHASH.update(GHASH.java:167)
        at com.sun.crypto.provider.GaloisCounterMode.doLastBlock(GaloisCounterMo
de.java:362)
        at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterM
ode.java:511)
        at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:102
3)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:960)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
        at javax.crypto.Cipher.doFinal(Cipher.java:2377)
        at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
        at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1003)
        - locked <0x00000000c2271a40> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:918)

        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x00000000c22726a8> (a sun.security.ssl.AppInputStream)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x00000000c2272bb8> (a java.io.BufferedInputStream)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        - locked <0x00000000c2272b78> (a sun.net.www.http.KeepAliveStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Http
URLConnection.java:3335)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Http
URLConnection.java:3328)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:62)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ProgressRepo
rtingDownload.download(DistributionFactory.java:177)
        at org.gradle.wrapper.Install$1.call(Install.java:59)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAcc
essManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistri
bution$1.call(DistributionFactory.java:122)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistri
bution$1.call(DistributionFactory.java:116)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

"Connection worker" #15 prio=5 os_prio=0 tid=0x0000000016984800 nid=0x1fa0 waiti
ng on condition [0x000000001780e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c208f3a0> (a java.util.concurrent.Futu
reTask)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistri
bution.getToolingImplementationClasspath(DistributionFactory.java:144)
        at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementat
ionLoader.create(CachingToolingImplementationLoader.java:39)
        at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplem
entationLoader.create(SynchronizedToolingImplementationLoader.java:42)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExe
cutor.onStartAction(LazyConsumerActionExecutor.java:99)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExe
cutor.run(LazyConsumerActionExecutor.java:82)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsum
erActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerAction
Executor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecut
orImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

"NonBlockingInputStreamThread" #12 daemon prio=5 os_prio=0 tid=0x000000001695980
0 nid=0x1f08 in Object.wait() [0x000000001750f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000c208ac00> (a jline.internal.NonBlockingInputStre
am)
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java
:278)
        - locked <0x00000000c208ac00> (a jline.internal.NonBlockingInputStream)
        at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x0000000016078800 nid=0x1054 ru
nnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x00000000147f0000 nid=0x3d4
 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x00000000147ec800 nid=0x8d4
 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x00000000147e7000 nid=0xb78
 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x00000000147e5800 nid=0x137c r
unnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x00000000147e4000 nid=0x158
waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000021fc000 nid=0x1008 in Obje
ct.wait() [0x0000000015b3f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000c212eb60> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000000c212eb60> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000021f3000 nid=0x17e
0 in Object.wait() [0x0000000015a3e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000c22c16e0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
        - locked <0x00000000c22c16e0> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x0000000002106800 nid=0x1f30 waiting on conditio
n [0x000000000204e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000c208ef90> (a java.util.concurrent.lock
s.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject
.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:
403)
        at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(
BlockingResultHandler.java:40)
        at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter.run(D
efaultBuildActionExecuter.java:46)
        at org.grails.cli.gradle.GradleUtil.runBuildActionWithConsoleOutput(Grad
leUtil.groovy:139)
        at org.grails.cli.gradle.GradleUtil.runBuildActionWithConsoleOutput(Grad
leUtil.groovy:132)
        at org.grails.cli.GrailsCli$1.readFromGradle(GrailsCli.groovy:365)
        at org.grails.cli.GrailsCli$1.readFromGradle(GrailsCli.groovy)
        at org.grails.cli.gradle.cache.CachedGradleOperation$_call_closure1.doCa
ll(CachedGradleOperation.groovy:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure2.doCa
ll(GradleUtil.groovy:87)
        at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure2.call
(GradleUtil.groovy)
        at grails.io.support.SystemOutErrCapturer.withNullOutput(SystemOutErrCap
turer.groovy:64)
        at org.grails.cli.gradle.GradleUtil.withProjectConnection(GradleUtil.gro
ovy:86)
        at org.grails.cli.gradle.cache.CachedGradleOperation.call(CachedGradleOp
eration.groovy:64)
        at org.grails.cli.GrailsCli.populateContextLoader(GrailsCli.groovy:357)
        at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:344)
        at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:192)
        at org.grails.cli.GrailsCli.main(GrailsCli.groovy:99)

"VM Thread" os_prio=2 tid=0x00000000147a7800 nid=0x274 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x000000000211c800 nid=0xc10 runna
ble

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x000000000211e000 nid=0x11d0 runn
able

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x000000000211f800 nid=0x230 runna
ble

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002121000 nid=0x954 runna
ble

"VM Periodic Task Thread" os_prio=2 tid=0x000000001483d000 nid=0x1ed8 waiting on
 condition

JNI global references: 248

Heap
 PSYoungGen      total 35328K, used 23378K [0x00000000eb380000, 0x00000000ef8800
00, 0x0000000100000000)
  eden space 32768K, 63% used [0x00000000eb380000,0x00000000ec7dc5e0,0x00000000e
d380000)
  from space 2560K, 98% used [0x00000000ed380000,0x00000000ed5f8328,0x00000000ed
600000)
  to   space 2560K, 0% used [0x00000000ef600000,0x00000000ef600000,0x00000000ef8
80000)
 ParOldGen       total 44032K, used 11022K [0x00000000c1a00000, 0x00000000c45000
00, 0x00000000eb380000)
  object space 44032K, 25% used [0x00000000c1a00000,0x00000000c24c3b88,0x0000000
0c4500000)
 Metaspace       used 14893K, capacity 15182K, committed 15488K, reserved 106291
2K
  class space    used 1775K, capacity 1880K, committed 1920K, reserved 1048576K

**Comment by garypaduana** [comment] 2015-06-17 19:10
Grails becomes completely unresponsive to interrupts when it arrives at this state.  It's practically unusable.

**Comment by scbarrett** [comment] 2015-06-25 04:52
Exactly the same as OP with Grails 3.0.2 on openSuse.

**Comment by AugierLe42e** [comment] 2015-06-26 10:38
Same here. Mageia 4.1 and OpenJDK 7. The stacktrace starts with:

    ERROR grails.boot.GrailsApp - Application startup failed
    Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException:
        Invalid bean definition with name 'hibernateDatastore' defined in null:
        Could not resolve placeholder 'HOSTNAME%%.*' in string value "history -a; echo -ne "\033]0;${USER}@${HOSTNAME%%.*}

There's more if you need it. It seems like an environement variable is interfering with Grails startup.

**Comment by graemerocher** [comment] 2015-06-26 11:37
@AugierLe42e that error is #671 which relates to something in your `bash_profile` that Spring Boot evaluates into a property placeholder

**Comment by AugierLe42e** [comment] 2015-06-26 16:48
Ok, thanks. Ping if you need more info ;)

**Comment by hernanemartinez** [comment] 2015-06-30 17:33
Guys, I've this very same issue. I do not read a proper solution. This is a bug? 
What's the workaround?

**Comment by scbarrett** [comment] 2015-06-30 17:52
The work around seems to be to ignore it. Everything works as expected,
except the interactive console. It is a bit irksome.

**Comment by garypaduana** [comment] 2015-06-30 18:23
The workaround for me was to switch to Spring MVC.  It's the long way around...

**Comment by faraz-ali** [comment] 2015-06-30 18:35
Spring Boot ;)

**Comment by graemerocher** [comment] 2015-06-30 21:17
@garypaduana That doesn't make much sense to me because doing `gradle bootRun` in a Spring Boot app results in exactly the same behaviour so I'm not sure how switching solves this for you...

**Comment by garypaduana** [comment] 2015-06-30 21:52
@graemerocher I was early enough on in this particular project that I switched entirely from groovy/grails/gradle and went back to java/boot/maven and run it from a jar.  My workaround was mainly in jest.  I still use grails for a few other projects so I'm looking forward to a resolution and definitely appreciate the effort put in by you and others.

**Comment by graemerocher** [comment] 2015-07-01 07:05
@garypaduana So your sole intention was to troll the Grails Github issues site? Nice to see people taking issue reports seriously...

**Comment by csbubbles** [comment] 2015-07-01 07:16
@graemerocher I believe the intention was rather to express the frustration with Grails developers not testing their releases. Which is totally understandable, actually.

**Comment by graemerocher** [comment] 2015-07-01 07:37
@csbubbles I don't see how this minor issue can be blown into something that people feel makes it unusable. If you do `run-app` from interactive mode yes it currently blocks further input but the server still runs, a minor usability issue that can be worked around by opening another interactive mode console. To go from that to some of the claims being made in this thread is just mind blowing to me

**Comment by graemerocher** [comment] 2015-07-01 07:40
@csbubbles In fact every single 'bug' that this thread claims happens exactly the same in Spring Boot since we are simply using Spring Boot infrastructure. So the whole "Grails has bugs so we will use Spring Boot" tone is moot since the origin of the problems is there... but anyway.. whatever floats your boat

**Comment by csbubbles** [comment] 2015-07-01 07:41
@graemerocher I haven't used Grails for about two years. So, recently when I needed to quickly create a small website, I have downloaded the latest version of Grails that I found, created a project, ran it and got this hanging. And I had no idea whether it worked or not worked, or whether it was really still processing something. So, sorry, I can't take it as "minor" issue. From my perspective (user perspective), Grails simply doesn't work as it hangs in the middle of something and never finishes. Whether it *actually* works or not is irrelevant to me as it doesn't let me understand that.

**Comment by graemerocher** [comment] 2015-07-01 07:45
@csbubbles So another troll that doesn't actual use Grails? So I assume you downloaded the Spring Boot sample did `gradle bootRun`, noted the exact same behaviour and abandoned it too? If an issue as minor as this presents such a barrier then a truly feel sorry for some of the other technologies you tried to adopt

**Comment by csbubbles** [comment] 2015-07-01 07:50
@graemerocher I even have no idea what Spring Boot is, to be honest. And no, I continue using Grails for that project. I run "grails" and then "run-app".

PS I also think it is at least impolite to call people, who filing issues and give Grails their user feedback hoping that the issues will be fixed one days, "trolls".

**Comment by graemerocher** [comment] 2015-07-01 07:55
@csbubbles I find it equally impolite from folks who do not use Grails and have no intention anything else other than to report falsehoods and spread FUD on our issues instance, in particular for an issue as minor as this, making claims that we do not test our releases or that the workaround is to "switch to Spring Boot" which, ironically, exhibits the exact same behaviour.

**Comment by csbubbles** [comment] 2015-07-01 08:01
@graemerocher I can only repeat again that this is unfortunate that we treat the severity of issues differently. From my perspective the version of Grails that has this particular issue simply doesn't let the product be considered as working. This is not a usability issue. This is a serious bug because the product doesn't provide any information for its user what is actually happening (whether it works or not at all).

**Comment by graemerocher** [comment] 2015-07-01 08:10
@csbubbles We will try to improve this then, I guess the line that reads:

       Grails application running at http://localhost:8080

Is not obvious enough a hint that the application is up and running oO

**Comment by csbubbles** [comment] 2015-07-01 08:11
@graemerocher It is not, because I can see that it is still "Building" something, and I can't run any command from the Grails CLI.

**Closed** 2015-07-01 08:38 UTC
Labels: Critical, Improvement

**Comment by graemerocher** [comment] 2015-07-01 08:39
Fixed by https://github.com/grails/grails-profile-repository/commit/aba2e52cae255615519735f8eda90c93654897fd

**Comment by ziadbasel** [comment] 2015-07-01 14:12
Thanks for the fix @graemerocher !

**Comment by garypaduana** [comment] 2015-07-01 15:10
@graemerocher After a few days of dealing with `grails run-app`, -> find process -> `kill` it was worth the effort to switch to a different environment.  'In jest' means if you are willing to change the project setup altogether then go ahead and use my workaround.  I needed a webapp that could be used in a team dev environment with as little complication as possible.  Changing the approach to use other tools was my actual workaround.  I'm sorry if you take that as trolling, but I'm definitely not.  Thank you for the fix.

**Comment by graemerocher** [comment] 2015-07-01 15:13
@garypaduana CTRL+C consistently kills the process for me in all versions of 3.0.x, it would be concerning if it didn't

**Comment by garypaduana** [comment] 2015-07-01 15:25
I just tried this again with mixed results.  Sometimes it would kill it immediately, other times it would hang for a while and then later kill (less than a minute later).

    Grails application running at http://localhost:8080
    > Building 83% > :bootRun^C^C^C^C^C^C^C^C^C^C

    | Grails Version: 3.0.1 
    | Groovy Version: 2.4.3
    | JVM Version: 1.8.0_45

It's entirely possible that the issue is on my end, but I remember having difficulty killing the process from a ctrl-c.

**Comment by graemerocher** [comment] 2015-07-01 15:27
@garypaduana Ok I have added a `stop-app` command along with the fix for the hanging, so this should provide a solution for your concerns. Thanks for the feedback.

**Comment by garypaduana** [comment] 2015-07-01 15:34
Thank you for the quick turnaround.

**Comment by kasbob** [comment] 2015-07-25 15:34
@graemerocher thanks for the contribution. I'm completely new to both github, groovy and grails, so I have zero clue of how to implement the fix. Could you give me a clue?

**Comment by anshbansal** [comment] 2015-07-25 15:40
@kasbob Which fix? The one grame added in comments? That is part of grails 3.0.3. You need to start using new version of grails

**Comment by kasbob** [comment] 2015-07-25 17:17
@anshbansal ok, that was what I didn't get. Thank you so much :)

**Comment by kasbob** [comment] 2015-07-26 11:17
@anshbansal - I have now updated grails. But the problem persists :(. I cannot even type anything into the terminal once i have given it the 'grails shell' command. Any ideas?

Setting grails 3.0.3 as default.
MacBook-Pro:gamereview Kasper$ grails console
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources
:classes
:findMainClass
:console
objc[8462]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

BUILD SUCCESSFUL

Total time: 1 mins 31.708 secs
MacBook-Pro:gamereview Kasper$ grails shell
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:shell
objc[8515]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Groovy Shell (2.4.3, JVM: 1.7.0_51)
Type ':help' or ':h' for help.
\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
groovy:000> 
\> Building 83% >  :shell

**Comment by ejaz-ahmed** [comment] 2015-07-27 05:45
@kasbob use 'grails console' as a workaround.

**Comment by kasbob** [comment] 2015-07-27 06:34
@ejaz-ahmed ok, will do :)

**Comment by graemerocher** [comment] 2015-07-27 08:56
@kasbob To use the shell you have to use `gradle -q shell` otherwise use `grails console`

**Comment by kasbob** [comment] 2015-07-27 09:17
Thank you for replying @graemerocher 
ok, so i tried the following, without success:

`<grails -q shell>` - didn't work. Got the following error-msg
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Task 'q' not found in root project 'test1'.

`<gradle -q shell>` 
> -bash: gradle: command not found

`<grails gradle -q shell>`  - http://pastebin.com/rrCeScBD

**Comment by anshbansal** [comment] 2015-07-27 09:20
@kasbob Don't use grails. Just gradle -q shell

**Comment by kasbob** [comment] 2015-07-27 09:23
@anshbansal - 

using `gradle -q shell` gave me the following error:
>-bash: gradle: command not found

**Comment by graemerocher** [comment] 2015-07-27 09:35
@kasbob Try `./gradlew -q shell`, you got that error because you don't have gradle installed

**Comment by kasbob** [comment] 2015-07-27 09:43
@graemerocher 
groovy:000> def thatTotallyWorks = "THANK YOU!"
===> THANK YOU!

**Comment by gkiko** [comment] 2016-02-06 10:23
Problem persists. I need to run `clean` several times to make it work
**Grails 3.1.1**
**Groovy 2.10**
**Java 1.8.60**
**OS X 10.11.3**

**Comment by ejaz-ahmed** [comment] 2016-02-06 15:03
Gradle bootRun also hangs some time. Looks like an upstream spring boot issue.

**Comment by rajat1saxena** [comment] 2016-10-02 03:18
Same issue on Ubuntu 16.04. Console seems to be stuck at:
`> Building 80% > :bootRun`

**Comment by jonigl** [comment] 2016-12-27 00:27
Same issue here. Grails 3.2.3 and using macOS Sierra 10.12.2 (16C67).
`> Building 81% > :client:bootRun`

**Comment by ValerianMenin** [comment] 2017-02-15 10:04
```gradle :server:bootRun
:server:compileJava UP-TO-DATE
:server:compileGroovy UP-TO-DATE
:server:buildProperties
:server:processResources
:server:classes
:server:findMainClass
:server:bootRun

Configuring Spring Security Core ...
... finished configuring Spring Security Core


Configuring Spring Security REST 2.0.0.M2...
... finished configuring Spring Security REST

Grails application running at http://localhost:8080 in environment: development
> Building 85% > :server:bootRun
```
Same issue using Grails 3.2.4 on a Kubuntu 16.04 system.
Is there a way to fix it ? I can't access my logs as long as it doesn't work.
I don't want to run my server by doing a `grails run-app`

**Comment by ibayetto** [comment] 2017-04-10 18:10
Same issue here using Grails 3.2.6
`> Building 85% > :bootRun`

**Comment by graemerocher** [comment] 2017-04-11 09:19
No idea why people keep commenting on this non-issue.

It may say `> Building 85% > :server:bootRun` but as you can see the application is running.

```
Grails application running at http://localhost:8080 in environment: development
```

There is nothing we can do about this Gradle console output as it comes from Gradle. However the behaviour is normal and is working as designed.

If your application is actually hanging and unreachable, then that is unrelated to this issue and something wrong with the application itself. 

Please stop posting comments on this thread that are completed related to the original reported issue.
