### ISSUE TITLE
localeResolver not called for dynamic mappings

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [grails/grails-core#10880] opened 2017-11-27 18:26 UTC
### Steps to Reproduce

1. Create an  URL mapping in UrlMappings.goovy like this:
 name mymapping: "/testurl" (view:'/myfile')

2. Create the GSP file myfile.gsp in the root folder of the view folder.

3. Implement a LocaleResolver and reference it in resources.groovy

4. Call http://localhost/myfile.gsp

### Expected Behaviour

The corresponding method of the class implementing the LocaleResolver should be called.

### Actual Behaviour

No method of the LocaleResolver is called.

### Workaround

Define an action in a controller like this:

def mymapping() { render (view: '/myvile) }

and declare a mapping in UrlMappings.groovy like this:

name mymapping: "/testurl" (controller: 'myController', action:'/mymapping')

So the LocaleResolver in resources.groovy is only invoked, when we use a action in our mapping. Just referencing a view will not invoke the LocaleResolver. 

### Environment Information

- **Operating System**: Debian 8.9
- **Grails Version:** 2.5.3
- **JDK Version:** jdk1.8.0_131

**Comment by sdelamo** [comment] 2017-12-21 07:49
Can you upload a sample project ?

**Comment by bobbywarner** [comment] 2020-07-01 03:56
Closing as no sample project was provided and can't reproduce.

**Closed by bobbywarner** 2020-07-01 03:56 UTC
Labels: closed: cannot reproduce, status: awaiting feedback
