### ISSUE TITLE
<g:formatDate /> TagLib throws groovy.lang.MissingMethodException

### ISSUE THREAD

**Issue by mariomatar** [grails/grails-core#9159] opened 2015-08-02 23:08 UTC
I do not know why it happened alone, g:formatDate does not works.

The problem seems here : 

![capture du 2015-08-03 00 59 09](https://cloud.githubusercontent.com/assets/1669985/9028516/1274b6d0-397c-11e5-9f8d-e2d344eeb68f.png)

And the signature is :

    public static synchronized FastDateFormat getInstance(String pattern, TimeZone timeZone, Locale locale)

And stacktrace : 

	URI
	/myapp/a/b
	Class
	groovy.lang.MissingMethodException
	Message
	Error processing GroovyPageView: Error executing tag <g:applyLayout>: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <g:formatDate>: No signature of method: static org.apache.commons.lang.time.FastDateFormat.getInstance() is applicable for argument types: (org.codehaus.groovy.grails.web.util.StreamCharBuffer, sun.util.calendar.ZoneInfo, java.util.Locale) values: [dd/MM/yy, sun.util.calendar.ZoneInfo[id="Europe/Paris",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=184,lastRule=java.util.SimpleTimeZone[id=Europe/Paris,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]], ...] Possible solutions: getInstance(), getInstance(java.lang.String, java.util.Locale), getInstance(java.lang.String, java.util.TimeZone, java.util.Locale), getInstance(java.lang.String), getInstance(java.lang.String, java.util.TimeZone)
	Caused by
	No signature of method: static org.apache.commons.lang.time.FastDateFormat.getInstance() is applicable for argument types: (org.codehaus.groovy.grails.web.util.StreamCharBuffer, sun.util.calendar.ZoneInfo, java.util.Locale) values: [dd/MM/yy, sun.util.calendar.ZoneInfo[id="Europe/Paris",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=184,lastRule=java.util.SimpleTimeZone[id=Europe/Paris,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]], ...] Possible solutions: getInstance(), getInstance(java.lang.String, java.util.Locale), getInstance(java.lang.String, java.util.TimeZone, java.util.Locale), getInstance(java.lang.String), getInstance(java.lang.String, java.util.TimeZone)

I used grails 2.5.0 and Java 8u25, but with this bug I switched to 2.5.1 and it's the same.

**Comment by jeffbrown** [comment] 2015-08-03 07:20
Can you show how you are supplying the `format`?

Thanks for the feedback.

**Comment by jeffbrown** [comment] 2015-08-03 07:23
At least for a simple case like https://github.com/jeffbrown/issue_9159/blob/22c6a2913788075bd3f8be56c2bea9b9361da92d/grails-app/views/demo/index.gsp#L3 I can't reproduce the problem.  I believe it is happening, but may need more info to track it down.

Thanks again.

**Comment by jeffbrown** [comment] 2015-08-03 07:24
I expect that your `format` must be dynamic.  Is that the case?

**Comment by mariomatar** [comment] 2015-08-03 11:31
yes it's dynamic 

    def format = attrs.format


I think it will be difficulte to reproduce 
I use grails for 2 years with g:formatDate, and it bug alone since yesterday. 
I looked my past commits, but nothings can create this bug

A workaround is to cast parameter to String : 


    class CustomFormatTagLib extends FormatTagLib  {
        Closure formatDateCustom = { attrs ->    
            String format = attrs.remove('format')
            if (format) {
                attrs.put('format', format)
            }
            out << g.formatDate(attrs)
        }
    }

(for information super.formatDate(attrs) not work)

**Comment by jeffbrown** [comment] 2015-08-03 12:50
@mariomatar FYI... if you are going to have your own tag like that, there is no reason or benefit to `CustomFormatTagLib` extending `FormatTagLib`.

**Comment by mariomatar** [comment] 2015-08-03 13:59
You're write. I's because I tried to use super
So, if next release correct this bug, I remove my custom tag
Thank you

**Comment by guramritpal-jft** [comment] 2015-08-04 13:30
@mariomatar  close this issue.   jeffbrown has already Acknowledged.  Thanks

**Comment by jeffbrown** [comment] 2015-08-04 13:41
> close this issue. jeffbrown has already Acknowledged. Thanks

@guramritpal-jft Why are you telling @mariomatar to close the issue?  I think I would like to track down the problematic scenario and fix it.

**Comment by guramritpal-jft** [comment] 2015-08-04 13:46
Got it @jeffbrown . Thanks for the correction

**Closed** 2015-08-23 11:41 UTC
Labels: Acknowledged, in progress
