### ISSUE TITLE
Grails 4: Flush causes TransactionRequiredException: no transaction is in progress

### ISSUE THREAD

**Issue by martinfrancois** [grails/grails-core#11376] opened 2019-07-21 12:13 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone example repository
2. Run `grails run-app`

### Expected Behaviour
Console outputs the `localhost:8080` url and the app was successfully started.

### Actual Behaviour
During startup, the following exception appears:
```
Configuring Spring Security Core ...
... finished configuring Spring Security Core

2019-07-21 13:58:58.574 ERROR --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

javax.persistence.TransactionRequiredException: no transaction is in progress
        at org.hibernate.internal.SessionImpl.checkTransactionNeeded(SessionImpl.java:3586)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1447)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1443)
        at org.hibernate.Session$flush.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at myapp.BootStrap$_closure1$_closure3.doCall(BootStrap.groovy:13)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
        at com.sun.proxy.$Proxy132.doInHibernate(Unknown Source)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:297)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:241)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:120)
        at org.grails.orm.hibernate.AbstractHibernateDatastore.withSession(AbstractHibernateDatastore.java:355)
        at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.withSession(AbstractHibernateGormStaticApi.groovy:88)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.withSession(GormEntity.groovy:917)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1470)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:985)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
        at myapp.UserRole.withSession(UserRole.groovy)
        at myapp.UserRole$withSession$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at myapp.BootStrap$_closure1.doCall(BootStrap.groovy:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1099)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:399)
        at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:541)
        at grails.util.Environment.executeForEnvironment(Environment.java:534)
        at grails.util.Environment.executeForCurrentEnvironment(Environment.java:510)
        at org.grails.web.servlet.boostrap.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:74)
        at org.grails.web.servlet.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:83)
        at org.grails.plugins.web.servlet.context.BootStrapClassRunner.onStartup(BootStrapClassRunner.groovy:56)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:269)
        at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:97)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:458)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:445)
        at myapp.Application.main(Application.groovy:11)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

`(BootStrap.groovy:13)` is the following:
```
UserRole.withSession {
            it.flush() // line 13
            it.clear()
}
```

### Environment Information

- **Operating System**: macOS 10.14.5
- **Grails Version:** 4.0.0
- **JDK Version:** 11.0.3

### Example Application
https://github.com/martinfrancois/grails-4-security-hello-world
The steps I did to set it up:
1. Download basic Grails 4 projects from the forge
2. Add grails-spring-security
3. Run s2-quickstart script
4. Add the code from here: https://grails-plugins.github.io/grails-spring-security-core/snapshot/index.html#5-edit-grails-app-init-bootstrap-groovy-to-add-a-test-user to the `Bootstrap` file.

Note: this previously worked fine with Grails 3.3.9

**Comment by martinfrancois** [comment] 2019-07-21 13:45
Just noticed, this seems to be the case not only here, but also in general when saving with a flush: `item.save(flush: true, failOnError: true)` will create the same exception

**Comment by martinfrancois** [comment] 2019-07-21 14:58
Just found the solution:
Since Hibernate 5.2, flushing outside of transactions is not allowed anymore, see: https://github.com/hibernate/hibernate-orm/blob/5.2/migration-guide.adoc#misc
The workaround for this would be to set the following flag in the `application.yml` file, to restore the previous behavior:
```
hibernate:
    allow_update_outside_transaction: true
```
But the "cleaner" way would be to solve the problem at the core, i.e. add transactions to all operations that flush or perform actions like deletions.
In the case as described in the issue above, the following works:
```
PersonRole.withTransaction { status ->
    PersonRole.withSession {
        it.flush()
        it.clear()
    }
}
```
If the operation that flushes is in a regular method, you can also annotate the method with `@Transactional` (this seems not to work in the `Bootstrap` file and in in static methods, per my testing).

Maybe this is something we should add to the Grails 4 migration guide and maybe also the `grails-spring-security` documentation?

**Comment by graemerocher** [comment] 2019-07-22 11:44
This is not a bug nor something we can fix. Hibernate now requires transactions. This is documented for GORM here http://gorm.grails.org/latest/hibernate/manual/index.html#upgradeNotes

**Comment by zoladkow** [comment] 2019-08-08 10:13
Hi I'll butt into this issue, since it seems closely related and not spam too much.

I just started the upgrade from 3.3.10 to 4.0.0 and facing two "no transaction" related exceptions and I am clueless given current migration guide what I might be missing.


**Initial opening of landing page** results in 503 with underlying stacktrace (repeated per each request):

```
2019-08-08 12:01:09.888 [https-jsse-nio-8443-exec-6] ERROR [][] o.g.w.e.GrailsExceptionResolver - TransactionRequiredException occurred when processing request: [GET] /favicon.ico
no transaction is in progress. Stacktrace follows:
javax.persistence.TransactionRequiredException: no transaction is in progress
        at org.hibernate.internal.SessionImpl.checkTransactionNeeded(SessionImpl.java:3586)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1447)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1443)
        at org.grails.plugin.hibernate.support.GrailsOpenSessionInViewInterceptor.postHandle(GrailsOpenSessionInViewInterceptor.java:64)
        at org.springframework.web.servlet.handler.WebRequestHandlerInterceptorAdapter.postHandle(WebRequestHandlerInterceptorAdapter.java:65)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPostHandle(HandlerExecutionChain.java:156)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1046)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

And also similar issue from within a job (grails-quartz plugin) even tough, the job runs a `@Transactional` method from a grails service:

```
2019-08-08 11:45:01.430 [quartzScheduler_Worker-2] ERROR [][] g.p.q.l.ExceptionPrinterJobListener - Exception occurred in job: Grails Job
org.quartz.JobExecutionException: java.lang.IllegalArgumentException: Active Connection is required
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.IllegalArgumentException: Active Connection is required
        at org.springframework.util.Assert.notNull(Assert.java:198)
        at org.springframework.jdbc.datasource.ConnectionHolder.getConnection(ConnectionHolder.java:160)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithNewSession(GrailsHibernateTemplate.java:171)
        at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:360)
        at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.withNewSession(AbstractHibernateGormStaticApi.groovy:82)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.withNewSession(GormEntity.groovy:1027)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$withNewSession$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at com.xx.minerva.User.withNewSession(User.groovy)
        at com.xx.minerva.User$withNewSession$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at com.xx.minerva.LdapSyncService$_processUsers_closure2.doCall(LdapSyncService.groovy:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:1014)
        at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:966)
        at org.grails.datastore.gorm.GormStaticApi.withNewTransaction(GormStaticApi.groovy:927)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.withNewTransaction(GormEntity.groovy:954)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper$withNewTransaction.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at com.xx.minerva.User.withNewTransaction(User.groovy)
        at com.xx.minerva.User$withNewTransaction.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at com.xx.minerva.LdapSyncService.processUsers(LdapSyncService.groovy:29)
        
```
Here you can actually see that I ended up wrapping the orm call into a `.withNewTransaction` closure which did not help.

**Comment by graemerocher** [comment] 2019-08-08 10:19
The first issue you should probably set the flush mode to manual with `grails.gorm.flushMode="MANUAL"` in config.

The latter stack trace is unrelated, but if you can provide an example that reproduces we can certainly take a look.

**Comment by zoladkow** [comment] 2019-08-08 10:56
Thanks, manual mode got me past that request related exception. Had also to meddle with other related properties, namely i commented those out:

```
#    grails.gorm.autoFlush: false
#    hibernate.flush.mode: AUTO
```

I had them since migration to 3.3.8, which helped with when the entities get persisted. will have to check how it behaves now later on.


Regarding the other, I'm preparing an example for you.

**Comment by zoladkow** [comment] 2019-08-08 11:41
Sample example with grails-quartz plugin.
[grails4jobissue.zip](https://github.com/grails/grails-core/files/3481501/grails4jobissue.zip)

It turns out that the exception starts occurring once the `.save()` call is wrapped in `Person.withNewSession { }`. But in my use case the new session is there to have a bulk of related changes committed in one go. And of course this works as-is now with Grails 3.3.10.

**Comment by martinfrancois** [comment] 2019-08-09 16:21
@zoladkow like I mentioned in my previous comment, try wrapping the `Person.withNewSession {}` call into a
```
Person.withTransaction { status -> 
  Person.withNewSession {...}
}
```

**Comment by zoladkow** [comment] 2019-08-12 07:25
@martinfrancois 
I did exactly that when I first saw this issue. But that did not eliminate the exception, only added frames to the stack. 

What did work, was removing `.withNewSession {...}` altogether. Or actually it was like that when I created the example @graemerocher asked for - it was just working without exception until I wrapped `.save()` in the session closure.

**Comment by miq** [comment] 2020-03-27 16:20
Does the first problem of @zoladkow essentially mean, that hibernate.flush.mode=AUTO is not working at all?

That is what I am experiencing when creating a fresh Grails 4.0.2 app and adding hibernate.flush.mode=AUTO to application.yml.

It simply renders a 500 error with the javax.persistence.TransactionRequiredException exception. It should be either stated clearly in the documentation or be fixed. Maybe that part should become a separate issue...

**Comment by pmcneil** [comment] 2020-07-08 22:54
Just reporting my experience today. Grails 4.0.2 app. Added a method to an existing service. Service has @Transactional. New method wouldn't correctly load, modify or save domain objects. adding save flush reveals the TransactionRequiredException exception. I'm still debugging this, but it seems related.

**Comment by pmcneil** [comment] 2020-07-08 23:01
wrapping the **method** in @Transactional makes it work as expected. Which to me is unexpected as other methods in the same Service work.

**Comment by pmcneil** [comment] 2020-07-08 23:08
Interestingly, the save(flush: true) actually works when I get the TransactionRequiredException and if I don't use save: flush it doesn't save.
I'll stop spamming now, and report when I find out what is happening.

**Comment by zoladkow** [comment] 2020-07-09 06:48
> 
> 
> Just reporting my experience today. Grails 4.0.2 app. Added a method to an existing service. Service has @transactional. New method wouldn't correctly load, modify or save domain objects. adding save flush reveals the TransactionRequiredException exception. I'm still debugging this, but it seems related.

@pmcneil Hi, what you're describing seems like a behaviour of `@Transactional` annotation at class level - as I recall, the handler will apply transactions only to non-javabean methods. So saving in a `setXXX` will fail unless you apply `@Transactional` directly to that method. Is that your case?

I thought I posted an issue for that, because that was so not clear from the docs, but cannot find it for reference... bah, i need vacation...

**Comment by pmcneil** [comment] 2020-07-09 12:18
Indeed this method is the only one called setBlah() and that would explain it. Thanks @zoladkow.

**Comment by davydotcom** [comment] 2020-08-27 12:01
This is well documented and should probably be closed. Use an @transactional or withTransaction in areas where the annotation isn't usable. Personally I use the hibernate setting that disabled this ridiculous default imposed by hibernate5

**Closed by davydotcom** 2020-08-27 12:01 UTC

**Comment by miq** [comment] 2020-12-18 16:20
@davydotcom : What would this hibernate setting to disable this default be?

**Comment by zoladkow** [comment] 2020-12-18 20:59
@davydotcom Sure, if you mean that since H5 transactions are mandatory.

And I'll leave this (https://github.com/grails/grails-data-mapping/issues/1203) , which is the other issue discussed here.

**Comment by beechovsky** [comment] 2022-01-20 15:14
This appears to happen inside services marked with the `@Transactional` annotation.

**Comment by NeoZephyr** [comment] 2022-03-24 07:51
> > Just reporting my experience today. Grails 4.0.2 app. Added a method to an existing service. Service has @transactional. New method wouldn't correctly load, modify or save domain objects. adding save flush reveals the TransactionRequiredException exception. I'm still debugging this, but it seems related.
> 
> @pmcneil Hi, what you're describing seems like a behaviour of `@Transactional` annotation at class level - as I recall, the handler will apply transactions only to non-javabean methods. So saving in a `setXXX` will fail unless you apply `@Transactional` directly to that method. Is that your case?
> 
> I thought I posted an issue for that, because that was so not clear from the docs, but cannot find it for reference... bah, i need vacation...

You are right!

Why @transaction annotation which at class level can not apply to 'setXXX' method？I've never seen this from any docs
