### ISSUE TITLE
Grails Central repo certificate appears to have expired 

### ISSUE THREAD

**Issue by digitaldiver** [grails/grails-core#11085] opened 2018-08-28 17:09 UTC
### Steps to Reproduce

1. Build grails project with reference to the grails central repo

### Expected Behaviour

Build should succeed

### Actual Behaviour

Build fails with:

Could not transfer artifact org.grails.plugins:standalone:zip:1.3 from/to grailsCentral (https://repo.grails.org/grails/plugins): sun.security.validator.ValidatorException: PKIX path validation failed: 

Inspecting the cert it looks like it expired at Tuesday, August 28, 2018 at 5:00:00 AM Pacific Daylight Time

### Environment Information

All?

**Comment by jameskleeh** [comment] 2018-08-28 17:12
Duplicate of #11082

**Closed by jameskleeh** 2018-08-28 17:12 UTC
