### ISSUE TITLE
Failed deployment in JBOSS Wildfly

### ISSUE THREAD

**Issue by jarantes17** [grails/grails-core#10286] opened 2016-10-31 16:55 UTC
I have an application in version 3.1 of grails and want to migrate it to version 3.2. Currently my server is the JBoss EAP 7.0.0 GA based wildfly

### Steps to Reproduce

1. Create a grails-app with profile = rest-api
2. Set tomcat dependency to "provided"
3. Clean and generate war file

### Expected Behaviour

Deploy and usually run the application in JBOSS as grails 3.1.

### Actual Behaviour

Failed deployment

### JBOSS LOG ERROR:
`
Caused by: java.lang.NoClassDefFoundError: Failed to link grails/async/web/AsyncGrailsWebRequest (Module \"deployment.myapp.war:main\" from Service Module Loader): groovy/lang/GroovyObject"`

### Environment Information

- **Operating System**: Windows 10/Linux CentOS
- **Grails Version:** 3.2.2
- **JDK Version:** 1.8
- **Container Version (If Applicable):** JBOSS EAP 7.0.0GA

**Comment by jeffbrown** [comment] 2016-10-31 21:19
> Implantar e executar normalmente a aplicação no JBOSS.

Does that translate to something like you expect the application to be successfully deployed on JBOSS?

**Comment by jeffbrown** [comment] 2016-10-31 21:20
Is there a `provided` scoped `groovy-ant` dependency in your `build.gradle`?

**Comment by jarantes17** [comment] 2016-10-31 21:47
Yes, as the rails 3.1 works.

This is my `build.gradle` file:

```
buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "org.grails.plugins:hibernate4:5.0.6"
        classpath "org.grails.plugins:views-gradle:1.0.11"
    }
}

version ""
group "service.api"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"war"
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.plugins.views-json"

ext {
    grailsVersion = project.grailsVersion
    gradleWrapperVersion = project.gradleWrapperVersion
}

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions false
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.springframework.boot:spring-boot-starter-actuator"
    provided "org.springframework.boot:spring-boot-starter-tomcat"
    compile "org.grails:grails-plugin-url-mappings"
    compile "org.grails:grails-plugin-rest"
    compile "org.grails:grails-plugin-codecs"
    compile "org.grails:grails-plugin-interceptors"
    compile "org.grails:grails-plugin-services"
    compile "org.grails:grails-plugin-datasource"
    compile "org.grails:grails-plugin-databinding"
    compile "org.grails:grails-plugin-async"
    compile "org.grails:grails-web-boot"
    compile "org.grails:grails-logging"
    compile "org.grails.plugins:cache"
    compile "org.grails.plugins:hibernate4"
    compile "org.hibernate:hibernate-ehcache"
    compile "org.grails.plugins:views-json"
    console "org.grails:grails-console"
    profile "org.grails.profiles:rest-api"
    runtime "com.h2database:h2"
    testCompile "org.grails:grails-plugin-testing"
    testCompile "org.grails.plugins:geb"
    testCompile "org.grails:grails-datastore-rest-client"
    testRuntime "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
    testRuntime "net.sourceforge.htmlunit:htmlunit:2.18"

    // my libraries
    runtime 'mysql:mysql-connector-java:5.1.36'
    compile 'org.codehaus.groovy.modules.http-builder:http-builder:0.7'
    compile group: 'org.json', name: 'json', version: '20160810'

}

task wrapper(type: Wrapper) {
    gradleVersion = gradleWrapperVersion
}
```

**Comment by sebDK** [comment] 2016-11-01 07:27
I got the same problem. @jeffbrown adivsed me to comment out `provided "org.codehaus.groovy:groovy-ant"` and it was working.

**Comment by jarantes17** [comment] 2016-11-01 10:48
Thank you! This solution solved my problem.

**Comment by jeffbrown** [comment] 2016-11-01 17:36
I think this is a duplicate of #10196.

**Closed by jeffbrown** 2016-11-01 17:36 UTC
