### ISSUE TITLE
is hot reloading supported with newer gradle  (> 3.5) ?

### ISSUE THREAD

**Issue by lraynal** [grails/grails-core#11046] opened 2018-07-07 16:52 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the project (gradle bootRun )
2. Change the method name foo1 to foo in ItemService and ItemController, 
3. wait for the recompiling.. message
4. go to http://localhost:8080/item
5. get an 
Error 500: Internal Server Error
No signature of method: test336.$ItemServiceImplementation.foo() is applicable

```
2018-07-07 18:38:07.268 ERROR --- [nio-8080-exec-3] o.g.web.errors.GrailsExceptionResolver   : MissingMethodException occurred when processing request: [GET] /item
No signature of method: test336.$ItemServiceImplementation.foo() is applicable for argument types: (java.lang.Integer, java.lang.Integer, test336.IndicatorCode) values: [2018, 5, IDFM1]
Possible solutions: foo1(int, int, test336.IndicatorCode), any(), find(), wait(), dump(), grep(). Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.lang.MissingMethodException: No signature of method: test336.$ItemServiceImplementation.foo() is applicable for argument types: (java.lang.Integer, java.lang.Integer, test336.IndicatorCode) values: [2018, 5, IDFM1]
Possible solutions: foo1(int, int, test336.IndicatorCode), any(), find(), wait(), dump(), grep()
        at test336.ItemController$$EQx8MHdw.index(ItemController.groovy:9)
        ... 14 common frames omitted
``` 

### Expected Behaviour

controller should display an empy list

### Actual Behaviour

standard error screen

### Environment Information

- **Operating System**: No signature of method: test336.$ItemServiceImplementation.foo() is applicable
- **Grails Version:** 3.3.6
- **JDK Version:** java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

- **Container Version (If Applicable):** N/A

### Example Application

[test336.zip](https://github.com/grails/grails-core/files/2172916/test336.zip)

**Comment by ilopmar** [comment] 2018-07-09 06:56
I can't reproduce the issue with the sample application attached. Once I change the method name I can see the recompile message and `http://localhost:8080/item` works.

**Comment by lraynal** [comment] 2018-07-09 08:12
Hi, sorry it may not be very clear, I'm seeing this with Gradle 4.8.1 (the wrapper should be positioned on this version). Anyway, probably a known spring-boot issue..

**Comment by ddelponte** [comment] 2019-05-09 21:45
@lraynal, do you have any objections to closing this ticket?  Reloading appears to be working as expected.

**Closed** 2019-05-15 16:55 UTC
Labels: Cannot Reproduce, Reloading
