### ISSUE TITLE
Grails 3.2.1 IllegalArgumentException when running generated WAR and attempting to save a domain object

### ISSUE THREAD

**Issue by tarpers** [grails/grails-core#10278] opened 2016-10-27 13:50 UTC
When running a Grails 3.2.1 app from the generated WAR created by the `package` command, an `IllegalArgumentException` is thrown when attempting to save a domain object.

### Steps to Reproduce

1. Create an app using Grails 3.2.1: `grails create-app helloworld321`
2. Create a domain class: `grails create-domain-class helloworld321.Person`
    ```
package helloworld321

class Person {
        String name
        Integer age
        Date lastVisit
}
``` 
3. Generate controller and views: `grails generate-all helloworld321.Person`
4. Update production datasource DB create mode from `none` to `update` in application.yml
5. Package the WAR: `grails package`
6. Run the app: `java -Dgrails.env=prod -jar build/libs/helloworld321-0.1.war` 
7. Attempt to create a `Person` via: [http://localhost:8080/person/create](http://localhost:8080/person/create)

### Expected Behaviour

The `Person` should be inserted into the database and the show page should be displayed.

A similar app created using Grails 3.2.0 worked as expected

### Actual Behaviour

The message 'An error has occurred' is displayed and the following exception is thrown:

`ERROR org.hibernate.property.access.spi.GetterMethodImpl - HHH000122: IllegalArgumentException in class: helloworld321.Person, getter method of property: id
`

See the full [stacktrace](https://github.com/grails/grails-core/files/555900/grails-3.2.1-stacktrace.txt) for further details.

Note that everything works fine when running the app using `grails prod run-app`.

Also, if the DB already exists and there are `Person` rows in the database, these rows are [listed](http://localhost:8080/person/) but clicking on one of them results in a 404.

### Environment Information

- **Operating System**: OS X El Capitan
- **Grails Version:** 3.2.1
- **JDK Version:** 1.8.0_74
- **Container Version (If Applicable):** N/A (issues occurs when running self-contained WAR)

### Example Application

Failing 3.2.1 version on the app:
- https://github.com/tarpers/helloworld321

Working 3.2.0 version of the app:
- https://github.com/tarpers/helloworld320

**Comment by graemerocher** [comment] 2016-10-27 14:56
Duplicate of https://github.com/grails/grails-core/issues/10244

**Closed by graemerocher** 2016-10-27 14:56 UTC
