### ISSUE TITLE
Grails Promises in controllers behavior inconsistent and broken

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-core#9896] opened 2016-04-26 02:25 UTC
### Steps to Reproduce

The usage of the async response via wrapping a controller method body in a task breaks on redirect and also doesn't reliable work for thrown errors.  Sometimes things work on the first request, but subsequent second or third requests break in unexpected or unreliable ways.

##### Redirects

``` groovy
class SiteController {

    SiteService siteService

    def home() {
        task {
            redirect action: 'index'
        }
    }
}
```

Having a redirect inside a task causes the following stack trace and clicking the link enough causes the site to throw an error.

```
No Session found for current thread. Stacktrace follows:
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at grails.web.mapping.ResponseRedirector.redirectResponse(ResponseRedirector.groovy:101)
	at grails.web.mapping.ResponseRedirector.redirect(ResponseRedirector.groovy:79)
	at grails.artefact.controller.support.ResponseRedirector$Trait$Helper.redirect(ResponseRedirector.groovy:119)
	at grails.artefact.Controller$Trait$Helper.redirect(Controller.groovy:241)
	at grails.async.demo.SiteController$_home_closure2.doCall(SiteController.groovy:20)
	at reactor.rx.Promises$1.accept(Promises.java:122)
	at reactor.rx.Promises$1.accept(Promises.java:119)
	at reactor.core.reactivestreams.PublisherFactory$ForEachBiConsumer.accept(PublisherFactory.java:411)
	at reactor.core.reactivestreams.PublisherFactory$ForEachBiConsumer.accept(PublisherFactory.java:375)
	at reactor.core.reactivestreams.PublisherFactory$SubscriberProxy.request(PublisherFactory.java:318)
	at reactor.rx.Promise.onSubscribe(Promise.java:589)
	at reactor.rx.Stream$SubscribeOn.accept(Stream.java:3128)
	at reactor.rx.Stream$SubscribeOn.onSubscribe(Stream.java:3134)
	at reactor.core.reactivestreams.PublisherFactory$ReactorPublisher.subscribe(PublisherFactory.java:259)
	at reactor.rx.Streams$1.subscribe(Streams.java:183)
	at reactor.rx.Stream$82.subscribe(Stream.java:2925)
	at reactor.rx.Stream$StreamDispatchedSubscribe.accept(Stream.java:3167)
	at reactor.rx.Stream$StreamDispatchedSubscribe.accept(Stream.java:3156)
	at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:160)
	at reactor.core.dispatch.SingleThreadDispatcher$SingleThreadTask.run(SingleThreadDispatcher.java:79)
	at reactor.core.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:156)
	at reactor.core.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:153)
	at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	... 26 common frames omitted
```

<img width="588" alt="screen shot 2016-04-25 at 9 10 18 pm" src="https://cloud.githubusercontent.com/assets/691357/14804556/29154de8-0b2a-11e6-87ec-cc999e243008.png">

##### Thrown Errors

When using the following code, a blank page is show.  This might be intended but there is no logging or other output that an error occurred at INFO level and no error page is shown.  It is unclear of the framework should render the 500 page or if nothing should happen with uncaught exceptions in tasks.

```
class SiteController {

    SiteService siteService

    def error2(){
        task {
            siteService.throwError()
        }
    }
}
```

##### Handled Errors

Running the following code causes odd, unpredictable and slow behavior after the first execution.  Also when using the param causeError=true, the redirect doesn't appear to work correctly as in the previous example.

```
class SiteController {

    SiteService siteService

    def error() {
        task {
            if (params.boolean('causeError')) {
                log.info('I am going to throw an error now.')
                siteService.throwError()
            } else {
                log.info('No error will be thrown')
            }
            return
        }.onError {
            redirect action: 'index'
            return
        }.onComplete {
            render model: siteService.getModel(), view: 'index'
            return
        }
    }
}
```

### Expected Behaviour

* Redirects should complete a promise and send redirect signal consistently
* Errors thrown should cause some behaviour like a 500 when no error handler is defined
* When error handler is defined then any containing code within the error or complete block should be honored (like redirect/render)
* Caught exceptions work when they simply defer to a render as in the caught method in the SiteController example

### Environment Information

Environment: development
App profile: web
App version: 0.1
Grails version: 3.1.5
Groovy version: 2.4.6
JVM version: 1.8.0_72
Reloading active: true

### Example Application

https://github.com/Grails-Plugin-Consortium/grails-async-demo

**Comment by aaloise** [comment] 2016-04-29 15:23
I'm facing somethig similar.

Consider the following many-to-many association:

class Ficha {
    ........
    static belongsTo = Autor
    static hasMany = [autores: Autor]
}

class Autor {
    .........
    static hasMany = [fichas: Ficha]
}

When trying to create an Autor with an async Controller, this is what happens:

HTTP Status 500 - Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/autor/show.gsp:22] Error executing tag <f:display>: failed to lazily initialize a collection of role: fichacatalografica.Autor.fichas, could not initialize proxy - no Session

Already tried to use eager fetch and lazy:false, the error continues to happen. With a regular Controller, everything works fine.

**Comment by aaloise** [comment] 2016-05-04 14:10
It seems to have something to do with the owner side of an association (one-to-many, many-to-many.....) and/or JSON rendering

E.g.: Campus has many courses and a Course belongs to a Campus (bidirectional one-to-many relationship).

In Bootstrap and Controllers, this works:

        Campus.async.findAllByNomeIlike("%man%").onComplete{ results ->
            println results.value //Bootstrap
            render results.value //Controller
        }

        Course.async.findAllByNomeIlike("%tec%").onComplete{ results ->
            println results.value //Bootstrap
            render results.value //Controller
        }

When using JSON rendering in Controllers:

        Campus.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
            render results.value as JSON //doesn't work
        }

        Course.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
            render results.value as JSON //this works
        }

The following happens after an unsuccessful "render as JSON" on the owner side:

                <ul class="errors">
                    <li>An error has occurred</li>
                    <li>Exception: </li>
                    <li>Message: </li>
                    <li>Path: </li>
                </ul>

**Comment by graemerocher** [comment] 2016-05-17 13:32
You cannot currently call any controller methods in `onComplete` or `onError`. The reason is these methods are callbacks to the currently executing thread (the initial request) and thus they reference the original request which was returned to the thread pool and completed when the async request was started.

One possible option is to use `startAsync` explicitly. So something like:

```groovy

def ctx = startAsync()
ctx.start {
     task {
           // do stuff
     }.onError {
           ctx.response.sendRedirect(..)
           ctx.complete()
     }
}
```

But we don't have anything built into the API yes to handle this case

**Comment by aaloise** [comment] 2016-05-17 15:38
Must say that I'm confused...

This is the method I created in the controller:

def getCampus(){
        Campus.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
            render results.value
        }
}

onComplete get's called and it works perfectly!

But if I change from "render results.value" to "render results.value as JSON", doesn't work anymore.

As I explained before, in a similar method of another controller, the "render results.value as JSON" works:

def getCourses(){
    Course.async.findAllByNomeIlike("%$params.q%").onComplete{ results ->
        render results.value as JSON
    }
}

There's a relationship between Campus and Course (one-to-many) where Campus is the owner side.

Conclusion: This particular case doesn't seem to be an issue with Promises per se, but with JSON rendering in a controller of the owner side, using Promises.

**Comment by graemerocher** [comment] 2016-05-17 15:53
@aaloise I was addressing the original error report, you report seems unrelated and a different issue

**Comment by aaloise** [comment] 2016-05-17 15:57
Oh! Ok @graemerocher 
My mistake, I'll raise another issue regarding what I have related

**Comment by aaloise** [comment] 2016-05-17 20:08
I think now it's possible to see the error happening more clearly. I created a method in a Controller with the exact same content of "Async Response Rendering" from http://docs.grails.org/3.1.x/guide/async.html

```
    def stock(String ticker) {
       task {
           ticker = ticker ?: 'GOOG'
           def url = new URL("http://download.finance.yahoo.com/d/quotes.csv?s=${ticker}&f=nsl1op&e=.csv")
           Double price = url.text.split(',')[-1] as Double
           render "ticker: $ticker, price: $price"
       }
    }
```

After a few tries, this error happens:

![capturar](https://cloud.githubusercontent.com/assets/1064972/15337392/7fd5a1ca-1c49-11e6-91cb-fb5d33e71b27.JPG)


Apparently there is in deed something wrong with the use of promises in controllers

**Comment by graemerocher** [comment] 2016-10-28 09:50
Almost certainly a duplicate of #10247 and Reactor 2's broken behaviour

**Closed by graemerocher** 2016-10-28 09:50 UTC
Labels: Web Layer
