### ISSUE TITLE
can't run war package.

### ISSUE THREAD

**Issue by nobusugi246** [grails/grails-core#9807] opened 2016-03-21 03:42 UTC
In my Mac OS X(10.11.3),
```
$ grails --version
| Grails Version: 3.1.4
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_66
$ grails create-app test
$ cd test
$ grails package
$ java -jar build/libs/test-0.1.war
Grails application running at http://localhost:8080 in environment: production
```

When open this by browser 'http://localhost:8080, then
```
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1226)
...
```

Comment out war plugin in build.gradle,
```
// apply plugin:"war"
```

```
$ grails package
$ java -jar build/libs/test-0.1.jar
Grails application running at http://localhost:8080 in environment: production
```

It's OK.

**Comment by jeffbrown** [comment] 2016-03-21 12:07
I think this is a duplicate of #9302.

**Closed** 2016-03-21 12:07 UTC
Labels: Duplicate
