### ISSUE TITLE
Custom Hyphenated URL converter cannot resolve view names

### ISSUE THREAD

**Issue by hamza3202** [grails/grails-core#11117] opened 2018-10-15 12:56 UTC
**Description**
When using Hyphenated URL converter (grails.web.CamelCaseUrlConverter.groovy) instead of camel casing URL converter (grails.web.CamelCaseUrlConverter), views cannot be found. It tries to find a view with hyphenated name instead of camel cased view name in the correct view package.

**Steps To Reproduce:**
Run the project here with branch **hyphenated-URLs**
https://github.com/hamza3202/hamzagorm/tree/hyphenated-URLs
On the main page, there are two links. 
The first one doesn't work because action doesn't specify which view gets rendered.
The second works because action specifies which view to render.

**Details**
The Hyphenated URL Converter was enabled by using grails.web.url.converter property.
According to Jeff's pull request https://github.com/hamza3202/hamzagorm/pull/1 the convention works if URL mapping is explicitly defined in UrlMappings.groovy.

**Environment**
Grails 3.2.2
Java 1.8
Gradle 3.0

**Comment by ilopmar** [comment] 2018-10-16 09:00
@hamza3202 I'm not able to reproduce the issue with Grails 3.3.8. I've created a new application and copy your changes and it works.
I've pushed the changes here: https://github.com/grails-core-issues-forks/grails-issue-11117

**Comment by hamza3202** [comment] 2018-10-16 09:50
@ilopmar I am not able to reproduce it in your repo but https://github.com/jeffbrown/hamzaurls is a sample 3.3.8 repo that @jeffbrown created for this issue...
If you remove the mapping for data privacy in `UrlMappings.groovy` and add the hyphenated configuration in application.yml then it fails...

**Comment by ilopmar** [comment] 2018-10-16 11:52
When you say _"I am not able to reproduce it in your repo"_ you mean that with my repo both links work, right?

**Comment by hamza3202** [comment] 2018-10-16 12:00
Yes, But I am also clarifying that the sample repo created by @jeffbrown has this issue and I am unable to identify the difference in your repo and his.

**Comment by ilopmar** [comment] 2018-10-16 12:09
I see... I'll check Jeff's repo.

**Comment by ilopmar** [comment] 2018-10-18 09:00
@hamza3202 I've done what you describe in your previous comment. I've cloned Jeff's repo, removed the mapping in `UrlMappings.groovy` and added the configuration for hyphenated urls in `application.yml`. After restart the application the link is generated correctly.
I'm afraid that unless you provide a sample application that fails with Grails 3.3.8, we'll close the issue as "not a bug".

**Comment by hamza3202** [comment] 2018-10-18 09:08
@ilopmar Okay. Give me some time to create a pull request to Jeff's repo

**Comment by ilopmar** [comment] 2018-10-18 09:14
This are the changes I've done:
```
diff --git a/grails-app/conf/application.yml b/grails-app/conf/application.yml
index c74cb23..66d23ea 100644
--- a/grails-app/conf/application.yml
+++ b/grails-app/conf/application.yml
@@ -28,6 +28,9 @@ endpoints:
 
 ---
 grails:
+    web:
+        url:
+            converter: hyphenated
     mime:
         disable:
             accept:
```

```
diff --git a/grails-app/controllers/hamzaurls/UrlMappings.groovy b/grails-app/controllers/hamzaurls/UrlMappings.groovy
index ec58108..1e5d80b 100644
--- a/grails-app/controllers/hamzaurls/UrlMappings.groovy
+++ b/grails-app/controllers/hamzaurls/UrlMappings.groovy
@@ -9,7 +9,7 @@ class UrlMappings {
             }
         }
 
-        '/data-privacy'(controller: 'publicInfo', action: 'dataPrivacy')
+//        '/data-privacy'(controller: 'publicInfo', action: 'dataPrivacy')
 
         "/"(view:"/index")
         "500"(view:'/error')
```

**Comment by hamza3202** [comment] 2018-10-18 10:49
@ilopmar Sorry! It seems like the issue only happens if you remove the URL mapping while the application is running... So I guess you can close this issue since it can be fixed by just restarting the app?

**Closed** 2018-10-18 10:54 UTC
Labels: Awaiting Feedback, Cannot Reproduce
