### ISSUE TITLE
can not create-app using grails 2.5.5

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10011] opened 2016-06-25 09:18 UTC
@graemerocher 
- Steps to reproduce 
  -- Install grails 2.5.5 using sdkman
  -- run command `grails create-app` (or just start grails console using `> grails`)
- Stacktrace

```
        module not found: org.codehaus.groovy#groovy-all;2.4.4
    ==== grailsPlugins: tried
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/work/9ci/lib/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/ivy-2.4.4.xml
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.4.jar
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/bundles/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.pom
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.xml
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.pom
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.jar
        ::::::::::::::::::::::::::::::::::::::::::::::
        ::          UNRESOLVED DEPENDENCIES         ::
        ::::::::::::::::::::::::::::::::::::::::::::::
        :: org.codehaus.groovy#groovy-all;2.4.4: not found
        ::::::::::::::::::::::::::::::::::::::::::::::

| Error Resolve error obtaining dependencies: Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.codehaus.groovy:groovy-all:2.4.4

 (Use --stacktrace to see the full trace)
:: problems summary ::
:::: WARNINGS
        module not found: org.codehaus.groovy#groovy-all;2.4.4
    ==== grailsPlugins: tried
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/work/9ci/lib/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/ivy-2.4.4.xml
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.4.jar
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/bundles/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.pom
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.xml
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.pom
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.jar
        ::::::::::::::::::::::::::::::::::::::::::::::
        ::          UNRESOLVED DEPENDENCIES         ::
        ::::::::::::::::::::::::::::::::::::::::::::::
        :: org.codehaus.groovy#groovy-all;2.4.4: not found
        ::::::::::::::::::::::::::::::::::::::::::::::

| Error Resolve error obtaining dependencies: Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.codehaus.groovy:groovy-all:2.4.4

 (Use --stacktrace to see the full trace)
:: problems summary ::
:::: WARNINGS
        module not found: org.codehaus.groovy#groovy-all;2.4.4
    ==== grailsPlugins: tried
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/work/9ci/lib/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/ivy-2.4.4.xml
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.4.jar
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/bundles/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.pom
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.xml
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.jar
    ==== grailsHome: tried
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.pom
      -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
      /Users/sudhir/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.jar
        ::::::::::::::::::::::::::::::::::::::::::::::
        ::          UNRESOLVED DEPENDENCIES         ::
        ::::::::::::::::::::::::::::::::::::::::::::::
        :: org.codehaus.groovy#groovy-all;2.4.4: not found
        ::::::::::::::::::::::::::::::::::::::::::::::

| Error Resolve error obtaining dependencies: Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.codehaus.groovy:groovy-all:2.4.4

 (Use --stacktrace to see the full trace)
| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.codehaus.groovy:groovy-all:2.4.4
```
- **Operating System**:  OSX EI Capitan
- **Grails Version:** 2.5.5
- **JDK Version:** 1.7.0_79

**Comment by snimavat** [comment] 2016-06-25 09:21
I see that i have  /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.5.jar available instead of  /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.4.jar

**Comment by graemerocher** [comment] 2016-06-25 09:22
I can't reproduce this personally

**Comment by snimavat** [comment] 2016-06-25 09:24
i just installed a fresh 2.5.5 copy using sdk man, tried to create a sample app, and it failed with above error, also i dont have groovy-all 2.4.4 jar at the location it is looking for (inside grails-home/lib/xxx)

**Comment by snimavat** [comment] 2016-06-25 09:26
Ok, so i downloaded and manually put the 2.4.4 jar at the location it was expecting and it worked.

**Comment by snimavat** [comment] 2016-06-25 09:39
Just a note: before i did create-app - i did grails compile (after changing grails.version to 2.5.5 in application.properties) on one of the old project which was on grails 2.4.4. if that makes any difference.

**Comment by jeffbrown** [comment] 2016-06-27 15:29
I also cannot reproduce this problem.

**Comment by jeffbrown** [comment] 2016-06-27 15:31
Grails 2.5.5 uses Groovy 2.4.5.  The errors above indicate that Grails is looking for Groovy 2.4.4.  It looks like your environment somehow got confused.

**Comment by snimavat** [comment] 2016-06-27 15:31
@jeffbrown definitely i had the issue, i dont know how come i had no groovy 2.4.4 in   /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars .. (instead i had groovy 2.4.5 jar there)

I just manually put the groovy 2.4.4 jar there, and i am good. if you want you can close the issue

**Comment by jeffbrown** [comment] 2016-06-27 15:33
> i dont know how come i had no groovy 2.4.4 in /Users/sudhir/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars .. (instead i had groovy 2.4.5 jar there)

That is expected:

```
~ $ ls ~/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars
groovy-all-2.4.5-javadoc.jar	groovy-all-2.4.5-sources.jar	groovy-all-2.4.5.jar
~ $ ls ~/.sdkman/candidates/grails/2.5.4/lib/org.codehaus.groovy/groovy-all/jars
groovy-all-2.4.4-javadoc.jar	groovy-all-2.4.4-sources.jar	groovy-all-2.4.4.jar
```

**Comment by snimavat** [comment] 2016-06-27 15:34
Ah okay, so from logs, you can see grails was looking for groovy 2.4.4 - its a freshly installed grails using sdkman

**Comment by jeffbrown** [comment] 2016-06-27 15:35
> Ah okay, so from logs, you can see grails was looking for groovy 2.4.4

Yes, I see that.  I don't know why that is though and can't reproduce it.

**Comment by jeffbrown** [comment] 2016-06-27 15:37
Can you try this?

```
rm -rf ~/.sdkman/candidates/grails/2.5.5/
sdk install grails 2.5.5
sdk use grails 2.5.5
mkdir ~/someNewDir
cd ~/someNewDir
grails create-app demo
```

And let us know if the problem persists?

**Comment by snimavat** [comment] 2016-06-27 15:38
sue

**Comment by jeffbrown** [comment] 2016-06-27 15:47
Thanks for the feedback.

**Comment by katherinessmith** [comment] 2016-06-30 14:37
I've run into a similar problem installing grails 2.5.5 via sdkman.

```
sdk install groovy 2.4.4
sdk use groovy 2.4.4
sdk install grails 2.5.5
sdk use grails 2.5.5
grails create-app test
```
Same errors as snimavat

```
		module not found: org.codehaus.groovy#groovy-all;2.4.4
	==== grailsPlugins: tried
	  -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
	  /Users/ksmith/Repos/lib/groovy-all-2.4.4.jar
	==== grailsHome: tried
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/ivy-2.4.4.xml
	  -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.4.jar
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/lib/org.codehaus.groovy/groovy-all/bundles/groovy-all-2.4.4.jar
	==== grailsHome: tried
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.pom
	  -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/dist/groovy-all-2.4.4.jar
	==== grailsHome: tried
	  /Users/ksmith/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.xml
	  -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
	  /Users/ksmith/.grails/2.5.5/cached-installed-plugins/groovy-all-2.4.4.jar
	==== grailsHome: tried
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.pom
	  -- artifact org.codehaus.groovy#groovy-all;2.4.4!groovy-all.jar:
	  /Users/ksmith/.sdkman/candidates/grails/2.5.5/plugins/groovy-all-2.4.4.jar
		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: org.codehaus.groovy#groovy-all;2.4.4: not found
		::::::::::::::::::::::::::::::::::::::::::::::

| Error Resolve error obtaining dependencies: Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.codehaus.groovy:groovy-all:2.4.4

 (Use --stacktrace to see the full trace)
```

Removing the directory or running sdk rm grails 2.5.5 and trying again doesn't fix the problem.

`rm -rf ~/.sdkman/candidates/grails/2.5.5/`
repeat above
same errors

```
sdk rm grails 2.5.5
sdk rm groovy 2.4.4
```
repeat above
same errors

Everything works fine with grails 2.5.4.

I also have other versions of grails/groovy for other applications I work on.

Same OS/versions as snimavat:
    Operating System: OSX EI Capitan
    Grails Version: 2.5.5
    JDK Version: 1.7.0_79

A coworker can reproduce with Yosemite.

**Comment by katherinessmith** [comment] 2016-06-30 14:43
Third time's the charm, and as soon as I posted this, it started working.

The only change in between was removing grails 2.5.5, switching to 2.5.4, trying again, switching back to 2.5.5 and it worked, though I tried the same thing yesterday with no luck.

**Comment by olavgg** [comment] 2016-07-05 11:49
I also had the same problem. To work around this I did as @katherinessmith said and created a new app with Grails 2.5.4.

If you want to reproduce this I guess a new Linux installation with openjdk should reproduce this.

**Comment by ZacharyKlein** [comment] 2016-07-13 18:41
I can reproduce this issue on OS X El Capitan, fresh install of 2.5.5 from sdkman.

**Comment by gschueler** [comment] 2016-07-14 18:22
same problem installing with sdkman

**Comment by jeffbrown** [comment] 2016-07-14 18:24
> same problem installing with sdkman

I doubt sdkman has anything to do with it.

**Comment by snimavat** [comment] 2016-07-15 10:52
Was setting up a new linux, and same problem.. also removing and reinstalling doesnt help

**Comment by gschueler** [comment] 2016-07-15 15:58
to follow up: using sdkman to install 2.5.4 first, and then 2.5.5 worked as suggested by @katherinessmith

**Comment by marvinthepa** [comment] 2016-09-02 10:56
I have the same problem with an existing app, `org.grails:grails-bootstrap:2.5.` depending on `org.codehaus.groovy:groovy-all:2.4.4` in grails 2.5.5. Grails was not installed using sdkman, but downloaded manually.
I get the same bogus dependency when using the grails wrapper when installed using grails 2.5.5.

**Comment by topr** [comment] 2016-09-07 00:30
I'm facing the same issue. Although I haven't got to the bottom of it, I was able to figure out why this odd sequence with using version 2.5.4 and just then 2.5.5 works.

1. Grails 2.5.5 still pulls groovy-all 2.4.4. This is at least what `dependency-report` is showing.
2. When app is created with grails installed in the system (whether it is via _sdkman_ or not) then grails resolves dependencies by default with **ivy**.
3. When wrapper is used it usually happens from within an existing app, in which by default value in generated _BuildConfig.groovy_ dependencies are resolved with **maven**.
4. Speaking shortly to reproduce: delete _groovy-all_ from ivy cache and ensure you run `create-app` with _ivy_ as dependency resolver.

**Comment by bernji** [comment] 2016-09-09 12:56
is there any fix for this? this is annoying!

**Comment by rpalcolea** [comment] 2016-09-09 13:06
Can this be related to https://github.com/grails/grails-core/blob/2.5.x/grails-bootstrap/src/main/groovy/org/codehaus/groovy/grails/resolve/GrailsCoreDependencies.java#L34 ?

**Comment by jeffbrown** [comment] 2016-09-09 13:29
@rpalcolea Yes.  See my comment at the bottom of https://github.com/grails/grails-core/commit/0ec157df1ec607ef7da58a751979f28d9a090cf4

**Comment by rpalcolea** [comment] 2016-09-09 13:30
Oops! didn't see that :( my mistake

**Comment by astecker** [comment] 2016-09-12 13:32
Same Problem here using manually downloaded zip under Windows 7 64bit / Oracle JDK 8.

**Comment by snimavat** [comment] 2016-09-28 11:34
Is it going to be fixed in next 2.5.x ?

**Comment by graemerocher** [comment] 2016-09-28 13:30
if there is another 2.x release yes

**Comment by snimavat** [comment] 2016-10-16 06:59
Can we have it fixed plz and a 2.5.6 release.. this is really painful to not to be able to create-app or plugins

**Comment by ken-roberts** [comment] 2016-11-03 15:01
+1 for 2.5.6 release. We shouldn't have to dirty up our grails installation because of a bug.

**Comment by larsauswsw** [comment] 2016-11-30 10:54
grails.project.dependency.resolver = "maven" in BuildConfig.groovy fixed it for me.

**Comment by wehe64** [comment] 2017-02-03 11:36
still the same over here - also using sdkman.
and also, first installing grails 2.5.4 and create-app with that did help...
kinda weird and quite ugly, but this page helped a lot.
+1 for a 2.5.6 or whatever the fix would be
thanks everyone! weHe

**Comment by mdaloia** [comment] 2017-02-16 01:39
As a workaround, you can define an environment variable specifying the Groovy version:

```
export CI_GROOVY_VERSION=2.4.5
```

**Comment by ciscoo** [comment] 2017-03-03 17:18
Same issue on Windows and macOS, fresh install of 2.5.5 and `grails create-app` fails with the same stacktrace above.

**Comment by jpalmer1026** [comment] 2017-03-09 22:37
Same issue here as well.

**Comment by snimavat** [comment] 2017-03-10 11:05
Create a brand new docker container for 2.5.5 and trying to run grails console would fail with same error too.

**Comment by pguerin** [comment] 2017-03-13 17:04
+1 for 2.5.6 ! Please.

**Comment by ColinHarrington** [comment] 2017-03-13 20:44
It does look like an old dependency declaration as [Jeff noted](https://github.com/grails/grails-core/commit/0ec157df1ec607ef7da58a751979f28d9a090cf4#commitcomment-18026070).  There are several workarounds:
* install and use grails 2.5.4 then switch back ([as @katherinessmith said](https://github.com/grails/grails-core/issues/10011#issuecomment-229679855))
* `export CI_GROOVY_VERSION=2.4.5`: ([thanks @mdaloia](https://github.com/grails/grails-core/issues/10011#issuecomment-280202448))

FYI, I can reproduce this in docker: https://github.com/ColinHarrington/grails-10011

**Closed** 2017-03-21 11:38 UTC
Labels: v2.x

**Comment by snimavat** [comment] 2017-03-23 08:48
Thanks for the release @graemerocher

**Comment by BrownsMN** [comment] 2021-03-31 09:54
1. Install Grails 2.5.5 and Get Grails 2.4.4
2. Copy/transfer groovy-all from Grails 2.4.4 to Grails 2.5.5 [ jar dependency match]
