### ISSUE TITLE
grails-3.2.8 + gorm-6.1 - domain class unit spec fails compilation error

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#10563] opened 2017-03-31 12:33 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a simple unit test for a domain `Dummy` like this:

```groovy
@TestFor(Dummy)
class DummySpec extends Specification {

    def "noop"(){
        when:
        true

        then:
        true
    }

}
```

2. run the test as unit test with `gradlew test` or from within intellij idea

### Expected Behaviour

test passes

### Actual Behaviour

`gradlew test`:
```
startup failed:
General error during canonicalization: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
	at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1101)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1079)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:537)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:174)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:56)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:73)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:64)
	at org.gradle.process.internal.daemon.WorkerDaemonServer.execute(WorkerDaemonServer.java:28)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerDaemonServer.execute(AbstractDaemonCompiler.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:392)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:275)
	at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:370)
	at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:433)
	at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:425)
	at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:198)
	at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:184)
	at org.grails.compiler.injection.test.TestForTransformation.weaveMixinClass(TestForTransformation.java:404)
	at org.grails.compiler.injection.test.TestForTransformation.weaveMock(TestForTransformation.java:280)
	at org.grails.compiler.injection.test.TestForTransformation.testFor(TestForTransformation.java:233)
	at org.grails.compiler.injection.test.TestForTransformation.handleTestForAnnotation(TestForTransformation.java:131)
	at org.grails.compiler.injection.test.TestForTransformation.visit(TestForTransformation.java:123)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:134)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:178)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	... 29 more
General error during canonicalization: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
	at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1101)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1079)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:537)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:174)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:56)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:73)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:64)
	at org.gradle.process.internal.daemon.WorkerDaemonServer.execute(WorkerDaemonServer.java:28)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerDaemonServer.execute(AbstractDaemonCompiler.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:392)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:275)
	at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:370)
	at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:433)
	at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:425)
	at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:198)
	at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:184)
	at org.grails.compiler.injection.test.TestForTransformation.weaveMixinClass(TestForTransformation.java:404)
	at org.grails.compiler.injection.test.TestForTransformation.weaveMock(TestForTransformation.java:280)
	at org.grails.compiler.injection.test.TestForTransformation.testFor(TestForTransformation.java:233)
	at org.grails.compiler.injection.test.TestForTransformation.handleTestForAnnotation(TestForTransformation.java:131)
	at org.grails.compiler.injection.test.TestForTransformation.visit(TestForTransformation.java:123)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:134)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:178)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	... 29 more
2 errors
:compileTestGroovy FAILED
```

intellij run test:
```
Error:Groovyc: While compiling tests of myapp_test: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
	at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1101)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1079)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.jetbrains.groovy.compiler.rt.GroovyCompilerWrapper.compile(GroovyCompilerWrapper.java:62)
	at org.jetbrains.groovy.compiler.rt.DependentGroovycRunner.runGroovyc(DependentGroovycRunner.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.groovy.compiler.rt.GroovycRunner.intMain2(GroovycRunner.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc.runGroovycInThisProcess(InProcessGroovyc.java:156)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc.access$000(InProcessGroovyc.java:51)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc$1.call(InProcessGroovyc.java:85)
	at org.jetbrains.jps.incremental.groovy.InProcessGroovyc$1.call(InProcessGroovyc.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:392)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:275)
	at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:370)
	at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:433)
	at org.codehaus.groovy.ast.ClassNode.getAllInterfaces(ClassNode.java:425)
	at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:198)
	at org.grails.compiler.injection.test.TestMixinTransformation.weaveMixinsIntoClass(TestMixinTransformation.java:184)
	at org.grails.compiler.injection.test.TestForTransformation.weaveMixinClass(TestForTransformation.java:404)
	at org.grails.compiler.injection.test.TestForTransformation.weaveMock(TestForTransformation.java:280)
	at org.grails.compiler.injection.test.TestForTransformation.testFor(TestForTransformation.java:233)
	at org.grails.compiler.injection.test.TestForTransformation.handleTestForAnnotation(TestForTransformation.java:131)
	at org.grails.compiler.injection.test.TestForTransformation.visit(TestForTransformation.java:123)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:134)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:178)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	... 22 more
```

### Environment Information

- **Operating System**: win10 x64
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8
- **Container Version (If Applicable):** n/a

### Example Application

- n/a

**Comment by jeffbrown** [comment] 2017-03-31 13:50
I think this is a duplicate of #10549

**Closed by jeffbrown** 2017-03-31 13:50 UTC

**Comment by zyro23** [comment] 2017-03-31 14:08
fix confirmed. adding `testCompile "org.grails:grails-datastore-gorm-test:$gormVersion"` does the trick. thanks!
