### ISSUE TITLE
Default service transactional status

### ISSUE THREAD

**Issue by Schlogen** [grails/grails-core#9272] opened 2015-09-21 15:07 UTC
Currently services are created with the `@Transactional` annotation that adds transactional behavior. If the annotation is removed, the service is still transactional by default using the spring annotation. I am proposing to deprecate/remove the static `transactional` variable and remove the default behavior of making all services transactional. The transactional state of the service would be based on whether or not the annotation exists.

**Comment by burtbeckwith** [comment] 2015-09-21 19:45
This makes sense in isolation, but it's been that way since before 1.0, so it's a pretty big change. Making this change, coupled with adding the Transactional annotation in generated controllers, is the wrong direction.

The template for a new service uses the Grails Transactional annotation, so only users who create services manually run the risk of unintentional incurring transaction overhead where it's not needed.

Note that the dataSource bean is actually two wrappers around the real datasource - the newer one is a LazyConnectionDataSourceProxy that doesn't get a real connection or configure transaction settings until real database access happens. So a method that does no database access or one that might but returns early before doing so won't incur the transaction overhead.

**Comment by Schlogen** [comment] 2015-09-21 19:56
@burtbeckwith I think its unintuitive to remove the `@Transactional` annotation, and the service still be transactional.

The transaction overhead is not the only issue. If the spring way is done, it uses a proxy which can cause other headaches.

**Comment by jeffbrown** [comment] 2015-09-21 20:14
What about something like this:

* Deprecate the `transactional` property in the next 3.0.x release, leave the behavior alone but log a warning where it is used
* In 3.1 yank support for the `transactional` property
* In 3.1 make the default be that if a service is not annotated, it is not transactional
* Document the changes in the 3.1 release notes and upgrade notes

Thoughts?

**Comment by burtbeckwith** [comment] 2015-09-21 20:19
@Schlogen The problem with Spring's annotation triggering the creation of a proxy is that calling an annotated method from one with different annotation settings will ignore the different settings. But that will only occur when explicitly using annotations.

**Comment by Schlogen** [comment] 2015-09-21 20:38
@jeffbrown Looks good to me

**Comment by jeffbrown** [comment] 2015-09-21 20:42
@graemerocher and @burtbeckwith What say ye?

**Comment by graemerocher** [comment] 2015-09-22 06:42
@jeffbrown I would go one step further and fail compilation of `transactional` is specified in 3.1, this will give the user early warning so they won't have to go digging for the upgrade docs

**Comment by graemerocher** [comment] 2015-12-02 07:55
I think I would prefer as a fix for this to completely remove support for Spring's proxying in favour of the AST transform `grails.transaction.Transactional`. By keeping the proxying we degrade startup time, add complexity and maintain the quirks in behaviour of Spring proxies when the transform is superior.

**Comment by hakanernam** [comment] 2015-12-02 09:14
+1 for simplicity and de-duplication of functionality. As a user I personally get lost/confused/anxious and stressed when there are two similar ways of doing things. 

+1 for startup time. It is painfully slow with the new "inline" plugin/module system we have.

Also would it be possible to make a M3 milestone with the really essential stuff some of which already fixed and postpone others such as this one, important as it is, for a possible M4? I have been watching the repo like I watch a basketball game score lately.

**Comment by graemerocher** [comment] 2015-12-02 09:20
@hakanernam M3 will be released in the next couple of days

**Comment by hakanernam** [comment] 2015-12-02 09:31
@graemerocher Thanks. Best news I had this week. I have been telling some customers to wait for a while for any request that is not a bug fix.

**Closed** 2015-12-09 08:56 UTC
