### ISSUE TITLE
[3.1.4] UTF characters broken if defined in plugin's messages.properties

### ISSUE THREAD

**Issue by droggo** [grails/grails-core#9821] opened 2016-03-25 14:46 UTC
If we define messages like 
```
message.with.unicode.character=Test ą Ć
message.with.unicode.code=Test \u0105 \u0106
```
In application, both will work fine when used on GSP. But when we define the same message in a plugin, result is `Test Ä Ä`

![image](https://cloud.githubusercontent.com/assets/3313302/14045871/ed8a99c6-f29d-11e5-9d4c-568e8e1adc58.png)

I have created an app with inline plugin to show this. If plugin is compiled and installed from dependency management issue stays the same. It doesn't matter if plugin is compiled on Linux or Windows and if application is run on Linux/Windows

Sample project: https://github.com/droggo/UnicodeFromPlugin
Can be started using `UnicodeFromPlugin/UnicodeApp/gradle bootRun` and index page will display messages

**Comment by graemerocher** [comment] 2016-04-06 08:36
Can't reproduce this personally with the sample app provided. Might be you need to pass `java.encoding` to your JVM?

**Comment by droggo** [comment] 2016-04-08 05:06
Adding `java.encoding` does not help. I tried with `gradle clean bootRun -Dfile.encoding=UTF8` and adding
```
bootRun { 
    systemProperty 'file.encoding', 'UTF-8'
}
```
to `build.gradle`.

Is it possible that Grails is loading plugin i18n properties with default OS encoding based on localization - no matter what `java.encoding` is? And differently to application i18n properties? I will try to find this in Grails code, if you can point me to class in which I could look for it it may be helpful.

I also tried saving file again - explicitly with UTF-8 encoding but this did not change anything. In plugin jar distribution file is also fine, it's just copy of the original.

Both options for `file.encoding` change system property `System.getProperty('file.encoding')` which can be see on screnshots below:

Before change:
![image](https://cloud.githubusercontent.com/assets/3313302/14374543/46e769b8-fd57-11e5-8059-86b63c94dd35.png)

After change:
![image](https://cloud.githubusercontent.com/assets/3313302/14374551/732edc7c-fd57-11e5-899c-aff2fdf3e69c.png)

**Comment by droggo** [comment] 2016-04-08 05:25
Few more observations:

If I print messages in the console using printline I get:
```
PLUGIN: Test ─? ─?
APP: Test ╣ Ă
```
It seems that something different is returned by `message()` method for the same characters based if those are defined in plugin or application.

If I change option `grails.views.gsp.encoding` to `windows-1250` view will look like:
![image](https://cloud.githubusercontent.com/assets/3313302/14374792/6b18e908-fd5a-11e5-9570-f16ffac0ef1d.png)
So now also App unicode is broken (as expected) but with different 'characters'

**Comment by andersb** [comment] 2016-05-24 11:39
I'm experiencing similar behavior on Windows 10 and Grails 3.1.7.
The messages in the app works as expected but messages read from a plugin will have incorrect encoding.
The difference is that it is actually working correctly on Linux.
The Windows machine have English as language but location set to Sweden.
The Linux is en_GB.UTF-8 as default.

During debugging I can see that the values that are in the PropertiesHolder are incorrect which makes me think that droggo has a point with "Is it possible that Grails is loading plugin i18n properties with default OS encoding based on localization - no matter what java.encoding is?"

**Comment by andersb** [comment] 2016-05-24 12:42
I found something that might give some clues.

In BinaryGrailsPlugin, the resources are loaded in the following method

```
private void loadFromResources(Properties properties, Resource[] resources) throws IOException {
	for (Resource messageResource : resources) {
		InputStream inputStream = messageResource.getInputStream();
		try {
			properties.load(inputStream);
		} finally {
			try {
				inputStream.close();
			} catch (IOException e) {
				// ignore
			}
		}
	}
}
```

the `properties.load(inputStream);` will assume ISO-8859-1 or Unicode.

However, what doesn't make sense is why it works on Linux for me.

**Comment by graemerocher** [comment] 2016-05-24 13:24
Thanks for investigating and the feedback, we will get this straightened out.

**Comment by graemerocher** [comment] 2016-05-26 11:47
I committed a fix, however since I cannot reproduce I will leave it to you guys to let me know if the issue is resolved for you.

**Closed by graemerocher** 2016-05-26 11:47 UTC
Labels: Blocker, in progress

**Comment by andersb** [comment] 2016-05-26 15:30
Okey so I got things working I also found the reason why things worked on Linux before.

First, passing in -Dfile.encoding=UTF-8 will make the loading of properties work.

Second, the reason it worked on linux was because during the build process, gradle converted properties files from UTF-8 to Unicode, which in turn worked with properties.load() from the start.

One could wonder why the build process is different between windows and linux. Guess that would be a question for a different forum :)

**Comment by droggo** [comment] 2016-05-26 19:39
Yeap, changing to `3.1.8-BUILD-SNAPSHOT` and running with `grails bootRun -Dfile.encoding=UTF-8` resolves the issue. I cannot check production deployment yet because of build errors caused by new version

**Comment by graemerocher** [comment] 2016-05-26 20:04
What build errors?

**Comment by droggo** [comment] 2016-05-26 20:10
if we have `application.groovy` with any `import` from plugin or Grails class, it will not compile with errors like ` script14642930441691380702520.groovy: 1: unable to resolve class grails.databinding.BindUsing`
this is fine in 3.1.7 but is broken with 3.1.8.BUILD.SNAPSHOT. I can create separate issue if needed, please let me know. Also wrote it on Slack

**Comment by droggo** [comment] 2016-05-26 20:14
And this happens when we call `gradle assemble` not during `bootRun`

**Comment by graemerocher** [comment] 2016-05-27 06:58
That doesn't surprise since `application.groovy` has to be able to be read before compilation and without the classpath present, the fact that it worked was by accident. We have a long term issue to add support for reading `application.groovy` settings for the CLI at which point you will certainly no longer be able to import classes. Anyway for the moment I will roll back the change causing this for 3.1.x but consider your use case deprecated for future releases.

**Comment by droggo** [comment] 2016-05-27 07:02
OK, thanks. I will skip creating issue then

**Comment by graemerocher** [comment] 2016-05-27 07:19
@droggo I was able to make it take into plugins https://github.com/grails/grails-core/commit/c9395593f0afe63b3e411c3530a2d21e49bc9f63

application classes can't be referenced though

**Comment by droggo** [comment] 2016-05-27 08:35
@graemerocher Great, thank you! Actually plugins are completely enough for our use cases and after your fix we have not more issues

I can also confirm that fix for UTF issue works on production deployment on tomcat. Tomcat also needs `-Dfile.encoding=UTF-8` option set (for example using `setenv.bat/sh` script)
