### ISSUE TITLE
Cannot resolve GSON views from plugin

### ISSUE THREAD

**Issue by pawelhalasa** [grails/grails-core#10104] opened 2016-08-16 15:49 UTC
My app is unable to resolve any GSON view from inline plugin, while GSON files from the app work fine.

### Steps to Reproduce

1. Create a new app and plugin supporting JSON views

   ```
grails create-app App --profile=rest-api
grails create-plugin Plugin --profile=rest-api-plugin
```
2. Link the app with plugin "inline" - as described in [Grails guide](http://docs.grails.org/latest/guide/plugins.html) (section "Inline Plugins in Grails 3.0")
3. Create 2 identical sample GSON files in the following locations:
  * App/grails-app/views/test1.gson
  * Plugin/grails-app/views/test2.gson
   ```
json.message {
        hello "world"
}
```
4. Create UrlMappings file in the plugin

   ```
static mappings = {
        "/test1" (view: '/test1')
        "/test2" (view: '/test2')
}
```
5. Run the app

### Expected Behaviour

Both views should be loaded correctly
```
http://localhost:8080/test1
http://localhost:8080/test2
```

### Actual Behaviour

Test1 view (from the file placed directly in the app) is displayed correctly, but test2 view (placed in the plugin) is not resolved

```
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [g
railsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/test2' in servlet with name 'g
railsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name '/test2' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1237)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

### Environment Information

- **Operating System**: Windows 7
- **Grails Version:** 3.2.0.M2 & 3.1.10
- **JDK Version:** 1.8.0_91

### Example Application

[sample_app.zip](https://github.com/grails/grails-core/files/420538/sample_app.zip)

**Comment by droggo** [comment] 2016-08-16 15:59
Isn't this duplicate of: https://github.com/grails/grails-views/issues/26 ?

**Comment by pawelhalasa** [comment] 2016-08-16 16:29
It seems very similar, except that in my URL mappings I don't use controllers at all, just directly point to the views. Besides, either the [suggested solution](http://views.grails.org/latest/#_customizing_the_compile_task) did not work or I applied it incorrectly.

How to verify if there is mismatch between the directory name and plugin name? In my case the name is just "Plugin", so I guess this root cause may be not even applicable.

**Comment by pawelhalasa** [comment] 2016-08-23 08:27
Issue may be possibly related to #10110 and #10047. It works fine without `-Dgrails.run.active`

**Comment by jameskleeh** [comment] 2016-08-27 05:21
Fixed by https://github.com/grails/grails-views/commit/a74dcded0b3038a904d88e3cc136f2f3fbf6ca5e

**Closed by jameskleeh** 2016-08-27 05:21 UTC
