### ISSUE TITLE
Grails war on Tomcat 7 results in 404

### ISSUE THREAD

**Issue by costerutilo** [grails/grails-core#9676] opened 2016-02-10 19:27 UTC
Creating a simple app with grails 3.1.1 result in 404 error on Tomcat 7.

Server version: Apache Tomcat/7.0. on Windows
Grails Version: 3.1.1
Groovy Version: 2.4.5
JVM Version: 1.7.0_80

1) I created a simple app with:
grails create-app test

2) I changed in build.gradle:

provided "org.springframework.boot:spring-boot-starter-tomcat"
3) grails run-app 
works fine, http://localhost:8080/ shows the grails home page

4) I created a war
grails war

5) I deploy the war on tomcat7:
In Tomcat Logs there are no errors an the tomcat manager shows the app:
/test-0.1
But if I call the page
http://localhost:8080/test-0.1
it gives a 404 error.

**Comment by AlexKovynev** [comment] 2016-02-11 07:16
I confirm. The log is without errors, just does not start application.

**Comment by AlexKovynev** [comment] 2016-02-11 09:02
I think this is not tomcat problem or not only tomcat, on jdk7 and tomcat8 problem the same.
Change jdk to 8 and all ok.

**Comment by BradBrown** [comment] 2016-02-13 04:09
If it helps, I was unable to replicate this on the 64-bit JVM 1.7.0_79 or _80 on Windows 10 and Tomcat 7.0.67.  http://localhost:8080/test-0.1 renders fine.

**Comment by costerutilo** [comment] 2016-02-13 09:18
Tank you BradBrown for testing.
It's strange, I have exactly the same settings:
- Windows 10 64 bit
- jdk1.7.0_79
- Apache Tomcat 7.0.67 Server
- Grails 3.1.1
- Groovy 2.4.5

http://localhost:8080/test-0.1 gives 404 error.

**Comment by arjangch** [comment] 2016-02-18 14:25
Did you use provided in build.gradle?

- provided

 "org.springframework.boot:spring-boot-starter-tomcat"

**Comment by arjangch** [comment] 2016-02-18 15:41
Also see this related ticket 

- https://github.com/grails/grails-core/issues/9719

**Comment by graemerocher** [comment] 2016-02-22 14:04
Tested again on Windows 7, JDK 7 and Tomcat 7.0.68 and unable to reproduce

**Comment by matrei** [comment] 2016-02-22 14:20
I can confirm this issue on:
Ubuntu 14.04 64-bit Server
Tomcat 7 and 8
jdk1.7.0_80
Grails 3.1.1

For Tomcat 7 I did change "org.springframework.boot:spring-boot-starter-tomcat" to provided.

After downgrading to Grails 3.0.14 it worked.

**Comment by bronoman** [comment] 2016-03-05 05:49
I can also confirm the issue on:

**Apache Tomcat 7.0.62** on Jelastic 4.2 PaaS [Env1]
**Grails Version: 3.1.3**
JVM Version: 1.7.

and

**Apache Tomcat 8.0.9** on Jelastic 4.2 PaaS
**Grails Version: 3.1.3**
JVM Version: 1.8

Jelastic seems to run CentOS on Intel.

On Windows 10, using runapp and it works beautifully.

What is weird on the PaaS platform (which works fine with Grails 2.5.1) is, that Tomcat does not seem to start the grails application as there is no indication of database activity or any log entries written from bootstrap. I can run another simple war on the same Tomcat node to prove that Tomcat itself is running. This is also indicated by the log catalina.out for [Env1]:

_Mar 05, 2016 5:38:05 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Mar 05, 2016 5:38:13 AM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [7,898] milliseconds.
Mar 05, 2016 5:38:13 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /opt/tomcat/webapps/brx-1.0.1.war has finished in 17,546 ms
Mar 05, 2016 5:38:13 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /opt/tomcat/webapps/console.war
Mar 05, 2016 5:38:14 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Mar 05, 2016 5:38:14 AM com.managecat.utils.common.SecurityUtil <init>
INFO: Setting up a SSLSocketFactory
Mar 05, 2016 5:38:15 AM com.managecat.utils.common.SecurityUtil <init>
INFO: Setting up a SSLSocketFactory has completed succesfully!
Mar 05, 2016 5:38:15 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /opt/tomcat/webapps/console.war has finished in 2,677 ms
Mar 05, 2016 5:38:15 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Mar 05, 2016 5:38:15 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Mar 05, 2016 5:38:15 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 20363 ms_

From this, you would think, everything is fine. Yet, **I get a 404** for the grails application...

**Comment by bronoman** [comment] 2016-03-08 17:00
I can now confirm observations from @matrei: the combination
Apache Tomcat 8.0.9 on Jelastic 4.2 PaaS
Grails Version: 3.0.14 
JVM Version: 1.8
works perfectly.
@graemerocher: can you please re-test this behaviour in a linux environment?

**Comment by bronoman** [comment] 2016-03-08 17:05
I can now confirm observations from @matrei: the combination
Apache Tomcat 8.0.9 on Jelastic 4.2 PaaS
Grails Version: 3.0.14 
JVM Version: 1.8
works perfectly.
@costerutilo: what operating system are you using?
@graemerocher: could you please re-test this in a linux environment?

**Comment by arjangch** [comment] 2016-03-08 18:54
This works for me. 

> Windows Apache Tomcat Version 7.0.67
> Groovy Version: 2.4.5
> JVM Version: 1.8.0_72
> Grails Version: 3.1.1
> War Build Date: Mon Feb 29 14:18:13 EST 2016

**Comment by costerutilo** [comment] 2016-03-08 21:58
@bronoman:
Windows 10 64 bit
jdk1.7.0_79
Apache Tomcat 7.0.67 Server
Grails 3.1.1
Groovy 2.4.5

Tomcat 8 with JVM 8 works,
Tomcat 7 with JVM 7 failes

**Comment by arjangch** [comment] 2016-03-08 22:42
Please make sure It is not related to this JDK bug.

**Comment by bronoman** [comment] 2016-03-09 14:47
@arjangch thanks for the hint! I have an open incident with Jelastic to determine their exact JDK/Tomcat versions. I have also not seen a problem with Win10-64, JDK 1.8.0_65 and grails 3.0.14 or grails 3.1.3 with their respective groovy libs.

**Comment by gsitter** [comment] 2016-03-09 15:19
I have the same problem on Linux: 
--> run-app on localhost  works, deploying war-file on Tomcat 7 results in 404-Error!
Environment
- Grails 3.0.9
- Java 1.8.0_65
- Ubuntu 14.04.3 LTS
- Apache Tomcat 7.0.52
Obviously a lot of people have the same problem but until now no solution provided!

**Comment by MudDawg** [comment] 2016-04-06 19:07
[TomcatDeployIssueResearch.xlsx](https://github.com/grails/grails-core/files/207138/TomcatDeployIssueResearch.xlsx)

So I read through this and compiled a simple spreadsheet to detail what worked, what didn't etc.  It let me figure out a path to getting my application to deploy.  I am attaching it in the hopes it will help others until this bug is fixed.  It's a minor annoyance, and likely will fall away soon enough.  

My issue was the I had a Java 1.7, Tomcat 7, and grails 3.1.1.  I was able to solve the issue by simply upgrading the java version to Java 1.8.  Now it works just fine.  Please use the spreadsheet to see if the same solution will work for your Java/Tomcat/Grails versions.

Sincerely,

Steve Keener
Director of Engineering
Praescient Analytics

**Comment by graemerocher** [comment] 2016-04-13 06:55
@MudDawg Thanks for the research I will try the combinations that don't work to investigate the problem

**Comment by benorama** [comment] 2016-04-14 14:21
We also have this issue since this week on my local machine:
- OSX
- java version "1.8.0_25"
- Tomcat 8.0.33
- Grails 3.1.4

And on AWS Beanstalk:
- Amazon Linux
- openjdk version "1.8.0_71"
- Tomcat 8.0.30
- Grails 3.1.4

I can't find a way to reproduce this issue on a sample app. 
From my investigations, it looks like this is linked to app/plugins profiles.
When the app bootstraps with `The following profiles are active: production`, it works fine, and when it bootstrap with `The following profiles are active: production,web` it’s broken (404 everywhere except for default index), but I could not find the reason why we get `production,web` profiles. It's pretty random once you get a medium size app with plugin dependencies.

Is there a workaround to force the active profile to `production` only?

**Comment by graemerocher** [comment] 2016-04-14 14:30
@benorama Try override `grailsApplicationPostProcessor()` of the `Application` class, then return a `GrailsApplicationPostProcessor` with the `setApplicationContext` method overridden to do something like:

```
    @Override
    void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        super.setApplicationContext(applicationContext)
         applicationContext.environment.setActiveProfiles(Environment.current.name)
    }
```

If that works consistently for you then we need to find out how to reproduce why the `setApplicationContext` method is called in some cases and not in others.

**Comment by benorama** [comment] 2016-04-14 22:36
It did not solve the problem but I think that I found the reason : a faulty internal plugin. 
@kerchuma222 described this issue in the Slack channel with an invalid WAR file (with several copies of files).

In my case, there was an internal plugin not well packaged (due a packaging renaming without cleaning which created duplicated files in the SNAPSHOT plugin jar). The side effect is really strange but it completely broke the app during bootstrap.
I let you know if this happens again.

**Comment by gsitter** [comment] 2016-04-15 06:19
Due to "MudDawg" I also made some experiments with the following results:
- Tomcat7 with JVM-Version 1.7.0_55-b14: Grails 3.x apps fail, Grails 2.x apps run
- Tomcat7 with JVM-Version 1.8.0_77-b03: Grals 3.x apps run, Grails 2.x apps fail
- Tomcat8 with JVM-Version 1.8.0_77-b03: Grals 3.x apps run, Grails 2.x apps fail**
- Tomcat8 with JVM-Version 1.7.0_55-b14: Grails 3.x apps fail, Grails 2.x apps run
--> Obviously it works with Java 8
--> Furthermore it is necessary to build the war file in Grails 3.0.9 with "grails dev war" (for whatever reason)

(At the moment I did not know why the old apps are now not starting)

**Comment by graemerocher** [comment] 2016-04-28 09:33
Followers of this issue may want to check out #9901 

The cause of the problem could be the same and a solution is provided

**Comment by jmorhardt** [comment] 2016-05-10 12:45
Successfully deployed app after some struggles with issue as described above. System specs:

Grails 3.1.6
JDK 1.8
Java 8
Tomcat 8
Ubuntu 14.04 on AWS

**Comment by Mutley5000** [comment] 2016-05-17 23:05
I had the same problem but the problem was caused from the Grails war being built with a different version of Java to what the Tomcat server was using.  When I reassembled the war with the same version of Java it was fine.

**Comment by jmorhardt** [comment] 2016-05-20 12:59
Yes, that was my original problem as well. I had deployed on Tomcat7 with JDK1.7. I built a new Tomcat8 server and rebuilt war with specs as above. Worked!

**Comment by graemerocher** [comment] 2016-07-23 11:37
Closing as most issues are problems at the application level and not with Grails itself

**Closed by graemerocher** 2016-07-23 11:37 UTC
Labels: Cannot Reproduce
