### ISSUE TITLE
Grails 2.5.0: Reloading of enums fails

### ISSUE THREAD

**Issue by zaccak** [grails/grails-core#703] opened 2015-05-14 15:47 UTC
If I'm running a Grails application and I change an enum it wont reload it. I will have to shut down the app and run-app again to fix it.

Please fix.
    
Line | Method
->> 1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    617 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by GrailsConfigurationException: Cannot add Domain class [class y.enums.x]. It is not a Domain!
->>  745 | run       in java.lang.Thread

**Comment by graemerocher** [comment] 2015-05-28 13:57
I tried to reproduce this by creating an enum and rendering a enum value, then changing the enum and rendering the newly added value and I received no such exception, if you want any progress on this issue you will need to upload an example to github with steps to reproduce

**Comment by zaccak** [comment] 2015-05-30 17:17
Hi Graeme,

I'm able to reproduce it using the following:
0. Make a new project: EnumBreaker
1. Make an emum:
package enumbreaker.enums
enum ProvinceEnum {
	AB("Alberta"),
	BC("British Columbia"),
	MB("Manitoba"),
	NB("New Brunswick"),
	NF("Newfoundland and Labrador"),
	NT("Northwest Territories"),
	NS("Nova Scotia"),
	NU("Nunavut"),
	ON("Ontario"),
	PE("Prince Edward Island"),
	QC("Quebec"),
	SK("Saskatchewan"),
	YT("Yukon")
	
	private final String value
		
	ProvinceEnum(String value) {
		this.value = value
	}
	
	String toString() {
		return value
	}
}

2. Make a domain that uses that enum:
package enumbreaker
import enumbreaker.enums.ProvinceEnum
class Clinic {
	
	String name
	ProvinceEnum province
	
	static constraints = {
		
    }
}

3. Run-app

4. Now change the enum (remove the last YT or add something new)

5. You should get this:
......
|Compiling 1 source files
.Error 
|
2015-05-30 13:14:11,141 [FileSystemWatcher: files=#1 cl=groovy.lang.GroovyClassLoader@7a64cb0c] ERROR plugins.AbstractGrailsPluginManager  - Plugin [domainClass:2.5.0] could not reload changes to file [/Users/xxx/EnumBreaker/grails-app/domain/enumbreaker/enums/ProvinceEnum.groovy]: Cannot add Domain class [class enumbreaker.enums.ProvinceEnum]. It is not a Domain!
Message: Cannot add Domain class [class enumbreaker.enums.ProvinceEnum]. It is not a Domain!
   Line | Method
->> 745 | run in java.lang.Thread
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by graemerocher** [comment] 2015-06-01 08:02
I followed your steps and I cannot reproduce with the master branch, maybe it has already been fixed by another commit

**Closed by graemerocher** 2015-06-01 08:02 UTC
Labels: Bug, Cannot Reproduce, Minor, Reloading

**Comment by zaccak** [comment] 2015-06-02 02:50
I can give it another shot when 2.5.1 comes out.

I should note that I'm running Grails 2.5.0 on Mac OS X 10.10.3 and Groovy/Grails Tool Suite Version: 3.6.4.RELEASE.
