### ISSUE TITLE
5.0.0.M2 - Could not instantiate persister org.hibernate.persister.entity.SingleTableEntityPersister

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#11882] opened 2021-07-23 00:23 UTC
I have two grails apps that I have upgraded to 5.0.0.M2.  Both are completely different, but both end up with the following exception:

```
Caused by: org.hibernate.MappingException: Could not instantiate persister org.hibernate.persister.entity.SingleTableEntityPersister
        at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:112)
        at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
        at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:181)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:303)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
        at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:287)
        at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
        at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39)
        at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23)
        at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
        at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
        at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
        at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:212)
        at jdk.internal.reflect.GeneratedConstructorAccessor91.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212)
        ... 213 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:390)
        at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:610)
        at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:128)
        at jdk.internal.reflect.GeneratedConstructorAccessor80.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
        ... 230 common frames omitted
```

I am not sure what is causing this issue, but it goes away if I downgrade hibernate from `5.4.32.Final` to what was used prior to 5.0.0.M2

```
implementation "org.hibernate:hibernate-core:5.4.18.Final"
```

works fine.

Not sure what the issue is here?

**Comment by transentia** [comment] 2021-07-23 10:16
I did the exact same thing; went to 5.4.32.Final. Got the same result and downgraded to 5.4.18.Final.

**Comment by lynchie14** [comment] 2021-07-23 11:49
I can reproduce the above in Grails 4.0.10 using Hibernate 4.5.32.Final

`Caused by: org.hibernate.MappingException: Could not instantiate persister org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:112)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:181)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:303)

`

However, that is only when I run with

-Dspring.devtools.restart.enabled=false

If I run without it, it fails in

`Caused by: java.lang.NullPointerException: null
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindSubClass(GrailsDomainBinder.java:1508)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindSubClasses(GrailsDomainBinder.java:1467)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindRoot(GrailsDomainBinder.java:1410)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.contribute(GrailsDomainBinder.java:161)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:292)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:689)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:287)
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:212)
	at jdk.internal.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)`

due to the Mapping cache in AbstractGrailsDomainBinder having its keys loaded by the RestartClassLoader initially and then the standard AppClassLoader looking to retrieve them using the instance loaded in its classloader.

The above worked fine until 5.4.28, once 5.4.29+ was used the above occurs.

**Comment by lynchie14** [comment] 2021-07-23 15:22
Change to https://hibernate.atlassian.net/browse/HHH-14464 seems to be the cause as NPE is being thrown in EntityMetamodel.java:390

`final boolean isAllOrDirty = optimisticLockStyle.isAllOrDirty();`

vs previous

```
		final boolean isAllOrDirty =
				optimisticLockStyle == OptimisticLockStyle.ALL
						|| optimisticLockStyle == OptimisticLockStyle.DIRTY;

```

**Comment by puneetbehl** [comment] 2021-07-23 22:25
I tried creating a new application using 5.0.0.M2 but failed replicate the above issue. Please share the steps to replicate it or a sample application.

**Comment by Taack** [comment] 2021-07-25 07:28
@puneetbehl I reproduce the problem, not sure but this might be because the application depends on: "org.grails.plugins:spring-security-core:4.0.3".

I will try to provide a minimal test-case reproducing the issue..

**Comment by lynchie14** [comment] 2021-07-26 08:59
@puneetbehl Sample project is here and fails against grails 4 (and I assume 5 too) https://github.com/lynchie14/hibernatetest

Only change from base project is increase hibernate to .29 and create a single domain with version false in its mapping.

**Comment by Taack** [comment] 2021-07-26 10:17
The culprit seems to be the line:
```groovy
	static mapping = {
		id composite: ['testUser', 'role']
	}
```
Commenting the composite ID makes the application run ...

**Comment by Taack** [comment] 2021-07-26 12:11
To sum up, if you include this domain, the application won't start:

```groovy
package test

import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
class AuoTest implements Serializable {
    String firstname
    String lastname
    
    static constraints = {
    }

    static mapping = {
        id composite: ['lastname', 'firstname']
        version false
    }
}
```

Hope this helps, tell me if you do not reproduce this issue.

**Comment by puneetbehl** [comment] 2021-08-06 10:47
It seems like the Grails 5.0.0.M2 is pointing to 7.1.0.M4 which is old, so adding the following in build.gradle should fix the problem:

```
gorm.hibernate.version=7.1.0.RC1
```

**Comment by puneetbehl** [comment] 2021-08-06 10:52
Duplicate of https://github.com/grails/gorm-hibernate5/issues/265

**Closed** 2021-08-06 10:52 UTC
