### ISSUE TITLE
Grails 3.2.0 - BootStrap doesn't execute when running as standalone jar/war

### ISSUE THREAD

**Issue by sbortman** [grails/grails-core#10189] opened 2016-09-29 15:19 UTC
Grails 3.2.0 - BootStrap doesn't execute when running as standalone jar/war

Steps to reproduce:

1.   Create a new project using Grails 3.2.0
2.  Add a println "Hello World" to BootStrap.groovy's init
3.  Run app using grails run-app,   should see message on console
4.  Create standalone war using ./gradlew assemble
5.  Run app using java -jar build/libs/<proj name>-0.1.war
6.  No message on the console.

**Comment by allnightlong** [comment] 2016-09-30 15:10
+1 for this issue
This is happening, because BootStrap.groovy has no package. 
Current workaround is to move BootStrap to `grails-app/init/mypackage`.

The same issue is with UrlMappings.groovy.
Default location for UrlMappings.groovy in 3.0.x is `grails-app/controllers/UrlMappings.groovy`.
In grails 3.1.x default location is `grails-app/controllers/mypackage/UrlMappings.groovy`, but in existing apps `grails-app/controllers/UrlMappings.groovy` was also working.
In grails 3.2.x `grails-app/controllers/UrlMappings.groovy` is not working, but in documentation we still have old path:
![2016-09-30_18-08-01](https://cloud.githubusercontent.com/assets/360961/18996414/f34ec384-8738-11e6-9e7b-8d09a645a801.png)

**Comment by allnightlong** [comment] 2016-09-30 15:17
Also, in my opinion, it is the right thing, to move all such a classes (BootStrap, UrlMapping) to packages (default packages is really [bad practice](http://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice)).

But this change should more better documented in user manual and upgrade notes.

**Comment by jameskleeh** [comment] 2016-09-30 15:31
@allnightlong I would recommend clicking the "Improve this doc" button on that page if you think it can be improved

**Comment by allnightlong** [comment] 2016-09-30 15:33
@jameskleeh at the moment i'm not sure if it's 'by design' or just a bug :)

**Comment by jameskleeh** [comment] 2016-09-30 15:35
@allnightlong The documentation referencing a file that does not exist in a fresh application is incorrect and should be fixed to reference the file it intends to reference. I would fix it in the 3.1.x docs as that is the earliest version where the docs are incorrect.

**Closed** 2016-10-04 13:00 UTC
Labels: Acknowledged, Blocker
