### ISSUE TITLE
3.1.1 innovations for inline plugin not working on windows (run-app)

### ISSUE THREAD

**Issue by AlexKovynev** [grails/grails-core#9637] opened 2016-02-04 17:33 UTC
* What went wrong:
Execution failed for task ':sklad:assetCompile'.
> java.io.FileNotFoundException: C:\Work\sklad31\testplugin\build\resources\main (Access denied)

grails {
    native2asciiAnt = true
    native2ascii = true
    exploded = true
    plugins {
        compile project(':testplugin')
    }

}

**Comment by AlexKovynev** [comment] 2016-02-05 02:37
Caused by: java.io.FileNotFoundException: C:\Work\sklad31\ckeditor\build\resources\main (╬Єърчрэю т фюёЄєях)
        at asset.pipeline.fs.JarAssetResolver.<init>(JarAssetResolver.groovy:45)
        at asset.pipeline.gradle.AssetCompile.registerJarResolvers(AssetCompile.groovy:201)
        at asset.pipeline.gradle.AssetCompile$_registerResolvers_closure2.doCall(AssetCompile.groovy:196)
        at asset.pipeline.gradle.AssetCompile$_registerResolvers_closure2.call(AssetCompile.groovy)
        at asset.pipeline.gradle.AssetCompile.registerResolvers(AssetCompile.groovy:196)
        at asset.pipeline.gradle.AssetCompile.compile(AssetCompile.groovy:170)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        ... 77 more

**Comment by jamie-kemp** [comment] 2016-02-10 14:21
I don't seem to get the exception above, but I cannot seem to get this new functionality to detect any changes to the inlined plugin on windows. Same code copied to a linux box detects changes instantly and works as expected.

**Comment by Schlogen** [comment] 2016-02-10 14:36
I had the same experience as @jamie-kemp. Tried it yesterday and didn't work on windows. No exceptions though.

**Comment by Eylen** [comment] 2016-02-11 12:06
I've just tried inline plugin reloading and seems to work fine (tried with some println and they were shown in console) but I have reached the problem stated in #9639

**Comment by graemerocher** [comment] 2016-02-11 12:13
@Eylen you are on Windows?

**Comment by Eylen** [comment] 2016-02-11 12:14
@graemerocher yes, haven't tried in linux yet

**Comment by AlexKovynev** [comment] 2016-02-18 06:16
Excuse me all, I found a problem. 3.1.1 broke my old workaround. But i have trouble with views, so can't test farther. Maybe it's 9639.

**Comment by graemerocher** [comment] 2016-02-22 16:40
Tested in a Windows 7 VM, couldn't reproduce so far..

**Comment by jamie-kemp** [comment] 2016-02-22 17:13
Uploaded a [test project](https://github.com/jamie-kemp/grails3-reloading-test) which creates this scenario (just tried again while putting this together to make sure it was not something I was doing to cause this behaviour - it still does not work). I am using windows 10. 

Steps to reproduce:

1. Call `grails run-app`
2. Wait until application is running
3. Browse to myplugin/grails-app/controllers/myplugin and open TestController.groovy
4. Change "test" to any other string

In my setup nothing happens at this point and the controller continues to output `test`. I have also tried adding classes under src/main with no success.

**Comment by MilesBehind** [comment] 2016-02-23 14:13
may be - we use windows 7 and jdk 1.7.0_79 as development environment.

**Comment by graemerocher** [comment] 2016-02-24 07:37
Fixed by https://github.com/grails/grails-core/commit/ee0c1c2025529d5ca681eb07b6095393566dc37c

**Closed by graemerocher** 2016-02-24 07:37 UTC
Labels: in progress, Windows
