### ISSUE TITLE
createTemplate with string and pageName not producing results as expected from 2.4.x

### ISSUE THREAD

**Issue by rgogulakrishnan** [grails/grails-core#9668] opened 2016-02-10 16:42 UTC
groovyPagesTemplateEngine createTemplate with string and pageName not producing results as expected. Works in 2.3.11 and not working in 2.4.x and 2.5.x. 

```groovy
package testapp1

class TestController {

	def groovyPagesTemplateEngine

    def index() { 

    	println groovyPagesTemplateEngine
    	String s = ""
    	def result = ""

    	// using createTemplate(java.lang.String txt, java.lang.String pageName) - not working as expected
    	for(number in 1..5) {
    		println "number: $number"
    		def out = new StringWriter()
    		// s formed first time is getting reused - not working as expected
    		s = "String Looping for $number <g:textField name='myField' value='${number}' />"
    		groovyPagesTemplateEngine.createTemplate(s, "sample").make().writeTo(out)
    		println out
    		result = result.concat(out.toString())
    	}

    	// createTemplate(java.io.InputStream inputStream) - working fine
    	for(number in 6..10) {
    		println "number: $number"
    		def out = new StringWriter()
    		s = "String Looping for $number <g:textField name='myField' value='${number}' />"
    		groovyPagesTemplateEngine.createTemplate(new ByteArrayInputStream(s.getBytes("UTF-8"))).make().writeTo(out)
    		println out
    		result = result.concat(out.toString())
    	}

    	render text: result
    }
}

```

and Output:
Using createTemplate(java.lang.String txt, java.lang.String pageName)
```html
number: 1
String Looping for 1 <input type="text" name="myField" value="1" id="myField" />
number: 2
String Looping for 1 <input type="text" name="myField" value="1" id="myField" />
number: 3
String Looping for 1 <input type="text" name="myField" value="1" id="myField" />
number: 4
String Looping for 1 <input type="text" name="myField" value="1" id="myField" />
number: 5
String Looping for 1 <input type="text" name="myField" value="1" id="myField" />
```
using:  createTemplate(java.io.InputStream inputStream)
```html
number: 6
String Looping for 6 <input type="text" name="myField" value="6" id="myField" />
number: 7
String Looping for 7 <input type="text" name="myField" value="7" id="myField" />
number: 8
String Looping for 8 <input type="text" name="myField" value="8" id="myField" />
number: 9
String Looping for 9 <input type="text" name="myField" value="9" id="myField" />
number: 10
String Looping for 10 <input type="text" name="myField" value="10" id="myField" />
```

**Comment by rgogulakrishnan** [comment] 2016-02-11 07:15
After exploring, clearing template engine page cache before calling createTemplate using 
```groovy 
groovyPagesTemplateEngine.clearPageCache()
``` 
fixes the problem.. Is that the proper way to do..? 

If yes, let me know, will close the issue. Thanks.

**Comment by graemerocher** [comment] 2016-02-11 08:10
Probably not by design, but since 2.4.x is no longer a supported version and you have a workaround, this won't be fixed

**Closed by graemerocher** 2016-02-11 08:10 UTC
Labels: Won't Fix

**Comment by rgogulakrishnan** [comment] 2016-02-11 08:25
This happens in 2.5.x as well..
