### ISSUE TITLE
Issue:Grails 4 Upgrade default URL '/' in URLMapping not working

### ISSUE THREAD

**Issue by ksgraghav** [grails/grails-core#11386] opened 2019-08-12 05:49 UTC
Hi,

I have upgraded my application to the below
Grails 4x
Open JDK 11
Tomcat 9.0.22.

After Upgrading our application from Grails 3.3.x to Grails 4.x,, we have faced lot of challenges.
The Default URL in URLMapping '/' doesn't seem to work anymore.It was working fine in the previous version.

When I try to invoke the URL 'http://localhost:8080/'
The below entry doesn't take me to the HomeController anymore.
	"/"(controller:"home",action:"index")

Suppose if I change the URL to 'http://localhost:8080/home' and added the required entry in URLMapping.groovy as "/home"(controller:'home', action:"index")  , then its taking me to the HomeController.

Please let me know if there is any workaround.

**Comment by jameskleeh** [comment] 2019-08-12 13:40
Probably being overridden by a plugin. Try 4.0.1.BUILD_SNAPSHOT

**Comment by jameskleeh** [comment] 2019-08-13 13:40
Duplicate of https://github.com/grails/grails-core/issues/11335

**Closed by jameskleeh** 2019-08-13 13:40 UTC

**Comment by ksgraghav** [comment] 2019-08-13 15:46
Hi .
Thanks for your information . I tried to use the snapshot that you have given but still the issue exists for me and not yet resolved ..

So, I have gone through the workaround to fix the issue but I am not still clear on what exactly that needs to be done in my application .
Could you please elaborate on that the below quick fix that you’re mentioning below what I need to do.

Thanks in advance

Quickfix / Workaround

‘You can throw a fixed version of the IsGrailsPluginComparator inside your app within the correct package. This should solve this problem for the moment.’

**Comment by jameskleeh** [comment] 2019-08-13 15:49
@ksgraghav If you can upload a project that demonstrates the issue using 4.0.1.BUILD-SNAPSHOT, then please include it here

**Comment by ksgraghav** [comment] 2019-08-14 08:51
Hi,
I removed this entry in build.gradle and it worked successfully.

compile "org.grails:grails-plugin-url-mappings"

Thanks for your help.

Thank you,
Ganesh
