### ISSUE TITLE
g:link tag does not automatically pickup namespace of current controller

### ISSUE THREAD

**Issue by snimavat** [grails/grails-core#10062] opened 2016-07-24 08:03 UTC
### Steps to Reproduce
Url mapping is:
``` "/admin/$controller/$action?/$id?(.$format)?"(namespace:"admin") ```

When g:link tag is used without a controller name, it intelligently findsout the name of current controller and does the proper reverse url mapping. 

But when the controller is in a namespace, and no namespace is specified in the g:link tag, it will generate wrong urls and will not consider namespace for reverse url mapping:

So, for the url mapping example given above:

If i do  ```<g:link action="create" class="btn btn-primary btn-xs">create</g:link>```
And the current controller is PageController, which is in namespace admin. The generated url will be ```page/create``` and not ```admin/page/create```

### Expected Behaviour
Just like how link tag automatically figureout the controller name, it should also check if the controller is in a namespace, and automatically apply the proper reverse url mapping if there's a namespaced url mapping.

- **Grails Version:** 3.0.11

**Comment by Schlogen** [comment] 2016-07-26 18:47
> When resolving a URL mapping (forward or reverse) to a namespaced controller, a mapping will only match if the namespace has been provided

The docs specifically state the namespace is required for it to resolve, however I agree this can be improved for the situations when the namespace is available in the request.

**Comment by Schlogen** [comment] 2016-07-27 14:54
Done by https://github.com/grails/grails-core/pull/10068. Will be included in the 3.1.10 release.

**Closed by Schlogen** 2016-07-27 14:54 UTC
Labels: Acknowledged, Improvement

**Comment by snimavat** [comment] 2016-08-01 07:04
Is it included in 3.1.10 ? changlog does not include this ticket https://github.com/grails/grails-core/issues?q=milestone%3Agrails-3.1.10

**Comment by snimavat** [comment] 2016-08-02 07:28
@Schlogen I am not sure whats changed in 3.1.10.
But looks like reverse url mapping is broken in 3.1.10

I have this url mappings

```

    static final List<String> FORBIDDEN = [
            'plugins',
            'WEB-INF',
            'assets',
            'console',
            'is-tomcat-running',
            "admin"
    ]
       "/admin/$controller/$action?/$id?(.$format)?"(namespace:"admin")
 "$uri**"(controller:"content") {
            action = ['GET': 'show', 'POST':'update']
            constraints {
                uri(validator: { path ->
                    return !FORBIDDEN.any { p -> return path?.startsWith(p) }
                })
            }
        }
```
when i do g.createLink(controller: 'content', action: "show", params: [uri:url] from a view which is rendered from a namespaced controller (admin namespace). it generates the link ```http://localhost:8080/admin/content/show?uri=THE_URI```

The generated link picks up namespaced url mapping for admin (first url mapping).. even if the content controller is not in admin namespace

**Comment by Schlogen** [comment] 2016-08-02 13:26
@snimavat So the issue is that it is applying the namespace for links that go to controllers that are not the current controller. Thanks for testing this. I'm working on a fix

**Comment by Schlogen** [comment] 2016-08-02 14:45
@snimavat Can you use 3.1.11.BUILD-SNAPSHOT to verify the issue is resolved for you?

**Comment by snimavat** [comment] 2016-08-02 17:18
@Schlogen where can i get the snapshot, i will test... 

Is it implemented as i explained ? Like the namespace should be determined based on the controller name specified in the g:link and not just the namespace in request ?

**Comment by snimavat** [comment] 2016-08-02 17:18
Should we reopen this issue? @Schlogen @graemerocher

**Comment by Schlogen** [comment] 2016-08-02 18:04
Just change your grails version to `3.1.11.BUILD-SNAPSHOT` in your `gradle.properties`

Reopening this issue doesn't make sense because the improvement was completed, it just introduced a bug. 

The namespace, if not specified, can only come from the request. It will not add the namespace for controllers other than the controller in the request. 

Determining the namespace for controllers other than the current controller is outside the scope of your initial improvement request, and therefore was not considered. I'm not sure how much work would be involved to do so, or if it even makes sense.

**Comment by snimavat** [comment] 2016-08-03 06:37
I think it makes sense to figureout the namespace from a controller when doing reverse url mapping... just like doing forward url mapping, Grails will findout which controller to use based on the name space in url mapping... the same should happen based on reverse url mapping... if controller is in name space, use that name space... if there are two controllers with same name in differnt name space, thn namespace must be provided, if one of the controller is in default namespace, that gets picked up.

Should i create a seperate issue for that ?
It not a deal breaker, but it would make g:link much more generic/intelligent

**Comment by Schlogen** [comment] 2016-08-03 17:43
@snimavat Yes you can create a separate issue for that if you would like that functionality

**Comment by snimavat** [comment] 2016-08-04 05:00
Done.. thanks
