### ISSUE TITLE
Problem With Dynamic Methods Added By A Plugin

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-core#9648] opened 2016-02-07 15:14 UTC
The project at https://github.com/jeffbrown/dynamicmethodplugin contains a Grails 3.0.11 plugin.  The plugin adds a dynamic method to all controllers...

```
// src/main/groovy/dynamicmethodplugin/DynamicmethodpluginGrailsPlugin.groovy
package dynamicmethodplugin

import grails.plugins.*

class DynamicmethodpluginGrailsPlugin extends Plugin {

    // ...

    void doWithDynamicMethods() {
        grailsApplication.controllerClasses*.metaClass*.addNumbers = { int x, int y ->
            x + y
        }
    }
}
```

The plugin contains a simple controller...

```
// grails-app/controllers/demo/DemoController.groovy
package demo

class DemoController {

    def add(int x, int y) {
        def sum = addNumbers(x, y)

        render "$x plus $y is 11."
    }
}
```

The following integration test passes...

```
// src/integration-test/demo/DemoControllerSpec.groovy
package demo

import geb.spock.GebSpec
import grails.test.mixin.integration.Integration

@Integration
class DemoControllerSpec extends GebSpec {
    void 'test controller action which uses dynamic method'() {
        when:
        go '/demo/add?x=4&y=7'

        then:
        $().text() == '4 plus 7 is 11.'
    }
}
```

If the `grailsVersion` property in `gradle.properties` is changed to 3.0.12, 3.0.13 or 3.0.14 the test will fail because of a `MissingMethodException`.

```
groovy.lang.MissingMethodException
Message
No signature of method: demo.DemoController.addNumbers() is applicable for argument types: (java.lang.Integer, java.lang.Integer) values: [4, 7] Possible solutions: addNumbers(int, int)
```

**Comment by graemerocher** [comment] 2016-02-15 09:30
So yeah this is another manifestation of not having ExpandoMetaClass enabled by default in Grails 3. If you add:

```class Application extends GrailsAutoConfiguration {
    static {
        ExpandoMetaClass.enableGlobally()
    }
```
To the `Application` class it fixes the issue. I believe the problem is because controllers are singleton, and so they are created as Spring beans and because they are Groovy classes they get a MetaClass assigned to their `metaClass` property which is not an EMC. Later when the meta class is modified programatically this does in fact change the meta class associated with the controller class, but the singleton instance created by Spring still has the older meta class stored in its `GroovyObject.metaClass` property.

There are a few possible solutions to this, since I don't think going back to having EMC enabled globally is the right thing to do. 

1) We could modify the controllers plugin to go through all the controllers and ensure have they right meta class associated with them. This is not ideal because it is another thing to do at startup.
2) We could update the documentation to say that if you modify the meta class of the controllers, you also have to do something like:

```
for(controller in applicationContext.getBeansOfType(Controller).values()) {
     controller.metaClass = GroovySystem.metaClassRegistry.getMetaClass(controller.getClass())
}
```

This makes it possible to solve the case where this is done, without making every Grails 3 users suffer the startup and runtime performance consequences.

Generally using this approach described in this issue is deprecated in favour of traits so I would favour the latter, but anyway thoughts welcome.

**Closed** 2016-07-23 11:03 UTC
Labels: Awaiting Feedback, Won't Fix
