### ISSUE TITLE
Multipart resolver exception handling doesn't appear to work

### ISSUE THREAD

**Issue by ZacharyKlein** [grails/grails-core#10928] opened 2018-02-07 20:57 UTC
### Steps to Reproduce

1. Set appropriate `maxUploadSize` and `maxRequestSize` config values
2. Create a custom subclass of `StandardMultipartResolver` and wire in `resources.groovy`
3. Attempt to catch exceptions and set a session variable, returning the request

### Expected Behaviour

The request should return a response to the browser, with the appropriate session variable set

### Actual Behaviour

The browser never receives a response and errors out with "server connection was reset" message.

### Environment Information

- **Operating System**:  macOS
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8
- **Container Version (If Applicable):** N/A

### Example Application

- https://github.com/ZacharyKlein/multipart-resolver-issue

**Comment by ZacharyKlein** [comment] 2018-02-07 21:00
For context, my sample project is an updated version of @jameskleeh's post here: https://stackoverflow.com/questions/29845943/grails3-file-upload-maxfilesize-limit/32974072#32974072

**Comment by ZacharyKlein** [comment] 2018-02-08 23:09
Via @graemerocher, a partial solution is to set the response status to 413 in the controller. 

```
response.status = HttpStatus.PAYLOAD_TOO_LARGE.value()
```

This works... sometimes. It appears to resolve the issue on Chrome and Safari, on macOS. However, Firefox on macOS exhibits the same issue (blank page, "connection was reset" message). 

What's worse, both Chrome and Firefox on Linux (Ubuntu) continue to display the problematic behavior. I'm told the same is true on Windows. 

This is entirely specific to the browser/OS - for example, when the test app is deployed to Tomcat on a remote server (ruling out any development environment specifics), a client on macOS/Safari will receive the correct response (form with an error message), and a client on Ubuntu/Chrome will receive the blank page/connection error.

I'm not sure how to debug this further.

**Comment by puneetbehl** [comment] 2018-10-11 11:01
@ZacharyKlein @jameskleeh I am not able to replicate this issue on Mac with Chrome, Firefox, and Safari. It seems to be happening in Linux. I do not have a Linux machine. So, I would request you to please assign it to someone with Linux machine.

**Comment by puneetbehl** [comment] 2018-10-12 08:00
ok, I am able to replicate the problem on VirtualBox Linux and on MacOS as well when I try to upload a file with size 20M or more.

It seems like it's related to the Tomcat default connector `maxSwallowSize`. If you try to upload a file whose size exceeded this value (default 2M) then Tomcat will reset the connection. 

I found similar old issue #9378 which is marked as won't-fix.

This is how you do it in a Grails/Spring Boot application: http://stackoverflow.com/questions/32250030/setting-a-tomcat-property-using-spring-boot-application-properties

**Comment by ppazos** [comment] 2020-06-26 22:23
@ZacharyKlein I'm getting an exception before reaching the controller, where do you put that code?

**Closed** 2020-10-19 20:13 UTC
Labels: closed: won't fix

**Comment by ppazos** [comment] 2020-10-20 17:48
The issue is not setting the max size, the problem is gracefully managing the exception when the max size is reached, since for every max size set a user can upload a bigger file. The exception happens in Spring, before the Grails controllers are reached, so it doesn't seem possible to catch the exception from Grails and return a friendly error to the user. IMO this is a pretty basic problem, not sure why this wasn't fixed, or at least why a strategy to deal with this wasn't documented in Grails.

**Comment by philippreston** [comment] 2021-07-22 20:37
Hitting this issue as well.  Was there any view on how this can even be worked around?  Throwing a 500 isn't particularly elegant or user friendly...

Thanks
