### ISSUE TITLE
run-command fails

### ISSUE THREAD

**Issue by 1442acb42ee0e3a727d7330e9755eb94** [grails/grails-core#12658] opened 2022-08-04 16:04 UTC
### Expected Behavior

The command should execute.

### Actual Behaviour

The command does not execute and fails with the following error message:

`/projects/grails521$ /opt/grails-5.2.1/bin/grails run-command test --stacktrace
<===========--> 85% EXECUTING [2s]
> :runCommand
Missing application class name and script name arguments

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runCommand'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runCommand'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
       ... 147 more
| Error Failed to execute a command
`

### Steps To Reproduce

1.Install grails 5.2.1 in /opt/
2. /opt/grails-5.2.1/bin/grails create-app grails521
3. /opt/grails-5.2.1/bin/grails run-command test --stacktrace

### Environment Information

Linux Debian
Java OpenJDK 11

### Version

5.2.1

**Comment by puneetbehl** [comment] 2022-08-04 18:02
It seems duplicate of #11588

**Closed as completed** 2022-08-04 18:03 UTC
Labels: closed: duplicate
