### ISSUE TITLE
GSP render after redirect can cause unexpected behavior

### ISSUE THREAD

**Issue by sjrd218** [grails/grails-core#10971] opened 2018-03-21 15:41 UTC
Grails attempts to render a gsp even though earlier in the code a redirect was called.
This is different behavior from the grails 2.5.x versions which did not attempt gsp rendering
when the request was being redirected.

### Steps to Reproduce

1. Write a controller and gsp that renders a model
2. In the controller call redirect before calling the render
4. render the view with a null model
5. observe the NPE

### Expected Behaviour

A call to render a gsp after a redirect method has been called should not
result in an attempt to render the page. 
This was the the behavior in grails 2.5.6 and upon upgrading our app to 
grails 3.3.2 the page flow is broken because the new version doesn't 
behave like the old.

### Actual Behaviour

An NPE is thrown because the model is null that the gsp is attempting to render.

### Environment Information

- **Operating System**: Mac OS 10.13.3
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.0_162
- **Container Version (If Applicable):** N/A

### Example Application
Example app demonstrating the problem is attached.
After starting the app, navigate to the demo controller index page.
[GspRedirectBug.zip](https://github.com/grails/grails-core/files/1833966/GspRedirectBug.zip)

**Comment by jeffbrown** [comment] 2018-03-21 16:02
I think this is a bug in the app, not the framework.  You have these controller actions...

```groovy
    def show() {
        if(params.doRedirect=="true") {
            redirect(action:'show',params:[params.doRedirect=false])
            return
        }

        return [myObj: [testProp: "my prop"]]
    }

    def demoRedirectBug() {
        def demoModel = show()
        render(view: 'show',model:demoModel)
    }
```

The problem there is `demoRedirectBug` is invoking the `show()` method, which is bad.  You are effectively invoking `redirect` and then invoking `render`.  There is no good reason to do that.

**Comment by jeffbrown** [comment] 2018-03-21 16:07
### Steps to Reproduce

1. Write a controller and gsp that renders a model
2. In the controller call redirect before calling the render
3. render the view with a null model
4. observe the NPE


Step 2 in your list there is the problem.  There isn't a good reason to do that.

**Comment by sjrd218** [comment] 2018-03-21 16:10
I agree that the code flow is not the way I would've written it. However the real world app I'm working with is much more complex that this demo, and what I'm reporting is that the grails 3.3.2 version works different than the 2.5.6 version which breaks the more complex app. I've distilled the behavior down into the reported steps even though considerably more is being done in the real app.

**Comment by jeffbrown** [comment] 2018-03-21 16:14
While this usage pattern may have happened to work in some versions of Grails, I don't think it is a feature or should be supported. 

@graemerocher @jameskleeh What do you guys think?

**Comment by jameskleeh** [comment] 2018-03-21 16:43
@jeffbrown I agree

**Comment by AdrienGuichard** [comment] 2018-03-22 09:32
I do not understand
`            redirect(action:'show',params:[params.doRedirect=false])
`
In my mind it should be 
`            redirect(action:'show',params:[doRedirect: false])
`

If it is not the same, then this bug is a duplicate of
#10965

**Comment by jeffbrown** [comment] 2018-03-22 18:46
@AdrienGuichard Those are not the the same and are mostly unrelated to this issue.

**Comment by jameskleeh** [comment] 2018-03-28 19:31
Closing this due to a lack of a clearly defined issue

**Closed by jameskleeh** 2018-03-28 19:31 UTC
