### ISSUE TITLE
Grails 3.2.8 war created for custom environment always runs under development environment.

### ISSUE THREAD

**Issue by HardikModha** [grails/grails-core#10569] opened 2017-04-05 18:58 UTC
### Task List

- [x] Steps to reproduce provided
- ~~[ ] Stacktrace (if present) provided~~
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use Grails version 3.2.7 or greater (Currently 3.2.8) to create a sample test application and create a war for any custom environment. 
e.g. Creating war with staging environment. `grails -Dgrails.env=staging war`
2. Now deploy war file on server (e.g. Tomcat) or use `java -jar Test.war`  to run the war using embedded tomcat container.
3. Although we created the war using staging environment, application will run in the development environment.

### Expected Behaviour

Custom environment specific war should be created and while running the application, it should run in the environment it was created for.

### Actual Behaviour

Application always runs in the development environment.
### Environment Information

- **Operating System**: Ubuntu 14.04
- **Grails Version:** 3.2.7 and 3.2.8
- **JDK Version:** 1.8.0_111

### Example Application
GitHub repo to reproduce this issue: [grails-test](https://github.com/HardikModha/grails-test)

[#10546](https://github.com/grails/grails-core/issues/10546) is relevant and claims to have fixed the issue but that solution only fixes the environment name printed after the war is created.
` Built application to build/libs using environment: staging` <---- It fixes only this display environment name.

**PS**: I used the same configuration, followed the same steps using grails v3.2.6 and got the expected/correct results.

**Comment by jameskleeh** [comment] 2017-04-05 19:06
This commit fixed the issue in my testing https://github.com/grails/grails-core/commit/d780175f3680969596b429819857565c310b8e21

**Comment by HardikModha** [comment] 2017-04-05 19:09
@jameskleeh But seems like that only fixes the environment displayed in the message.
`Built application to build/libs using environment: staging` <--- This environment name.

I tried creating war with the custom environment using version 3.2.8 and it didn't work. Application was running in the development environment. It can be reproduced easily.

**Comment by jameskleeh** [comment] 2017-04-05 19:10
@HardikModha No, that is a different commit, https://github.com/grails-profiles/base/commit/1f1ea0989d6222f39a20322d5c6d15f037667abb

**Comment by HardikModha** [comment] 2017-04-05 19:12
@jameskleeh doesn't fix the issue.

**Comment by jameskleeh** [comment] 2017-04-05 20:16
I can't reproduce the issue. Steps I took:

1. `grails create-app test-war` (Grails 3.2.8)
2. Add staging database configuration:
```
    staging:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:./stagingDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
```
3. Add a domain class (`grails create-domain-class Test`)
4. Save the domain class in Bootstrap `new Test().save()`
5. Build war with `grails -Dgrails.env=staging war`
6. Deploy to Tomcat 8.5.13
7. Verify `stagingDb.mv.db` exists in the tomcat root directory

**Comment by HardikModha** [comment] 2017-04-08 06:23
@jameskleeh Sorry for the delayed response. I have created a demo project [grails-test](https://github.com/HardikModha/grails-test) which reproduces the specific issue. Can you please take a look at it.

**Comment by HardikModha** [comment] 2017-04-11 15:51
@jameskleeh Have you looked at [grails-test](https://github.com/HardikModha/grails-test) which reproduces the issue?

**Comment by jameskleeh** [comment] 2017-04-11 15:57
Yes, I cannot reproduce. 
<img width="440" alt="screen shot 2017-04-11 at 11 56 44 am" src="https://cloud.githubusercontent.com/assets/1583789/24918319/ff7284c2-1ead-11e7-8909-1d3d710d298a.png">

**Comment by HardikModha** [comment] 2017-04-11 16:05
I'm not getting this. I tried multiple times with different environments and everytime when the environment is custom it runs in development environment. On my machine it is working fine for grails version <= 3.2.6. Issue occurs only for latest version of Grails. What can be the possible reasons?

**Comment by ColinHarrington** [comment] 2017-04-11 17:30
I'm trying to reproduce this on Ubuntu 14.04.  I know you said `JDK Version: 1.8.0_111`  There isn't a JDK8 in the repositories.  Which version did you use: Oracle? OpenJDK? and from which sources?

**Comment by HardikModha** [comment] 2017-04-12 14:31
@ColinHarrington I'm using Oracle JDK. I setup using ppa and apt repositories.

**Comment by ankit-agrawal11** [comment] 2017-04-13 14:11
@ColinHarrington, @jameskleeh, @HardikModha 
I am able to reproduce the issue on my system. I cloned Hardik's repo and created a war using `grails clean && grails -Dgrails.env=staging` command. When I ran this war with `java -jar /path/to/war` command, I found the environment to be development. 

Here is my system configuration - 

```
OS - Ubuntu 14.04
JDK - Oracle 1.8.0_101
Grails version - 3.2.8
```

**Comment by jameskleeh** [comment] 2017-04-13 14:28
I'm able to reproduce while running with `java -jar`, but not while deploying to a standalone tomcat instance.

**Comment by jameskleeh** [comment] 2017-04-13 14:55
The `build.gradle` in the example project is totally borked. It looks like there is one complete configuration above another complete configuration. Removing the duplicate configuration resolved the issue for me.

**Comment by jameskleeh** [comment] 2017-04-13 15:03
Submitted a PR to fix the example project https://github.com/HardikModha/grails-test/pull/1

**Comment by HardikModha** [comment] 2017-04-14 02:09
@jameskleeh That duplicate content in `build.gradle` was a mistake. But even after removing the duplicate code, I'm able to reproduce the error using `java -jar TestEnv-0.1.war`.

**Comment by ankit-agrawal11** [comment] 2017-04-14 04:07
@jameskleeh Thanx for taking out the time to look into the issue. I created a war with the updated `build.gradle` file but unfortunately that didn't solve the issue and I am still getting `development` environment.

**Comment by shushkevich** [comment] 2017-05-01 09:16
There is workaround - create war with Gradle:
`gradle -Dgrails.env=stagin assemble`

**Comment by nardhar** [comment] 2017-06-08 19:26
In case someone is still troubling with this error and lands here (like me), I found the correct solution after having two projects, one created with grails 3.2.3 (but upgraded to 3.2.9) and another one created with grails 3.2.8 (also upgraded to 3.2.9).

Both of the projects had
`archiveName "${war.baseName}${Environment.current == Environment.PRODUCTION ? '' : '_' + Environment.current.name}.war"`

But it only generated `myproject_customenv.war` in the first one, so as I searched for any difference I found out that the error was in the gormVersion specified in `gradle.properties`

The first one had `gormVersion=6.0.4.RELEASE` and the second `gormVersion=6.0.9.RELEASE`, so maybe GORM v6.0.9 changes custom envs to development, hence this problem.

Obviously we should not downgrade to 6.0.4 but to upgrade to the latest version (6.1.4), which has the correction as well

**Comment by gnaaromat** [comment] 2017-06-28 12:58
Can confirm the error on an ubuntu 16 running a docker instance with 

_Apache Tomcat/8.0.37
JVM Version:           1.8.0_102-8u102-b14.1-1~bpo8+1-b14
OS Version:            4.4.0-38-generic_

The interesting thing is, that it only doesnt work custom environments. 
`gradle -Dgrails.env=autotest assemble`
will result in the development env whereas
`gradle -Dgrails.env=test assemble `
gives me the test environment

**Comment by Wellssow** [comment] 2017-07-03 09:18
I can confirm this for gradle build with Grails 3.2.10 that the file WEB-INF/classes/META-INF/grails.build.info inside the WAR package does not contain any custom enviroment value.

Running "gradle -Dgrails.env=$ENV war" creates:

$ENV               grails.build.info
-------             --------------------------
testing       --> grails.env=development
test            --> grails.env=test
production --> grails.env=production

Apache Tomcat 8.5.15
JVM Version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
OSX Version Sierra 10.12.5

**Comment by HardikModha** [comment] 2017-07-03 11:13
@Wellssow Thanks for reporting. I can also confirm that I'm still able to reproduce the issue on Grails version 3.2.10. @jameskleeh I think the issue should be reopened and investigated thoroughly.

**Comment by jameskleeh** [comment] 2017-07-03 13:40
@HardikModha In order to do so I would need an example project

**Comment by jameskleeh** [comment] 2017-07-03 13:47
Quick test

```
Using grails version 3.2.10 in this shell.
Jamess-MacBook-Pro:sample-projects jameskleeh$ grails create-app test-war
| Application created at /Users/jameskleeh/IdeaProjects/sample-projects/test-war
Jamess-MacBook-Pro:sample-projects jameskleeh$ cd test-war
...
BUILD SUCCESSFUL

Total time: 19.649 secs
Jamess-MacBook-Pro:test-war jameskleeh$ cd build/libs
Jamess-MacBook-Pro:libs jameskleeh$ unzip test-war-0.1.war 
Archive:  test-war-0.1.war
...   
Jamess-MacBook-Pro:libs jameskleeh$ cat WEB-INF/classes/META-INF/grails.build.info 
#Mon, 03 Jul 2017 09:45:32 -0400

info.app.version=0.1
info.app.name=test-war
grails.env=testing
info.app.grailsVersion=3.2.10

```

**Comment by Wellssow** [comment] 2017-07-03 15:18
@jammeskleeh Which gradle version are you running?
On my site version 3.4.1 (./gradlew) and 3.5 (gradle) wont do that trick :-( 
Or this might have other conflict in files like gradle.properties?

**Comment by Wellssow** [comment] 2017-07-04 08:51
So the only difference is the Grails version.
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.5 x86_64

**Comment by gnaaromat** [comment] 2017-07-04 09:08
For me, it worked after if went back to gradle 2.9. Had gradle 3.4.1 before and was using the gradle assemble and war commands.

My jenkins script now reads:
```
#!/bin/bash
source /var/lib/jenkins/.bashrc
export PATH=$PATH:"$JENKINS_HOME/.sdkman/candidates/grails/3.2.8/bin:$JENKINS_HOME/.sdkman/candidates/gradle/2.9/bin"
sdk use grails 3.2.8
sdk use groovy 2.4.7
sdk use gradle 2.9
grails -version
groovy -version
gradle -version
gradle wrapper --gradle-version 2.9
grails clean
grails -Dgrails.env=custom war
```

The project was a grails 3.0 that we subsequently upgraded to grails 3.2.8. The only real change I did while stumbling across this bug was setting the gorm version to 6.0.9 as it is in a new grails project generated with version 3.2.8

**Comment by graemerocher** [comment] 2017-07-04 10:04
Out of interest does it make any difference if you run `./gradlew --stop` before running `grails war` or `./gradlew assemble`

**Comment by Wellssow** [comment] 2017-07-04 11:31
@graemerocher: Big deal (thumbsup)
Running ./gradlew --stop"  solved my issue.

**Comment by graemerocher** [comment] 2017-07-04 12:33
So seems to be a Gradle daemon / static cached state issue

**Comment by Wellssow** [comment] 2017-07-06 15:38
Unfortunately the value stored in the **grails.build.info** is not used as environment setting when deploying the war file on a tomcat 8.5.15.
 [ost-startStop-6] cloudeventmanager.ApplicationLoader : Running with Spring Boot v1.4.6.RELEASE, Spring v4.3.7.RELEASE
 [ost-startStop-6] cloudeventmanager.ApplicationLoader : The following profiles are active: [initializing:false]

I can set  the CATALINA_OPTS="-Dgrails.env=stage", but that would render the grails.env value inside the grail.build.info file useless.

Additionally the deployment process seems to be altering the profiles setup.
Sometimes the deployment starts up fine logging:
 > The following profiles are active: stage

but sometimes the logging states:
> cloudeventmanager.ApplicationLoader : The following profiles are active: stage,web

and then the Bootstrap.groovy is executed twice, but the application only shows:
```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Jul 06 17:33:13 CEST 2017
There was an unexpected error (type=Not Found, status=404).
No message available
```

It seems like grails/spring mixes the "grails.env" and "grails.profile" values

**Comment by Wellssow** [comment] 2017-07-11 14:46
There's a 50% chance for a valid or broken profile.

**Comment by graemerocher** [comment] 2017-07-14 14:37
Can't reproduce this personally, most likely cause is that you have a plugin that has `ApplicationLoader` in it and it is loading your application twice. This would be the same cause as #9901 and #9904 etc.

Add debug logging and see where this second `ApplicationLoader` is coming from and remove it from your application or fix the plugin. In the meantime I have pushed a fix that prevents the need for doing `./gradlew --stop`

**Closed by graemerocher** 2017-07-14 14:37 UTC

**Comment by Wellssow** [comment] 2017-07-20 15:44
My colleague found the "breaking" plugin.

It's the Grails-Plugin "filterpane-3.0.8", which has an extra "Application" and "ApplicationLoader" class inside the jar, under /org/grails/plugins/filterpane/test. ;-) 

Whenever spring starts the filterpane-plugin "Application" first, the real application is dead.

**Comment by demon101** [comment] 2017-08-30 19:02
Nice, waiting for release of Grails 3.2.12

**Comment by sctse999** [comment] 2017-09-08 02:32
I can also confirm that running ./gradlew --stop solved my issue.

**Comment by ChiranjibKarn** [comment] 2017-10-06 09:51
"gradlew --stop" worked for me as well in local tomcat. Struggling with Jenkins script now.

**Comment by gnaaromat** [comment] 2017-10-06 09:56
I am using this now. Note that the grails clean has to come before the gradle stop

gradle wrapper --gradle-version 3.5
grails stop
chmod +x gradlew
./gradlew --stop
./gradlew -Dgrails.env=qa war

**Comment by sctse999** [comment] 2017-10-09 02:01
I am trying to use db migration plugin and the following command line defaults to development again. Quite frustrating.

grails -Dgrails.env=staging dbm-status

**Comment by kdmashruwala** [comment] 2018-04-11 09:08
I am using Grails 3.2.7 @graemerocher your solution to stop gradlew worked for me to create war with staging environment.

I used following commands
grails clean
gradlew --stop
grails -Dgrails.env=staging war

After extracting the war and cheking grails.build.info file, I see grails.env=staging.

Still bug in displaying information on console message which still displays
Built application to build\libs using environment: development
