### ISSUE TITLE
Grails 3.x - External domain JPA library causes GrailsConfigurationException in Spock Unit Tests

### ISSUE THREAD

**Issue by nathankooistra** [grails/grails-core#9282] opened 2015-09-23 19:12 UTC
I am using an external jar (Hibernate JPA) as my domain by creating a hibernate.cfg.xml file in grails-app/conf.

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE hibernate-configuration PUBLIC
        "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
        "http://hibernate.sourceforge.net/hibernate-configuration-3.0.dtd">
<hibernate-configuration>
	<session-factory>
        <mapping package="com.myapp.hibernate"/>
        <mapping class="com.myapp.hibernate.domainClass"/>
...
```

This is working great in the source code. I'm getting the GORM queries added as expected and everything is functioning.

For my tests, however, I'm getting:
`org.grails.core.exceptions.GrailsConfigurationException: Cannot add Domain class [class domainClass]. It is not a Domain!`

Here's my test format:
```java
@TestFor(DomainClassController)
@Mock(DomainClass)
class DomainClassControllerSpec extends Specification
```

It appears Spock is not recognizing my DomainClass in the @Mock annotation as an actual Domain object.

Is this a user issue, Spock issue, or Grails issue? Workaround?

**Comment by nathankooistra** [comment] 2015-09-23 19:45
mockDomain as follows gives the same GrailsConfigurationException:

```java
@TestFor(DomainClassController)
@TestMixin(DomainClassUnitTestMixin)
class DomainClassControllerSpec extends Specification {

def setup()
{
mockDomain(DomainClass)
}
```

**Comment by nathankooistra** [comment] 2015-09-23 20:49
Digging into `DomainClassArtefactHandler.doIsDomainClassCheck)` it looks like if the class has the annotation grails.persistence.Entity it's considered a domain class. My JPA classes are annotated as javax.persistence.Entity.

There's the disconnect. Is this intended behavior?

**Comment by nathankooistra** [comment] 2015-09-23 22:06
OK, I got past that check by forcing an @Version getter on the JPA domain classes. However, the Domain objects aren't getting decorated as Gorm objects.

I'm unable to call a .save() on my mocked objects - I get the error `No signature of method: com.identifix.hibernate.User.save()`.

Similar error happens when I do mockDomain() as well.

**Comment by graemerocher** [comment] 2015-09-25 10:11
Please upload an example to github that reproduces the issue and we can take a look

**Comment by graemerocher** [comment] 2015-11-27 17:46
Since Java domains are no longer supported as of GORM 5 and no feedback was provided we won't be fixing this

**Closed by graemerocher** 2015-11-27 17:46 UTC
Labels: Awaiting Feedback, Won't Fix

**Comment by ckalan** [comment] 2016-03-14 18:24
Java domains are not supported as of GORM 5 ? Graeme I think this must be documented very clearly  because like us many people may try moving from Grails 2 to Grails 3 and then find out that GORM is not working and all the existing GORM based code is garbage. 

Besides, I must note that, not supporting all those standardized JPA annotations and just depending on Grails mappings is a huge disadvantage for Grails. Grails mappings support only a part of what can be done with JPA annotations and now it is ignoring common enterprise standards. I think best part of Gorm was that it had this flexibility. 

At least there must be a way to manually enhance these java domain classes to have Gorm api methods right ? Is there any ?

**Comment by graemerocher** [comment] 2016-03-14 20:31
You can continue to use GORM 4 if you wish to map JPA domains

**Comment by ckalan** [comment] 2016-03-14 23:31
Thanks Graeme that's a very good news. Can you please give an example build config for Grails 3.1.3 to use Gorm 4 instead of 5 ?
