### ISSUE TITLE
chain does not interpret uri controller parameter correctly

### ISSUE THREAD

**Issue by tmanthey** [grails/grails-core#11246] opened 2019-02-19 11:35 UTC
### Steps to Reproduce

1. Create controller _mycontroller_ with method _index_
2. Create _index.gsp_ under _mycontroller_
3. Create another controller e.g. _myothercontroller_ with method e.g. _somemethod_ so _myothercontroller/somemethod_
4. Call method _myothercontroller/somemethod_ with a link 
e.g. _createlink(controller: "myothercontroller") action:"somemethod")_ 
5.) in _myconroller/somemethod_ method add the line
`chain(uri: request.getHeader('referer') , model: [hello: "bug"])`

### Expected Behaviour

As the referrer is _..../mycontroller/index_ the `chain` method should behave analogue to the _redirect_ method which interprets the referrer URL correctly and return to _mycontroller/index_ 

### Actual Behaviour

Error 500: Internal Server Error

URI
    **/myothercontroller**
Class
    java.lang.IllegalArgumentException
Message
    Invalid action name: index

the `chain` method obviously fails to interpret the controller part of the URI correctly and tries to call _myotherconroller/index_ instead of _mycontroller/index_

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Grails Version:** 3.3.8
- **JDK Version:**  1.8.0_201-b09
- **Container Version (If Applicable):** TODO

**Comment by ilopmar** [comment] 2019-04-08 13:31
@tmanthey Can you please provide a sample app the reproduces the issue?

**Comment by jeffbrown** [comment] 2021-06-14 14:36
Does your `request.getHeader('referer')` evaluate to `null`?

**Comment by puneetbehl** [comment] 2021-09-16 17:48
Closing due to lack of information and feedback.

**Closed by puneetbehl** 2021-09-16 17:48 UTC
Labels: status: awaiting feedback
