### ISSUE TITLE
Another Memory Leak for Tests Using @DirtiesContext Annotation

### ISSUE THREAD

**Issue by jonroler** [grails/grails-core#10550] opened 2017-03-24 01:28 UTC
This issue is similar to #10535 which was fixed in grails 3.2.8. It's another way (this is still present in grails 3.2.8) that grails is leaking a copy of the spring application context, hibernate session factory, etc. for each test method that uses the @DirtiesContext annotation.

### Steps to Reproduce

1. `git clone https://github.com/jonroler/grails-dirties-context-mem-leak-2.git`
2. `cd grails-dirties-context-mem-leak-2`
3. `./grailsw test-app -integration`

### Expected Behaviour

The size of the `grails.validation.ConstrainedProperty.constraints.unique` list should remain the same after the execution of a test annotated with `@DirtiesContext`. According to the grails docs, grails should support the `@DirtiesContext` annotation: http://docs.grails.org/latest/guide/testing.html#integrationTesting.

### Actual Behaviour

The size of `grails.validation.ConstrainedProperty.constraints.unique` increases by one after the execution of a test annotated with `@DirtiesContext` (see the standard output generated by the test run). This appears to be a memory leak. It is a pretty serious memory leak because it appears to leak a copy of the spring application context, hibernate session factory, etc. for every single test method with the `@DirtiesContext` annotation. Most of our tests do not use this annotation, but we have enough of them that this leak is causing us to not be able to run our integration tests with a 4GB heap when a 1GB heap should normally be sufficient (and was sufficient in grails 2.5.1--we're attempting to upgrade to grails 3 right now, but this bug is blocking us).

### Environment Information

- **Operating System**: Linux lone 4.9.7-1-ARCH #1 SMP PREEMPT Wed Feb 1 19:33:40 CET 2017 x86_64 GNU/Linux
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_121
- **Container Version (If Applicable):** N/A

### Example Application

https://github.com/jonroler/grails-dirties-context-mem-leak-2

**Comment by jameskleeh** [comment] 2017-05-05 16:59
The problem is the way the hibernate plugins attempt to remove the constraint

https://github.com/grails/gorm-hibernate4/blob/master/grails-plugin/src/main/groovy/grails/plugin/hibernate/HibernateGrailsPlugin.groovy#L84
https://github.com/grails/gorm-hibernate5/blob/master/grails-plugin/src/main/groovy/grails/plugin/hibernate/HibernateGrailsPlugin.groovy#L93

It is created with the factory, however the removal method specifies the inner class so `UniqueConstraint.isInstance(<<instance of PersistentConstraintFactory>>)` fails.

**Comment by jameskleeh** [comment] 2017-05-15 14:38
Fixed by https://github.com/grails/gorm-hibernate5/commit/da9882f85c171fee30aaeff0e61c350f2bd9241f and https://github.com/grails/gorm-hibernate4/commit/5b7ccd1660bda6883e7997118c5af61986412b16

**Closed by jameskleeh** 2017-05-15 14:38 UTC
