### ISSUE TITLE
Can't render template that lives in a plugin

### ISSUE THREAD

**Issue by kdickerson** [grails/grails-core#9406] opened 2015-11-06 23:09 UTC
Attempting to render a template that lives in a plugin (inline) results in a 500 error stating that the template cannot be found.

Grails: 3.0.9
Java: 1.7
OS: Win 7 64-bit

--

To Reproduce:

    > grails create-plugin simplePlugin
    > grails create-app simpleApp
    > echo include 'simplePlugin', 'simpleApp' > settings.gradle
    > echo TemplateBodyHere > simplePlugin/grails-app/views/_fromPlugin.gsp

Edit simpleApp\build.gradle and add:

    dependencies {
      compile project(":simplePlugin")
      ....
    }

Edit simpleApp\grails-app\views\index.gsp and add:

    <g:render plugin="simplePlugin" template="fromPlugin" />

Run the application:

    > cd simpleApp
    > grails
    grails> run-app

Load the default index page: http://localhost:8080/

Will result in a 500 error:
> GroovyPageView: [views/index.gsp:108] Template not found for name [fromPlugin] and path [//_fromPlugin.gsp]

**Comment by ctoestreich** [comment] 2015-12-21 20:01
On a side note, this does work if you remove the plugin="..." from the g:render

<g:render template="fromPlugin" />
<img width="973" alt="screen shot 2015-12-21 at 2 00 43 pm" src="https://cloud.githubusercontent.com/assets/691357/11940014/4e2728ec-a7eb-11e5-9c89-e96575d6e59c.png">

**Comment by ctoestreich** [comment] 2015-12-21 20:11
The issue here is that the context path is replacing the actual camel case with a `-` character this isn't found.

<img width="1159" alt="screen shot 2015-12-21 at 2 10 12 pm" src="https://cloud.githubusercontent.com/assets/691357/11940202/a313b48c-a7ec-11e5-98c7-8494fb429af3.png">

If I hardcode the lookup to use camel case it succeeds where as the name with the - fails.

<img width="1121" alt="screen shot 2015-12-21 at 2 11 10 pm" src="https://cloud.githubusercontent.com/assets/691357/11940215/c69c6c00-a7ec-11e5-8fb4-0330abe342a7.png">

**Comment by ctoestreich** [comment] 2015-12-21 20:23
The fix is in [this class on this line](https://github.com/grails/grails-core/blob/master/grails-bootstrap/src/main/groovy/grails/util/GrailsNameUtils.java#L335) where it converts the camel case to dash-case.  I am not sure how you would recommend fixing this.

Could try loading the template via plugin name replacement as it is written now, then if the context path isn't found and try again with actual name no dash replacement?  That would be a double scan for the plugin, but should be quick?  This would have to occur somewhere in DefaultGroovyPageLocator.java

```
 public GroovyPageScriptSource findPageInBinding(String pluginName, String uri, TemplateVariableBinding binding) {
        String contextPath = resolveContextPath(pluginName, uri, binding);

        GroovyPageScriptSource scriptSource = findPageInBinding(GrailsResourceUtils.appendPiecesForUri(contextPath, uri), binding);
        if (scriptSource == null) {
            scriptSource = findResourceScriptSource(uri);
        }
  
       //do a last ditch effort and don't munge name with camel to dash
       if(scriptSource == null){
              contextPath = resolveContextPath(pluginName, uri, binding, false); //add param for dash-case or camel-case or new method with new name
               scriptSource = findPageInBinding(GrailsResourceUtils.appendPiecesForUri(contextPath, uri), binding);
      }
       
        return scriptSource;
    }
```

No pull requests until you suggest a direction. ;)

**Comment by ctoestreich** [comment] 2015-12-21 20:29
The title of this should be <b>Can't render template from plugin whose name uses camel case when specifying plugin="theName" in render block</b>

@kdickerson You should rename your plugins for now... what problems could that possibly cause... :laughing:

**Comment by ctoestreich** [comment] 2016-01-12 22:25
See comment in #9545 for additional details on places this is breaking.

**Closed** 2016-01-13 08:36 UTC

**Comment by danleahy** [comment] 2016-07-16 14:59
This bug is not fixed, leaving out the plugin attribute is not a fix.

i am getting the same errror when not using camelcase names

**Comment by ctoestreich** [comment] 2016-07-16 17:27
@danleahy do you have an example project where this breaks?

**Comment by danleahy** [comment] 2016-07-16 19:22
Hi,
    zip of example project that shows the issue is attached to

Issue  #10047

Regards,
                  Daniel.
