### ISSUE TITLE
Asset pipeline links missing cache digest names

### ISSUE THREAD

**Issue by dpilafian** [grails/grails-core#9100] opened 2015-07-11 07:32 UTC
With **Grails 3.0.3** links to assets look to be created as plain file names instead of their expected cache digest names.

Example:

    <link rel="stylesheet" href="/assets/application.css"/>

instead of something like:

    <link rel="stylesheet" href="/assets/application-49484e7b1391d107c5fc3cc2921733ec.css"/>

#### Reproduce:

The issue can be reproduced in a plain default application:
```
$ grails --version
| Grails Version: 3.0.3
| Groovy Version: 2.4.3
| JVM Version: 1.8.0_45
$ grails create-app app303
$ cd app303
$ grails package
$ java -Dgrails.env=prod -jar build/libs/app303-0.1.jar
Grails application running at http://localhost:8080 in environment: production
```

```
$ curl --silent http://localhost:8080 | grep stylesheet
   <link rel="stylesheet" href="/assets/application.css"/>
```

#### Expect:

Under **Grails 3.0.2**, the above steps for `app302` result in the expected:

```
$ curl --silent http://localhost:8080 | grep stylesheet
   <link rel="stylesheet" href="/assets/application-49484e7b1391d107c5fc3cc2921733ec.css"/>
```

#### Environment:

    Darwin Blade.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Comment by graemerocher** [comment] 2015-07-11 08:34
@davydotcom Any idea what could cause this?

**Comment by graemerocher** [comment] 2015-07-11 08:35
@dpilafian Does using `asset-pipeline` 3.0.1 help in `build.grade`?

**Comment by dpilafian** [comment] 2015-07-13 00:08
Yes.  The cache digest names are generated for `app303` after updating `build.gradle` by replacing:

    runtime "org.grails.plugins:asset-pipeline"

with:

    runtime "org.grails.plugins:asset-pipeline:3.0.1"

**Comment by graemerocher** [comment] 2015-07-13 07:13
Ok seems like a bug in the latest asset pipeline

**Comment by graemerocher** [comment] 2015-07-14 07:32
@davydotcom pushed a fix here https://github.com/bertramdev/asset-pipeline/commit/c467c14de8d39dbb0bf65c5e3294c4dac48ca849

**Closed** 2015-07-29 07:02 UTC
Labels: Acknowledged, Blocker

**Comment by davydotcom** [comment] 2015-07-30 14:03
seems fine in jar: http://bertram.d.pr/16q0e

**Comment by graemerocher** [comment] 2015-07-30 14:05
@davydotcom Yeah `java -jar` works the problem is when deploying to Tomcat it seems (see #9151), also #9145 is a separate bug

**Comment by davydotcom** [comment] 2015-07-30 14:06
yea ill try and get these fixed before my talk this afternoon ;)
