### ISSUE TITLE
Grails 3.0.4: After method in Interceptors does not allow response when set to FALSE

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9175] opened 2015-08-09 17:59 UTC
When setting FALSE in 'after' method in interceptor, I was previously able to still send a REST response (even if I was not sending to a view). This is acceptable form as we don't want to use a view but want the postHandle (aka 'after' method) to handle and be able to pass back to preHandle (aka 'before') should it need to on a redirect.

Currently in Grails 3.0, 'after' cannot handle response as even if I put 'return false' prior to response, it will still expect a view if a response is given.

Example...

if(content){
    //respond content.apiToolkitContent, [formats:['xml', 'json']]
    response.getOutputStream().print(content.apiToolkitContent)
    return false
}

One can duplicate this by simply 'returning' data from controller/method (do not use respond or render) and then try and output response but NOT a view. The grailsDispatcherServlet will then throw an error.

Sample interceptor viewable here... https://github.com/orubel/api-framework/blob/master/grails-app/controllers/net/nosegrind/apiframework/ApiFrameworkInterceptor.groovy

**Comment by orubel** [comment] 2015-08-09 20:54
I can see in the 'GrailsInterceptorHandlerInterceptorAdapter/postHandle' how it gets used but for some reason, the Handlerinterceptor 'after' method in a plugin cannot have a response sent from it otherwise 'return false' is not seen or is ignored .

**Comment by orubel** [comment] 2015-08-09 21:37
Ok so I take it back... loks like it is hitting GrailsInterceptorHandlerInterceptorAdapter as the view name and view are both NULL; it's the 'grailsDispatcherServlet' that is complaining.

Getting back an error as follows:

ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [ModelAndView [ModelAndView: materialized View is [null]; model is {post=Post : 1}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: ModelAndView [ModelAndView: materialized View is [null]; model is {post=Post : 1}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'

**Comment by orubel** [comment] 2015-08-10 03:33
The full error I get back from bootRun when calling an api is as follows:

ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [ModelAndView [ModelAndView: materialized View is [null]; model is {post=Post : 1}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: ModelAndView [ModelAndView: materialized View is [null]; model is {post=Post : 1}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1235) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) ~[spring-webmvc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-emb-8.0.20.jar:8.0.20]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291) ~[spring-boot-actuator-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102) ~[spring-boot-actuator-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:73) ~[grails-web-mvc-3.0.1.jar:3.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-c.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67) ~[grails-web-mvc-3.0.1.jar:3.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90) ~[spring-boot-actuator-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) ~[tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalinStandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
> Building 83% > :bootRun

**Comment by orubel** [comment] 2015-08-11 04:12
Closing issue. Will just output with response.printWriter

**Comment by jeffbrown** [comment] 2015-08-11 04:50
@orubel 

> This is acceptable form as we don't want to use a view but want the 'after' method to handle and be able to pass back to 'before' should it need to.

What do you mean by "pass back to before"?

**Comment by orubel** [comment] 2015-08-11 12:35
well a redirect should pass back to the urlmapping which checks where to route which then sends to handlerInterceptor beforeHandler if there is a handlerInterceptor for it

**Comment by orubel** [comment] 2015-08-11 12:42
shoot. I'm trying to use print writer to output this and I still see that modelview error even though I am getting back a correct response.

**Comment by jeffbrown** [comment] 2015-08-11 13:25
> well a redirect should pass back to the url mapping

I am having trouble understanding how all of this fits together.  From your `after` method are you trying to issue a redirect, write to the response or something else?  I thought you were trying to right content to the response but I now think that I misunderstood.

Thanks for clarification.

**Comment by orubel** [comment] 2015-08-11 13:31
No not right now. Thats just potential functionality. Right now the only thing I am trying to solve is getting a response back from controller...

def show(){
    def post = Post.get(params.id.toLong())
    if(post){
        LinkedHashMap model = ['post':post]
        return model
    }
    return null
}

... process that through preHandle, then through postHandle and then return response WITHOUT a view.

Cannot use 'respond' as that formats response and want formatting to be separate

**Comment by jeffbrown** [comment] 2015-08-11 13:40
> Right now the only thing I am trying to solve is getting a response back from controller

There is a bunch of stuff in this issue that isn't related to that.  I am going to close the issue for now. Please post a question on the mailing list describing what it is you want to be able to do and if that discussion leads to a specific feature request or bug report, I will open a corresponding issue.

Thanks for the feedback.

**Closed by jeffbrown** 2015-08-11 13:40 UTC

**Comment by orubel** [comment] 2015-08-11 13:44
Is this be closed because this isn't an issue...

ModelAndView [ModelAndView: materialized View is [null]; model is {post=Post : 1}] neither contains a view name nor a View object in servlet with name 'grailsDispatcherServlet'] with root cause

**Comment by jeffbrown** [comment] 2015-08-11 13:49
> Is this be closed because this isn't an issue... or that I'm not explaining it well...

The latter, but not just that you aren't explaining it well.  There are several pieces of the discussion here which don't fit together as far as I can tell and I would like to have a better understanding of the actual problem(s).

Please post a question on the mailing list describing what it is you want to be able to do and if that discussion leads to a specific feature request or bug report, I will open a corresponding issue.

Thanks for the feedback.

**Comment by orubel** [comment] 2015-08-11 14:11
What if I simplify like this... returning from controller like below...

def show(){
    def post = Post.get(params.id.toLong())
    if(post){
        LinkedHashMap model = ['post':post]
        return model
    }
    return null
}

causes error above in handlerInterceptor/before?

Is this better?

**Comment by jeffbrown** [comment] 2015-08-11 16:01
@orubel 

> causes error above in handlerInterceptor/before?

After that action executes there will not be any before interceptor invoked.  It isn't clear what any of that has to do with a redirect.

If you will provide a simple sample app which demonstrates problematic behavior I will be happy to look at that.

**Comment by orubel** [comment] 2015-08-11 16:06
I'm sorry... I mispoke. I meant handlerInterceptor/after (postHandle) as thats where you get the ModelAndView. I'll put up a sample app in a couple seconds.

**Comment by jeffbrown** [comment] 2015-08-11 16:07
>  I mispoke. I meant handlerInterceptor/after (postHandle) as thats where you get the ModelAndView. I'll put up a sample app in a couple seconds.

That will be a giant help.  I will look at that tonight.

Thanks.

**Comment by jeffbrown** [comment] 2015-08-11 16:08
Can you also clarify how redirect factors in?

**Comment by orubel** [comment] 2015-08-11 16:35
well (as an example) when I  do 'batch api processing' I detect in postHandle if(sent params are list && batch==true) then we pop from param.list and redirect back to original method until param.list is empty

this saves developers from having to implement batch processing in EVERY controller method; they simply provide a variable in a properties file declaring the method as 'batchable'.

**Comment by orubel** [comment] 2015-08-11 16:38
Ok so I just uploaded a project that uses the api-framework plugin I'm building out; this demo's a full api abstraction layer for distributed architectures. (https://github.com/orubel/api-framework-example)

**Comment by jeffbrown** [comment] 2015-08-11 16:38
Thanks.  Will investigate.

**Comment by jeffbrown** [comment] 2015-08-11 16:59
@orubel If you can describe a simple way to invoke the problematic behavior that will be helpful.

Thanks again.

**Comment by orubel** [comment] 2015-08-11 22:40
Oh I should mention, I've only been testing by curling GET 'localhost:8080/api_v0.1/post/show/1' so far as the others have render/response on them still. I can dump a simple data structure too if needed to save you some time.

**Comment by jeffbrown** [comment] 2015-08-12 00:24
@orubel There is a bunch of stuff in that project that doesn't make sense to me.  I don't see any interceptors.  The UrlMappings is empty.  The application won't even run because of unresolvable dependencies.  I can tell from looking at it that figuring out whatever the issue is is going to call for more time than I can invest in the thing.  I am sorry that I can't help.

Please post a question on the mailing list describing what it is you want to be able to do and if that discussion leads to a specific feature request or bug report, I will open a corresponding issue.

**Comment by orubel** [comment] 2015-08-12 04:01
Its because that the example project... the actual code lies in the api-framework plugin I'm working on (https://github.com/orubel/api-framework) That project I sent you just implements the plugin.

This is why I'm having a bit of an issue trying to explain it to you; it's not cut and dry.

The handlerInterceptor is being pulled from a plugin and the api management and handling is all being done through services in there. They can be done better but I am just trying to get things done in a spring-boot/grails 3.0 way first and THEN optimize.

**Comment by orubel** [comment] 2015-08-12 04:21
I'm a bit puzzled. I mentioned in the original bug post up above that the handlerInterceptor was in the api-framework project.

I then sent you a link to a project called 'api-framework-example' which used it as part of the gradle build. 

I believe you even cloned the api-framework the other day. So I'm puzzled why we keep having this miscommunication.

I'm doing everything I can to literally point you directly at my interceptor; providing the link, providing the project, providing examples, providing the error output.

You tell me what you need from me and I will help you to help me.

**Comment by orubel** [comment] 2015-08-12 04:28
Also I'm a little frustrated because you closed the bug saying that I didn't explain it well and then came back and didn't even look where I originally pointed in the bug description and just gave up.

I understand I'm doing something 'odd' and 'different' but a return from a controller should still be able to be handled by a HandlerInterceptor/postHandle without throwing that error.

It is still a bug. You don't have to like what I'm doing or even like me, but if this is a testable bug, at least check it out.

I'll acknowledge that I'm not going to get help and work on a workaround.

**Comment by Schlogen** [comment] 2015-08-12 04:28
@orubel When you provide an example project, you want to have the simplest project possible that demonstrates the problem. Providing a project that isn't able to be run is no benefit to the team that is trying to help. If providing the simplest possible project means you need to rip code out of your plugin, then do so.

**Comment by orubel** [comment] 2015-08-12 04:29
I understand, this was just what I had handy.

**Comment by Schlogen** [comment] 2015-08-12 04:30
@orubel That isn't very respectful of other people's time

**Comment by orubel** [comment] 2015-08-12 04:35
I apologize if it comes across disrespectful as it is not meant to be. I'm wording this to be very respectful as I have respect for the talented people who put all their time and effort into Grails.

I am merely trying to file a bug report and no one stated 'this is broken'. You are stating 'it was broken' which was not the feedback that was given. The feedback that was given when asked was that the ticket was closed because I didn't explain it well.

And it is difficult to explain api abstraction to people who are used to an api pattern wherein the api is bound to the business logic. So I don't even try. I just attempt to explain how the projects talk to each other, forwards, redirects and the classes involved.

This can confuse people just as much.

**Comment by orubel** [comment] 2015-08-12 04:48
And what I meant by the statement : 'I'll acknowledge I'm not going to get help and work on a workaround' was to say 'I'll stop being a pest'. Of course you are right... that was a VERY rude way to say it. For that I am sorry. So I'm just going to shutup and go away.

**Comment by jeffbrown** [comment] 2015-08-12 12:03
> Right now the only issue I have is that when the controller in the implementing project passes a resource back to the handlerInterceptor that is served from the plugin, it throws that error at the postHandle.

I don't know what "passes a resource back to the handlerInterceptor" means.

> I then sent you a link to a project called 'api-framework-example' which used it as part of the gradle build.

I thought that was going to be helpful but it I can't figure out how to make it helpful.  I can't find any code in that project that I can identify as being related to the problematic behavior.  I am not saying that it isn't there, but I don't know what it might be.

> I believe you even cloned the api-framework the other day. So I'm puzzled why we keep having this miscommunication.

I did clone your project, last night from home, because I wanted to try and help you.  Looking at the code in that project didn't help me understand what the problem is.

>  You tell me what you need from me and I will help you to help me.

Please post a question on the mailing list describing what it is you want to be able to do and if that discussion leads to a specific feature request or bug report, I will open a corresponding issue.

I am not saying that there isn't a bug.  I am saying that I don't understand what you are saying.  That is not your problem.  It is mine.  I have asked several times for your to post a question to the mailing list describing what it is that you want to be able to do.  If you would do that, I will help you sort it out.

**Comment by jeffbrown** [comment] 2015-08-12 12:09
To possibly save some people some time who might try to investigate what is going on here note that some of the links @orubel provided above are currently broken because the repo appears to have been deleted.  I have a fork of the code at https://github.com/jeffbrown/api-framework-example which may prove useful in tracking the problem down.

**Comment by jeffbrown** [comment] 2015-08-12 12:12
@orubel 

> Also I'm a little frustrated because you closed the bug saying that I didn't explain it well and then came back and didn't even look where I originally pointed in the bug description and just gave up.

I am not sure why you thought I have given up.  I am still trying to figure it out.  I have not given up.

**Comment by orubel** [comment] 2015-08-12 13:35
A 'resource' is what is sent back from an api call and what is commonly requested when making an api call. It is built in the business logic (ie controller) and is an object which can consist of a domain object, command object, list, map, file, etc

In Spring, the controller will pass back the 'resource' as a ModelMap in the ModelAndView from the controller the the postHandle() in the HandleInterceptor where it can be processed further before sending to the View.

If no view, the ModelMap is commonly returned to the client.

**Comment by jeffbrown** [comment] 2015-08-12 13:46
> A 'resource' is what is sent back from an api call and what is commonly requested when making an api call. It is built in the business logic (ie controller) and is an object which can consist of a domain object, command object, list, map, file, etc

> In Spring, the controller will pass back the 'resource' as a ModelMap in the ModelAndView from the controller to the postHandle() in the HandleInterceptor where it can be processed further before sending to the View.

Can you show me the simplest HandleInterceptor that demonstrates the problematic behavior?

**Comment by orubel** [comment] 2015-08-12 13:59
I can try.

Owen Rubel
415-971-0976
orubel@gmail.com

**Comment by jeffbrown** [comment] 2015-08-12 14:41
@orubel 

> I can try.

Great.  That will be helpful.  I asked for the simplest example.  Really any example that I can run and see the problematic behavior will be helpful.  If you have trouble creating a simple one, if you can share any project which I can run on my machine to see the problem, that would be a big help.

**Comment by orubel** [comment] 2015-08-12 15:50
I'll build out a simple application with handler interceptor that demos it tonight. Just tested it with ModelAndView with only a model in it (no view or viewName) as well as just a simple 'return ['post':post]' in the controller which both create the same object and they through an identical error.

This is wherein the problem lies; the 'return ['post':post]' in Controller creates a ModelMap but the 'false' in the postHandle of the handlerInterceptor which is supposed to tell it NOT TO RENDER A VIEW, throws the error because the class expects a fully created ModelAndView... not just a returned Model.

**Comment by jeffbrown** [comment] 2015-08-12 16:20
@orubel 

> I'll build out a simple application with handler interceptor that demos it tonight. 

Great.  That will be helpful.

**Comment by jeffbrown** [comment] 2015-08-12 16:59
>  In which case, passing a model and setting 'true' in postHandle would result in blank view I would assume.

One thing that that isn't clear to be is what you mean by "setting true" there.  `postHandle` doesn't have a return value so I expect you are setting the property of something to true, but I don't know what that might be.  Can you clarify?

**Comment by orubel** [comment] 2015-08-12 17:07
in the Grails 3.0 documentation for Interceptors (which is an extension of HandlerInterceptor), the Interceptor implementation of Interceptor/before (preHandle) and Interceptor/after (postHandle) both return a boolean. The boolean in Interceptor/after is meant to declare 'no view rendering' according to documentation.

**Comment by jeffbrown** [comment] 2015-08-12 17:12
So you are writing a Grails Interceptor, not a `HandlerInterceptor` directly.  If so, are you doing anything at all with `HandlerInterceptor` directly?  Do you have a `postHandle` method anywhere in your application or in any plugin that your application is using?

**Comment by jeffbrown** [comment] 2015-08-12 17:15
I am still trying to clarify what you mean by the following:

> In which case, passing a model and setting 'true' in postHandle would result in blank view I would assume.

If by "setting `true` in `postHandle`" you mean "returning `true` from `after()`", then I don't think a blank view would be expected.  I think returning `true` from `after()` is supposed to cause the view to be rendered as per usual.

**Comment by orubel** [comment] 2015-08-12 17:19
No. Just using that terminology as last time I used the term Interceptor, I
remember you confusing with Controller Interceptor and Graeme stepped in
and said 'he's talking about a HandlerInterceptor' which he meant is the
new Interceptor that replaces filters which extends HandlerInterceptor

I'm merely trying to avoid ongoing confusion that we continue to have; the
term Interceptor is applied in two places and we had this confusion before
and as Graeme attempted to clear it up by calling it HandlerInterceptor, I
used his terminology in hopes that would be clearer.




Owen Rubel
415-971-0976
orubel@gmail.com

On Wed, Aug 12, 2015 at 10:12 AM, Jeff Scott Brown <notifications@github.com

**Comment by orubel** [comment] 2015-08-12 17:20
I apologize... I meant false.

Owen Rubel
415-971-0976
orubel@gmail.com

On Wed, Aug 12, 2015 at 10:15 AM, Jeff Scott Brown <notifications@github.com

**Comment by jeffbrown** [comment] 2015-08-12 17:26
> I apologize... I meant false.

Is the whole problem here that if your controller action returns a model and the after interceptor returns `false` that the system is still trying to render a view?

**Comment by orubel** [comment] 2015-08-12 17:38
Not necessarily. I send back only a Model... no view or viewName as you can
see from the error. Which causes a bad ModelAndView error.

The bug appears to center around ModelAndView being required from
controller and not being able to send Model:

1) cannot handle  just a Model being returned; will throw model and view
error because View and Viewname are empty in ModelAndView
2) response.getWriter().print('something'), this will throw and printwriter
error if you attempt to output response.
3) render prior to 'return false' will actually attempt to render page;
boolean might be better if sent to method and intercepted (ie
after(false){} )


Owen Rubel
415-971-0976
orubel@gmail.com

On Wed, Aug 12, 2015 at 10:26 AM, Jeff Scott Brown <notifications@github.com

**Comment by jeffbrown** [comment] 2015-08-13 02:04
@orubel 

> I'll build out a simple application with handler interceptor that demos it tonight.

Are you still planning to do that?

Thanks again for your help.

**Comment by orubel** [comment] 2015-08-13 03:54
https://github.com/orubel/testapp

Simple app and its still duplicating the bug. No database. Just sending a map back from a API request.... but it's very easy to see what is happening.

**Comment by orubel** [comment] 2015-08-13 04:18
there we go sorry about that. forgot to merge the readme. Its up there now.

**Comment by jeffbrown** [comment] 2015-08-13 09:11
The code at https://github.com/orubel/testapp/blob/6ac0a070602208472423624c85fc19f4bf1f8df4/grails-app/controllers/TestappInterceptor.groovy#L27 is throwing a `MissingPropertyException` because `apiResponseService` is undeclared.  If I fix that, then I can recreate the problem.

**Comment by graemerocher** [comment] 2015-08-13 09:15
@jeffbrown So this should be reopened now that we have an example?

**Comment by jeffbrown** [comment] 2015-08-13 09:35
@graemerocher I created #9183 which references this issue.  I think there is a lot of info in this issue that obfuscates the problematic scenario, for me anyway.

@orubel Thanks for your help.
