### ISSUE TITLE
grails run-app and grails war produce different functioning applications

### ISSUE THREAD

**Issue by donald-jackson** [grails/grails-core#9836] opened 2016-03-30 20:17 UTC
When running my application using grails-app - everything functions as I expect it to. I have layouts/views/templates in my main application which intentionally override views and layouts from plugins (for example this login screen, which overrides the spring-security one)

Using grails run-app:

![screenshot 2016-03-30 21 56 32](https://cloud.githubusercontent.com/assets/605195/14155509/521af2be-f6c2-11e5-8bfe-4393fd731a36.png)

Using grails war & then saving as ROOT.war on Tomcat.

![screenshot 2016-03-30 21 59 48](https://cloud.githubusercontent.com/assets/605195/14155634/cfdfb7f2-f6c2-11e5-9b35-d9af2416f5b2.png)

Which then gets exploded to ROOT directory, and the tree structure looks as follows as in the attachment
[root_files.txt](https://github.com/grails/grails-core/files/196366/root_files.txt)

You will see the file looks nothing like the one rendered (looks like the default spring security one)

	[tomcat@centos7-builder webapps]$ cat ROOT/WEB-INF/classes/gsp_prizecloud_loginauth_gsp_html.data
	<html>

	    

	)
	<div class="col-lg-5 col-sm-6">
	    <h1>
	        </h1>

	    )
	        <div class='alert alert-danger'>
	                                        </div>
	    

	    <form action='x' method='POST' autocomplete='off' name="loginForm">
	        <div class='form-group'>
	            <label for='username'>?</label>
	            <input type='text' class='form-control' name='username' id='username'/>
	        </div>

	        <div class='form-group'>
	            <label for='password'>?</label>
	            <input type='password' class='form-control' name='password' id='password'/>
	        </div>

	        <div class='checkbox'>

	            <label for='remember_me'><input type='checkbox' name='' id='remember_me' checked='checked'/> Y</label>
	        </div>

	        <p>
	            <input type='submit' id="submit" value=')' class="btn btn-primary"/>

	            ?
	        </p>
	    </form>
	</div>
	<script type='text/javascript'>
	    
	</script>
		
	</html>

Rendered html (from view source): 
![screenshot 2016-03-30 22 15 37](https://cloud.githubusercontent.com/assets/605195/14156098/f50b693e-f6c4-11e5-8aa4-6c95a6d35c5f.png)

I basically believe I have taken all necessary steps to rule out human error here but I won't say its impossible. The project being built has no inline plugins and all private plugins have been cleaned and rebuilt using grails 3.0.15.

Grails 3.0.15
Java 1.8.0_77
Linux CentOS 7
Tomcat 8.0.33

**Comment by donald-jackson** [comment] 2016-03-30 23:23
I've tried everything here - changed to Grails 3.0.11, slightly older versions of Tomcat (8.0.30) and Java (1.8.0_65) and nothing, behaviour persists.

**Comment by donald-jackson** [comment] 2016-03-31 09:43
So I believe I have narrowed down the problem - out of the box when using application.yml the applications function correctly, but when changing this to application.groovy based config things start going wrong.

Demonstration project here: https://github.com/donald-jackson/grails-view-error-demo

When running grails run-app and visiting http://localhost:8080/login/auth you will see a page like this:

![screenshot 2016-03-31 11 37 57](https://cloud.githubusercontent.com/assets/605195/14171788/0ce7bd80-f735-11e5-8365-f3ee77770455.png)

When running via tomcat after grails war, you'll get this:

![screenshot 2016-03-31 11 42 29](https://cloud.githubusercontent.com/assets/605195/14171891/aced3fe4-f735-11e5-84af-fd256a0ad097.png)

I'm going to attempt to refactor my original project to a .yml file and perhaps that will solve my problems.

**Comment by donald-jackson** [comment] 2016-03-31 10:33
I can confirm refactoring my original application to an application.yml did solve this problem, leaving me to suspect that application.groovy is being overridden by other plugins etc's .yml files.

**Comment by jeffbrown** [comment] 2016-03-31 17:27
I expect that this is a duplicate of #9647

**Comment by graemerocher** [comment] 2016-04-11 10:05
This was a bug in the GSP plugin, not exactly sure why `application.groovy` vs `application.yml` impacted the issue, it was a simple matter of the order of plugin view loading being incorrect.

**Closed by graemerocher** 2016-04-11 10:05 UTC
Labels: Blocker

**Comment by donald-jackson** [comment] 2016-04-12 13:58
Thanks @graemerocher
