### ISSUE TITLE
Unable to create a deployable WAR from example

### ISSUE THREAD

**Issue by wuwu2000** [grails/grails-core#12346] opened 2022-01-18 17:53 UTC
### Expected Behavior

Call `gradlew assemble`, put .war into tomcat webapps folder and start

### Actual Behaviour

- With settings `spring.main.allow-bean-definition-overriding=false` I get a exception Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'characterEncodingFilter' defined in null: Cannot register bean definition [Generic bean: class [org.springframework.boot.web.servlet.FilterRegistrationBean]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'characterEncodingFilter': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration; factoryMethodName=characterEncodingFilter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/HttpEncodingAutoConfiguration.class]] bound.
- With settings `spring.main.allow-bean-definition-overriding=true` there are some circular dependencies.
- With depenendy org.springframework.boot:spring-boot-starter-tomcat as `runtimeOnly` instead `implementation` class `jakarta.annotation.PreDestroy` not found

### Steps To Reproduce

```
grails
create-app
CTRL+C
gradlew assemble
```

App runs with `gradlew bootRun` 

### Environment Information

Build environment windows both tried with jdk8 and 11 (16 doesn't seem to work at all). Also tried with some unix docker build slave under jdk 8

### Version

5.1.1

**Comment by puneetbehl** [comment] 2022-01-18 18:22
It seems duplicate of #12288

**Closed as completed by puneetbehl** 2022-01-18 18:22 UTC
Labels: closed: duplicate

**Comment by wuwu2000** [comment] 2022-01-18 19:07
can confirm 5.1.2-SNAPSHOT is working. Is every version 5.0.0 >= n < 5.1.2 broken?
