### ISSUE TITLE
Deep marshaling of simple objects gives wrong output

### ISSUE THREAD

**Issue by sashasch** [grails/grails-core#10325] opened 2016-11-21 08:47 UTC
Migrated from Grails 3.1.6 to Grails 3.2.3. Deep marshaling of simple objects which worked normally in 3.1.6 not works more.

### Task List

- [V ] Steps to reproduce provided
- [V ] Example that reproduces the problem present
- [ V] Full description of the issue provided (see below)

### Steps to Reproduce

**1. Create simple controller:**
```
class TestMarshalingController {
	static responseFormats = ['json', 'xml']

    class LikeMap extends HashMap<String, String> {

    }

    class ListLikeMaps {
        List<LikeMap> likeMaps = new ArrayList<>()
    }
	
    def ListLikeMaps index() {
        def likeMap = new LikeMap()
        likeMap["someKey1"] = "some value1"
        likeMap["someKey2"] = "some value2"
        likeMap["someKey3"] = "some value3"
        def listLikeMaps = new ListLikeMaps()
        listLikeMaps.likeMaps << likeMap
        def w = new StringWriter()
        def json = new groovy.json.StreamingJsonBuilder(w, listLikeMaps)
        println w
        respond listLikeMaps
    }
}
```
**2. Call the action** [testMarshaling](http://localhost:8080/testMarshaling)
It prints to console:
Grails application running at http://localhost:8080 in environment: production
{"likeMaps":[{"someKey3":"some value3","someKey2":"some value2","someKey1":"some value1"}]}

### Expected Behaviour

The browser response should be same as printed out:
{"likeMaps":[{"someKey3":"some value3","someKey2":"some value2","someKey1":"some value1"}]}

### Actual Behaviour

The browser response is:
{"likeMaps":[{}]}

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.3
- **JDK Version:** 1.8.0_77
- **Execution Method:** Grails project on Intellij Idea 2016.2.5. Application -> Debug

### Example Application

- Provided

**Comment by jameskleeh** [comment] 2016-11-23 04:05
Duplicate of https://github.com/grails/grails-views/issues/96

**Closed** 2016-12-08 19:31 UTC
