### ISSUE TITLE
Grails 3.0.8 integration test rollback 'No Session found for current thread'

### ISSUE THREAD

**Issue by olliefreeman** [grails/grails-core#9304] opened 2015-09-30 08:31 UTC
I'm not sure what version of grails 3 this started happending as I have been updating however I am using 3.0.8 and I have verified I have the same issue in 3.0.7 but running 

`test-app uk.ac.ox.ndm.lrd.domain.v0_2.endpoint.coreclinical.xxx.XxxControllerSpec -integration`

and I'm getting the exception

```
org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:1014)
	at org.grails.orm.hibernate.validation.HibernateDomainClassValidator.validate(HibernateDomainClassValidator.java:64)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:140)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:165)
	at uk.ac.ox.ndm.lrd.domain.v0_2.endpoint.coreclinical.xxx.XxxControllerSpec.$tt__setupData(XxxControllerSpec.groovy:93)
	at uk.ac.ox.ndm.lrd.domain.v0_2.endpoint.coreclinical.xxx.XxxControllerSpec.setupData_closure1(XxxControllerSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:67)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
	at uk.ac.ox.ndm.lrd.domain.v0_2.endpoint.coreclinical.xxx.XxxControllerSpec.$tt__$spock_feature_0_1(XxxControllerSpec.groovy:106)
	at uk.ac.ox.ndm.lrd.domain.v0_2.endpoint.coreclinical.xxx.XxxControllerSpec.test list with data_closure3(XxxControllerSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:67)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:64)
	at uk.ac.ox.ndm.lrd.domain.v0_2.endpoint.coreclinical.xxx.XxxControllerSpec.test list with data(XxxControllerSpec.groovy)
```

The class was generated using `create-integration-test` and is annotated with `grails.test.mixin.integration.Integration` and `grails.transaction.Rollback`

**Comment by graemerocher** [comment] 2015-09-30 08:39
Please upload an example that reproduces the problem.

**Comment by olliefreeman** [comment] 2015-09-30 08:46
i'll put one together, unfortunately I can't upload the actual code I'm using....so hoping I can reproduce it in a new project. I assume you only need the bare minimum of classes

**Comment by graemerocher** [comment] 2015-09-30 08:47
yes please.. thanks.

**Comment by olliefreeman** [comment] 2015-09-30 09:08
I've created a clean grails app and added all the dependencies I'm using in my project and added a simple domain to reproduce the issue...i suppose happily it is reproduceable

https://github.com/olliefreeman/rollover-issue

**Comment by graemerocher** [comment] 2015-09-30 09:18
Thanks

**Comment by olliefreeman** [comment] 2015-10-01 09:50
I have updated the name of the repo holding the example: (sorry for any resulting hassle)

https://github.com/olliefreeman/grails-issues

**Comment by olliefreeman** [comment] 2015-10-08 09:56
it would also appear that rollback isn't actually rolling back the DB. Using restful interface and using 'POST' to the URL the save is working but its remaining in the DB after the test

**Comment by graemerocher** [comment] 2015-10-13 10:25
With the example referenced I get 

```
Caused by: java.lang.AbstractMethodError: org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.getConfigurationValues()Ljava/util/Map;
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:404) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844) ~[hibernate-entitymanager-4.3.8.Final.jar:4.3.8.Final]
```

In addition, `@Rollback` is designed to be used when testing services that don't yet have a transaction present. You seem to want to mix persistence integration testing with calling out to REST web services (i.e. functional tests) which is not supported right now.

**Comment by kschmit90** [comment] 2015-10-20 14:49
I am having the same issue running integration tests in 3.0.9.

Have a reproducing example.

https://github.com/kschmit90/IntegrationTestNoSessionFound309

**Comment by longwa** [comment] 2015-10-23 19:41
I'm also having this problem with 3.0.9 and integration tests.

**Comment by graemerocher** [comment] 2015-10-24 09:53
@kschmit90 your example saves a domain instance in the setup() method where a transaction is not present. hence the error

**Comment by kschmit90** [comment] 2015-10-24 16:08
@graemerocher Ah, yeah I see that now in the docs... -_-

**Comment by olliefreeman** [comment] 2015-10-28 12:10
@graemerocher I just ran the test to see if i got the same error as you, however

`test-app rollback.issue.RollbackControllerSpec -integration`

definitely still gives me the `org.hibernate.HibernateException: No Session found for current thread` exception. 

I'm running it with grails 3.0.9, and just starting grails then running the command. Not sure why you're getting a different error.

I understand the rollback won't work with the rest calls, its more the fact i can't save data or make GORM calls such as `Rollback.list()` inside the tests, which means I can't actually preload the database with information and then make calls to retrieve it. This may not actually be a rollback annotation issue but an integration annotation issue. 

I know I can't do it in the setup() method but then why can't I do it in the test methods?

**Comment by graemerocher** [comment] 2015-11-30 13:37
Closing this as I cannot reproduce.

**Closed by graemerocher** 2015-11-30 13:37 UTC
Labels: Awaiting Feedback, Cannot Reproduce, Example Attached

**Comment by circadence-andrew** [comment] 2015-12-07 16:03
I have another example application that I believe reproduces this issue, if that helps: https://github.com/circadence-andrew/grails3-issues.

It seems like it could be related to issue 378 from grails-spring-security-core as well.

If the line containing `compile "org.hibernate:hibernate-entitymanager"` in build.gradle is commented out, the integration test passes.  If it's present, then the integration test fails, but I'm not sure why.  That line was added because it's a dependency of `compile "org.jadira.usertype:usertype.extended:4.0.0.GA"`, which although it is not explicitly used in the sample application linked, it is used by the application where I first observed this.

**Comment by shutyaev** [comment] 2016-04-28 20:40
I can confirm this too. Steps to reproduce:

- create a new grails project
- add `spring-security` plugin
- run `grails s2-quickstart`
- add some user (e.g. via `Bootstrap.groovy`)
- create a `@Secured` page

At this point everything works fine. Secured page redirects to login, login succeeds. Now if you add

`compile 'org.jadira.usertype:usertype.extended:5.0.0.GA'`

to `build.gradle`, login stops working. The root cause exception is

`org.hibernate.HibernateException: No Session found for current thread`

Full stacktrace: [stacktrace.txt](https://github.com/grails/grails-core/files/241403/stacktrace.txt)

Now, as @circadence-andrew pointed out, the problem seems to be in `org.hibernate:hibernate-entitymanager`, which is a transitive dependency of `org.jadira.usertype:usertype.extended`. If you exclude this dependency, everything starts working fine:

`compile('org.jadira.usertype:usertype.extended:5.0.0.GA') {`
`     exclude group: 'org.hibernate', module: 'hibernate-entitymanager'`
`}`

**Comment by edwardotis** [comment] 2016-11-16 20:39
@shutyaev 
Thank you! 
I've been trying to migrate from grails 2.5.5 to 3.1.14, and this was the root cause of my errors within spring-security-core and 
`org.hibernate.HibernateException: No Session found for current thread error. 
`
I'm using Hibernate4, and the exclusion works correctly for 4.0.0.GA as well.

```
compile('org.jadira.usertype:usertype.extended:4.0.0.GA') {
exclude group: 'org.hibernate', module: 'hibernate-entitymanager'
}
```
