### ISSUE TITLE
Grails 3.0.12 - Added params/attributes/sessions not being passed when forwarded through RequestForwarder

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9597] opened 2016-01-27 16:28 UTC
Per ticket #9539 that was closed, Graeme stated:

> Rather than params you should be using request attributes to do what you want to achieve. Mutating params if a forward is not possible at the servlet container level

I tried using attributes and even sessions (an extension of request.attributes) but neither will forward; the forward seems to be resending original request. Hence any changes to attributes are ALSO LOST.

If attributes are expected to be used or even session variables, then this is broken behaviour and is a blocker as same behaviour with params exists with attributes.

Can someone suggest standardized behaviour for sending variables with forward as one would with regular request as a fix? I'm a bit desperate at this point and have rewritten code several times per suggestions by team. And am completely blocked.

Previously this functionality all worked fine in 2.x and could forward params and session variables

**Comment by orubel** [comment] 2016-01-27 19:18
This is a serious blocker right now as any params, attributes or session variables cannot be forwarded and in previous versions of grails they could and it would make sense that we should be able to at least INCREMENT with each forward or update session or something similar.

This is very broken behaviour.

**Comment by orubel** [comment] 2016-01-28 16:40
The reason why some kind of param needs to persist in a forward vs a redirect is because this keeps the process CPU bound rather than with a redirect which makes it IO bound. With a forward, we can enable better automation with batching, shared state, decrease the number of requests, improve processing and syncronization.

I'm willing to accept any kind of work around. But this is a tremendous blocker that changes to sessions/attributes/params cant persist through a forward.

**Comment by graemerocher** [comment] 2016-01-28 16:50
It seems odd to me that request attributes do not survive the forward, I don't believe this to be the case and in fact the following example works fine for me:

    package forwardtest

    class ForwardController {

        def index() { 
            request.test = "bar"
            forward action:'two'
        }

        def two() {
            render "good ${request.test}"
        }

    }

So if you're having issues I can only suggest uploading an example that reproduces the issue to github and we can take a look. Thanks.

**Comment by orubel** [comment] 2016-01-28 16:51
will do

**Comment by orubel** [comment] 2016-01-28 18:00
Here is a project with it showing broken state. Attributes are not being read properly in Interceptor. Only Loops once.

https://github.com/orubel/test3

**Comment by jeffbrown** [comment] 2016-01-29 13:23
I have tried working with the app at https://github.com/orubel/test3.  This is what I am seeing...

```
./gradlew clean run
```


```
$ curl --verbose --request GET --header "Content-Type: application/json" "http://localhost:8080/v0.1/post/show/1" --cookie cookies.txt
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /v0.1/post/show/1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 500 Internal Server Error
< Server: Apache-Coyote/1.1
< Content-Type: application/json;charset=UTF-8
< Content-Length: 209
< Date: Fri, 29 Jan 2016 13:17:24 GMT
< Connection: close
< 
* Closing connection 0
{"timestamp":"Jan 29, 2016 7:17:24 AM","status":500,"error":"Internal Server Error","exception":"java.lang.NoClassDefFoundError","message":"Could not initialize class org.slf4j.MDC","path":"/v0.1/post/show/1"}
```

I spent a few minutes trying to sort out what your app is doing and I had to jump ship because there is a lot of unrelated things in your project which complicate troubleshooting it.  

I recommend using `0.5.4.RELEASE` of `io.spring.dependency-management` instead of `0.4.0.RELEASE`.

I would recommend getting `spring-security-core` out of the mix to simplify the situation, or use `3.0.3` instead of `3.0.0.M1`.

Best of luck.

**Comment by jeffbrown** [comment] 2016-01-29 13:25
So there is a stable reference point in case the repository changes, the code I tested is the code under https://github.com/orubel/test3/tree/322714aa1658f0158bd96f6b0295b63471e668c4 which at the moment is the latest code on the `master` branch.

**Comment by jeffbrown** [comment] 2016-01-29 15:06
@orubel The PR at https://github.com/orubel/test3/pull/1 demonstrates that in general this does work.  If you can identify a set of changes to my code that indicate a problem in the framework, please let me know.  I am going to go ahead and close this issue for now.

Thanks for the feedback.

**Closed by jeffbrown** 2016-01-29 15:06 UTC
Labels: Awaiting Feedback

**Comment by orubel** [comment] 2016-01-29 16:43
went ahead and simplified the example. Let me know if this works or if I need to open another ticket.

**Comment by orubel** [comment] 2016-01-29 16:57
oh and thanks again for your help

**Comment by jeffbrown** [comment] 2016-01-29 17:09
@orubel 

> Ok so you added two dependencies in order to get this to work

No, I did not add those dependencies to get this to work.  I fixed the broken logic in your interceptor to get this to work.   This does not appear to be a bug in the framework.  It appears to be a bug in your interceptor.  The commit at https://github.com/jeffbrown/test3/commit/28ac50131487f83819c90ed0a2ce652c9a381283 makes the problem go away.

**Comment by jeffbrown** [comment] 2016-01-29 17:15
I added those dependencies while trying to troubleshoot it because their absence was just 1 more thing on the list of peculiarities in your app that made it complicated to figure out what was actually going wrong, which was effectively you were initializing a value to zero, looping until it was greater than zero, and never incrementing the value.

**Comment by orubel** [comment] 2016-01-29 17:18
*SMACK* ok I'm an idiot but I don't understand why I couldn't do (0+1) as increment. Thats bizarre!

"Either way. Thank you for pointing out my idiocy!" (put that in quotes for you so you can have that needlepointed or at least retweeted for DW)

**Comment by jeffbrown** [comment] 2016-01-29 17:22
> SMACK ok I'm an idiot but I don't understand why I couldn't do (0+1) as increment. Thats bizarre!

You can do 0+1, but your code wasn't.  You had code like this...

```
            if (!request.getAttribute('batchInc')) {
                println('init batchinc')
                request.setAttribute('batchInc', 0)
            } else {
                println('increment batchinc')
                request.setAttribute('batchInc', request.getAttribute('batchInc').toInteger() + 1)
            }
```

The `else` block was never executed because `request.getAttribute('batchInc')` was always evaluating to zero, which is `false`.  Your if condition was effectively `if(!false)` so it was always true.

> "Either way. Thank you for pointing out my idiocy!" (put that in quotes for you so you can have that needlepointed or at least retweeted for DW)

I don't know what "DW" is.

**Comment by orubel** [comment] 2016-01-29 17:23
DAMN! Oh I always forget testing for NULL can be confused for testing for BOOLEAN. That messes me up everytime. And I deserve smacked for that
