### ISSUE TITLE
g.createLink with resource attribute working not with namespaces

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-core#10517] opened 2017-03-03 19:47 UTC
Hi!

We use g.createLink with the resource attribute to choose the right controller for domain classes with subclasses. Let's say we have a super domain class `AbstractStuff` and two sub classes `CoolStuff` `BoringStuff`. With `g.createLink(resource: stuffObject, action: "edit")` we get

```
/boringStuff/create/x
/coolStuff/create/x
```

This works as we want even with namespaces, at least as long as the namespace is the same for all. If we call g.createLink inside a controller/view which is in another namespace, this namespace is used for all links.

### Environment Information

- **Operating System**: Windows 10 x64
- **Grails Version:** 3.2.4
- **JDK Version:** 1.8.0_112

**Comment by jameskleeh** [comment] 2017-03-03 19:50
Please provide an example application

**Comment by andreasschiestl** [comment] 2017-03-03 22:19
Hi!

Here is a example application https://github.com/andreasschiestl/createLinkNamespaceTest

### Expected Behaviour

Start the app and open http://localhost:8080/main/abstractStuff/index and you shoudl get the following console output:

> /implementationTwo/coolStuff/edit/1
> /implementationOne/boringStuff/edit/2

The app creates two objects in the Bootstrap.groovy, queries these in the controller action and creates links for the objects


### Actual Behaviour

the console output is:

> /main/coolStuff/edit/1
> /main/boringStuff/edit/2

main is not the correct namespace for the CoolStuffController and BoringStuffController

**Comment by jameskleeh** [comment] 2017-03-03 22:34
@andreasschiestl Please update the application to 3.2.6

**Comment by jameskleeh** [comment] 2017-03-03 22:40
Relevant: https://github.com/grails/grails-core/issues/10086

**Comment by jameskleeh** [comment] 2017-03-04 07:37
I verified this is happening in 3.2.6. I'm investigating the cause

**Comment by jameskleeh** [comment] 2017-03-04 08:30
With the changes for 3.2.7, you will get the following exception with the above code ```grails.web.mapping.exceptions.UrlMappingException: Unable to create URL for mapping [/(*)/(*)/(*)?/(*)?(.(*))?] and parameters [{id=1, controller=coolStuff, action=edit}]. Parameter [namespace] is required, but was not specified!```

That is more correct than applying the wrong controller. This then becomes the same issue as #10086.

**Comment by jameskleeh** [comment] 2017-03-04 08:35
Fixed by https://github.com/grails/grails-core/commit/1f47caffef4a50d74b3dadbaa4a8ce94674907be

**Closed by jameskleeh** 2017-03-04 08:35 UTC
Labels: Acknowledged

**Comment by andreasschiestl** [comment] 2017-03-04 08:44
Wow, thank you for the really fast fix!
