### ISSUE TITLE
Cannot access webpage after deploying grails war-file with JSON-views (profile:rest-api) to tomcat getting 404

### ISSUE THREAD

**Issue by CHANetcompany** [grails/grails-core#10285] opened 2016-10-28 22:16 UTC
I am having problems with the rest-api profile in grails, when deploying war to tomcat-server I get 404
### Task List
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)
### Steps to Reproduce
1. install _Grails 3.2.1_
2. install _tomcat9_
3. install _Java(TM) SE Runtime Environment (build 1.8.0_111-b14)_
4. **grails create-app myapp -profile=rest-api**
5. change: compile _"org.springframework.boot:spring-boot-starter-tomcat"_ in _build.gradle_ to _provided_
6. **gradlew assemble**
7. copy _myapp-0.1.war_ to _tomcat9/webapps_
8. restart tomcat
9. navigate browser to _http://localhost:8080/myapp-0.1/_
### Expected Behaviour

visualization of JSON-view index.gson
### Actual Behaviour
1. Apache Http status 404 is shown (not the internel 404 page of the application)
2. I have tried to look through all tomcat logs. They do not seem to produce any stacktrace or anything suspecious.
### Environment Information
- **Operating System:** Windows 10
- **Grails Version:** 3.2.1 (but I am experiencing same on 3.1.8)
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
- **Container Version (If Applicable):** tomcat9 
### Example Application

Follow the steps to create example application

**Comment by CHANetcompany** [comment] 2016-10-28 22:19
If this is an issue, a workaround will be very much appreciated. Thanx in advance.

**Comment by CHANetcompany** [comment] 2016-10-31 08:23
We have found a workaround: in *build.gradle* change **provided "org.codehaus.groovy:groovy-ant"** to **runtime**

**Comment by jeffbrown** [comment] 2016-10-31 14:30
I think this is basically a duplicate of #10196.

The `groovy-ant` dependency is only needed to support reloading of `i81n` message properties in the development environment.  The issue with marking it as `provided` is its transitive dependencies up `provided`, which includes some key pieces (like the main Groovy library).  Those pieces can't be made provided.

**Closed by jeffbrown** 2016-10-31 14:30 UTC

**Comment by CHANetcompany** [comment] 2016-10-31 14:55
@jeffbrown  Your comment agrees precisely with what we are experiencing.
