### ISSUE TITLE
Grails 3.1.0 "Could not resolve view" exceptions when running executible war

### ISSUE THREAD

**Issue by jwagenleitner** [grails/grails-core#9302] opened 2015-09-29 22:21 UTC
Executing the war file after running `grails war` or `gradlew build` generates the following exception when navigating to the index page in Grails v3.1.0.M1 or v3.1.0.BUILD-SNAPSHOT (39fc3e9c4e99316540afdd4925d9ab3aafcd817a):

`java -Dgrails.env=prod -jar build\libs\app310-0.1.war`

```
Grails application running at http://localhost:8080 in environment: production
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for
servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/index' in
servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name '/index' in servlet with name 'grailsDispatcherServlet'

        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1227) ~[spring-webmvc-4.2.1.R
ELEASE.jar!/:4.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring
-webmvc-4.2.1.RELEASE.jar!/:4.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) ~[spring-webmvc-4.2.
1.RELEASE.jar!/:4.2.1.RELEASE]
```

Full stacktrace is available at https://gist.github.com/jwagenleitner/96928fdb8e342e50c9f6.

The application starts up normally if `grails run-app` or `grails prod run-app` is executed.

Environments:
```
Windows 7 64-bit
| Grails Version: 3.1.0.BUILD-SNAPSHOT
| Groovy Version: 2.4.4
| JVM Version: 1.8.0_60
```

```
Windows 7 64-bit
| Grails Version: 3.1.0.M1
| Groovy Version: 2.4.4
| JVM Version: 1.8.0_60
```

To reproduce:

1.  `grails create-app app310`
1.  `cd app310`
1.  `grails war` or `gradlew build`
1.  `java -Dgrails.env=prod -jar build\libs\app310-0.1.war`
1.  Navigate in browser to `http://localhost:8080/`

**Comment by graemerocher** [comment] 2015-10-07 13:07
You can workaround the issue by doing `cd build/libs` and then `java -jar app310-0.1.war`

Grails gets confused because it thinks you are running the project locally if you run it from the project root.

**Comment by jwagenleitner** [comment] 2015-10-07 20:25
Thanks, that worked.

**Comment by arvind-das** [comment] 2015-11-05 18:08
Thanks @jwagenleitner for pointing it out, exactly in the same problem with grails 3.0.7 and tried to solve of my own but couldn't. Thanks to @graemerocher for providing a workaround, now atleast the app runs , though it has problems with assets compressions but yes, app is running in production mode without that Dispatcher servlet exception related to view . Hoping for a fix soon

**Comment by arvind-das** [comment] 2015-11-05 18:39
now assets have a problem, any ideas ?

`ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception
java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
	at asset.pipeline.AssetPipelineFilter$_doFilterInternal_closure1.doCall(AssetPipelineFilter.groovy:55) ~[asset-pipeline-3.0.8.jar!/:na]
	at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-2.4.4.jar!/:2.4.4]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-2.4.4.jar!/:2.4.4]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-2.4.4.jar!/:2.4.4]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) ~[groovy-2.4.4.jar!/:2.4.4]
	at groovy.lang.Closure.call(Closure.java:426) ~[groovy-2.4.4.jar!/:2.4.4]
	at groovy.lang.Closure.call(Closure.java:442) ~[groovy-2.4.4.jar!/:2.4.4]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5228) ~[groovy-2.4.4.jar!/:2.4.4]
`
??

**Comment by Schlogen** [comment] 2015-11-10 20:46
I'm seeing this same issue with assets

**Comment by davydotcom** [comment] 2015-11-17 13:22
@Schlogen the asset error is fixed with `asset-pipeline:3.0.14`

**Comment by I-question-this** [comment] 2015-11-20 20:30
The work around is not working for our code base.

The following errors are thrown:

`Could not resolve view with name 'getSsn' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1227) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.servle
t.FrameworkServlet.processRequest(FrameworkServlet.java:967) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[servlet-api.jar:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.21]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.21]
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295) ~[spring-boot-actuator-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilter`

**Comment by I-question-this** [comment] 2015-11-25 15:39
Thanks to graemerocher I was able to fix my issue. My issue had to do with naming controllers and folders storing view with consistent casing. Example
SsnControler with views stored in grails-app/views/SSN is wrong. It should be grails-app/views/ssn

**Comment by rafaeleyng** [comment] 2015-12-21 18:45
I ended up here because I'm trying to understand [this](http://grails.github.io/grails-doc/3.0.x/guide/single.html#urlMappings) part of the docs, where they say that *Extending your API to include more end points then becomes trivial:*  

```
"/books"(resources:"book") {
    "/publisher"(controller:"publisher", method:"GET")
}
```

After adding the code above to my UrlMappings, I've created a PublisherController with `index` and `show` methods (I would consider myself happy enough just to see my program flow passing by either of these methods).

Then I try to access `/books/1/publisher` (according to the same doc above), and I get: 
> Could not resolve view with name '/publisher/index' in servlet with name 'grailsDispatcherServlet'

As far as I understand, there's nothing to do with views, since my project is only an API. A think I'm missing the point by a far margin, so any help would be appreciated.

> You can workaround the issue by doing `cd build/libs` and then `java -jar app310-0.1.war`

Did that and I continue to get the same error.

**Comment by graemerocher** [comment] 2015-12-21 20:38
What does you `index` action look like?

**Comment by rafaeleyng** [comment] 2015-12-21 23:51
@graemerocher at the moment of this comment it was only a `println`

**Comment by graemerocher** [comment] 2015-12-22 07:45
Well that is your problem then, your action is returning `null` so Grails tries to look for an `index` view and there isn´t one

**Comment by rafaeleyng** [comment] 2015-12-22 09:59
I don't think so, because this print was never called.

**Comment by graemerocher** [comment] 2015-12-22 09:59
Well either way your issue is completely unrelated to this one, if you believe you have a valid issue raise a new github issue and upload an example that reproduces the problem to Github

**Comment by nourlan** [comment] 2016-04-18 12:42
When I use grails utility to run app - everything is ok. But when I try to run app from IDE (Idea 14) I receive the following error:
type Exception report

message javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
grails.plugin.cache.web.filter.AbstractFilter.logThrowable(AbstractFilter.java:116)
grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:70)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:75)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:113)
org.springframework.boot.context.web.ErrorPageFilter.forwardToErrorPage(ErrorPageFilter.java:188)
org.springframework.boot.context.web.ErrorPageFilter.handleException(ErrorPageFilter.java:171)
org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:135)
org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:61)
org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:95)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:113)

What is wrong?

**Comment by nikhilsharma8193** [comment] 2016-06-01 06:54
@rafaeleyng 
It works for me if I use a `render ""` or `return true` or `return false`, else it fails even for `grails run-app` in development mode. I have a simple controller that does nothing but prints some statements that I need for testing. It works well on Grails 2.x.

**Comment by shawnchain** [comment] 2016-07-17 06:58
Under 3.1.9, running under APP directory with "java -jar build/libs/MyApp.war" will cause the "HTTP Status 500 - Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'" error.  I think this is the same issue.

**Closed** 2016-08-26 14:08 UTC
Labels: in progress, Minor, Workaround Available

**Comment by bilalsha** [comment] 2016-09-05 19:43
Under Grails 3.1.9 or 3.1.11, I am facing this issue `HTTP Status 500 - javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'` I have explained the complete issue here #10138

**Comment by angstream555** [comment] 2017-03-03 12:27
update grails version at last 3.2.6
