### ISSUE TITLE
3.1.1 Problem with command Validateable inheritance

### ISSUE THREAD

**Issue by AleksanderGrzybowski** [grails/grails-core#9972] opened 2016-06-01 06:55 UTC
Hello! I have a problem related to `Validateable` trait inheritance. Maybe I just don't understand how traits are supposed to  work (groovy docs didn't help). I have 2 command objects connected by inheritance chain. I was expecting for this code to run both validators (since `DerivedCommand instanceof Validateable` is true), however, only `BaseCommand` validator runs.
```
package com.abc

import grails.validation.Validateable

class BookController {
    def index() {
        def cmd = new DerivedCommand(baseProp: 'a', derivedProp: 'b')
        cmd.validate()
        render 'response'
    }
}

class BaseCommand implements Validateable {
    String baseProp

    static constraints = {
        baseProp validator: { val, obj ->
            println "Base validator called"
        }
    }
}

class DerivedCommand extends BaseCommand {
    String derivedProp

    static constraints = {
        derivedProp validator: { val, obj ->
            println "Derived validator called"
        }
    }
}

```

**Comment by droggo** [comment] 2016-06-01 07:06
I think this is duplicate of: https://github.com/grails/grails-core/issues/9595

**Comment by AleksanderGrzybowski** [comment] 2016-06-01 07:25
Oh, I must have missed this. Yeah, this is a duplicate.

**Closed** 2016-06-01 15:21 UTC
Labels: Duplicate
